cncProd/force-app/main/default/objects/NewOverride__c/NewOverride__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting to check access to override in the &quot;New&quot; button.</description>
    <label>New Override</label>
</CustomObject>

cncProd/force-app/main/default/objects/NewOverride__c/fields/AllowNew__c.field-meta.xml
<CustomField>
    <fullName>AllowNew__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow override in New button.</description>
    <label>Allow New?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContactRedirect.cls
/****************************************
 * Class Name: ContactRedirect
 * Description: Controller of ContactRedirect.vfp
****************************************/ 
public without sharing class ContactRedirect {
    
    public Contact conVal {get; set;}
    public Boolean renderError {get; set;}    
    
    //constructor
    public ContactRedirect(ApexPages.StandardController sc){
        conVal = (Contact) sc.getRecord();
    }
    
    //if System Admin, redirect to the Lead Creation page.
    public PageReference redirectToError(){
        //check permission
        PageReference rf;
        NewOverride__c ov = NewOverride__c.getInstance();
		String linkOverride = '/'+ Contact.sObjectType.getDescribe().getKeyPrefix() +'/e?nooverride=1';
        if(!ov.AllowNew__c){
            //does not have new
            renderError = true;
        }else{
            renderError = false;
            //New functionality prevent override
            rf = new PageReference( linkOverride ); 
        }
        return rf;
    }
}