cncProd/force-app/main/default/objects/Case/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <label>Appointment Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Case/fields/Appointment_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Time__c</fullName>
    <label>Appointment Time</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Booking_ID__c.field-meta.xml
<CustomField>
    <fullName>Booking_ID__c</fullName>
    <externalId>true</externalId>
    <label>Booking ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Case/fields/CSE_Remarks__c.field-meta.xml
<CustomField>
    <fullName>CSE_Remarks__c</fullName>
    <label>CSE Remarks</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

cncProd/force-app/main/default/objects/Case/fields/FranchiseCode__c.field-meta.xml
<CustomField>
    <fullName>FranchiseCode__c</fullName>
    <label>Autoline Franchise Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateCBS.cls
global class UpdateCBS {   
    
@Invocablemethod
global static void initialMethod(List<String> vCaseId)
{
   
    case c = [select id, Booking_ID__c, FranchiseCode__c, CSE_Remarks__c, Appointment_Date__c,
              					Appointment_Time__c From Case where id=: vCaseId[0] Limit 1];
    if(c.id!=null || c.id!=''){
        String vBookingId = string.valueof(c.Booking_ID__c);
        String vFranchiseCode = c.FranchiseCode__c;
        String vComments =  c.CSE_Remarks__c + ' ' + 'Booking confirmed by customer via SMS on ' + c.Appointment_Date__c + ' ' + c.Appointment_Time__c;    
        String vCSERemarks = c.CSE_Remarks__c + ' ' + 'Booking confirmed by customer via SMS on ' + c.Appointment_Date__c + ' ' + c.Appointment_Time__c;    
        UpdateCBSRemarks.UpdBookingRemarks(vBookingId, vFranchiseCode,vComments,vCSERemarks);
        c.CSE_Remarks__c = vCSERemarks;
        update c;
    }       
}
    
}