cncProd/force-app/main/default/objects/Case/fields/Case_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Category__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tow Service</fullName>
            </value>
            <value>
                <fullName>Complain</fullName>
            </value>
            <value>
                <fullName>Compliment</fullName>
            </value>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Change of Ownership</fullName>
            </value>
            <value>
                <fullName>Change of Particulars</fullName>
            </value>
            <value>
                <fullName>Change of Vehicle Registration Number</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>MB Sales CLI</fullName>
            </value>
            <value>
                <fullName>MB SFU</fullName>
            </value>
            <value>
                <fullName>MB Sales CSI</fullName>
            </value>
            <value>
                <fullName>Booking List</fullName>
            </value>
            <value>
                <fullName>Created List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Status__c.field-meta.xml
<CustomField>
    <fullName>SMS_Status__c</fullName>
    <label>SMS Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <label>Sent but not responded</label>
            </value>
            <value>
                <fullName>Not Sent</fullName>
            </value>
            <value>
                <fullName>Confirm Appointment</fullName>
            </value>
            <value>
                <fullName>Change Appointment</fullName>
            </value>
            <value>
                <fullName>Cancel Appointment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Case/recordTypes/Servicing_and_Grooming.recordType-meta.xml
<RecordType>
    <fullName>Servicing_and_Grooming</fullName>
    <active>true</active>
    <businessProcess>Client Engagement Status</businessProcess>
    <label>Servicing and Grooming</label>
</RecordType>

cncProd/force-app/main/default/classes/CancelCBSQueuable_Test.cls
@IsTest
public class CancelCBSQueuable_Test {

    static testmethod void test4CancelUpd()    
	{
        List<Case> CasesForCBS = New List<Case>();
        Case c = New Case();
    	c.subject ='case 1';
        c.Case_Category__c = 'Booking List';
    	c.SMS_Status__c='Cancel Appointment';
    	c.Status='Open';
    	insert c;
        CasesForCBS.add(c);
     
        Case c1 = New Case();
    	c1.subject ='case 11';
        c1.Case_Category__c = 'Booking List';
    	c1.SMS_Status__c='Confirm Appointment';
    	c1.Status='Open';
    	insert c1;
        CasesForCBS.add(c1);
     
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new externalMock());
        
            ID jobId = System.enqueueJob(New CancelCBSQueuable(CasesForCBS));
        Test.stopTest();
    }
    

    @isTest
    static void testBookingCancellation2()
    {
        Case cs = New Case();
    	cs.subject           = 'Dummy Test';
        cs.Case_Category__c  = 'Booking List';
    	cs.SMS_Status__c     = 'Cancel Appointment';
        cs.Status            = 'Open';
        cs.RecordTypeId      = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get( 'Servicing_and_Grooming' ).getRecordTypeId(); 
    	insert cs;

        System.Test.startTest();
            Test.setMock(HttpCalloutMock.class, new CBSFailureMock());
            System.enqueueJob(new CancelCBSQueuable( new List<Case>{ cs }));
        System.Test.stopTest();
        System.assert( ([SELECT Id, Status FROM Case WHERE ID = :cs.Id AND Status = 'Closed']).size() == 1 );
    }


    public class CBSFailureMock implements HttpCalloutMock 
    {
        public HTTPResponse respond(HTTPRequest req) {
            String body = '{"data":{},"error":{"code":540,"message":"The booking cannot be cancelled again"}}';
            HttpResponse respond = new HttpResponse();
            respond.setHeader('Content-Type', 'application/json');
            respond.setBody(body);
            respond.setStatusCode(200);
            respond.setStatus('200');
            return respond;
        }
    }
    
}