force-app/main/default/objects/Campaign/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/TC_Val__c.field-meta.xml
<CustomField>
    <fullName>TC_Val__c</fullName>
    <inlineHelpText>Term &amp; condition for in-app promo. content need to copy &amp; paste from sitecore</inlineHelpText>
    <label>TC_Val</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/Campaign_Promo_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Campaign Upsell Accessory</label>
    <nameField>
        <label>Campaign Upsell Accessories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Upsell Accessories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Upsell Accessories</relationshipLabel>
    <relationshipName>Campaign_Promo_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Group_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Display_Name__c</fullName>
    <formula>Promo_Line_Item__r.Group_Display_Name__c</formula>
    <label>Group Display Name</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Item_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Display_Name__c</fullName>
    <formula>Promo_Line_Item__r.Item_Display_Name__c</formula>
    <label>Item Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Item_Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Group_Code__c</fullName>
    <formula>Promo_Line_Item__r.Item_Group_Code__c</formula>
    <label>Item Group Code</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Promo_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Promo_Line_Item__c</fullName>
    <label>Upsell Accessory</label>
    <referenceTo>Promo_Line_Item__c</referenceTo>
    <relationshipLabel>Campaign Upsell Accessories</relationshipLabel>
    <relationshipName>Campaign_Promo_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Promo_Price__c.field-meta.xml
<CustomField>
    <fullName>Promo_Price__c</fullName>
    <formula>Promo_Line_Item__r.Promo_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Promo Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Usual_Price__c.field-meta.xml
<CustomField>
    <fullName>Usual_Price__c</fullName>
    <formula>Promo_Line_Item__r.Usual_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Usual Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Variant_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Variant_Display_Name__c</fullName>
    <formula>Promo_Line_Item__r.Variant_Display_Name__c</formula>
    <label>Variant Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/Promo_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Accessories tied to the Targeted Sales Promo campaigns for Upselling Accessories during DSA process.</description>
    <label>Upsell Accessory</label>
    <nameField>
        <label>Upsell Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upsell Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Promo_Line_Item__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Promo_Line_Item__c/fields/Group_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Display_Name__c</fullName>
    <label>Group Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Promo_Line_Item__c/fields/Item_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Display_Name__c</fullName>
    <label>Upsell Accessory Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Promo_Line_Item__c/fields/Item_Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Group_Code__c</fullName>
    <label>Item Group Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/fields/No_of_Stock__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stock__c</fullName>
    <label>No. of Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/fields/Promo_Price__c.field-meta.xml
<CustomField>
    <fullName>Promo_Price__c</fullName>
    <label>Promo Price (w/GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/fields/Usual_Price__c.field-meta.xml
<CustomField>
    <fullName>Usual_Price__c</fullName>
    <label>Usual Price (w/GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/fields/Variant_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Variant_Display_Name__c</fullName>
    <label>Variant Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/SalesTargetedPromoItemsAPI.cls
/** *****
* Description : Get Sales Targeted Campaign and related Promo Line Items
* 
* Change History
* Date(YYYYMMDD)       Name                            Description
* 20220324             thanh.ly@aodigy.com             Created Initial Version. 
* 
** *****/
@RestResource(urlMapping = '/promotion/getSalesTargetedCampaign/*')
global class SalesTargetedPromoItemsAPI{

    private static RestRequest req  = RestContext.request;
    private static RestResponse res = RestContext.response;
    private static RequestBody reqBody  = new RequestBody();
    private static ResponseBody resBody = new ResponseBody();
    private static List<String> campaignsNoTC = new List<String>();
    private static httpErrorResponse errorResponse;

    @HttpPost
    global static void doPost()
    {
        res.addHeader('Content-Type', 'application/json');
        try
        {
            processPostRequest();
        }
        catch(Exception e)
        {
            loggerDataPool.buildLogDataPool('SalesTargetedCampaignAPI', e);
            errorResponse = new httpErrorResponse('Failed', e.getMessage() + ' ' + e.getLineNumber());
        }

        if(errorResponse != null && errorResponse.status == 'Failed')
        {
            res.statusCode = 400;
            res.responseBody = Blob.valueOf(JSON.serialize(errorResponse));
        }

        serviceDataPool.buildServiceDataPool('SalesTargetedCampaignAPI', 'SalesTargetedCampaignAPI', '', req, res);

        if (!campaignsNoTC.isEmpty())
        {
            InvoiceEmail_ProcessBuilder_RestTC.apexcallout(campaignsNoTC);
        }
    }

    public static void processPostRequest()
    {
        reqBody = (RequestBody)JSON.deserialize(req.requestBody.toString(), RequestBody.class);

        if(String.isBlank(reqBody.CampaignID))
        {
            errorResponse = new httpErrorResponse('Failed', 'Mandatory Fields Missing');
        }
        else 
        {
            generateResponseBody();
        }
    }

    public static void generateResponseBody()
    {
        List<Campaign_Promo_Line_Item__c> campaignPromoItems = new List<Campaign_Promo_Line_Item__c>();
        List<Campaign> campaigns                             = new List<Campaign>();

        campaigns =  [SELECT Id, Type, Status, StartDate, Name, EndDate, Description, Brand__c, Branch_Code__c, TC_Val__c,
                            (SELECT Id, Promo_Line_Item__c, Promo_Line_Item__r.Item_Display_Name__c, 
                                    Promo_Line_Item__r.Variant_Display_Name__c, Promo_Line_Item__r.Group_Display_Name__c, Promo_Line_Item__r.Item_Group_Code__c, 
                                    Promo_Line_Item__r.Usual_Price__c, Promo_Line_Item__r.Promo_Price__c, Promo_Line_Item__r.No_of_Stock__c
                            FROM Campaign_Promo_Line_Items__r)
                    FROM Campaign
                    WHERE Id =: reqBody.CampaignID AND IsActive = true
                    LIMIT 1];

        if (campaigns.isEmpty())
        {
            errorResponse = new httpErrorResponse('Failed', 'Invalid Campaign Id: ' + reqBody.CampaignID);
            return;
        }

        resBody.Type        = campaigns[0].Type;
        resBody.Status      = campaigns[0].Status;
        resBody.StartDate   = campaigns[0].StartDate;
        resBody.Name        = campaigns[0].Name;
        resBody.EndDate     = campaigns[0].EndDate;
        resBody.Description = campaigns[0].Description;
        resBody.CampaignID  = campaigns[0].Id;
        resBody.Brand       = campaigns[0].Brand__c;
        resBody.BranchCode  = campaigns[0].Branch_Code__c;
        campaignPromoItems  = campaigns[0].Campaign_Promo_Line_Items__r;

        if (campaigns[0].TC_Val__c == null)
        {
            campaignsNoTC.add(campaigns[0].Id);
        }

        if(!campaignPromoItems.isEmpty())
        {
            Map<String, Accessory> accMap = new Map<String, Accessory>();
            List<Accessory> accs          = new List<Accessory>();
            Accessory tempAcc; 
            Item tempItem;

            for (Campaign_Promo_Line_Item__c item : campaignPromoItems)
            {
                tempItem               = new Item();
                tempItem.ItemID        = item.Promo_Line_Item__c;
                tempItem.ActualPrice   = item.Promo_Line_Item__r.Usual_Price__c;
                tempItem.DiscountPrice = item.Promo_Line_Item__r.Promo_Price__c;
                tempItem.Quantity      = item.Promo_Line_Item__r.No_of_Stock__c;
                tempItem.Label         = String.isNotBlank(item.Promo_Line_Item__r.Item_Group_Code__c) ? item.Promo_Line_Item__r.Variant_Display_Name__c : '';
                tempItem.Name          = item.Promo_Line_Item__r.Item_Display_Name__c;

                if (String.isNotBlank(item.Promo_Line_Item__r.Item_Group_Code__c))
                {
                    if (accMap.containsKey(item.Promo_Line_Item__r.Item_Group_Code__c))
                    {
                        tempAcc = accMap.get(item.Promo_Line_Item__r.Item_Group_Code__c);
                        tempAcc.Items.add(tempItem);
                        accMap.put(item.Promo_Line_Item__r.Item_Group_Code__c, tempAcc);
                    }
                    else 
                    {
                        accMap.put(item.Promo_Line_Item__r.Item_Group_Code__c, new Accessory(item.Promo_Line_Item__r.Group_Display_Name__c, new List<Item>{tempItem}));
                    }
                }
                else 
                {
                    accs.add(new Accessory('', new List<Item>{tempItem}));
                }
            }

            System.debug('accMap: ' + accMap);

            accs.addAll(accMap.values());
            resBody.Accessories = accs;
        }
           
        res.statusCode = 200;
        res.responseBody = Blob.valueOf(JSON.serialize(resBody));
    }

    public class RequestBody
    {
        public String CampaignID; 
    }

    public class ResponseBody
    {
        public String Type;
        public String Status;
        public Date StartDate;
        public String Name;
        public Date EndDate;
        public String Description;
        public String CampaignID;
        public String Brand;
        public String BranchCode;
        public List<Accessory> Accessories;
    }

    public class Accessory
    {
        public String GroupName;
        public List<Item> Items;

        public Accessory(String groupName, List<Item> items)
        {
            this.GroupName = groupName;
            this.Items     = items;
        }
    }

    public class Item
    {
        public String Name;
        public String ItemID;
        public Double ActualPrice;
        public Double DiscountPrice;
        public String Label;
        public Decimal Quantity; 
    }
    
    public class httpErrorResponse
    {
        public String status;
        public String message;

        public httpErrorResponse(String statusValue, String messageValue)
        {
            status = statusValue;
            message = messageValue;
        }
    }


}