force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/Budgeted_Cost_in_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Budgeted_Cost_in_Campaign__c</fullName>
    <label>Budgeted Cost In Campaign</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/Target_Audience__c.field-meta.xml
<CustomField>
    <fullName>Target_Audience__c</fullName>
    <label>Target Audience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public and Targeted</fullName>
            </value>
            <value>
                <fullName>Targeted Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/CampaignPromoForPublicAPITest.cls
/** *****
 * Description : Test Class for CheckCampaignPromoCodeAPI class
 * 
 * Change History
 * Date(YYYYMMDD)       Name                 Description
 * 20210412             tphung@aodigy           Created Initial Version. 
 * 
** *****/
@isTest
private class CampaignPromoForPublicAPITest {
    @isTest
    private static void testPromoCamp_ValidBrandAndBranchCode(){

        Campaign camp = Test_DataFactory.createCamp(true, 'KIA Party', 'Events', 'CCK');
        camp.Brand__c = 'MIT';
        camp.EndDate = Date.today().addDays(30);
        camp.Description = 'Wiper';
        camp.Status ='Planned';
        camp.IsActive = True;
        camp.Target_Audience__c = 'Public And Targeted';
        camp.Budgeted_Cost_in_Campaign__c = 200;
        update camp;
        System.debug(camp);
        String reqBody ='{'+
        '  "BranchCode": "CCK",'+
        '  "Brand": "MIT"'+
        '}';                       
        Test.startTest();
        String reqURI = '/promotion/getCampaigns/*'; 
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CampaignPromoForPublicAPI.doPost();
        Test.stopTest();
    }
    @isTest
    private static void testPromoCamp_MissingRequired(){
        String reqBody ='{'+
        '  "BranchCode": "",'+
        '  "Brand": "MIT"'+
        '}';
        Test.startTest();
        String reqURI = '/promotion/getCampaigns/*'; 
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CampaignPromoForPublicAPI.doPost();
        Test.stopTest();

    }
    @isTest
    private static void testPromoCamp_NonExistBrand(){
        String reqBody ='{'+
        '  "BranchCode": "CCK",'+
        '  "Brand": "MIAA"'+
        '}';
        Test.startTest();
        String reqURI = '/promotion/getCampaigns/*'; 
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CampaignPromoForPublicAPI.doPost();
        Test.stopTest();

        
    }
    @isTest
    private static void testPromoCamp_InvalidPayloadFormat_ExceptionThrown() {
        String reqBody ='{'+
                        '  "BranchCode": '+
                        '  "Brand": "MAA"'+
                        '}';
        Test.startTest();
        String reqURI = '/promotion/checkPromoCode/*'; 
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CampaignPromoForPublicAPI.doPost();
        Test.stopTest();
    }
}