force-app/main/default/objects/Campaign/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Guest Unit Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Event_Registration__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/PromoID__c.field-meta.xml
<CustomField>
    <fullName>PromoID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PromoID</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>PromoID</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{YYMM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <formula>/*IF(text(Transaction_Status__c) == &apos;processor_declined&apos;, &apos;processor_declined&apos;, TEXT(SeqNum__c))*/ 


IF(

DATEVALUE(CreatedDate) &gt; DATEVALUE(&quot;2019-10-30&quot;) &amp;&amp; 
Department__c = &apos;CCI&apos;,

&quot;SG-CCI-&quot;
&amp;
IF(SequenceIdentifier__c=&quot;Paid Event&quot;,&quot;EVT&quot; &amp; 
IF(Promotion_Type__c = &apos;One Time Purchase&apos;, &quot;-OTP&quot; &amp; SUBSTITUTE(Campaign__r.CampaignId__c, &quot;CID&quot;, &quot;&quot;), 
IF(Promotion_Type__c = &apos;Service Package&apos;, &quot;-SVCP&quot; &amp; SUBSTITUTE(Campaign__r.CampaignId__c, &quot;CID&quot;, &quot;&quot;), 
IF(Promotion_Type__c = &apos;Merchandise&apos;, &quot;-MER&quot; &amp; SUBSTITUTE(Campaign__r.CampaignId__c, &quot;CID&quot;, &quot;&quot;), &quot;&quot;))), 

IF(SequenceIdentifier__c=&quot;AfterSales&quot;,&quot;AFT&quot; &amp; 
IF(Promotion_Type__c = &apos;One Time Purchase&apos;, &quot;-OTP&quot; &amp; SUBSTITUTE(Campaign__r.CampaignId__c, &quot;CID&quot;, &quot;&quot;), 
IF(Promotion_Type__c = &apos;Service Package&apos;, &quot;-SVCP&quot; &amp; SUBSTITUTE(Campaign__r.CampaignId__c, &quot;CID&quot;, &quot;&quot;), 
IF(Promotion_Type__c = &apos;Merchandise&apos;, &quot;-MER&quot; &amp; SUBSTITUTE(Campaign__r.CampaignId__c, &quot;CID&quot;, &quot;&quot;), &quot;&quot;))), 
LPAD(TEXT(MONTH( DATEVALUE(CreatedDate) )),2,&apos;0&apos;)
&amp;
RIGHT(TEXT(YEAR( DATEVALUE(CreatedDate))),2)
))
&amp;
&quot;-&quot;&amp;IF(TEXT(Transaction_Status__c) == &apos;processor_declined&apos;, &apos;processor_declined&apos;, TEXT(SeqNum__c))
/*&quot;-&quot;&amp;TEXT(SeqNum__c)*/

,

&quot;SG-&quot;&amp;Department__c&amp;&quot;-&quot;
&amp;
IF(SequenceIdentifier__c=&quot;Paid Event&quot;,&quot;EVT&quot; &amp; SUBSTITUTE(Campaign__r.CampaignId__c, &quot;CID&quot;, &quot;&quot;) ,
IF(SequenceIdentifier__c=&quot;AfterSales&quot;,&quot;AFT&quot; &amp; SUBSTITUTE(Campaign__r.CampaignId__c, &quot;CID&quot;, &quot;&quot;) ,
IF(SequenceIdentifier__c=&quot;Sales Targeted Promo&quot;,&quot;STP&quot; &amp; SUBSTITUTE(Campaign__r.CampaignId__c, &quot;CID&quot;, &quot;&quot;) ,			
LPAD(TEXT(MONTH( DATEVALUE(CreatedDate) )),2,&apos;0&apos;)
&amp;
RIGHT(TEXT(YEAR( DATEVALUE(CreatedDate))),2)
)
)
)
&amp;
&quot;-&quot;&amp;IF(TEXT(Transaction_Status__c) == &apos;processor_declined&apos;, &apos;processor_declined&apos;, LPAD(TEXT(SeqNum__c),8,&apos;0&apos;))
/*&quot;-&quot;&amp;LPAD(TEXT(SeqNum__c),8,&apos;0&apos;)*/
)</formula>
    <label>Order No / Invoice No</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/Invoice_Pdf_PaidEvents_Save.cls
//Queable class to upload invoice PDF to files
public class Invoice_Pdf_PaidEvents_Save implements Queueable, Database.AllowsCallouts{
    List<Event_Registration__c> paidEvents;
    Map<String, String> campIdList;

    public Invoice_Pdf_PaidEvents_Save (List<Event_Registration__c> paidEventList, Map<String, String> campIdWithER){
        this.paidEvents = paidEventList;
        this.campIdList = campIdWithER ;
    }    
    public void execute(QueueableContext context){
        try {  
    //calling VF Page to generate PDF here.
        
            Map<String,String> erWithPublicURL = new Map<String, String>();
            Map<String, Campaign> camps =  new Map<String, Campaign>([Select Id,Name,Description,UnitPrice__c,Type, Branch_Code__c from Campaign where Id IN :campIdList.values()]);
            if(!camps.isEmpty()) {
                Map<Id,String> eventIdToInvoiceNum = new Map<Id,String>(); 
                for(Event_Registration__c er : paidEvents){
                    if(camps.get(er.PromoID__c).Type=='Paid Event'){
                        eventIdToInvoiceNum.put(er.payment__c,er.id);
                    }
                }
                List<ContentVersion> conVerList = new List<ContentVersion>();
                Map<String,String> cvWithER = new Map<String,String>();
                for(Invoice__c inv : [Select Id,Invoice_Number__c from Invoice__c where Id=:eventIdToInvoiceNum.KeySet()]){
                    if(eventIdToInvoiceNum.ContainsKey(inv.id) && eventIdToInvoiceNum.get(inv.id) != null && inv.Invoice_Number__c != null){
                        String EventRegisId = eventIdToInvoiceNum.get(inv.id);
                        String invoiceNumber = inv.Invoice_Number__c ;
                        pagereference Pg = Page.Invoice_Pdf_PaidEvents;
                        Pg.getParameters().put('EventRegistrationId',eventIdToInvoiceNum.get(inv.id)); 
                        
                        //Using utility class to generate file
                        erWithPublicURL = FileHelper.generateFile(EventRegisId,invoiceNumber,pg);                
                    }  
            
                    EventRegistration_ConfirmationEmail.sendEmail(campIdList,erWithPublicURL,false);               
                }  
            }
        }
        catch(Exception e){
            loggerDataPool.buildLogDataPool('Invoice_Pdf_PaidEvents_Save',e); 
        }
    }
}