force-app/main/default/objects/Campaign/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/Promo_Category__c.field-meta.xml
<CustomField>
    <fullName>Promo_Category__c</fullName>
    <label>Promo Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Promotional</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Exclusive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/Promo_Code__c.field-meta.xml
<CustomField>
    <fullName>Promo_Code__c</fullName>
    <inlineHelpText>Promo Code. 
This can be fixture or partial fixture promo code</inlineHelpText>
    <label>Promo Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Promo_Code_Type__c.field-meta.xml
<CustomField>
    <fullName>Promo_Code_Type__c</fullName>
    <inlineHelpText>This is to allow indicate whether the promo code is issue a fix code or unique running random number</inlineHelpText>
    <label>Promo Code Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixture</fullName>
            </value>
            <value>
                <fullName>Partial Fixture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Invited_members__c/Campaign_Invited_members__c.object-meta.xml
<CustomObject>
    <description>Target customer / lead for campaign initiate. i.e promo code, voucher etc....</description>
    <label>Campaign Invited members</label>
    <nameField>
        <displayFormat>Member-{00000000}</displayFormat>
        <label>Campaign Invited members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Invited members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Invited_members__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Invited members</relationshipLabel>
    <relationshipName>Campaign_Invited_members</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Invited_members__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Invited_members__c/fields/Redeem__c.field-meta.xml
<CustomField>
    <fullName>Redeem__c</fullName>
    <label>Redeem?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promo_gift_line_item__c/Promo_gift_line_item__c.object-meta.xml
<CustomObject>
    <description>This is the list of item that will tag under a promo code</description>
    <label>Promo gift line item</label>
    <nameField>
        <label>Promo gift line item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo gift line items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promo_gift_line_item__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Promo gift line items</relationshipLabel>
    <relationshipName>Promo_gift_line_items</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Promo_gift_line_item__c/fields/Gift_type__c.field-meta.xml
<CustomField>
    <fullName>Gift_type__c</fullName>
    <label>Gift type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Price Discount</fullName>
            </value>
            <value>
                <fullName>Service Credit</fullName>
            </value>
            <value>
                <fullName>Accessories Credit</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/Test_restCheckPromoCode.cls
/*******
 * Description : Test class for restCheckPromoCode.cls
 * 
 * Change History : 
 * Date(YYYYMMDD)      Name       Description
 * 20200520             TP     Created Initial Version 
*******/
@isTest
private class Test_restCheckPromoCode {
    
   @isTest
    static void test_restCheckPromoCode_Success() {
        Campaign campaign = new Campaign(Name = 'Kia Special Discount Exclusive Promo',
                                         Promo_Code__c = 'ILYMA20000',
                                         Promo_Category__c = 'Exclusive',
                                         Branch_Code__c = 'CCK',
                                         Brand__c = 'KIA',
                                         //RecordTypeId = '012O0000000brQ0IAI',
                                         StartDate = Date.today().addDays(-1),
                                         EndDate = Date.today().addDays(5), 
                                         Promo_Code_Type__c = 'Fixture');
        insert campaign;
        Campaign_Invited_members__c member = new Campaign_Invited_members__c(First_Name__c = 'Tori',
                                                                             Last_Name__c = 'Phan',
                                                                             Email__c = 'phan.thu@aodigy.com',
                                                                             Redeem__c = 'Open',
                                                                             Campaign__c = campaign.Id);
        insert member;
        Promo_gift_line_item__c item1 = new Promo_gift_line_item__c(Campaign__c = campaign.Id,
                                                                    Gift_type__c = 'Price Discount',
                                                                    Name = '2000');
        insert item1;
        Promo_gift_line_item__c item2 = new Promo_gift_line_item__c(Campaign__c = campaign.Id,
                                                                    Gift_type__c = 'Accessories Credit',
                                                                    Name = '4000');
        insert item2;
        Promo_gift_line_item__c item3 = new Promo_gift_line_item__c(Campaign__c = campaign.Id,
                                                                    Gift_type__c = 'Gift',
                                                                    Name = 'Blackvue Camera');
        insert item3;

        String reqBody = '{"Email" : "phan.thu@aodigy.com","PromoCode" : "ILYMA20000","PromoCategory" : "Exclusive","Branch" : "CCK","Brand" : "KIA" }';
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = 'services/apexrest/restCheckPromoCode';
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(reqBody);
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestHttpGenerator(200,reqBody));
        restCheckPromoCode.doPost();
        Test.stopTest();
    }

    @isTest
    static void test_restCheckPromoCode_NoCampaignFound() {
        Campaign campaign = new Campaign(Name = 'Kia Special Discount Exclusive Promo',
                                         Promo_Code__c = 'ILYMA20000',
                                         Promo_Category__c = 'Exclusive',
                                         Branch_Code__c = 'CCK',
                                         Brand__c = 'KIA',
                                         //RecordTypeId = '012O0000000brQ0IAI',
                                         StartDate = Date.today().addDays(-1),
                                         EndDate = Date.today().addDays(5), 
                                         Promo_Code_Type__c = 'Fixture');
        insert campaign;
        Campaign_Invited_members__c member = new Campaign_Invited_members__c(First_Name__c = 'Tori',
                                                                             Last_Name__c = 'Phan',
                                                                             Email__c = 'phan.thu@aodigy.com',
                                                                             Redeem__c = 'Open',
                                                                             Campaign__c = campaign.Id);
        insert member;
        Promo_gift_line_item__c item = new Promo_gift_line_item__c(Campaign__c = campaign.Id,
                                                                   Gift_type__c = 'Price Discount',
                                                                   Name = '2000');
        insert item;

        String reqBody = '{"Email" : "phan.thu@aodigy.com","PromoCode" : "ILYMA200004","PromoCategory" : "Exclusive","Branch" : "CCK","Brand" : "KIA" }';
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = 'services/apexrest/restCheckPromoCode';
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(reqBody);
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestHttpGenerator(200,reqBody));
        restCheckPromoCode.doPost();
        Test.stopTest();
    }

    @isTest
    static void test_restCheckPromoCode_NoValidCode() {
        Campaign campaign = new Campaign(Name = 'Kia Special Discount Exclusive Promo 2',
                                         Promo_Code__c = 'ILYMA2005',
                                         Promo_Category__c = 'Exclusive',
                                         Branch_Code__c = 'CCK',
                                         Brand__c = 'KIA',
                                         //RecordTypeId = '012O0000000brQ0IAI',
                                         StartDate = Date.today().addDays(3),
                                         EndDate = Date.today().addDays(5), 
                                         Promo_Code_Type__c = 'Fixture');
        insert campaign;
        Campaign_Invited_members__c member = new Campaign_Invited_members__c(First_Name__c = 'Tori',
                                                                             Last_Name__c = 'Phan',
                                                                             Email__c = 'phan.thu@aodigy.com',
                                                                             Redeem__c = 'Open',
                                                                             Campaign__c = campaign.Id);
        insert member;
        Promo_gift_line_item__c item = new Promo_gift_line_item__c(Campaign__c = campaign.Id,
                                                                   Gift_type__c = 'Price Discount',
                                                                   Name = '2000');
        insert item;

        String reqBody = '{"Email" : "phan.thu@aodigy.com","PromoCode" : "ILYMA2005","PromoCategory" : "Exclusive","Branch" : "CCK","Brand" : "KIA" }';
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = 'services/apexrest/restCheckPromoCode';
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(reqBody);
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestHttpGenerator(200,reqBody));
        restCheckPromoCode.doPost();
        Test.stopTest();
    }
    
    @isTest
    static void test_restCheckPromoCode_EmailError() {
        Campaign campaign = new Campaign(Name = 'Kia Special Discount Exclusive Promo 3',
                                         Promo_Code__c = 'ILYMA2007',
                                         Promo_Category__c = 'Exclusive',
                                         Branch_Code__c = 'CCK',
                                         Brand__c = 'KIA',
                                         //RecordTypeId = '012O0000000brQ0IAI',
                                         StartDate = Date.today().addDays(-3),
                                         EndDate = Date.today().addDays(5), 
                                         Promo_Code_Type__c = 'Fixture');
        insert campaign;
        Campaign_Invited_members__c member = new Campaign_Invited_members__c(First_Name__c = 'Tori',
                                                                             Last_Name__c = 'Phan',
                                                                             Email__c = 'phan.thu@aodigy.com',
                                                                             Redeem__c = 'Open',
                                                                             Campaign__c = campaign.Id);
        insert member;
        Promo_gift_line_item__c item = new Promo_gift_line_item__c(Campaign__c = campaign.Id,
                                                                   Gift_type__c = 'Price Discount',
                                                                   Name = '2000');
        insert item;
        
        String reqBody = '{"Email" : "tphan@aodigy.com","PromoCode" : "ILYMA2007","PromoCategory" : "Exclusive","Branch" : "CCK","Brand" : "KIA" }';
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = 'services/apexrest/restCheckPromoCode';
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(reqBody);
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestHttpGenerator(200,reqBody));
        restCheckPromoCode.doPost();
        Test.stopTest();
    }
    
    @isTest
    static void test_restCheckPromoCode_CodeError() {
        Campaign campaign = new Campaign(Name = 'Kia Special Discount Exclusive Promo 4',
                                         Promo_Code__c = 'ILYMA2008',
                                         Promo_Category__c = 'Exclusive',
                                         Branch_Code__c = 'CCK',
                                         Brand__c = 'KIA',
                                         //RecordTypeId = '012O0000000brQ0IAI',
                                         StartDate = Date.today().addDays(-3),
                                         EndDate = Date.today().addDays(5), 
                                         Promo_Code_Type__c = 'Fixture');
        insert campaign;
        Campaign_Invited_members__c member = new Campaign_Invited_members__c(First_Name__c = 'Tori',
                                                                             Last_Name__c = 'Phan',
                                                                             Email__c = 'phan.thu@aodigy.com',
                                                                             Redeem__c = 'Redeemed',
                                                                             Campaign__c = campaign.Id);
        insert member;
        Promo_gift_line_item__c item = new Promo_gift_line_item__c(Campaign__c = campaign.Id,
                                                                   Gift_type__c = 'Price Discount',
                                                                   Name = '2000');
        insert item;
        
        String reqBody = '{"Email" : "phan.thu@aodigy.com","PromoCode" : "ILYMA2008","PromoCategory" : "Exclusive","Branch" : "CCK","Brand" : "KIA" }';
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = 'services/apexrest/restCheckPromoCode';
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(reqBody);
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestHttpGenerator(200,reqBody));
        restCheckPromoCode.doPost();
        Test.stopTest();
    }
}