force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/Campaign_Promo_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Campaign Upsell Accessory</label>
    <nameField>
        <label>Campaign Upsell Accessories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Upsell Accessories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Item_Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Group_Code__c</fullName>
    <formula>Promo_Line_Item__r.Item_Group_Code__c</formula>
    <label>Item Group Code</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Promo_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Promo_Line_Item__c</fullName>
    <label>Upsell Accessory</label>
    <referenceTo>Promo_Line_Item__c</referenceTo>
    <relationshipLabel>Campaign Upsell Accessories</relationshipLabel>
    <relationshipName>Campaign_Promo_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Amount__c</fullName>
    <formula>Promo_Line_Item__r.Threshold_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Threshold Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/Promo_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Accessories tied to the Targeted Sales Promo campaigns for Upselling Accessories during DSA process.</description>
    <label>Upsell Accessory</label>
    <nameField>
        <label>Upsell Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upsell Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promo_Line_Item__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Promo_Line_Item__c/fields/Item_Group_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Group_Code__c</fullName>
    <label>Item Group Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/fields/No_of_Stock__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stock__c</fullName>
    <label>No. of Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/fields/Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Amount__c</fullName>
    <label>Threshold Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PromoLineItemsTest.cls
/** *****
 * Description : Test Class for PromoLineItems Trigger Handler class
 * 
 * Change History
 * Date(YYYYMMDD)       Name                      Description
 * 20220518             thanh.ly@aodigy           Created Initial Version. 
 * 
** *****/
@isTest
private class PromoLineItemsTest {
    @TestSetup
    private static void setup(){
        User user = Test_DataFactory.createUser(true, 'Thanh', '123');
        
        Campaign cam = Test_DataFactory.createCamp(false, 'Targeted Promo Kia', 'Test', 'CCK');
        cam.Status = 'Planned';
        cam.StartDate = Date.today();
        cam.EndDate = Date.today() + 1;
        cam.Description = 'Targeted Promo Kia';
        cam.Brand__c = 'KIA';
        cam.IsActive = true;
        cam.OwnerId = user.Id;
        insert cam;

        Promo_Line_Item__c item1 = Test_DataFactory.createPromoLineItem(false, 'USB Device', 30, 20, 'Blue', 10);
        item1.Item_Group_Code__c = '001';
        item1.Threshold_Amount__c = 100;
        insert item1;

        Promo_Line_Item__c item2 = Test_DataFactory.createPromoLineItem(false, 'Firefly Bluetooth Receiver', 40, 30, null, 10);
        item2.Threshold_Amount__c = 80;
        insert item2;

        Campaign_Promo_Line_Item__c camItem1 = Test_DataFactory.createCampaignPromoLineItem(true, cam.Id, item1.Id);
        Campaign_Promo_Line_Item__c camItem2 = Test_DataFactory.createCampaignPromoLineItem(true, cam.Id, item2.Id);
        
        Account acc = Test_DataFactory.createAccount(true, 'Test');
        Contact con = Test_DataFactory.createContact(true, null, 'Sales Targeted Dummy Contact', acc.Id);
    }
    
    @isTest
    private static void testOnAfterUpdate(){
        List<Promo_Line_Item__c> promoItems = new List<Promo_Line_Item__c>();
        promoItems = [SELECT Id, No_of_Stock__c, Threshold_Amount__c
                        FROM Promo_Line_Item__c];
        promoItems[0].No_of_Stock__c = 9;
        update promoItems;
    }
}