force-app/main/default/objects/Campaign/fields/Sales_Targeted_Promo_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Targeted_Promo_Type__c</fullName>
    <label>Sales Targeted Promo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/TC_Val__c.field-meta.xml
<CustomField>
    <fullName>TC_Val__c</fullName>
    <inlineHelpText>Term &amp; condition for in-app promo. content need to copy &amp; paste from sitecore</inlineHelpText>
    <label>TC_Val</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Vehicle__c/Campaign_Member_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Campaign Member and Vehicles</label>
    <nameField>
        <label>Campaign Member  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member and Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles (Account)</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CampaignMemberAndVehicleTest.cls
/** ******
 * Description: Test Class for CampaignMemberAndVehicles Trigger handler
 * 
 * Change History:
 * Date(YYYYMMDD)       Name                    Description
 * 20220520             thanh.ly@aodigy.com     Created Initial Version. 
** ******/
@isTest
private class CampaignMemberAndVehicleTest {
    @TestSetup
    private static void setup(){
        Account acc = Test_DataFactory.createAccount(true, 'Bob');
        Contact con = Test_DataFactory.createContact(true, 'Bob', 'Lee', acc.Id);
        
        Campaign camp = Test_DataFactory.createCamp(false, 'Paid Event', 'type', 'CCK');
        Id campRT = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('C&C Campaign RT (Sales Targeted Promo)').getRecordTypeId();
        camp.RecordTypeId = campRT;
        camp.Type = 'Sales Targeted Promo';
        camp.Sales_Targeted_Promo_Type__c = 'Single';
        insert camp;

        Campaign camp1 = Test_DataFactory.createCamp(false, 'Test', 'Promotions', 'CCK');
        camp1.RecordTypeId = campRT;
        camp1.TC_Val__c = 'Hello';
        camp1.Sales_Targeted_Promo_Type__c = 'Single';
        insert camp1;
    }
    @isTest
    private static void testOnAfterInsert_TCNull() {
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Campaign cam = [SELECT Id FROM Campaign WHERE Name = 'Paid Event'];
        Campaign_Member_Vehicle__c camMemVehicle = new Campaign_Member_Vehicle__c();
        camMemVehicle.Name = 'Test';
        camMemVehicle.Campaign__c = cam.Id;
        camMemVehicle.Contact__c = con.Id;
        camMemVehicle.Account__c = acc.Id;
        insert camMemVehicle;
    }

    @isTest
    private static void testOnAfterInsert_TC() {
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Campaign cam1 = [SELECT Id FROM Campaign WHERE Name = 'Test'];
        Campaign_Member_Vehicle__c camMemVehicle1 = new Campaign_Member_Vehicle__c();
        camMemVehicle1.Name = 'Test 123';
        camMemVehicle1.Campaign__c = cam1.Id;
        camMemVehicle1.Contact__c = con.Id;
        camMemVehicle1.Account__c = acc.Id;
        insert camMemVehicle1;
    }
}