force-app/main/default/objects/Manufacturer_Invoice__c/Manufacturer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Inward Declaration Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inward Declaration Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manufacturer_Invoice__c/fields/Vehicle_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Shipment</label>
    <referenceTo>Vehicle_Shipment__c</referenceTo>
    <relationshipName>Manufacturer_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/Shipment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Shipment Line Item</label>
    <nameField>
        <displayFormat>SLI-{YYYYMM}-{00000}</displayFormat>
        <label>Shipment Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Vehicle_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Shipment__c</fullName>
    <label>Vehicle Shipment</label>
    <referenceTo>Vehicle_Shipment__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Shipment__c/Vehicle_Shipment__c.object-meta.xml
<CustomObject>
    <label>Vehicle Shipment</label>
    <nameField>
        <displayFormat>Ship-{YYYYMM}-{00000}</displayFormat>
        <label>Vehicle Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ManufacturerInvoiceSelectorTest.cls
/*==========================================================================================================================================================================
 * Test class for Manufacturer Invoice Entity
 * Created By: Aodigy Team
 * Create Date: August 2022
 * History
 *              DATE::                              BY::                                TICKET::                                            CHANGELOG
 *           6 Sep 2022                        nam@aodigy.com                                                                               init
 * ========================================================================================================================================================================== 
 */
@isTest
public with sharing class ManufacturerInvoiceSelectorTest {
    @TestSetup
    static void makeData(){
       
         // create account supplier
        Account supplier = Test_DataFactory.createAccount(true, 'Supplier Account');

        //create vehicle shipment 
        Vehicle_Shipment__c VehicleShipment         = Test_DataFactory.createVehicleShipment(true, supplier.Id);

        // create manufacturer invoice
        Manufacturer_Invoice__c manufacturerInvoice = Test_DataFactory.createManufacturerInvoice(true);

         //create shipment line item
         Shipment_Line_Item__c shipmentLineItem     = Test_DataFactory.createShipmentLineItem(true, VehicleShipment.Id, manufacturerInvoice.Id);

    }
    /**
     * Get Manufaturer Invoice together with Shipment Line Item via correct MI Id
     * Expected: correct MI retrieved together with related SLI
     */
    @IsTest
    private static void getManufacturerInvoiceWithShipmentLineItems_success()
    {
        Manufacturer_Invoice__c invoice = [SELECT Id FROM Manufacturer_Invoice__c];

        ManufacturerInvoiceSelector selector = new ManufacturerInvoiceSelector();

        List<Manufacturer_Invoice__c> result = selector.selectManufacturerInvoiceWithSLIByIds(new Set<Id> {invoice.Id});

        // result should contain 1 invoice
        System.assert(result.size() == 1, 'Actual result size: ' + result.size());

    }
    /**
     * Get Manufaturer Invoice together with Vehicle Shipment via correct MI Id
     * Expected: correct MI retrieved together with related Vehicle Shipment
     */
    @IsTest
    private static void getManufacturerInvoicesByVehicleShipment_success()
    {
        Manufacturer_Invoice__c invoice = [SELECT Id FROM Manufacturer_Invoice__c];

        ManufacturerInvoiceSelector selector = new ManufacturerInvoiceSelector();

        List<Manufacturer_Invoice__c> result = selector.selectManufacturerInvoicesByVehicleShipmentIds(new Set<Id> {invoice.Id});

    }

    @IsTest
    private static void selectManufacturerInvoicesByInvoiceNos_success()
    {
        Manufacturer_Invoice__c invoice = [SELECT Id FROM Manufacturer_Invoice__c];

        ManufacturerInvoiceSelector selector = new ManufacturerInvoiceSelector();

        List<Manufacturer_Invoice__c> result = selector.selectManufacturerInvoicesByInvoiceNos(new Set<String> {invoice.Id});

    }

}