cncProd/force-app/main/default/objects/Campaign/fields/Actual_Cost_in_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Actual_Cost_in_Campaign__c</fullName>
    <label>Actual Cost in Campaign</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/Budgeted_Cost_in_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Budgeted_Cost_in_Campaign__c</fullName>
    <label>Budgeted Cost In Campaign</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/CampaignId__c.field-meta.xml
<CustomField>
    <fullName>CampaignId__c</fullName>
    <displayFormat>CID-{0}</displayFormat>
    <label>CampaignID</label>
    <type>AutoNumber</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/CTA__c.field-meta.xml
<CustomField>
    <fullName>CTA__c</fullName>
    <label>CTA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy Now</fullName>
            </value>
            <value>
                <fullName>Book a Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/IsExclusive__c.field-meta.xml
<CustomField>
    <fullName>IsExclusive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsExclusive</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/Target_Audience__c.field-meta.xml
<CustomField>
    <fullName>Target_Audience__c</fullName>
    <label>Target Audience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public and Targeted</fullName>
            </value>
            <value>
                <fullName>Targeted Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/recordTypes/C_C_Campaign_RT_Sales_Targeted_Promo.recordType-meta.xml
<RecordType>
    <fullName>C_C_Campaign_RT_Sales_Targeted_Promo</fullName>
    <active>true</active>
    <description>This is the Record Type for Sales Targeted Promotions</description>
    <label>C&amp;C Campaign RT (Sales Targeted Promo)</label>
</RecordType>

force-app/main/default/objects/Campaign_Member_Vehicle__c/Campaign_Member_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Campaign Member and Vehicles</label>
    <nameField>
        <label>Campaign Member  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member and Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles (Account)</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Offboarded__c.field-meta.xml
<CustomField>
    <fullName>Offboarded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Offboarded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated in case of Sales Targeted Promo</description>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Please enter the last 4 digits of the Customer&apos;s NRIC followed by the Date of Birth in the following format DDMMYYY. E.g. 314B10101976</inlineHelpText>
    <label>NRIC _ Passport No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Agreements (Account)</relationshipLabel>
    <relationshipName>Sales_Agreements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Branch_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CCF</fullName>
    </customValue>
    <customValue>
        <fullName>CCK</fullName>
    </customValue>
    <customValue>
        <fullName>CCA</fullName>
    </customValue>
    <customValue>
        <fullName>CNC</fullName>
        <isActive>false</isActive>
        <label>CNC</label>
    </customValue>
    <masterLabel>Branch Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GetCampaign_RegisteredVehicle_fromNRIC.cls
/** *****
 * Description : GetCampaign_RegisteredVehicle_fromNRIC API
 * 
 * Change History:
 * Date(YYYYMMDD)      Name                          Description
 * 20180630            Jacob Khouli                  Created Initial Version. 
 * 20200921            khanh.do@aodigy               Added PA - Phase 2 Changes
 * 20210412            phan.thu@aodigy               Added logic on line 66 - Generic AfterSales Promotions
** *****/
@RestResource(urlMapping='/GetCampaign_RegisteredVehicle_fromNRIC/v1/*')
global with sharing class GetCampaign_RegisteredVehicle_fromNRIC {

    @HttpGet
    global static void GetCampaign_RegisteredVehicle_fromNRIC() 
    {
        //Get NRIC ID from the request URL here
        RestRequest request = RestContext.request;
        String InputNRIC = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        String Errormsg='';
        
        List<Campaign> records = new List<Campaign>();    
        RestResponse res = RestContext.response;
        Map<String, String> errorRes = new Map<String, String>();
        List<Map<String, String>> errorResList = new List<Map<String, String>>();

		System.debug('InputNRIC ++ ' + InputNRIC);
        
        //Check if input NRIC is not blank  
        if( String.isNotBlank(InputNRIC) )
        {
            try
            {	
                //Get all the CampaignId based upon the CampaignMemebers having NRIC_Passport_No__c equal to NRIC provided in request.                    
                //Put all of the CampaignId's into List of type string
                List<String> CampaignMemList = new List<String>();
                
				//for(CampaignMember cm: [SELECT CampaignId FROM CampaignMember WHERE /*Contact.NRIC_Passport_No__c =:c.NRIC_Passport_No__c*/ ContactId =: InputNRIC]) 
                //{
                //    if(cm.CampaignId != null)
                //    {
                //        CampaignMemList.add(cm.CampaignId);  
                //    } 
                //}       

				for(Campaign_Member_Vehicle__c cmv : [select Campaign__r.id, Campaign__r.RecordType.DeveloperName, Offboarded__c from Campaign_Member_Vehicle__c where Contact__c=: InputNRIC])
				{
					if(cmv.Campaign__r.id != null)
					{
                        if ((cmv.Campaign__r.RecordType.DeveloperName == 'C_C_Campaign_RT_Sales_Targeted_Promo' && cmv.Offboarded__c == false)
                            || (cmv.Campaign__r.RecordType.DeveloperName <> 'C_C_Campaign_RT_Sales_Targeted_Promo'))
                        {
                            CampaignMemList.add(cmv.Campaign__r.id);
                        }
					}
				}
                
                //Get all the Campaign and Registered Vehicles related to that Campaign based upon the list of the Campaigns returned above. 
                records = [SELECT Name, Description, Type, Status, StartDate, EndDate, Parent.Id, Owner.Id, 
                                  Actual_Cost_in_Campaign__c, Budgeted_Cost_in_Campaign__c,
                                  IsExclusive__c, CTA__c, CampaignID__c, Branch_Code__c,
                                  ( SELECT Registered_Vehicle__c, Account__c, Sales_Agreement__c
                                    FROM Campaign_Member_and_Vehicles__r 
                                    WHERE Contact__c =: InputNRIC
                                    //Contact__r.NRIC_Passport_No__c = :c.NRIC_Passport_No__c
                                    AND Offboarded__c = false)
                           FROM Campaign 
                           WHERE Id IN : CampaignMemList 
                           AND IsActive = true 
                           AND EndDate >= Today 
                           AND Target_Audience__c != 'Public And Targeted'
                           ORDER BY StartDate DESC, CreatedDate DESC];
                
                res.statusCode = 200;            
            }
            //Catch the error If any
            catch (DmlException e)
            {   
                errorMsg = 'A system exception has occurred, Please contact your administrator.';
                errorRes.put('ErrorCode', 'Err04-SF');
                errorRes.put('Message', errorMsg);  
                errorResList.add(errorRes);
                res.responseBody = Blob.valueOf(JSON.serialize(errorResList));
                res.statusCode=400;
            }
        }
        else
        {
            //Throw an error If input NRIC is blank
            Errormsg='Required fields not supplied. Fields: InputNRIC';      
            res.statusCode=400;
            errorRes.put('ErrorCode', 'Err02-SF');
            errorRes.put('Message', errorMsg);  
            errorResList.add(errorRes);
            res.responseBody = Blob.valueOf(JSON.serialize(errorResList));
        }    
        //Return List of registered vehicles      
        if(res.statusCode == 200)
        {
            res.responseBody = Blob.valueOf(JSON.serialize(records).replace('Budgeted_Cost_in_Campaign__c','BudgetedCost').replace('Actual_Cost_in_Campaign__c','ActualCost'));
        }
        RestContext.response = res;
        res.addHeader('Content-Type', 'application/json');
    }
}