cncProd/force-app/main/default/objects/Campaign/fields/Actual_Cost_in_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Actual_Cost_in_Campaign__c</fullName>
    <label>Actual Cost in Campaign</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/Budgeted_Cost_in_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Budgeted_Cost_in_Campaign__c</fullName>
    <label>Budgeted Cost In Campaign</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/CTA__c.field-meta.xml
<CustomField>
    <fullName>CTA__c</fullName>
    <label>CTA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy Now</fullName>
            </value>
            <value>
                <fullName>Book a Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/TC_Val__c.field-meta.xml
<CustomField>
    <fullName>TC_Val__c</fullName>
    <inlineHelpText>Term &amp; condition for in-app promo. content need to copy &amp; paste from sitecore</inlineHelpText>
    <label>TC_Val</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

cncProd/force-app/main/default/classes/CampaignPromoForPublicAPI.cls
/** *****
* Description : Get Campaigns for public
* End Point: 
* Method : POST 
* 
* Change History
* Date(YYYYMMDD)       Name                            Description
* 20210407             tphung@aodigy.com             	Created Initial Version. 
* 
** *****/
@RestResource(urlMapping = '/promotion/getCampaigns/*')
global with sharing class CampaignPromoForPublicAPI {
    
    private static RestRequest req = RestContext.request;
    private static RestResponse res = RestContext.response;
    private static RequestBody reqBody = new RequestBody();
    private static ResponseBody resBody = new ResponseBody();
    private static httpErrorResponse errorResponse;     
    private static List<Campaign> campaignList = new List<Campaign>();
    private static List<String> campaignsNoTC = new List<String>();
    
    @HttpPost
    global static void doPost(){
        res.addHeader('Content-Type','application/json');
        
        try{
            processPostRequest();
            
        }catch(Exception e){
            loggerDataPool.buildLogDataPool('CampaignPromoForPublicAPI', e);
            errorResponse = new httpErrorResponse('Failed',e.getMessage());
        }
        if(errorResponse !=null && errorResponse.status == 'Failed'){
            res.statusCode = 400;
            res.responseBody = Blob.valueOf(JSON.serialize(errorResponse));
        }
        serviceDataPool.buildServiceDataPool('CampaignPromoForPublicAPI', 'CampaignPromoForPublicAPI', '', req, res);

        if (campaignsNoTC.size() > 0)
        {
            InvoiceEmail_ProcessBuilder_RestTC.apexcallout(campaignsNoTC);
        }
    }
    
    public static void processPostRequest(){
        reqBody = (RequestBody)JSON.deserialize(req.requestBody.toString(), RequestBody.class);
        String brand = reqBody.Brand;
        String branchCode = reqBody.BranchCode;
        if(String.isBlank(brand) || String.isBlank(branchCode)){
            errorResponse = new httpErrorResponse('Failed','Mandatory Fields Missing');
        }
        else{
            // query cond: status planned, public, matching brand,branchcode, isactive 
            campaignList = CampaignService.getCampaignListByBrandAndBranchCode(brand, branchCode);
            generateResponseBody();
        }
        
    }
    
    public static void generateResponseBody(){
        List<PromoCampaign> promoCampaigns = new List<PromoCampaign>();
        if(campaignList.size() > 0){
            for (Campaign proCampaign :campaignList)
            {
                PromoCampaign cam = new PromoCampaign();
                cam.CampaignID = proCampaign.Id;
                cam.Name = proCampaign.Name;
                cam.Description = proCampaign.Description;
                cam.Type = proCampaign.Type;
                cam.Status = proCampaign.Status;
                cam.StartDate = proCampaign.StartDate <> null ?  proCampaign.StartDate.format() : ''; //check if null to prevent null exception
                cam.EndDate = proCampaign.EndDate <> null ? proCampaign.EndDate.format() : ''; //check if null to prevent null exception           
                cam.ActualCost = proCampaign.Actual_Cost_in_Campaign__c;
                cam.DiscountCost = proCampaign.Budgeted_Cost_in_Campaign__c;
                cam.CTA = proCampaign.CTA__c <> null ? proCampaign.CTA__c : '';
                cam.Brand = proCampaign.Brand__c;
                cam.BranchCode = proCampaign.Branch_Code__c;
                promoCampaigns.add(cam);

                if (proCampaign.TC_Val__c == null)
                {
                    campaignsNoTC.add(proCampaign.Id);
                }
            }            
        }

        resBody.Campaigns = promoCampaigns;
        //resBody.message = 'This is a message.';
        res.statusCode = 200;
        res.responseBody = Blob.valueOf(JSON.serialize(resBody));
    }
    public class RequestBody{
        public String BranchCode;
        public String Brand;
    }
    
    public class ResponseBody{
        public List<PromoCampaign> Campaigns; 
        //public String message;
    }
    
    public class PromoCampaign{
        public String CampaignID;
        public String Name;
        public String Description;
        public String Type;
        public String Status;
        public String StartDate;
        public String EndDate;
        public Decimal ActualCost;
        public Decimal DiscountCost;
        public String CTA;
        public String BranchCode;
        public String Brand;
    }
    
    public class httpErrorResponse{
        public String status;
        public String message;
        public httpErrorResponse(String statusValue,String messageValue){
            status = statusValue;
            message = messageValue;
            
        }
    }
    
    
}