cncProd/force-app/main/default/objects/Campaign/fields/Campaign_ID_18_Char__c.field-meta.xml
<CustomField>
    <fullName>Campaign_ID_18_Char__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign ID 18 Char</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/TC_Val__c.field-meta.xml
<CustomField>
    <fullName>TC_Val__c</fullName>
    <inlineHelpText>Term &amp; condition for in-app promo. content need to copy &amp; paste from sitecore</inlineHelpText>
    <label>TC_Val</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Vehicle__c/Campaign_Member_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Campaign Member and Vehicles</label>
    <nameField>
        <label>Campaign Member  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member and Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles (Account)</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/global_var__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>JCC Global Variables</label>
</CustomObject>

force-app/main/default/objects/global_var__c/fields/APIGateway_key__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_key__c</fullName>
    <label>APIGateway_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/fields/APIGateway_url__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_url__c</fullName>
    <label>APIGateway_url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/AddCampaignMember.cls
public class AddCampaignMember {

    @InvocableMethod
    public static void InsertRecords(List<Id> Campaign_Contact_ID)
    {

		string cmpgId ='';
        List<Campaign_Member_Vehicle__c> cmv = [SELECT Contact__c,Campaign__c, Campaign__r.Campaign_ID_18_Char__c, Account__c from Campaign_Member_Vehicle__c
                                                WHERE Id in :Campaign_Contact_ID];

        List<CampaignMember> CM = new List<CampaignMember>();
        for(Campaign_Member_Vehicle__c TempCmv : cmv)
        {
            CampaignMember TempCM = new CampaignMember();
            TempCM.CampaignId = TempCmv.Campaign__c;
            TempCM.ContactId = TempCmv.Contact__c;
            CM.add(TempCM);
			cmpgId = TempCmv.Campaign__r.Campaign_ID_18_Char__c;
        }
        try
        {
			updateTC_Cmpg(cmpgId);
            database.insert(CM,false);
        }
        catch(Exception e)
        { 
            loggerDataPool.buildLogDataPool('AddCampaignMember', e);
            System.debug('An exception occurred: ' + e.getMessage());		
		}

    }

	//replicated method from InvoiceEmail_ProcessBuilder_RestTC
	@future (callout=true)
	public static void updateTC_Cmpg (string CampaignId)
	{
		string promoid = CampaignId;

		HttpRequest req = new HttpRequest();
		HttpResponse resInput = new HttpResponse();
		Http http = new Http();
		String TC_Val = '';
		global_var__c JCC_GlobalVar = global_var__c.getOrgDefaults();      
		System.debug('+++ '+ JCC_GlobalVar);
		//String  APIGateway_url =   'https://api.stg.cyclecarriage.com/CmsAPI/GetPromos' ;
		String  APIGateway_url =	(String)JCC_GlobalVar.APIGateway_url__c;
		String  APIGateway_key =    (String)JCC_GlobalVar.APIGateway_key__c;     
    
		//Rest call to CMS for getting the T&C data.
		req.setEndpoint(APIGateway_url+'/CmsAPI/GetPromos');
		req.setMethod('POST');
		req.setHeader('Content-Type', 'application/json;charset=UTF-8'); 
		//req.setHeader('apikey', '1b58ae26-48d4-4efc-944d-f089258f81sf2');  
		System.debug('+++ '+ APIGateway_url + '+++ ' + APIGateway_key);
		req.setHeader('apikey', APIGateway_key);             
		req.setBody('{"PromoIDs": ["'+promoid+'"], "CountryName": "SG"}');
		req.setTimeout(120000);  
		system.debug('1==='+req.getBody());
		try 
		{   
			//Send http request, capture response and pass the response to mothod       
			resInput = http.send(req); 
			Invoice_TC_JSON2Apex sVar = Invoice_TC_JSON2Apex.parse(resInput.getBody());           
			TC_Val = sVar.Result.Promo[0].PromoTermsAndConditions.Content;
			system.debug('2==='+TC_Val);

			Campaign updateCmpgObj = new Campaign(id = CampaignId);
			updateCmpgObj.TC_Val__c = TC_Val;
			update updateCmpgObj;

		}
		catch(exception ex1)
		{
			system.debug(ex1.getMessage());
		}

	}

}