cncProd/force-app/main/default/objects/Campaign/fields/Deep_linking_URL__c.field-meta.xml
<CustomField>
    <fullName>Deep_linking_URL__c</fullName>
    <inlineHelpText>This is for deeplinking via different external comms API interface such as SMS, Email, Push Notification</inlineHelpText>
    <label>Deep linking URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Promo_Inbox_Text__c.field-meta.xml
<CustomField>
    <fullName>Promo_Inbox_Text__c</fullName>
    <label>Promo Inbox Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Sales_Targeted_Promo_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Targeted_Promo_Type__c</fullName>
    <label>Sales Targeted Promo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/TC_Val__c.field-meta.xml
<CustomField>
    <fullName>TC_Val__c</fullName>
    <inlineHelpText>Term &amp; condition for in-app promo. content need to copy &amp; paste from sitecore</inlineHelpText>
    <label>TC_Val</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/recordTypes/C_C_Campaign_RT_Sales_Targeted_Promo.recordType-meta.xml
<RecordType>
    <fullName>C_C_Campaign_RT_Sales_Targeted_Promo</fullName>
    <active>true</active>
    <description>This is the Record Type for Sales Targeted Promotions</description>
    <label>C&amp;C Campaign RT (Sales Targeted Promo)</label>
</RecordType>

force-app/main/default/objects/Campaign_Member_Vehicle__c/Campaign_Member_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Campaign Member and Vehicles</label>
    <nameField>
        <label>Campaign Member  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member and Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles (Account)</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/CustomerAlerts__c.object-meta.xml
<CustomObject>
    <label>CustomerAlerts</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerAlerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CustomerAlerts (Account)</relationshipLabel>
    <relationshipName>CustomerAlerts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Alert_Description__c.field-meta.xml
<CustomField>
    <fullName>Alert_Description__c</fullName>
    <label>Alert Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign Lookup Reference</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Deep_Linking_URL__c.field-meta.xml
<CustomField>
    <fullName>Deep_Linking_URL__c</fullName>
    <inlineHelpText>For deeplink</inlineHelpText>
    <label>Deep Linking URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isAlert__c.field-meta.xml
<CustomField>
    <fullName>isAlert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isAlert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isEmail__c.field-meta.xml
<CustomField>
    <fullName>isEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isEmail</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/isPush__c.field-meta.xml
<CustomField>
    <fullName>isPush__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPush</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isSMS__c.field-meta.xml
<CustomField>
    <fullName>isSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSMS</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>unread</fullName>
            </value>
            <value>
                <fullName>read</fullName>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
            <value>
                <fullName>eyriuwbicaueiq</fullName>
                <isActive>false</isActive>
                <label>eyriuwbicaueiq</label>
            </value>
            <value>
                <fullName>unred</fullName>
                <isActive>false</isActive>
                <label>unred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>SubType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due 1st Reminder</fullName>
            </value>
            <value>
                <fullName>Due 2nd Reminder</fullName>
            </value>
            <value>
                <fullName>Due 3rd Reminder</fullName>
            </value>
            <value>
                <fullName>Overdue 1st Reminder</fullName>
            </value>
            <value>
                <fullName>Overdue 2nd Reminder</fullName>
            </value>
            <value>
                <fullName>Overdue 3rd Reminder</fullName>
            </value>
            <value>
                <fullName>E-shop</fullName>
            </value>
            <value>
                <fullName>Notice</fullName>
            </value>
            <value>
                <fullName>Evergreen Promotion</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Paid Event</fullName>
            </value>
            <value>
                <fullName>Non-Paid Event</fullName>
            </value>
            <value>
                <fullName>Sales Targeted Promo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First Service</fullName>
            </value>
            <value>
                <fullName>Subsequent Service</fullName>
            </value>
            <value>
                <fullName>Plan/Package</fullName>
            </value>
            <value>
                <fullName>Service Credits</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
            <value>
                <fullName>Battery Change</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
            <value>
                <fullName>Accessories Credits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/recordTypes/Alert.recordType-meta.xml
<RecordType>
    <fullName>Alert</fullName>
    <active>true</active>
    <description>Customer Alert</description>
    <label>Alert</label>
</RecordType>

cncProd/force-app/main/default/objects/CustomerAlerts__c/recordTypes/Broadcast.recordType-meta.xml
<RecordType>
    <fullName>Broadcast</fullName>
    <active>true</active>
    <description>Broadcast-typed Customer Alert</description>
    <label>Broadcast</label>
</RecordType>

cncProd/force-app/main/default/classes/CampaignMemberAndVehicles.cls
/** ******
 * Description: Trigger handler for the Campaign_Member_Vehicle__c custom object
 * 
 * Change History:
 * Date(YYYYMMDD)       Name                Description
 * 20220415           TPhan@aodigy.com    Created Initial Version. 
** ******/

public class CampaignMemberAndVehicles extends ADGLIB_SObjectDomain
{
    public CampaignMemberAndVehicles(List<Campaign_Member_Vehicle__c> sObjectList) 
    {
        super(sObjectList);
    }

    public class Constructor implements ADGLIB_SObjectDomain.IConstructable 
    {
		public ADGLIB_SObjectDomain construct(List<SObject> sObjectList) 
        {
			return new CampaignMemberAndVehicles(sObjectList);
		}
	}

    public override void onAfterInsert()
    {
        createCustomerAlerts();
    }

    private void createCustomerAlerts()
    {
        List<String> campaignsNoTC        = new List<String>();
        List<CustomerAlerts__c> newAlerts = new List<CustomerAlerts__c>();
        
        Map<String,Schema.RecordTypeInfo> recType     = BroadcastController.getCustomerAlertRtByDeveloperName();
        List<Campaign_Member_Vehicle__c> campaignMems = [SELECT Campaign__c, Campaign__r.TC_Val__c, Campaign__r.Sales_Targeted_Promo_Type__c, Campaign__r.Deep_Linking_URL__c,
                                                                Campaign__r.RecordType.DeveloperName, Campaign__r.Type, Campaign__r.Promo_Inbox_Text__c,
                                                                Contact__c, Contact__r.AccountId
                                                        FROM Campaign_Member_Vehicle__c 
                                                        WHERE ID IN: Trigger.new];

        for (Campaign_Member_Vehicle__c member: campaignMems)
        {
            if (member.Campaign__r.RecordType.DeveloperName == 'C_C_Campaign_RT_Sales_Targeted_Promo' && member.Campaign__r.Type == 'Sales Targeted Promo')
            {
                newAlerts.add(new CustomerAlerts__c(Name = 'Notification',
                                                    Date__c = System.today(),
                                                    DateTime__c = System.now(),
                                                    Status__c = 'unread',
                                                    isAlert__c = true,
                                                    isEmail__c = false,
                                                    isPush__c = false,
                                                    isSMS__c = false,
                                                    Type__c = 'Broadcast',
                                                    Account__c = member.Contact__r.AccountId,
                                                    Contact__c = member.Contact__c,
                                                    Alert_Description__c = member.Campaign__r.Promo_Inbox_Text__c,
                                                    Description__c = member.Campaign__r.Promo_Inbox_Text__c,
                                                    Deep_Linking_URL__c = member.Campaign__r.Deep_Linking_URL__c,
                                                    Campaign__c = member.Campaign__c,
                                                    SubType__c = 'Sales Targeted Promo',
                                                    RecordTypeId = recType.containsKey('Broadcast') ? recType.get('Broadcast').getRecordTypeId() : ''));
                
                if (member.Campaign__r.Sales_Targeted_Promo_Type__c == 'Single' && member.Campaign__r.TC_Val__c == null && !campaignsNoTC.contains(member.Campaign__c))
                {
                    campaignsNoTC.add(member.Campaign__c);
                }
            }
        }

        if (!campaignsNoTC.isEmpty())
        {
            if (System.isBatch() == false && System.isFuture() == false)
            {
                if (!newAlerts.isEmpty())
                {          
                    insert newAlerts;
                }

                InvoiceEmail_ProcessBuilder_RestTC.apexcallout(campaignsNoTC);                     
            }

            if (System.isBatch() == true || System.isFuture() == true || System.Test.isRunningTest())
            {
                Set<Id> alertIds = new Set<Id>();

                if (!newAlerts.isEmpty() && !System.Test.isRunningTest())
                { 
                    TriggerExclusion.excludeTrigger('CustomerAlerts__c', true);         
                    insert newAlerts;
                    TriggerExclusion.excludeTrigger('CustomerAlerts__c', false);

                    for (CustomerAlerts__c alert : newAlerts)
                    {
                        alertIds.add(alert.Id);
                    }
                }

                System.enqueueJob(new InvoiceEmail_RestTCQueueable(campaignsNoTC, alertIds));
            }
        }
        else 
        {                     
            if (!newAlerts.isEmpty())
            {          
                insert newAlerts;
            }
        }
    }
}