cncProd/force-app/main/default/objects/Campaign/fields/Deep_linking_URL__c.field-meta.xml
<CustomField>
    <fullName>Deep_linking_URL__c</fullName>
    <inlineHelpText>This is for deeplinking via different external comms API interface such as SMS, Email, Push Notification</inlineHelpText>
    <label>Deep linking URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/CustomerAlerts__c.object-meta.xml
<CustomObject>
    <label>CustomerAlerts</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerAlerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CustomerAlerts (Account)</relationshipLabel>
    <relationshipName>CustomerAlerts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign Lookup Reference</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Deep_Linking_URL__c.field-meta.xml
<CustomField>
    <fullName>Deep_Linking_URL__c</fullName>
    <inlineHelpText>For deeplink</inlineHelpText>
    <label>Deep Linking URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isAlert__c.field-meta.xml
<CustomField>
    <fullName>isAlert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isAlert</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/recordTypes/Alert.recordType-meta.xml
<RecordType>
    <fullName>Alert</fullName>
    <active>true</active>
    <description>Customer Alert</description>
    <label>Alert</label>
</RecordType>

cncProd/force-app/main/default/objects/CustomerAlerts__c/recordTypes/Broadcast.recordType-meta.xml
<RecordType>
    <fullName>Broadcast</fullName>
    <active>true</active>
    <description>Broadcast-typed Customer Alert</description>
    <label>Broadcast</label>
</RecordType>

force-app/main/default/classes/InvoiceEmail_RestTCQueueableTest.cls
/** ******
 * Description : Test Class for InvoiceEmail_RestTCQueueable class
 * 
 * Change History : 
 * Date(YYYYMMDD)      Name                        Description
 * 20220519            thanh.ly@aodigy.com         Created Initial Version
 * 
** ******/
@isTest
private class InvoiceEmail_RestTCQueueableTest {
    @TestSetup
    private static void setup(){
        Campaign camp = Test_DataFactory.createCamp(true, 'Paid Event', 'type', 'CCK');

        Account acc = Test_DataFactory.createAccount(false, 'Thanh');
        insert acc;
        Contact con = Test_DataFactory.createContact(true, 'Thanh', 'Ly', acc.Id);

        Id alertRT = Schema.SObjectType.CustomerAlerts__c.getRecordTypeInfosByName().get('Broadcast').getRecordTypeId();
        CustomerAlerts__c alert = Test_DataFactory.createCusAlert(false, 'Notification', con.Id);
        alert.isAlert__c = true;
        alert.Account__c = acc.Id;
        alert.Description__c = 'Test';
        alert.Deep_Linking_URL__c = 'https:/123/';
        alert.Campaign__c = camp.Id;
        alert.RecordTypeId = alertRT;
        insert alert;
    }

    @isTest
    private static void testExecute() {
        Campaign camp = [SELECT Id FROM Campaign LIMIT 1];
        CustomerAlerts__c alert = [SELECT Id FROM CustomerAlerts__c LIMIT 1];

        Test.setMock(HttpCalloutMock.class, new InvoiceEmail_ProcessBuilder_RestTCMock());
        Test.startTest();
        InvoiceEmail_RestTCQueueable restTC = new InvoiceEmail_RestTCQueueable(new List<String> {(String)camp.Id}, new Set<Id> {alert.Id});
        System.enqueueJob(restTC);
        Test.stopTest();
    }
}