cncProd/force-app/main/default/objects/Campaign/fields/Promo_PUSH_Text__c.field-meta.xml
<CustomField>
    <fullName>Promo_PUSH_Text__c</fullName>
    <label>Promo PUSH Text</label>
    <type>TextArea</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/Promo_SMS_Text__c.field-meta.xml
<CustomField>
    <fullName>Promo_SMS_Text__c</fullName>
    <label>Promo SMS Text</label>
    <type>TextArea</type>
</CustomField>

cncProd/force-app/main/default/objects/CampaignMember/fields/SMS_Status__c.field-meta.xml
<CustomField>
    <fullName>SMS_Status__c</fullName>
    <label>SMS Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Responded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignMember_Promo_Push_SMS_Test.cls
@isTest
private class CampaignMember_Promo_Push_SMS_Test {

    @isTest
    private static void testOnInsert() {
        Account acc = Test_DataFactory.createAccount(true, 'Bob');
        Contact con = Test_DataFactory.createContact(true, 'Bob', 'Lee', acc.Id);
        
        Campaign camp = Test_DataFactory.createCamp(false, 'Paid Event', 'type', 'CCK');
        camp.Promo_PUSH_Text__c = 'Hi there';
        camp.Promo_SMS_Text__c = 'Hello';
        camp.EndDate = Date.today().addDays(30);
        insert camp;
        
        CampaignMember cm = new CampaignMember();
        cm.CampaignId = camp.Id;
        cm.ContactId = con.Id;
        insert cm;
        
        cm.SMS_Status__c = 'Sent';
        update cm;
    }
    
}