cncProd/force-app/main/default/objects/Accs_Rate_Master__c/Accs_Rate_Master__c.object-meta.xml
<CustomObject>
    <description>Accessories Rate master contain the rate for accessories. Different accessories have different rate</description>
    <label>Accs Rate Master</label>
    <nameField>
        <displayFormat>ARM-{0000000000}</displayFormat>
        <label>Accs Rate Master ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accs Rate Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accs_Rate_Master__c/fields/Accessories__c.field-meta.xml
<CustomField>
    <fullName>Accessories__c</fullName>
    <label>Accessories</label>
    <referenceTo>Accessories_Master__c</referenceTo>
    <relationshipLabel>Accs Rate Master</relationshipLabel>
    <relationshipName>Accs_Rate_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Accs_Rate_Master__c/fields/ARM_EFFDT__c.field-meta.xml
<CustomField>
    <fullName>ARM_EFFDT__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Accs_Rate_Master__c/fields/ARM_SALEPRICE__c.field-meta.xml
<CustomField>
    <fullName>ARM_SALEPRICE__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccsRateMasters.cls
public inherited sharing class AccsRateMasters extends ADGLIB_SObjectDomain {
    public AccsRateMasters(List<Accs_Rate_Master__c> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements ADGLIB_SObjectDomain.IConstructable {
		public ADGLIB_SObjectDomain construct(List<SObject> sObjectList) {
			return new AccsRateMasters(sObjectList);
		}
	}
	
    public override void onAfterInsert() {
		recalculateAccessoriesMasterRate(null);    
    }

    public override void onAfterUpdate(Map<Id, SObject> existingRecords) {
		recalculateAccessoriesMasterRate((Map<Id, Accs_Rate_Master__c>)existingRecords);   
    }

    public override void onAfterDelete() {
		recalculateAccessoriesMasterRate(null);       
    }    
    
    private void recalculateAccessoriesMasterRate(Map<Id, Accs_Rate_Master__c> existingRecords) {
        Set<Id> accMasterIds = new Set<Id>();
        for(Accs_Rate_Master__c armMaster : (List<Accs_Rate_Master__c>)Records) {
            if(existingRecords != null) {
                Accs_Rate_Master__c oldArmMaster = (Accs_Rate_Master__c)existingRecords.get(armMaster.Id);
                if(armMaster.ARM_EFFDT__c != oldArmMaster.ARM_EFFDT__c || 
                   armMaster.ARM_SALEPRICE__c != oldArmMaster.ARM_SALEPRICE__c ||
                   armMaster.Accessories__c != oldArmMaster.Accessories__c)
                {
                    accMasterIds.add(armMaster.Accessories__c);
                }                
            } else {
                accMasterIds.add(armMaster.Accessories__c);
            }
        }        
        
		AccessoriesMasters accessoriesMasters = new AccessoriesMasters(
            new AccessoriesMasterSelector().selectAccsMastersWithRateMastersByIds(accMasterIds)
        );  
        accessoriesMasters.updateRate(); 
    }
}