force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/Model_Color_Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Model Color Trim Master</label>
    <nameField>
        <label>MTC Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Color Trim Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Color Code</label>
    <referenceTo>Color_Master__c</referenceTo>
    <relationshipLabel>Model Color Trim Master</relationshipLabel>
    <relationshipName>ModelColors</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model Code</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Color Trim Master</relationshipLabel>
    <relationshipName>ModelColors</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/fields/Trim_Code__c.field-meta.xml
<CustomField>
    <fullName>Trim_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trim Code</label>
    <referenceTo>Trim_Master__c</referenceTo>
    <relationshipName>ModelColors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Model_Year_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/Vehicle_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Vehicle Purchase Order</label>
    <nameField>
        <displayFormat>PO-{YYYY}{MM}-{00000}</displayFormat>
        <label>Vehicle Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>RMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Franchise_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Production_Month__c.field-meta.xml
<CustomField>
    <fullName>Production_Month__c</fullName>
    <inlineHelpText>Input first day of the month</inlineHelpText>
    <label>Production Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Supplier_Account__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicle Purchase Orders</relationshipLabel>
    <relationshipName>Vehicle_Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Franchise_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CITCV</fullName>
    </customValue>
    <customValue>
        <fullName>CITPC</fullName>
    </customValue>
    <customValue>
        <fullName>KIACV</fullName>
    </customValue>
    <customValue>
        <fullName>KIAPC</fullName>
    </customValue>
    <customValue>
        <fullName>MITCV</fullName>
    </customValue>
    <customValue>
        <fullName>MITPC</fullName>
    </customValue>
    <customValue>
        <fullName>MBCV</fullName>
    </customValue>
    <customValue>
        <fullName>MBPC</fullName>
    </customValue>
    <masterLabel>Franchise Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AttachmentDomainTest.cls
@IsTest
private with sharing class AttachmentDomainTest
{
    @TestSetup
    private static void makeData()
    {
        // create model master
        Model_Master__c modelMaster = Test_DataFactory.createModelCode(true, 'Model Master');

        // create color master
        Color_Master__c colorMaster = Test_DataFactory.createColorCode(true, 'Color Master', 'CM', 'KIA', 'KIAPC');

        // create trim master
        Trim_Master__c trimMaster = Test_DataFactory.createTrimCode(true, 'Trim Master');

        // create model color trim master
        Model_Color_Trim_Master__c modelColorTrimMaster = new Model_Color_Trim_Master__c(
            Name = 'Model Color Trim Master',
            Branch_Code__c = 'KIA',
            Franchise_Code__c = 'KIAPC',
            Model_Code__c = modelMaster.Id,
            Color_Code__c = colorMaster.Id,
            Trim_Code__c = trimMaster.Id
        );
        insert modelColorTrimMaster;

        // create model year master
        Model_Year_Master__c modelYearMaster = Test_DataFactory.createModelYearCode(true, modelMaster.Id);

        // create non-admin user
        Profile salesManagerProfile = [SELECT Id FROM Profile WHERE Name = 'KIAPC Sales Manager'];

        User salesManagerUser = Test_DataFactory.createUserWithProfileID(true, 'Sample', 'SalesManager', 'salesmanager279831@gmail.com', salesManagerProfile.Id);
        
        System.runas(salesManagerUser)
        {
            // create supplier account
            Account supplier = Test_DataFactory.createAccount(true, 'Supplier Account');

            // create PO
            Vehicle_Purchase_Order__c order = new Vehicle_Purchase_Order__c(
                Franchise_Code__c = 'KIAPC',
                Production_Month__c = Date.today(),
                Supplier_Account__c = supplier.Id,
                Currency_Code__c = 'USD'
            );
            insert order;
            
            // insert attachment as sales manager so that this user can edit on test method later
            Attachment snapshot = new Attachment(
                Name = 'snapshot.txt',
                Description = '#snapshot',
                Body = Blob.valueOf('Sample Content'),
                ParentId = order.Id
            );
            insert snapshot;
        }
    }

    /**
     * test deleting snapshot attachment as non-admin user
     * expected: trigger prevent attachment from being deleted
     */
    @IsTest
    private static void deleteSnapShotAsNonAdmin()
    {
        User salesManagerUser = [SELECT Id FROM User WHERE LastName = 'SalesManager'];

        System.runAs(salesManagerUser)
        {
            try
            {
                delete [SELECT Id FROM Attachment WHERE Name = 'snapshot.txt'];
            }
            catch (Exception e)
            {
                System.assert(e.getMessage().contains('Only System Admin is allowed to delete snapshot attachment'), 'Actual exception: ' + e.getMessage());
            }
        }
    }

    /**
     * test deleting snapshot attachment as admin user
     * expected: attachment can be deleted
     */
    @IsTest
    private static void deleteSnapShotAsAdmin()
    {
        delete [SELECT Id FROM Attachment WHERE Name = 'snapshot.txt'];

        List<Attachment> remainings = [SELECT Id FROM Attachment];

        System.assert(remainings.size() == 0, 'Snapshot attachment is not deleted');
    }

    /**
     * test updating snapshot attachment as non-admin user
     * expected: trigger prevent attachment from being updated
     */
    @IsTest
    private static void updateSnapShotAsNonAdmin()
    {
        User salesManagerUser = [SELECT Id FROM User WHERE LastName = 'SalesManager'];

        System.runAs(salesManagerUser)
        {
            try
            {
                Attachment snapshot = [SELECT Id, Description FROM Attachment];

                snapshot.Description = '';
                update snapshot;
            }
            catch (Exception e)
            {
                System.assert(e.getMessage().contains('Only System Admin is allowed to edit snapshot attachment'), 'Actual exception: ' + e.getMessage());
            }
        }
    }

    /**
     * test updating snapshot attachment as non-admin user
     * expected: attachment can be updated
     */
    @IsTest
    private static void updateSnapShotAsAdmin()
    {
        // admin update
        Attachment snapshot = [SELECT Id, Description FROM Attachment];
        snapshot.Description = '';
        update snapshot;

        // assert
        snapshot = [SELECT Id, Description FROM Attachment];
        System.assert(String.isBlank(snapshot.Description), 'Actual snapshot description: ' + snapshot.Description);
    }
}