force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Duty_Additional_Contract__c/Duty_Additional_Contract__c.object-meta.xml
<CustomObject>
    <label>Duty Additional Contract</label>
    <nameField>
        <displayFormat>DAC-{0000000}</displayFormat>
        <label>Duty Additional Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Duty Additional Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Duty_Additional_Contract__c/fields/Cover_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Cover_Percentage__c</fullName>
    <formula>Forward_Duty_Contract__r.Cover_Percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cover Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Duty_Additional_Contract__c/fields/Forward_Duty_Contract__c.field-meta.xml
<CustomField>
    <fullName>Forward_Duty_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forward Duty Contract</label>
    <referenceTo>Forward_Duty_Contract__c</referenceTo>
    <relationshipLabel>Duty Additional Contracts</relationshipLabel>
    <relationshipName>Duty_Additional_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Duty_Additional_Contract__c/fields/Premium_Discount__c.field-meta.xml
<CustomField>
    <fullName>Premium_Discount__c</fullName>
    <formula>Forward_Duty_Contract__r.Premium_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Premium(+) / Discount(-)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Duty_Additional_Contract__c/fields/Spot_Rate__c.field-meta.xml
<CustomField>
    <fullName>Spot_Rate__c</fullName>
    <label>Spot Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Duty_Additional_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Forward Contract Sell</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Completed (PO Cancel)</fullName>
            </value>
            <value>
                <fullName>PO Cancellation</fullName>
            </value>
            <value>
                <fullName>Forward Contract Duty Sale</fullName>
            </value>
            <value>
                <fullName>Forward Contract Execute</fullName>
                <isActive>false</isActive>
                <label>Forward Contract Execute</label>
            </value>
            <value>
                <fullName>Forward Contract Sell on Maturity</fullName>
                <isActive>false</isActive>
                <label>Forward Contract Sell on Maturity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forward_Duty_Contract__c/Forward_Duty_Contract__c.object-meta.xml
<CustomObject>
    <label>Forward Duty Contract</label>
    <nameField>
        <displayFormat>FDC-{0000000}</displayFormat>
        <label>Forward Contract Duty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward Duty Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forward_Duty_Contract__c/fields/Cover_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Cover_Percentage__c</fullName>
    <defaultValue>0.75</defaultValue>
    <label>Cover Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Forward_Duty_Contract__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Forward Duty Contracts</relationshipLabel>
    <relationshipName>Forward_Duty_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forward_Duty_Contract_Line_Item__c/Forward_Duty_Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Forward Duty Contract Line Item</label>
    <nameField>
        <displayFormat>FDCL-{00000000}</displayFormat>
        <label>Forward Duty Contract Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward Duty Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forward_Duty_Contract_Line_Item__c/fields/Duty_Additional_Contract__c.field-meta.xml
<CustomField>
    <fullName>Duty_Additional_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duty Additional Contract</label>
    <referenceTo>Duty_Additional_Contract__c</referenceTo>
    <relationshipLabel>Forward Duty Contract Line Items</relationshipLabel>
    <relationshipName>Forward_Duty_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forward_Duty_Contract_Line_Item__c/fields/Forward_Duty_Contract__c.field-meta.xml
<CustomField>
    <fullName>Forward_Duty_Contract__c</fullName>
    <label>Forward Duty Contract</label>
    <referenceTo>Forward_Duty_Contract__c</referenceTo>
    <relationshipLabel>Forward Duty Contract Line Items</relationshipLabel>
    <relationshipName>Forward_Duty_Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forward_Duty_Contract_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( !ISBLANK( Forward_Duty_Contract__c ) &amp;&amp; ISBLANK( Duty_Additional_Contract__c ) , &apos;Forward Contract Buy&apos; , TEXT( Duty_Additional_Contract__r.Status__c ))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forward_Duty_Contract_Line_Item__c/fields/Stock_Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Stock_Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock Vehicle Master</label>
    <referenceTo>Vehicle_Master2__c</referenceTo>
    <relationshipLabel>Forward Duty Contract Line Items</relationshipLabel>
    <relationshipName>Forward_Duty_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>TMS PO Group</label>
    <nameField>
        <displayFormat>TMSPO-{YYYY}{MM}-{00000}</displayFormat>
        <label>TMS Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMS PO Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>Franchise__c</fullName>
    <label>Franchise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Franchise_Code</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/fields/Chassis__c.field-meta.xml
<CustomField>
    <fullName>Chassis__c</fullName>
    <label>Chassis</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Color Code</label>
    <referenceTo>Color_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Duty_Done__c.field-meta.xml
<CustomField>
    <fullName>Duty_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Duty Completed</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No.</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/FOB_Done__c.field-meta.xml
<CustomField>
    <fullName>FOB_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FOB Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Code</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Year_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Year_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Year Code</label>
    <referenceTo>Model_Year_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Original_Commcase__c.field-meta.xml
<CustomField>
    <fullName>Original_Commcase__c</fullName>
    <label>Original Commcase</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/ProductionMonth__c.field-meta.xml
<CustomField>
    <fullName>ProductionMonth__c</fullName>
    <label>Production Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is used for Treasury Management</description>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/System_Commcase__c.field-meta.xml
<CustomField>
    <fullName>System_Commcase__c</fullName>
    <label>System Commcase</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Trim_Code__c.field-meta.xml
<CustomField>
    <fullName>Trim_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trim Code</label>
    <referenceTo>Trim_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Franchise_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CITCV</fullName>
    </customValue>
    <customValue>
        <fullName>CITPC</fullName>
    </customValue>
    <customValue>
        <fullName>KIACV</fullName>
    </customValue>
    <customValue>
        <fullName>KIAPC</fullName>
    </customValue>
    <customValue>
        <fullName>MITCV</fullName>
    </customValue>
    <customValue>
        <fullName>MITPC</fullName>
    </customValue>
    <customValue>
        <fullName>MBCV</fullName>
    </customValue>
    <customValue>
        <fullName>MBPC</fullName>
    </customValue>
    <masterLabel>Franchise Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DutyAdditionalContractTriggerTest.cls
@isTest(seeAllData=false)
private class DutyAdditionalContractTriggerTest {
	@testSetup()
    static void setUp() {
        Model_Master__c modelCode = Test_DataFactory.createModelCode(true, 'Test Model Code');
        Model_Year_Master__c modelYearCode = Test_DataFactory.createModelYearCode(true, modelCode.Id);
        Color_Master__c colorCode = Test_DataFactory.createColorCode(true, 'Test Color Code', 'Test', 'CCK', 'KIAPC');
        Trim_Master__c trimCode = Test_DataFactory.createTrimCode(true, 'Test Trim Code');
        // Create Purchase Order
		Purchase_Order__c po = new Purchase_Order__c(Franchise__c = 'KIAPC');
        insert po;
        Date productionMonth = Date.newInstance(2019, 08, 01);  
        Vehicle_Master2__c vMaster = new Vehicle_Master2__c(Original_Commcase__c = 'KIAPC0120190086', 
                                                            Model_Year_Code__c = modelYearCode.ID,
                                                            System_Commcase__c = 'KIAPC0120190086', 
                                                            Engine_No__c = 'ENGINE279831',
                                                            Chassis__c = 'CHAS279831', 
                                                            Model_Code__c = modelCode.ID, 
                                                            ProductionMonth__c = productionMonth,
                                                            Color_Code__c = colorCode.ID, 
                                                            Trim_Code__c = trimCode.ID,
                                                            Purchase_Order__c = po.Id);
        insert vMaster;
        Forward_Duty_Contract__c dutyContract = new Forward_Duty_Contract__c(Status__c = 'Active',
                                                                             Cover_Percentage__c = 75,
                                                                             Spot_Rate__c = 1.2345663,
                                                                             Premium_Discount__c = 1.1,
                                                                             Purchase_Order__c = po.Id);
        insert dutyContract;

        Duty_Additional_Contract__c addnlDutyContract = new Duty_Additional_Contract__c(Forward_Duty_Contract__c = dutyContract.Id,
                                                                                        Status__c = 'Forward Contract Sell');
        insert addnlDutyContract;
        Forward_Duty_Contract_Line_Item__c dutyItem = new Forward_Duty_Contract_Line_Item__c(Forward_Duty_Contract__c = dutyContract.Id,
                                                                                         	Duty_Additional_Contract__c = addnlDutyContract.Id,
                                                                                            Stock_Vehicle_Master__c = vMaster.Id);
        insert dutyItem;	       
    }

    @isTest
    static void Test_afterUpdate() {
        Purchase_Order__c po = [SELECT ID FROM Purchase_Order__c];
        Vehicle_Master2__c vMaster = [SELECT ID, FOB_Done__c, Duty_Done__c FROM Vehicle_Master2__c WHERE Purchase_Order__c = :po.Id];
        Forward_Duty_Contract__c dutyContract = [SELECT ID, Status__c FROM Forward_Duty_Contract__c WHERE Purchase_Order__c = :po.Id];
        Duty_Additional_Contract__c addnlDutyContract = [SELECT ID, Status__c FROM Duty_Additional_Contract__c WHERE Forward_Duty_Contract__c = :dutyContract.Id];
        addnlDutyContract.Status__c = 'Completed';
        update addnlDutyContract;

        Test.startTest();
        dutyContract = [SELECT ID, Status__c FROM Forward_Duty_Contract__c WHERE Purchase_Order__c = :po.Id];
        vMaster = [SELECT ID, FOB_Done__c, Duty_Done__c FROM Vehicle_Master2__c WHERE Purchase_Order__c = :po.Id];
        System.assertEquals(true, vMaster.Duty_Done__c);
        System.assertEquals('Sold', dutyContract.Status__c);
        Test.stopTest(); 
    }
}