force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Color_Master__c/fields/Color_Description__c.field-meta.xml
<CustomField>
    <fullName>Color_Description__c</fullName>
    <label>Color Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Color_Master__c/fields/ColorCode__c.field-meta.xml
<CustomField>
    <fullName>ColorCode__c</fullName>
    <externalId>true</externalId>
    <label>ColorCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/fields/Model_Description__c.field-meta.xml
<CustomField>
    <fullName>Model_Description__c</fullName>
    <label>Model Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trim_Master__c/fields/Trim_Description__c.field-meta.xml
<CustomField>
    <fullName>Trim_Description__c</fullName>
    <label>Trim Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Color Code</label>
    <referenceTo>Color_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Manufacturer_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Ref_No__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Manufacturer Ref. No.</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Code</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Description__c.field-meta.xml
<CustomField>
    <fullName>Model_Description__c</fullName>
    <formula>Model_Code__r.Model_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Model Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Trim_Code__c.field-meta.xml
<CustomField>
    <fullName>Trim_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trim Code</label>
    <referenceTo>Trim_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Vehicle_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Purchase Order</label>
    <referenceTo>Vehicle_Purchase_Order__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Vehicle_Purchase_Status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Purchase_Status__c</fullName>
    <label>Vehicle Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
                <default>true</default>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>In Shipment</fullName>
            </value>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>SCL_Cancel</fullName>
                <label>SCL (Cancel)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Status__c</fullName>
    <label>Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FREE</fullName>
                <default>true</default>
                <label>FREE</label>
            </value>
            <value>
                <fullName>ORD</fullName>
            </value>
            <value>
                <fullName>SCL</fullName>
            </value>
            <value>
                <fullName>RESRV</fullName>
            </value>
            <value>
                <fullName>ALLOC</fullName>
            </value>
            <value>
                <fullName>SOLD</fullName>
            </value>
            <value>
                <fullName>CONF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/Vehicle_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Vehicle Purchase Order</label>
    <nameField>
        <displayFormat>PO-{YYYY}{MM}-{00000}</displayFormat>
        <label>Vehicle Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/vpo_StockVehicleMasterIOController.cls
public with sharing class vpo_StockVehicleMasterIOController
{
    @AuraEnabled(cacheable=true)
    public static List<Vehicle_Master2__c> getStockVehicleMaster(String orderId)
    {
        try
        {
            return [SELECT  Id, Name, Model_Code__r.Name, Color_Code__r.ColorCode__c,Trim_Code__r.Name, Manufacturer_Ref_No__c,
                            Vehicle_Purchase_Status__c, Vehicle_Status__c, Model_Description__c, Color_Description__c, Trim_Description__c
                    FROM Vehicle_Master2__c
                    WHERE Vehicle_Purchase_Order__c = :orderId];
        }
        catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateStockVehicleMaster(String orderId, String contentDocumentId, String contentVersionId)
    {
        try
        {
            System.assert(contentDocumentId != null, 'Invalid Content Document Id');

            System.assert(contentVersionId != null, 'Invalid Content Version Id');

            System.assert(orderId != null, 'Invalid Vehicle Purchase Order Id');

            // get shipment's stock vehicle master
            Map<Id, Vehicle_Master2__c> stockVehicleMasters = new Map<Id, Vehicle_Master2__c>([SELECT Id FROM Vehicle_Master2__c WHERE Vehicle_Purchase_Order__c = :orderId]);

            System.assert(stockVehicleMasters.size() > 0, 'This shipment do not have any related Stock Vehicle Master');

            ContentVersion uploadedReport = [SELECT Id, VersionData FROM ContentVersion WHERE ContentDocumentId = :contentDocumentId];

            // clear uploaded file in a separate context
            deleteUploadedReport(contentDocumentId);

            String csv = uploadedReport.VersionData.toString();

            List<Map<String, String>> consumedTable = new ADGLIB_CommaSeparatedValuesFileReader(csv).withHeader().withStrictMode().read().exportResultAsMap();

            List<Vehicle_Master2__c> updatingStockVehicleMaster = new List<Vehicle_Master2__c>();

            for (Map<String, String> row : consumedTable)
            {
                System.assert(row.keySet().contains('Id'), 'A row is uploaded without Id field');
                System.assert(row.keySet().contains('Manufacturer_Ref_No__c'), 'A row is uploaded without Manufacturer_Ref_No__c field');

                Id stockId                  = (Id) row.get('Id');
                String manufacturerRefNo    = row.get('Manufacturer_Ref_No__c');

                System.assert(stockVehicleMasters.keySet().contains(stockId), 'A row is uploaded with stock ID not belong to this purchase order');

                updatingStockVehicleMaster.add(new Vehicle_Master2__c(Id = stockId, Manufacturer_Ref_No__c = manufacturerRefNo));
            }

            update updatingStockVehicleMaster;
        }
        catch (Exception e)
        {
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());

            // for DML exception, throw it as a custom exception so that it will be displayed on screen
            // for non DML exception, throw it as a AuraHandledException and do not display on screen
            if (e instanceof System.DmlException)
            {
                throw new StockVehicleMasterReportException(e.getMessage());
            }
            else
            {
                throw new AuraHandledException(e.getMessage());
            }
        }
    }

    @future
    private static void deleteUploadedReport(String contentDocumentId)
    {
        delete [SELECT Id FROM ContentDocument WHERE Id =:contentDocumentId];
    }

    public class StockVehicleMasterReportException extends Exception {}
}