force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/Model_Color_Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Model Color Trim Master</label>
    <nameField>
        <label>MTC Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Color Trim Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Color Code</label>
    <referenceTo>Color_Master__c</referenceTo>
    <relationshipLabel>Model Color Trim Master</relationshipLabel>
    <relationshipName>ModelColors</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model Code</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Color Trim Master</relationshipLabel>
    <relationshipName>ModelColors</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/fields/Trim_Code__c.field-meta.xml
<CustomField>
    <fullName>Trim_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trim Code</label>
    <referenceTo>Trim_Master__c</referenceTo>
    <relationshipName>ModelColors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/MTCMasterPost.cls
@RestResource(urlMapping='/MTCMaster/*')
global without sharing class MTCMasterPost {
    @HttpPost
    global static void getPost(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.responseBody = Blob.valueOf('NOT OK, Action not recognize');
        
        HttpResponse rese=new HttpResponse();
        
        String Action = req.params.get('Action');
        String Active = req.params.get('Status');
        String FranchiseCode = req.params.get('FranchiseCode');
        String BranchCode = req.params.get('BranchCode');
        String ColorCode = req.params.get('ColorCode');
        String ModelCode = req.params.get('ModelCode');
        String TrimCode = req.params.get('TrimCode');
        String Name=ModelCode+' '+TrimCode+' '+ColorCode;
        
        Model_Color_Trim_Master__c MTCM=new Model_Color_Trim_Master__c();
        Color_Master__c CM=new Color_Master__c();
        Model_Master__c MM=new Model_Master__c();
        Trim_Master__c TM=new Trim_Master__c();
        
        if(FranchiseCode == 'MITPC'){
        	BranchCode = 'CCA';
        }
        
        try{
            CM=[select id from Color_Master__c where name=:ColorCode and Franchise_Code__c=:FranchiseCode and  Branch_Code__c =:BranchCode limit 1];
            MM=[select id from Model_Master__c where name=:ModelCode and Franchise_Code__c=:FranchiseCode and  Branch_Code__c =:BranchCode limit 1];
            TM=[select id from Trim_Master__c where name=:TrimCode and Franchise_Code__c=:FranchiseCode and  Branch_Code__c =:BranchCode limit 1];
            
            List<Model_Color_Trim_Master__c> MTCMlist=[select Id,Name,Franchise_Code__c,Branch_Code__c,Active__c,Color_Code__c,Model_Code__c,Trim_Code__c
                      from Model_Color_Trim_Master__c where Name=:Name and Franchise_Code__c=:FranchiseCode and  Branch_Code__c =:BranchCode];
            if(MTCMlist != null && MTCMlist.size() > 0){
            	MTCM = MTCMlist[0];
            }
            MTCM.Name=Name;
            MTCM.Franchise_Code__c=FranchiseCode;
            MTCM.Branch_Code__c=BranchCode;
            MTCM.Color_Code__c=CM.id;
            MTCM.Model_Code__c=MM.id;
            MTCM.Trim_Code__c=TM.id;
            if (Active=='A'){
                MTCM.Active__c=true;
            }else{
                MTCM.Active__c=false;
            }         
            insert MTCM;
            res.responseBody = Blob.valueOf('OK');
            
            /*if (Action=='Insert'){
                List<Model_Color_Trim_Master__c> MTCMlist=[select Id from Model_Color_Trim_Master__c where Name=:Name and Franchise_Code__c=:FranchiseCode and  Branch_Code__c =:BranchCode];
                if(MTCMlist.size()<=0){
                MTCM.Name=Name;
                MTCM.Franchise_Code__c=FranchiseCode;
                MTCM.Branch_Code__c=BranchCode;
                MTCM.Color_Code__c=CM.id;
                MTCM.Model_Code__c=MM.id;
                MTCM.Trim_Code__c=TM.id;
                if (Active=='A'){
                    MTCM.Active__c=true;
                }else{
                    MTCM.Active__c=false;
                }         
                insert MTCM;
                res.responseBody = Blob.valueOf('OK');
                }else{
                //send email eror
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                List<String> idList = new List<String>();
                List<String> mailToAddresses = new List<String>();
                Group g = [SELECT (select userOrGroupId from groupMembers) FROM group WHERE name = 'VSMS Admin'];
                for (GroupMember gm : g.groupMembers) {
                    idList.add(gm.userOrGroupId);
                }
                User[] usr = [SELECT email FROM user WHERE id IN :idList];
                for(User u : usr) {
                    mailToAddresses.add(u.email);
                }
                mail.setToAddresses(mailToAddresses);
                mail.setSubject('MTC Master Eror');
                mail.setPlainTextBody('Duplicate Record');
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                res.responseBody = Blob.valueOf('NOT OK, Duplicate Record');
                }
            }
            if (Action=='Update'){
                MTCM=[select Id,Name,Franchise_Code__c,Branch_Code__c,Active__c,Color_Code__c,Model_Code__c,Trim_Code__c
                      from Model_Color_Trim_Master__c where Name=:Name and Franchise_Code__c=:FranchiseCode and  Branch_Code__c =:BranchCode];
                MTCM.Franchise_Code__c=FranchiseCode;
                MTCM.Branch_Code__c=BranchCode;
                MTCM.Color_Code__c=CM.id;
                MTCM.Model_Code__c=MM.id;
                MTCM.Trim_Code__c=TM.id;
                if (Active=='A'){
                    MTCM.Active__c=true;
                }else{
                    MTCM.Active__c=false;
                }
                update MTCM;
                res.responseBody = Blob.valueOf('OK');
            }*/
        }catch(Exception e) {
            res.responseBody = Blob.valueOf('The following exception has occurred: ' + e.getMessage());
            System.debug('The following exception has occurred: ' + e.getMessage());
            //send email eror
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            List<String> idList = new List<String>();
            List<String> mailToAddresses = new List<String>();
            Group g = [SELECT (select userOrGroupId from groupMembers) FROM group WHERE name = 'VSMS Admin'];
            for (GroupMember gm : g.groupMembers) {
                idList.add(gm.userOrGroupId);
            }
            User[] usr = [SELECT email FROM user WHERE id IN :idList];
            for(User u : usr) {
                mailToAddresses.add(u.email);
            }
            mail.setToAddresses(mailToAddresses);
            mail.setSubject('MTC Master Eror');
            mail.setPlainTextBody(e.getMessage());
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}