force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Color_Master__c/fields/Color_Description__c.field-meta.xml
<CustomField>
    <fullName>Color_Description__c</fullName>
    <label>Color Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/Model_Color_Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Model Color Trim Master</label>
    <nameField>
        <label>MTC Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Color Trim Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Color_Trim_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Model_Year_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trim_Master__c/fields/Trim_Description__c.field-meta.xml
<CustomField>
    <fullName>Trim_Description__c</fullName>
    <label>Trim Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Production_Month__c.field-meta.xml
<CustomField>
    <fullName>Production_Month__c</fullName>
    <label>Production Month</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Vehicle_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Purchase Order</label>
    <referenceTo>Vehicle_Purchase_Order__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Vehicle_Purchase_Order_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Purchase_Order_Line_Items__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Purchase Order Line Items</label>
    <referenceTo>Vehicle_Purchase_Order_Line_Items__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/Vehicle_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Vehicle Purchase Order</label>
    <nameField>
        <displayFormat>PO-{YYYY}{MM}-{00000}</displayFormat>
        <label>Vehicle Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>RMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Franchise_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/PI_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>PI_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PI Uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/PO_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Approved_Date__c</fullName>
    <label>PO Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Production_Month__c.field-meta.xml
<CustomField>
    <fullName>Production_Month__c</fullName>
    <inlineHelpText>Input first day of the month</inlineHelpText>
    <label>Production Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Manufacturer_Confirmed</fullName>
                <label>Manufacturer Confirmation</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Supplier_Account__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicle Purchase Orders</relationshipLabel>
    <relationshipName>Vehicle_Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Total_PO_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_PO_Value__c</fullName>
    <label>Total PO Value</label>
    <summarizedField>Vehicle_Purchase_Order_Line_Items__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Vehicle_Purchase_Order_Line_Items__c.Vehicle_Purchase_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Total_Units_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Total_Units_Confirmed__c</fullName>
    <label>Total Units Confirmed</label>
    <summarizedField>Vehicle_Purchase_Order_Line_Items__c.Units_Confirmed__c</summarizedField>
    <summaryForeignKey>Vehicle_Purchase_Order_Line_Items__c.Vehicle_Purchase_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order__c/fields/Total_Units_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Total_Units_Ordered__c</fullName>
    <label>Total Units Ordered</label>
    <summarizedField>Vehicle_Purchase_Order_Line_Items__c.Units_Ordered__c</summarizedField>
    <summaryForeignKey>Vehicle_Purchase_Order_Line_Items__c.Vehicle_Purchase_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order_Line_Items__c/Vehicle_Purchase_Order_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Vehicle Purchase Order Line Items</label>
    <nameField>
        <displayFormat>POLI-{YYYY}{MM}-{000}</displayFormat>
        <label>Vehicle Purchase Order Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Purchase_Order_Line_Items__c/fields/Color_Master__c.field-meta.xml
<CustomField>
    <fullName>Color_Master__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Color</label>
    <referenceTo>Color_Master__c</referenceTo>
    <relationshipLabel>Vehicle Purchase Order Line Items</relationshipLabel>
    <relationshipName>Vehicle_Purchase_Order_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order_Line_Items__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order_Line_Items__c/fields/Model_Color_Trim_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Color_Trim_Master__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Color Trim Master</label>
    <referenceTo>Model_Color_Trim_Master__c</referenceTo>
    <relationshipLabel>Vehicle Purchase Order Line Items</relationshipLabel>
    <relationshipName>Vehicle_Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order_Line_Items__c/fields/Trim_Master__c.field-meta.xml
<CustomField>
    <fullName>Trim_Master__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trim</label>
    <referenceTo>Trim_Master__c</referenceTo>
    <relationshipLabel>Vehicle Purchase Order Line Items</relationshipLabel>
    <relationshipName>Vehicle_Purchase_Order_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Purchase_Order_Line_Items__c/fields/Vehicle_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Purchase_Order__c</fullName>
    <label>Vehicle Purchase Order</label>
    <referenceTo>Vehicle_Purchase_Order__c</referenceTo>
    <relationshipLabel>Vehicle Purchase Order Line Items</relationshipLabel>
    <relationshipName>Vehicle_Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Franchise_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CITCV</fullName>
    </customValue>
    <customValue>
        <fullName>CITPC</fullName>
    </customValue>
    <customValue>
        <fullName>KIACV</fullName>
    </customValue>
    <customValue>
        <fullName>KIAPC</fullName>
    </customValue>
    <customValue>
        <fullName>MITCV</fullName>
    </customValue>
    <customValue>
        <fullName>MITPC</fullName>
    </customValue>
    <customValue>
        <fullName>MBCV</fullName>
    </customValue>
    <customValue>
        <fullName>MBPC</fullName>
    </customValue>
    <masterLabel>Franchise Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VehiclePurchaseOrderSelector.cls
/*==========================================================================================================================================================================
 * Selector class for Vehicle Purchase Order Entity
 * Created By: Aodigy Team
 * Create Date: July 2022
 * History
 *              DATE::                              BY::                                TICKET::                                            CHANGELOG
 *      27 July 2022                        dangphap.mai@aodigy.com                 US-VPO-000016                                              init
 * ========================================================================================================================================================================== 
 */
public inherited sharing class VehiclePurchaseOrderSelector extends ADGLIB_SObjectSelector
{
    public VehiclePurchaseOrderSelector()
    {

    }

    public Schema.SObjectType getSObjectType()
    {
        return Vehicle_Purchase_Order__c.sObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList()
    {
        // return new List<Schema.SObjectField>
        // {
        //     Vehicle_Purchase_Order__c.Currency_Code__c,
        //     Vehicle_Purchase_Order__c.Franchise_Code__c,
        //     Vehicle_Purchase_Order__c.PI_Uploaded__c,
        //     Vehicle_Purchase_Order__c.PO_Approved_Date__c,
        //     Vehicle_Purchase_Order__c.Production_Month__c,
        //     Vehicle_Purchase_Order__c.Remarks__c,
        //     Vehicle_Purchase_Order__c.Stage__c,
        //     Vehicle_Purchase_Order__c.Supplier_Account__c,
        //     Vehicle_Purchase_Order__c.Total_PO_Value__c,
        //     Vehicle_Purchase_Order__c.Total_Units_Confirmed__c,
        //     Vehicle_Purchase_Order__c.Total_Units_Ordered__c,
        //     Vehicle_Purchase_Order__c.Name,
        //     Vehicle_Purchase_Order__c.OwnerId,
        //     Vehicle_Purchase_Order__c.LastModifiedById,
        //     Vehicle_Purchase_Order__c.CreatedById
        // };

        return getSObjectType().getDescribe().fields.getMap().values();
    }

    /**
     * select vehicle purchase order together with line items by order Ids
     * @param orderIds: list of targeted Vehicle Purchase Order's Id
     */
    public List<Vehicle_Purchase_Order__c> selectByIdsWithLineItems(Set<Id> orderIds)
    {
        Boolean assertCRUD                              = false;    // by pass CRUD
        Boolean enforceFLS                              = false;    // by pass FLS
        Boolean includeSelectorFields                   = true;     // include fields from getSObjectFieldList()
        adglib_QueryFactory orderQueryFactory           = this.newQueryFactory(assertCRUD, enforceFLS, includeSelectorFields).setCondition('Id IN :orderIds');
        
        // select line items
        adglib_QueryFactory lineItemsQueryFactory       = orderQueryFactory.subselectQuery(Vehicle_Purchase_Order_Line_Items__c.sObjectType);
        lineItemsQueryFactory.selectFields(new VPOLineItemsSelector().getSObjectFieldList());

        // get POLI parents name
        lineItemsQueryFactory.selectField('Color_Master__r.Color_Description__c');
        lineItemsQueryFactory.selectField('Model_Color_Trim_Master__r.Name');
        lineItemsQueryFactory.selectField('Trim_Master__r.Trim_Description__c');
        lineItemsQueryFactory.selectField('Model_Master__r.Model_Description__c');
        lineItemsQueryFactory.selectField('Model_Year_Master__r.Name');

        // select converted stock vehicle master
        adglib_QueryFactory convertedStockQueryFactory  = orderQueryFactory.subselectQuery(Vehicle_Master2__c.sObjectType);
        convertedStockQueryFactory.selectField(Vehicle_Master2__c.Id);
        convertedStockQueryFactory.selectField(Vehicle_Master2__c.Vehicle_Purchase_Order__c);
        convertedStockQueryFactory.selectField(Vehicle_Master2__c.Vehicle_Purchase_Order_Line_Items__c);
        
        return Database.query(orderQueryFactory.toSOQL());
    }
}