force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Model_Rate_Master__c/Model_Rate_Master__c.object-meta.xml
<CustomObject>
    <label>Model Rate Master</label>
    <nameField>
        <displayFormat>MRM-{0000}</displayFormat>
        <label>Model Rate Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Model Rate Masters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Rate_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Rate Masters</relationshipLabel>
    <relationshipName>Model_Rate_Masters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Model_Rate_Master__c/fields/MRM_MYM_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>MRM_MYM_FRNCD__c</fullName>
    <label>MRM_MYM_FRNCD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/fields/ProductionMonth__c.field-meta.xml
<CustomField>
    <fullName>ProductionMonth__c</fullName>
    <label>Production Month</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/classes/StockVehicleMasterSelectorTest.cls
@isTest
private class StockVehicleMasterSelectorTest {
	@testSetup
    static void setUp() {
        // Create master data
        Model_Master__c modelCode = Test_DataFactory.createModelCode(true, 'Test Model Code');
        Model_Rate_Master__c modelRateMaster = new Model_Rate_Master__c(Model_Master__c = modelCode.Id,
                                                                       	MRM_MYM_FRNCD__c = 'KIAPC');
        insert modelRateMaster;
        Model_Year_Master__c modelYearCode = Test_DataFactory.createModelYearCode(true, modelCode.Id);
        Color_Master__c colorCode = Test_DataFactory.createColorCode(true, 'Test Color Code', 'Test', 'CCK', 'KIAPC');
        Trim_Master__c trimCode = Test_DataFactory.createTrimCode(true, 'Test Trim Code');

        Vehicle_Master2__c vhMaster = Test_DataFactory.createVehicleMaster2(false, modelCode.Id, colorCode.Id, trimCode.Id, modelYearCode.Id, '0119-5047522', 'KIAPC0120190059');
        vhMaster.ProductionMonth__c = Date.newInstance(2019, 01, 01);
        insert vhMaster;
    }

    @isTest
    static void Test_selectStockVehicleMastersBySystemCommcases() {
        StockVehicleMasterSelector svmSelector = new StockVehicleMasterSelector();
        List<Vehicle_Master2__c> vhMasters = svmSelector.selectStockVehicleMastersBySystemCommcases(new Set<String>{'KIAPC0120190059'});

        System.assertEquals(1, vhMasters.size());
    }
}