force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/fields/Chassis__c.field-meta.xml
<CustomField>
    <fullName>Chassis__c</fullName>
    <label>Chassis</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Color Code</label>
    <referenceTo>Color_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No.</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Code</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Year_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Year_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Year Code</label>
    <referenceTo>Model_Year_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Original_Commcase__c.field-meta.xml
<CustomField>
    <fullName>Original_Commcase__c</fullName>
    <label>Original Commcase</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/ProductionMonth__c.field-meta.xml
<CustomField>
    <fullName>ProductionMonth__c</fullName>
    <label>Production Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/System_Commcase__c.field-meta.xml
<CustomField>
    <fullName>System_Commcase__c</fullName>
    <label>System Commcase</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Trim_Code__c.field-meta.xml
<CustomField>
    <fullName>Trim_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trim Code</label>
    <referenceTo>Trim_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StockVehicleMasterServiceTest.cls
/*==========================================================================================================================================================================
 * Test service class for Stock Vehicle Master Entity
 * Created By: Aodigy Team
 * Create Date: August 2022
 * History
 *              DATE::                              BY::                                TICKET::                                            CHANGELOG
 *           8 Sep 2022                       nam@aodigy.com                                                                               init
 * ========================================================================================================================================================================== 
 */
@isTest
public with sharing class StockVehicleMasterServiceTest {
    @TestSetup
    static void makeData(){
        // Create model master
        Model_Master__c modelCode = Test_DataFactory.createModelCode(true, 'Test Model Code');
        
        // create model year master
        Model_Year_Master__c modelYearCode = Test_DataFactory.createModelYearCode(true, modelCode.Id);
        
        // create color master
        Color_Master__c colorCode = Test_DataFactory.createColorCode(true, 'Test Color Code', 'Test', 'CCK', 'KIAPC');
        
        // create trim master
        Trim_Master__c trimCode = Test_DataFactory.createTrimCode(true, 'Test Trim Code');

        // create stock vehicle master
        Date productionMonth = Date.newInstance(2019, 08, 01);  
        Vehicle_Master2__c vMaster = new Vehicle_Master2__c(Original_Commcase__c = 'KIAPC0120190086', 
                                                            Model_Year_Code__c = modelYearCode.ID,
                                                            System_Commcase__c = 'KIAPC0120190086', 
                                                            Engine_No__c = 'ENGINE279831',
                                                            Chassis__c = 'CHAS279831', 
                                                            Model_Code__c = modelCode.ID, 
                                                            ProductionMonth__c = productionMonth,
                                                            Color_Code__c = colorCode.ID, 
                                                            Trim_Code__c = trimCode.ID,
                                                            Duty_Payment_Date__c = Date.today());
        insert vMaster;
        
    }
    @IsTest
    private static void selectStockVehicleMastersForDutyRequest_success()
    {
        List<Vehicle_Master2__c> svms = [SELECT Id FROM Vehicle_Master2__c];
        StockVehicleMasterSelector sel = new StockVehicleMasterSelector();
        StockVehicleMasterService.selectStockVehicleMastersForDutyRequest();
    }
    
    @IsTest
    private static void selectByIds_success()
    {
        List<Vehicle_Master2__c> svms = [SELECT Id FROM Vehicle_Master2__c];
        StockVehicleMasterSelector sel = new StockVehicleMasterSelector();
        List<String> vehiclemasterIds = new List<String>();
        StockVehicleMasterService.selectByIds(vehiclemasterIds);

    }

    @IsTest
    private static void selectStockVehicleMastersByInvoiceIds_success()
    {
        List<Vehicle_Master2__c> svms = [SELECT Id FROM Vehicle_Master2__c];
        StockVehicleMasterSelector sel = new StockVehicleMasterSelector();
        Set<Id> invoiceIds = new Set<Id>();
        StockVehicleMasterService.selectStockVehicleMastersByInvoiceIds(invoiceIds);

    }
}