cncProd/force-app/main/default/objects/Forms_Controller__c/Forms_Controller__c.object-meta.xml
<CustomObject>
    <label>Forms Controller</label>
    <nameField>
        <displayFormat>F-{0000000}</displayFormat>
        <label>Forms Controller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Controllers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Forms_Controller__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>AND ( TODAY() &gt;=  Start_Date__c ,  TODAY() &lt;=  End_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Forms_Controller__c/fields/Associated_Checkbox_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Associated_Checkbox_Field_API_Name__c</fullName>
    <description>If document has been generated, the corresponding checkbox will be ticked automatically. May be useful for automation purposes (Eg. Vehicle Delivery Certificate)</description>
    <inlineHelpText>Automatically tick corresponding checkbox field. Leave blank if no checkbox.</inlineHelpText>
    <label>Associated Checkbox Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Forms_Controller__c/fields/Button_Condition_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Button_Condition_Field_API_Name__c</fullName>
    <description>If the field = true, button will appear</description>
    <inlineHelpText>Leave blank if no condition</inlineHelpText>
    <label>Button Condition Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forms_Controller__c/fields/File_Naming_Convention__c.field-meta.xml
<CustomField>
    <fullName>File_Naming_Convention__c</fullName>
    <label>File Naming Convention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Forms_Controller__c/fields/Form_Body__c.field-meta.xml
<CustomField>
    <fullName>Form_Body__c</fullName>
    <label>Form Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

cncProd/force-app/main/default/objects/Forms_Controller__c/fields/Form_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Name__c</fullName>
    <label>Form Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/FormsPanelController.cls
public with sharing class FormsPanelController {
    @AuraEnabled(cacheable=true)
    public static FormsDefinitionDetails getActiveForms(Id recordId) {
        system.debug('record id:: ' + recordId);
        String objApiName = recordId.getSObjectType().getDescribe().getName();
        system.debug('obj API Name ' + objApiName);
        FormsDefinitionDetails formDetails = new FormsDefinitionDetails(objApiName);
        formDetails.objInfo = getRecords(objApiName, 'Id', recordId, null)[0];
        for (Forms_Controller__c fc : [SELECT Start_Date__c, End_Date__c, Object_API_Name__c, Form_Title__c, Form_Body__c, Form_Name__c, Active__c,
                                              File_Naming_Convention__c, Button_Condition_Field_API_Name__c, Associated_Checkbox_Field_API_Name__c, Display_Order__c
                                       FROM Forms_Controller__c
                                       WHERE Object_API_Name__c = :objApiName
                                       ORDER BY Display_Order__c ASC]) {
            formDetails.forms.add(fc);
        }

        return formDetails;
    }

    @AuraEnabled(cacheable=true)
    public static List<sObject> getRecordInfo(Id recordId) {
        String objApiName = recordId.getSObjectType().getDescribe().getName();
        List<sObject> records = getRecords(objApiName, 'Id', recordId, null);

        return records;
    }

    @AuraEnabled
    public static List<sObject> getRecords(String objNm, String fieldReference, String fieldValue, String additionalConditions) {
        String mainQueryCondition = fieldReference + ' = ' + '\'' + fieldValue + '\'';
        
        if (additionalConditions != null && String.isNotBlank(additionalConditions)) {
            mainQueryCondition = mainQueryCondition + ' ' + additionalConditions;
        }

        List<sObject> records = ADGLIB_UtilityHelper.getSObjectRecords(objNm, mainQueryCondition, false); 
        return records;
    }

    /**
     * This method to save Form as Attachment to the record
     * And delete signature image file after finishing
     */
    @AuraEnabled
    public static Id saveAttachment(String recordId, String formId, String fileName, String associatedFieldAPINm) {
        system.debug('*** START createAttachment ***');
        Id cdID;
        try {
            // Save form pdf as Attachment to the record
            Blob formContent;
            if (!Test.isRunningTest()) {
               formContent = new PageReference('/apex/SDP_FormControllerPDF?id=' + recordId + '&formId=' + formId).getContentAsPDF();
            } else {
                formContent = Blob.valueOf('Test');
            }
            ContentVersion formCV = new ContentVersion();
            // Create content version
            formCV.ContentLocation = 'S';
            formCV.PathOnClient = '/' + fileName + '.pdf';
            formCV.Origin = 'C';
            formCV.OwnerId = UserInfo.getUserId();
            formCV.Title = fileName + '.pdf';
            formCV.VersionData = formContent;
            insert formCV;

            // After saving the Content Verison, get the ContentDocumentId
            cdID = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :formCV.Id].ContentDocumentId;

            // Do this for file to appear on File tab
            ContentDocument cd = [SELECT Description FROM ContentDocument WHERE ID = :cdID];
            cd.Description = fileName;
            update cd;

            // Insert ContentDocumentLink for the file to appear on record's related list
            ContentDocumentLink cDocLink = new ContentDocumentLink();
            cDocLink.ContentDocumentId = cdID;
            cDocLink.LinkedEntityId = recordId;
            cDocLink.ShareType = 'I';
            cDocLink.Visibility = 'AllUsers';
            insert cDocLink;

            // Update associated checkbox for the record to be checked
            if (String.isNotEmpty(associatedFieldAPINm)) {
                saveRecord(recordId, associatedFieldAPINm, 'true');
            }
        } catch (Exception e) {
            throw new AuraException('Error happen when saving Attachment. Please contact your Administrator for more details!' + e.getMessage());
        }

        system.debug('*** END createAttachment ***');
        return cdID;
    }

    @AuraEnabled
    public static void saveRecord(string recordId, String fieldAPINm, String fieldValue){
        system.debug('*** START saveRecord() ***');

        id objectId = (id)recordId;
        SObject record = objectId.getSobjectType().newSObject(objectId);                                         // re-build record
        Map<String, Schema.SObjectField> objectFields = objectId.getSobjectType().getDescribe().fields.getMap(); // get fields map
        Schema.DescribeFieldResult fieldDescribe = objectFields.get(fieldAPINm).getDescribe();
        String fieldtype = fieldDescribe.getType().name();
        system.debug('Updating for field: ' + fieldAPINm);
        system.debug('Field type: ' + fieldtype);
        switch on fieldtype {
            when 'BOOLEAN' {record.put(fieldAPINm, boolean.valueOf(fieldValue));}
            when 'CURRENCY' {record.put(fieldAPINm, decimal.valueOf(fieldValue));}
            when 'ID' {record.put(fieldAPINm, id.valueOf(fieldValue));}
            when 'INTEGER' {record.put(fieldAPINm, integer.valueOf(fieldValue));}
            when 'LONG' {record.put(fieldAPINm, long.valueOf(fieldValue));}
            when 'PERCENT' {record.put(fieldAPINm, decimal.valueOf(fieldValue));}
            when else {record.put(fieldAPINm, fieldValue);}
        }

        Database.SaveResult sr = Database.update(record, true);
        if (!sr.isSuccess()) throw new AuraException('Error happen when updating record: ' + sr.getErrors()[0].getMessage());
        system.debug('*** END saveRecord() ***');
    }

    public class FormsDefinitionDetails {
        @AuraEnabled public List<Forms_Controller__c> forms {get;set;}
        @AuraEnabled public sObject objInfo {get;set;}

        public FormsDefinitionDetails(String objApiName) {
            this.forms = new List<Forms_Controller__c>();
            this.objInfo = Schema.getGlobalDescribe().get(objApiName).newSObject();
        }
    }
}