force-app/main/default/objects/JIT_Day__c/JIT_Day__c.object-meta.xml
<CustomObject>
    <label>JIT Day</label>
    <nameField>
        <label>JIT Day Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JIT Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JIT_Day__c/fields/JIT_Date__c.field-meta.xml
<CustomField>
    <fullName>JIT_Date__c</fullName>
    <label>JIT Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JIT_Day__c/fields/Utilised_Slots__c.field-meta.xml
<CustomField>
    <fullName>Utilised_Slots__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Utilised Slots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Agreement__c/fields/JIT_Date__c.field-meta.xml
<CustomField>
    <fullName>JIT_Date__c</fullName>
    <label>JIT Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/JIT_Day__c.field-meta.xml
<CustomField>
    <fullName>JIT_Day__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JIT Day</label>
    <referenceTo>JIT_Day__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/JIT_Status__c.field-meta.xml
<CustomField>
    <fullName>JIT_Status__c</fullName>
    <label>JIT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Sales_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Sales_Consultant__c</fullName>
    <formula>Owner:User.FirstName + &apos; &apos; + Owner:User.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Consultant</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/SOH_SONO__c.field-meta.xml
<CustomField>
    <fullName>SOH_SONO__c</fullName>
    <externalId>true</externalId>
    <label>Sales Agreement No</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Stock_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Stock_Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Stock Reservation</label>
    <referenceTo>Stock_Reservation__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Reservation__c/fields/Agreement_No__c.field-meta.xml
<CustomField>
    <fullName>Agreement_No__c</fullName>
    <label>Agreement No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Stock_Reservation__c/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Master</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Vehicle_Master2__c.Color_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Color_Code__c</valueField>
        </filterItems>
        <filterItems>
            <field>Vehicle_Master2__c.Model_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Model_Code__c</valueField>
        </filterItems>
        <filterItems>
            <field>Vehicle_Master2__c.Trim_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Trim_Code__c</valueField>
        </filterItems>
        <filterItems>
            <field>Vehicle_Master2__c.Model_Year_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Model_Year_Code__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vehicle_Master2__c</referenceTo>
    <relationshipLabel>Stock Reservations</relationshipLabel>
    <relationshipName>Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/fields/Chassis__c.field-meta.xml
<CustomField>
    <fullName>Chassis__c</fullName>
    <label>Chassis</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/JIT_Date__c.field-meta.xml
<CustomField>
    <fullName>JIT_Date__c</fullName>
    <label>JIT Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/JIT_Day__c.field-meta.xml
<CustomField>
    <fullName>JIT_Day__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JIT Day</label>
    <referenceTo>JIT_Day__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/JITController.cls
public without sharing class JITController {
    private static final List<String> SALES_ADMIN_PROFILES      = new List<String>{'KIAPC Sales Admin', 'CITPC Marketing', 'System Administrator'};
    private static final List<String> SALES_CONSULTANT_PROFILES = new List<String>{'KIAPC Sales', 'MITPC Sales', 'CITPC Sales'};

    @AuraEnabled(cacheable=true)
    public static JITWrapper constructWrapper(String objAPINm, String recordId)
    {
        JITWrapper wrapper = new JITWrapper();
        wrapper.curRecInfo = getRecords(objAPINm, 'Id', recordId, null)[0];

        if ((Date)wrapper.curRecInfo.get('JIT_Date__c') == null)
        {
            // throw new AuraHandledException('JIT Date is currently empty. Please check again!');
            AuraHandledException e = new AuraHandledException('JIT Date is currently empty. Please check again!');
            e.setMessage('JIT Date is currently empty. Please check again!');
            system.debug(e);
            throw e;
        }

        if (String.isNotBlank((Id)wrapper.curRecInfo.get('JIT_Day__c')))
        {
            wrapper.bookedJIT = new JITDaysSelector().selectById((Id)wrapper.curRecInfo.get('JIT_Day__c'));
        }

        wrapper.jitDaysList = new JITDaysSelector().selectByJITDate((Date)wrapper.curRecInfo.get('JIT_Date__c'));

        Profile authorizedProfile = [SELECT Id, Name FROM Profile WHERE Id = :UserInfo.getProfileId()];
        wrapper.isSalesAdmin      = SALES_ADMIN_PROFILES.contains(authorizedProfile.Name);
        wrapper.isSalesConsultant = SALES_CONSULTANT_PROFILES.contains(authorizedProfile.Name);

        return wrapper;
    }

    /*
    ** 1. Increment JIT Day "Utilised Slots" field by 1.
    ** 2. Update "JIT Day" lookup field on Stock Vehicle Master (SVM) of SA to look up to the same JIT Day record as SA.
    */
    @AuraEnabled 
    public static void lookUpJITDayRecord(String sObjectName, Id recordId, Id JIT_recordId)
    {
        Savepoint sp = Database.setSavepoint();

        List<sObject> records = getRecords(sObjectName, 'Id', recordId, null);
        records[0].put('JIT_Day__c', JIT_recordId);

        system.debug(records[0]);

        JIT_Day__c jitDay = new JITDaysSelector().selectById(JIT_recordId);
        if(jitDay != null)
        {
            jitDay.Utilised_Slots__c += 1;
        }
        

        Vehicle_Master2__c svm;
        if (sObjectName == 'Sales_Agreement__c')
        {
            Sales_Agreement__c sa  = SalesAgreementService.getSalesAgrmnt(recordId);

            svm = (Vehicle_Master2__c)getRecords('Vehicle_Master2__c', 'Id', sa.Stock_Reservation__r.Vehicle_Master__r.Id, null)[0];
            svm.JIT_Day__c  = JIT_recordId;
            svm.JIT_Date__c = jitDay.JIT_Date__c;
        }

        try
        {
            update records;
            update jitDay;
            if (svm != null)
            {
                update svm;
            }
        }
        catch(Exception e)
        {
            Database.rollback(sp);

            throw e;
        }
    }

    @AuraEnabled
    public static void cancelSlot(String objAPINm, String recordId)
    {
        Savepoint sp = Database.setSavepoint();

        List<sObject> records = getRecords(objAPINm, 'Id', recordId, null);
        Id jitRecordId        = (Id)records[0].get('JIT_Day__c');
        records[0].put('JIT_Day__c', null);

        JIT_Day__c jitDay = new JITDaysSelector().selectById(jitRecordId);
        if (jitDay.Utilised_Slots__c < 0)
        {
            // throw new AuraHandledException('Oops! Something wrong with Utilised Slot. Please check again!');
            AuraHandledException e = new AuraHandledException('Oops! Something wrong with Utilised Slot. Please check again!');
            e.setMessage('Oops! Something wrong with Utilised Slot. Please check again!');
            system.debug(e);
            throw e;
        }

        jitDay.Utilised_Slots__c -= 1;

        Vehicle_Master2__c svm;
        if (objAPINm == 'Sales_Agreement__c')
        {
            Sales_Agreement__c sa  = SalesAgreementService.getSalesAgrmnt(recordId);

            if(sa.JIT_Status__c == 'Pending')
            {
                svm = (Vehicle_Master2__c)getRecords('Vehicle_Master2__c', 'Id', sa.Stock_Reservation__r.Vehicle_Master__r.Id, null)[0];
                svm.JIT_Day__c = null;                
                sendEmailToNCLUsers(sa.SOH_SONO__c, svm.Agreement_No__c, sa.Sales_Consultant__c, svm.Chassis__c, svm.Name);
            }
            else
            {
                // throw new AuraHandledException('JIT SLot can not be cancelled. Please check JIT Status!');
                AuraHandledException e = new AuraHandledException('JIT SLot can not be cancelled. Please check JIT Status!');
                e.setMessage('JIT SLot can not be cancelled. Please check JIT Status!');
                system.debug(e);
                throw e;

            }
        }

        try
        {
            update records;
            update jitDay;
            if (svm != null)
            {
                update svm;
            }
            
        }
        catch (Exception e)
        {
            Database.rollback(sp);

            throw e;
        }
    }
    
    @testVisible
    private static List<sObject> getRecords(String objectName, String conditionField, String conditionValue, String additionalCondition) 
    {
        String mainQueryCondition = conditionField + ' = ' + '\'' + conditionValue + '\'';

        if (additionalCondition != null && String.isNotBlank(additionalCondition)) 
        {
            mainQueryCondition += ' ' + additionalCondition;
        }

        List<SObject> result = ADGLIB_UtilityHelper.getSObjectRecords(objectName, mainQueryCondition, false); 

        return result;
    }

    @testVisible
    private static void sendEmailToNCLUsers(String saNo, String svmNo, String scName, String chassic, String svmName)
    {
        List<Profile> profiles = [SELECT Id FROM Profile WHERE Name = 'New Car Logistic'];
        
        List<Id> profileIds = new List<Id>();
        for(Profile profile : profiles){
            profileIds.add(profile.Id);
        }

        List<User> newCarLogistics = [SELECT Id, Email FROM User WHERE ProfileId IN :profileIds];

        List<String> emailAddress = new List<String>();

        if(newCarLogistics.size()>0)
        {
            for(User NCLUser : newCarLogistics)
            {
                emailAddress.add(NCLUser.Email);
            }
        }
        
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();        
        mail.setToAddresses(emailAddress);        
        mail.setSubject('JIT Slot has beeb cancelled');
        mail.setPlainTextBody('Dear User \nJIT Slot has beeb cancelled as below info: \n SA No.: ' + saNo +'\nSVM No.: ' + svmNo + '\nSC Name: ' + scName + '\nVehicle Chassic: ' + chassic + '\nSVM Name: ' + svmName);
        System.debug('Send to Email Address :' + mail.getToAddresses());
        mails.add(mail);        

        if (mails.size() > 0) 
        {
            Messaging.SendEmailResult[] results = Messaging.sendEmail(mails, false);       
            
            for (Messaging.SendEmailResult rs : results) 
            {
                if (!rs.isSuccess()) 
                {
                    for(Messaging.SendEmailError err : rs.getErrors()) 
                    {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('fields that affected this error: ' + err.getFields());
                    }
                }
                else
                {
                    System.debug('Successfull send email to NCL');  
                }
            }  
        }
    }

    public class JITWrapper {
        @AuraEnabled public sObject curRecInfo           { get; set; }
        @AuraEnabled public List<JIT_Day__c> jitDaysList { get; set; }
        @AuraEnabled public JIT_Day__c bookedJIT         { get; set; }
        @AuraEnabled public Boolean isSalesAdmin         { get; set; }
        @AuraEnabled public Boolean isSalesConsultant    { get; set; }
    }
}