cncProd/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Custom object representing showroom/service center.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Special_Tool__c/Special_Tool__c.object-meta.xml
<CustomObject>
    <label>Special Tool</label>
    <nameField>
        <label>Special Tool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Tools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Special_Tool__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates booking availability of tool</description>
    <label>Available for Booking</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Special_Tool__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Special_Tool__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Special_Tool__c/fields/Service_Centre__c.field-meta.xml
<CustomField>
    <fullName>Service_Centre__c</fullName>
    <description>Location of Service Centre for the tool</description>
    <label>Service Centre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Centre_Location</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Special_Tool__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VALID</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Special_Tool_Booking__c/Special_Tool_Booking__c.object-meta.xml
<CustomObject>
    <label>Special Tool Booking</label>
    <nameField>
        <displayFormat>Booking-{0000}</displayFormat>
        <label>Special Tool Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Tool Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Special_Tool_Booking__c/fields/Borrow_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Borrow_DateTime__c</fullName>
    <label>Borrowed Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Special_Tool_Booking__c/fields/Borrowed_By__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrowed By</label>
    <referenceTo>Workshop_Technician__c</referenceTo>
    <relationshipLabel>Special Tool Bookings</relationshipLabel>
    <relationshipName>Special_Tool_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Special_Tool_Booking__c/fields/Borrowed_Location__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_Location__c</fullName>
    <label>Borrowed Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Centre_Location</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Special_Tool_Booking__c/fields/Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Status__c</fullName>
    <label>Loan Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Special_Tool_Booking__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <formula>Special_Tool__r.Part_Number__c</formula>
    <label>Part Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Special_Tool_Booking__c/fields/Return_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Return_DateTime__c</fullName>
    <label>Returned Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Special_Tool_Booking__c/fields/Returned_By__c.field-meta.xml
<CustomField>
    <fullName>Returned_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Returned By</label>
    <referenceTo>Workshop_Technician__c</referenceTo>
    <relationshipLabel>Special Tool Bookings (Returned By)</relationshipLabel>
    <relationshipName>Special_Tool_Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Special_Tool_Booking__c/fields/Returned_Location__c.field-meta.xml
<CustomField>
    <fullName>Returned_Location__c</fullName>
    <label>Returned Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Centre_Location</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Special_Tool_Booking__c/fields/Special_Tool__c.field-meta.xml
<CustomField>
    <fullName>Special_Tool__c</fullName>
    <label>Special Tool</label>
    <referenceTo>Special_Tool__c</referenceTo>
    <relationshipName>Special_Tools_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Leng Kee</fullName>
            </value>
            <value>
                <fullName>Pandan Gardens</fullName>
            </value>
            <value>
                <fullName>Sin Ming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workshop_Technician__c/Workshop_Technician__c.object-meta.xml
<CustomObject>
    <label>Workshop Technician</label>
    <nameField>
        <label>Workshop Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workshop Technicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Workshop_Technician__c/fields/Access_Code__c.field-meta.xml
<CustomField>
    <fullName>Access_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Access Code</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Workshop_Technician__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Centre_Location</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/globalValueSets/Service_Centre_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mercedes Benz Service Center Pandan Loop</fullName>
    </customValue>
    <customValue>
        <fullName>Mercedes Benz Service Center Eunos</fullName>
    </customValue>
    <customValue>
        <fullName>Mercedes Benz Service Center Alexandra</fullName>
    </customValue>
    <customValue>
        <fullName>Mercedes-Benz Commercial Vehicle Service Center Pandan Garden</fullName>
    </customValue>
    <customValue>
        <fullName>Leng Kee Service Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Sin Ming Service Centre</fullName>
    </customValue>
    <masterLabel>Service Centre Location</masterLabel>
</GlobalValueSet>

cncProd/force-app/main/default/classes/specialToolController.cls
/** ******
* Description: Tool Actions
* 
* Change History:
* Date(YYYYMMDD)      Name        		    Description
* yyyymmdd            nguyen.thang          Created Initial Version.
* 
** ******/

public class specialToolController {
    
    @AuraEnabled
    public static User getRunningUser(){
        User runningUsr = [Select Name, UserRole.Name From User Where Id = :UserInfo.getUserId() LIMIT 1];  
        return runningUsr;
    }
    
    @AuraEnabled
    public static Workshop_Technician__c getUserInfo(String accessCode){
        try{     
            Workshop_Technician__c userInfo = [Select Name, Department__c, Location__c From Workshop_Technician__c 
                                               Where Access_code__c = :accessCode LIMIT 1];  
            return userInfo;         
        }
        catch(Exception e){
            return null;  
        }
    }
    
    /*@AuraEnabled
    public static Object getTool(String partNo){
        try{
            Special_Tool__c tool = [Select Id, Part_Number__c, Name, Remarks__c, Available__c, Service_Centre__c From Special_Tool__c 
                                    Where Part_Number__c = :partNo LIMIT 1];  
            if(tool.Available__c){      
                return tool;
            }else{
                return 'ToolNotAvailable';
            }    
        }
        catch(Exception e){
            return 'Empty';  
        }
    }*/

    /**
     * ADDED BY THIEU DANG VU - 22/10/2021
     * Part No is not unique identifier anymore
     */
    @AuraEnabled
    public static List<Special_Tool__c> getTool(String partNo) {

        return [SELECT Id, Part_Number__c, Name, Remarks__c, Available__c, Service_Centre__c 
                FROM Special_Tool__c 
                WHERE Part_Number__c = :partNo AND Available__c = true AND Status__c = 'VALID'
                ORDER BY Id];
    }
    
    @AuraEnabled
    public static List<Special_Tool_Booking__c> borrowTools(String userId, List<Special_Tool__c> tools){
        try{
            List<Special_Tool_Booking__c> stbToInsert = new List<Special_Tool_Booking__c>();
            Set<Id> toolIds = new Set<Id>();
            for(Special_Tool__c tool: tools){
                if(tool.Available__c){
                    Special_Tool_Booking__c stb = new Special_Tool_Booking__c();
                    stb.Borrowed_By__c = userId;
                    stb.Loan_Status__c = 'Borrowed';
                    stb.Special_Tool__c = tool.Id;
                    stb.Borrowed_Location__c = tool.Service_Centre__c;
                    stb.Borrow_DateTime__c = system.now();
                    stbToInsert.add(stb);
                    toolIds.add(tool.Id);
                }
            }
            
            if(!stbToInsert.isEmpty()){
                insert stbToInsert;   
                List<Special_Tool__c> stl = [SELECT Id, Available__c FROM Special_Tool__c WHERE Id IN: toolIds];
                for(Special_Tool__c st: stl){
                    st.Available__c = false;
                }
                update stl;
            }
            
            List<Special_Tool_Booking__c> toolsBorrowedByUser = [SELECT Id, Borrowed_By__r.Name, Borrow_DateTime__c, Borrowed_Location__c,
                                                                 Special_Tool__r.Id, Special_Tool__r.Part_Number__c, Special_Tool__r.Name, Special_Tool__r.Remarks__c
                                                                 FROM Special_Tool_Booking__c 
                                                                 WHERE Borrowed_By__c = : userId AND Loan_Status__c = 'Borrowed' 
                                                                 AND Special_Tool__r.Id IN: toolIds];
            return toolsBorrowedByUser;
        }
        catch(Exception e){
            return null;  
        }    
    }
    
    /*@AuraEnabled
    public static Object getToolBooking(String partNo){
        try{        
            Special_Tool__c tool = [Select Id, Part_Number__c, Name, Available__c From Special_Tool__c Where Part_Number__c = :partNo LIMIT 1]; 
            if(tool.Available__c){
                return 'ToolIsAvailable';
            }
            Special_Tool_Booking__c toolBooking = [SELECT Id, Borrowed_By__r.Name, Borrow_DateTime__c, Borrowed_Location__c,
                                                   Special_Tool__r.Id, Special_Tool__r.Part_Number__c, Special_Tool__r.Name, Special_Tool__r.Remarks__c
                                                   FROM Special_Tool_Booking__c 
                                                   WHERE Special_Tool__r.Part_Number__c = : partNo AND Loan_Status__c = 'Borrowed' LIMIT 1];
            return toolBooking; 
        }
        catch(Exception e){
            return 'Empty';  
        }
    }*/

    /**
     * ADDED BY THIEU DANG VU - 22/10/2021
     * Part No is not unique identifier anymore
    */
    @AuraEnabled
    public static List<Special_Tool_Booking__c> getToolBooking(String partNo, String userId) {

        return [SELECT Id, Borrowed_By__r.Name, Borrow_DateTime__c, Borrowed_Location__c,
                        Special_Tool__r.Id, Special_Tool__r.Part_Number__c, Special_Tool__r.Name, Special_Tool__r.Remarks__c
                FROM Special_Tool_Booking__c 
                WHERE Special_Tool__r.Part_Number__c = : partNo AND Loan_Status__c = 'Borrowed' AND Borrowed_By__r.Id = :userId];
    }
    
    @AuraEnabled
    public static void returnTool(String userId, List<Special_Tool_Booking__c> toolBookings, String location){
        Set<Id> toolIds = new Set<Id>();
        for(Special_Tool_Booking__c stb: toolBookings){
            stb.Loan_Status__c = 'Returned';
            stb.Returned_By__c = userId;
            stb.Return_DateTime__c = system.now();
            stb.Returned_Location__c = location;
            toolIds.add(stb.Special_Tool__r.Id);
        }
        update toolBookings;
        
        if(!toolIds.isEmpty()){
            List<Special_Tool__c> stls = [SELECT Id, Available__c FROM Special_Tool__c WHERE Id IN :toolIds];
            for(Special_Tool__c tool:stls){
                tool.Available__c = true;
            } 
            update stls;
        }
        
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getPickListLocation(){
        List<String> values = new List<String>();
        Schema.DescribeFieldResult fieldResult = Special_Tool__c.Service_Centre__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            values.add(pickListVal.getLabel());
        }     
        return values;
    }   
    
}