cncProd/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Custom object representing showroom/service center.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Meeting_Log_V2__c/Meeting_Log_V2__c.object-meta.xml
<CustomObject>
    <label>Meeting Log</label>
    <nameField>
        <displayFormat>Meeting-{0000}</displayFormat>
        <label>Meeting Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Log_V2__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kia Showroom</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Kia Showroom</label>
            </value>
            <value>
                <fullName>Mitsubishi Showroom</fullName>
            </value>
            <value>
                <fullName>Citroen Showroom</fullName>
            </value>
            <value>
                <fullName>DS Showroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Meeting_Log_V2__c/fields/Type_of_Meeting_Logs__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Meeting_Logs__c</fullName>
    <label>Type of Meeting Logs</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning Briefing</fullName>
            </value>
            <value>
                <fullName>Debrief</fullName>
            </value>
            <value>
                <fullName>Biweekly Sales Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/MeetingLogCreatedRelatedAgendasTest.cls
@IsTest
public class MeetingLogCreatedRelatedAgendasTest 
{
    static testMethod void testMeetingLogCreatedAgendas()
    {
        Test.startTest();
        
        Meeting_Log_V2__c meetingLogs = new Meeting_Log_V2__c();
        meetingLogs.Location__c = 'Location1';
        meetingLogs.Type_of_Meeting_Logs__c = 'Morning Briefing';
        meetingLogs.Location__c = 'Kia Showroom1';
        insert meetingLogs;
        
        Meeting_Log_V2__c meetingLogs1 = new Meeting_Log_V2__c();
        meetingLogs1.Location__c = 'Location2';
        meetingLogs1.Type_of_Meeting_Logs__c = 'Debrief';
        meetingLogs1.Location__c = 'Kia Showroom2';
        insert meetingLogs1;
        
        Meeting_Log_V2__c meetingLogs2 = new Meeting_Log_V2__c();
        meetingLogs2.Location__c = 'Location3';
        meetingLogs2.Type_of_Meeting_Logs__c = 'Biweekly Sales Marketing';
        meetingLogs2.Location__c = 'Kia Showroom3';
        insert meetingLogs2;

        Test.stopTest();
        
    }
}