cncProd/force-app/main/default/objects/Term_and_Condition__mdt/Term_and_Condition__mdt.object-meta.xml
<CustomObject>
    <label>Term and Condition</label>
    <pluralLabel>Term and Conditions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Term_and_Condition__mdt/fields/Associated_Checkbox_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Associated_Checkbox_Field_API_Name__c</fullName>
    <inlineHelpText>If filled, it will update the associate API Field</inlineHelpText>
    <label>Associated Checkbox Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Term_and_Condition__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <inlineHelpText>Object API Name of the Field to be updated</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/termsAndConditionsCtl.cls
public with sharing class termsAndConditionsCtl {
    
    public class ResponseWrapper {
        @AuraEnabled public Term_and_Condition__mdt metadataRecord { get; set; }
        @AuraEnabled public sObject currentRecord { get; set; }
    }

    @AuraEnabled(cacheable=true)
    public static ResponseWrapper doGetInformation(String CurrentRecordId, String FieldValue,  String ObjectName, String FieldName) {
        ResponseWrapper returnWrap = new ResponseWrapper();

        returnWrap.metadataRecord = (Term_and_Condition__mdt)fetchRecords(FieldValue, ObjectName, FieldName, '')[0];
 
        if(String.isBlank(returnWrap.metadataRecord.Associated_Checkbox_Field_API_Name__c) == false && returnWrap.metadataRecord.Associated_Checkbox_Field_API_Name__c != ''){
            returnWrap.currentRecord = fetchRecords(CurrentRecordId, returnWrap.metadataRecord.Object_API_Name__c, 'Id', '')[0];
        }
        return returnWrap;
    }


    @AuraEnabled
    public static string updateInformation(String ObjectName, String FieldName, String FieldValue, Id RecordId){
        Boolean value = Boolean.valueOf(FieldValue);
        List<SObject> sObjectsToUpdate = new List<SObject>();

        SObject currentRecord = RecordId.getSObjectType().newSObject(RecordId);
        currentRecord.put(FieldName, value);
        sObjectsToUpdate.add(currentRecord);
        update sObjectsToUpdate;

        return 'updated';
    }

    @AuraEnabled(cacheable=true)
    public static List<sObject> fetchRecords(String RecordId, String ObjectName, String FieldName, String AdditionalCondition) {
        String MainQueryCondition = FieldName + ' = ' + '\'' + RecordId + '\'';
        if(String.isNotBlank(AdditionalCondition)) {
            MainQueryCondition += ' ORDER BY ' + AdditionalCondition;
        }

        List<sObject> ListofRecords = ADGLIB_UtilityHelper.getSObjectRecords(ObjectName, MainQueryCondition, false); 
        return ListofRecords;
    }
}