cncProd/force-app/main/default/objects/ClashDeal__c/ClashDeal__c.object-meta.xml
<CustomObject>
    <description>Temporary Storage of Clash Deals Notification for End of Day Reporting</description>
    <label>Clash Opportunity</label>
    <nameField>
        <displayFormat>CLASH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clash Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Custom_Quote__c/Custom_Quote__c.object-meta.xml
<CustomObject>
    <label>Custom Quote</label>
    <nameField>
        <label>Custom Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>All app feedbacks are migrated to be case records</description>
    <label>Feedback (Not Used Anymore)</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{YYMM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Custom_Quote__c.field-meta.xml
<CustomField>
    <fullName>Custom_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Drive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Share__c/Share__c.object-meta.xml
<CustomObject>
    <label>Share</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Share</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PABatchLeadToPAConverter.cls
/** *****
 * Description : Batch class to create prospect PA from Lead
 * 
 * Change History
 * Date(YYYYMMDD)      Name        Description
 * 20200224            AT          Created Initial Version. 
 * 
** *****/
global class PABatchLeadToPAConverter implements Database.Batchable<sObject>, Database.Stateful{

    private List<String> errMsgs = new List<String>();
    Set<Id> setTargetedLeadIds = new Set<Id>();

    global PABatchLeadToPAConverter(){}

    global PABatchLeadToPAConverter( Set<Id> setOfLeadIds ){
        this.setTargetedLeadIds = setOfLeadIds;
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        LeadSelector selector = new LeadSelector();
        // return Database.getQueryLocator( selector.getUnconvertedLead() );
        System.debug('@@@@DEBUG PABatchLeadToPAConverter >> start >> setTargetedLeadIds.size() = ' + setTargetedLeadIds.size() );
        return Database.getQueryLocator( selector.getUnconvertedLead(  ((setTargetedLeadIds<>null && !setTargetedLeadIds.isEmpty())  ? setTargetedLeadIds : null )  ) );
        //return Database.getQueryLocator( selector.getSelectiveUnconvertedLead(setTargetedLeadIds) );
    }

    global void execute(Database.BatchableContext bc, List<Lead> leads){
        System.debug('@@@@DEBUG PABatchLeadToPAConverter >> execute >> leads.size() = ' + leads.size() );

        try{
            List<String> childObjects = new List<String>{'Event_Registration__c','Share__c','ClashDeal__c','Opportunity','Invoice__c',
                                                        'Custom_Quote__c','Customer_Detail__c','Test_Drive__c','Feedback__c'};
            
            LeadSelector selector = new LeadSelector();
            Set<String> leadIds = new Set<String>();
            for(Lead ld : leads){
                leadIds.add(ld.Id);
            }

            List<Map<String, List<SObject>>> childListMaps = new List<Map<String, List<SObject>>>();
            for(String childObject : childObjects){
                childListMaps.add(selector.getSObjectLeadMap(leadIds, childObject));
            }                                            
            
            PAMigrationService.processConversion(leads, childListMaps);
        }
        catch(Exception ex){
            errMsgs.add(ex.getMessage());
        }
        
    }

    global void finish(Database.BatchableContext BC){
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses              = new String[] {'hwanshyan.lim@aodigy.com'};
        mail.setToAddresses(toAddresses);
        // mail.setTargetObjectId( UserInfo.getUserId() );
    	// mail.setSaveAsActivity(false);
        String body;
        if(!errMsgs.isEmpty()){
            for(Integer i=0; i<errMsgs.size(); i++){
                body += (String.valueof(i+1)+' '+errMsgs[i]+ '\r\n');
            }
            System.debug('@@@@DEBUG PABatchLeadToPAConverter >> finish :: body = ' + body);
        }
        else{
            body = 'Success';
        }
        mail.setPlainTextBody(body);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }

}