cncProd/force-app/main/default/objects/MB_Build_Spec__c/MB_Build_Spec__c.object-meta.xml
<CustomObject>
    <label>MB Build Spec</label>
    <nameField>
        <displayFormat>MBBS-{00000000}</displayFormat>
        <label>MB Build Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Build Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Build_Spec__c/fields/AVCODE__c.field-meta.xml
<CustomField>
    <fullName>AVCODE__c</fullName>
    <label>AVCODE</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Build_Spec__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>MB Build Specs</relationshipLabel>
    <relationshipName>MB_Build_Specs</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Build_Spec__c/fields/Option_Type__c.field-meta.xml
<CustomField>
    <fullName>Option_Type__c</fullName>
    <label>Option Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Build_Spec__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>MB Build Specs</relationshipLabel>
    <relationshipName>MB_Build_Specs</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_SA_Spec__c/MB_SA_Spec__c.object-meta.xml
<CustomObject>
    <label>MB SA Spec</label>
    <nameField>
        <displayFormat>MBSAS-{000000}</displayFormat>
        <label>MB SA Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB SA Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_SA_Spec__c/fields/Fit_Type__c.field-meta.xml
<CustomField>
    <fullName>Fit_Type__c</fullName>
    <inlineHelpText>S = Standard Items
O = Optional Items</inlineHelpText>
    <label>Fit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/MB_SA_Spec__c/fields/MB_Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>MB_Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MB Sales Agreement</label>
    <referenceTo>MB_Sales_Agreement__c</referenceTo>
    <relationshipLabel>MB SA Specs</relationshipLabel>
    <relationshipName>MB_SA_Specs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MB_SA_Spec__c/fields/PRINT__c.field-meta.xml
<CustomField>
    <fullName>PRINT__c</fullName>
    <label>PRINT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YN</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/MB_Sales_Agreement__c/MB_Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>MB Sales Agreement</label>
    <nameField>
        <displayFormat>MBSA-{000000}</displayFormat>
        <label>MB Sales Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Sales_Agreement__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>MB_Stock_Vehicle_Master__r.Model__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Model</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Sales_Agreement__c/fields/Total_Optional_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Total_Optional_Equipment__c</fullName>
    <label>Total Optional Equipment Charges Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Sales_Agreement__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <formula>MB_Stock_Vehicle_Master__r.VariantDescription__c</formula>
    <label>Variant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Code__c/Product_Code__c.object-meta.xml
<CustomObject>
    <description>For Inward Declaration</description>
    <label>Product Code</label>
    <nameField>
        <label>Product Code Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Code__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Variant__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <externalId>true</externalId>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/YN.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
    </customValue>
    <customValue>
        <fullName>N</fullName>
    </customValue>
    <masterLabel>YN</masterLabel>
</GlobalValueSet>

cncProd/force-app/main/default/classes/mbVehicleSpecsCtl.cls
public with sharing class mbVehicleSpecsCtl {

    /**
     * wrapper class for spec data
     */
    public class SpecData {
        @AuraEnabled public SObject SA { get; set; }
        @AuraEnabled public List<SObject> specs { get; set; }
    }

    /**
     * get sales agreement together with its specs
     */
    @AuraEnabled(cacheable=true)
    public static SpecData getSpecData(String recordID) 
    {
        // throw new AuraHandledException('TEST');
        SpecData returnWrap = new SpecData();
        returnWrap.SA = getRecords('MB_Sales_Agreement__c', 'ID', recordID,  '')[0];
        returnWrap.specs = getRecords('MB_SA_Spec__c', 'MB_Sales_Agreement__c', recordID, ' AND PRINT__C = \'Y\'');
        return returnWrap;
    }

    /**
     * 
     */
    @AuraEnabled(cacheable=true)
    public static List<SObject> doGetAvailableSpecs(String VariantId, String ModelId, String Keyword) 
    {
        List<sObject> BuildSpecRecords = new List<sObject>();
        //Conditions: Only AVCODE O and S + Only Option Type D and F + Model and Variant of stock OR Model of stocks with empty variant OR both model and variant empty
        string AdditionalCondition = '(AVCODE__c =\'O\' OR AVCODE__c = \'S\') AND (Option_Type__c =\'D\' OR Option_Type__c = \'F\')';
        string ModelVariantCondition = '((Model__c =\'' + ModelId + '\' AND Variant__c =\'' + VariantId + '\') OR (Model__c =\'\' AND Variant__c =\'\') OR (Model__c =\'' + ModelId + '\' AND Variant__c =\'\'))';

        AdditionalCondition = AdditionalCondition + ' AND ' + ModelVariantCondition + ' ORDER BY Description__c ASC';
        //If there are keywords to search
        if(Keyword != ''){
            AdditionalCondition = AdditionalCondition + ' AND Description__c LIKE ' + '\'%' +  Keyword  + '%\'';
        }

        BuildSpecRecords = fetchRecordwithConditionOnly('MB_Build_Spec__c', AdditionalCondition);

        return BuildSpecRecords;
    }

    @AuraEnabled
    public static void deleteSpec(String saID, String specID) 
    {
        List<MB_SA_Spec__c> specs = [SELECT ID FROM MB_SA_Spec__c WHERE ID = :specID];

        if (specs.size() == 0) return;

        Savepoint sp = Database.setSavepoint();

        try {
            delete specs;
            updateTOEV(saID);
        } catch(Exception e) {
            Database.rollback(sp);
            throw e;
        }
        
    }

    /**
     * update total optional equipment value
     */
    @AuraEnabled
    public static void updateTOEV(String saID)
    {
        List<MB_SA_Spec__c> specs = [SELECT Invoice_Value__c, Product_Code__c FROM MB_SA_Spec__c 
                                    WHERE MB_Sales_Agreement__c = :saID 
                                    AND PRINT__C = 'Y'
                                    AND Fit_Type__c = 'O'];

        MB_Sales_Agreement__c SA = [SELECT Total_Optional_Equipment__c FROM MB_Sales_Agreement__c WHERE ID = :saID];

        Decimal total = 0;

        for (MB_SA_Spec__c spec : specs) {
            Boolean isSVCOrBoutique = false;
            if (String.isNotEmpty(spec.Product_Code__c)) {
                isSVCOrBoutique = spec.Product_Code__c.startsWith('SVC') || spec.Product_Code__c.startsWith('RSVC') ||
                                    spec.Product_Code__c.startsWith('BOUTVC');
            }
            if (!isSVCOrBoutique && spec.Invoice_Value__c != null) {
                total += spec.Invoice_Value__c;
            }
        }

        SA.Total_Optional_Equipment__c = total;

        update SA;
    }

    /**
     * get records that have @conditionField equal @conditionValue and met @additionalCondition
     */
    private static List<sObject> getRecords(String objectName, String conditionField, String conditionValue, String additionalCondition) 
    {
        String mainQueryCondition = conditionField + ' = ' + '\'' + conditionValue + '\'';

        if(additionalCondition != null && String.isNotBlank(additionalCondition)) 
        {
            mainQueryCondition += ' ' + additionalCondition;
        }

        List<SObject> result = ADGLIB_UtilityHelper.getSObjectRecords(objectName, mainQueryCondition, false); 
        return result;
    }

    public static List<SObject> fetchRecordwithConditionOnly(String ObjectName, String AdditionalCondition) 
    {
        List<sObject> results = ADGLIB_UtilityHelper.getSObjectRecords(ObjectName, AdditionalCondition, false); 
        return results;
    }

}