force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Models_Interested__c/Models_Interested__c.object-meta.xml
<CustomObject>
    <label>Models Interested</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Models Interested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Models Interested</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Models_Interested__c/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <formula>IF(INCLUDES( Touch_Points__c, &apos;Event Registration&apos;),1,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Registration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Models_Interested__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Models Interested</relationshipLabel>
    <relationshipName>Models_Interested</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Models_Interested__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Opportunity_Closed_6Month_Scheduler.cls
public class Opportunity_Closed_6Month_Scheduler implements Database.Batchable<sObject>, Schedulable, Database.Stateful{
  
    public String queryString = '';
    public String batchForDataPool = '';
    Date before180days = Date.today().addDays(-180);
    
    public Opportunity_Closed_6Month_Scheduler(){
        batchForDataPool = 'Opportunity_Closed_6Month_Scheduler';
        queryString = 'Select Id, StageName from Opportunity where LastModifiedDate <= :before180days AND StageName!=\'Booked\' AND StageName!=\'Lost\' ';
        System.debug('@@@'+queryString);
      }
      
    public Database.QueryLocator start(Database.BatchableContext bc){
        return database.getQueryLocator(queryString);
      }
      
    public void execute(Database.BatchableContext bc, list<Opportunity> OppsToClose){ 
        Map<Id,Opportunity> oppMap = new Map<Id,Opportunity>();
        List<Models_Interested__c> mIUpdList = new List<Models_Interested__c>();
        List<Opportunity> oppList= new List<Opportunity>();
       
        if(!OppsToClose.isEmpty()){
            for(Opportunity opp : OppsToClose)
                {
                    oppMap.put(opp.id,opp);  
                }
            if(!oppMap.isEmpty()){
                 for(Models_Interested__c mi :[SELECT id,Opportunity__c,Status__c from Models_Interested__c where Opportunity__c!=null and Opportunity__c IN : oppMap.KeySet() and LastModifieddate >= : before180days ]){
                        if(oppMap.ContainsKey(mi.Opportunity__c)){
                            oppMap.remove(mi.Opportunity__c);    
                        }
                    }             
                 for(Event_Registration__c er : [SELECT id,Opportunity__c from Event_Registration__c where Opportunity__c!=null and Opportunity__c IN : oppMap.KeySet() and LastModifieddate >= : before180days]){
                     if(oppMap.ContainsKey(er.Opportunity__c)){
                            oppMap.remove(er.Opportunity__c);    
                        }
                  }                                
                 for (Opportunity opp : oppMap.values())
                    {
                        opp.StageName = 'Lost';
                        oppList.add(opp);
                    }
            
             TriggerExclusion.excludeTrigger('Opportunity', true);
                 DataBase.Update(oppList);
             TriggerExclusion.excludeTrigger('Opportunity', false);
             if(!oppList.isEmpty()){
                    for(Models_Interested__c mi : [SELECT id,Opportunity__c,Status__c from Models_Interested__c where Opportunity__c!=null and Opportunity__c IN : OppList]){
                        if(oppMap.ContainsKey(mi.Opportunity__c)){
                            mi.Status__c = 'Lost';   
                            mIUpdList.add(mi);                     
                        }
                    }
                    DataBase.Update(mIUpdList);                 
             }
           }
        }         
    }
  
     public void finish(Database.BatchableContext bc){
         batchDataPool.buildBatchDataPool(batchForDataPool, bc.getJobId());    
     }
     
     public void execute(SchedulableContext sc){
            new BatchManager('Opportunity_Closed_6Month_Scheduler', null);
     }
     
}