force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Reservation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Stock Reservations</relationshipLabel>
    <relationshipName>Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Re_Reserve_To_VSMS__c.field-meta.xml
<CustomField>
    <fullName>Re_Reserve_To_VSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-Reserve To VSMS?</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/classes/BatchToUpdateSRToVSMS.cls
/*
	Author: Hari Panneerselvam
*/
global class BatchToUpdateSRToVSMS implements Database.Batchable<sObject>, Database.AllowsCallouts{
	 
	public String queryString = '';
	public String batchForDataPool = '';
	
	public BatchToUpdateSRToVSMS(String batchFor){
		batchForDataPool = batchFor;
		queryString = Queries.updateSRToVSMS;
	}
	 
	global Database.QueryLocator start(Database.BatchableContext bc){
		return database.getQueryLocator(queryString);
	}
	
	global void execute(Database.BatchableContext bc, list<Stock_Reservation__c> lstStockReservation){
		for(Stock_Reservation__c itr : lstStockReservation){
			itr.Re_Reserve_To_VSMS__c = false;
			BusinessRuleHandlerVSMS.isBatchCall = true;
			BusinessRuleHandlerVSMS.updateStockVSMS(itr.Id, itr.Opportunity__r.Owner.Username2__c, false); 
		}
		update lstStockReservation;
	}
	 
	global void finish(Database.BatchableContext bc){
    	batchDataPool.buildBatchDataPool(batchForDataPool, bc.getJobId());
    }
    
}