force-app/main/default/objects/Business_Associate_Master__c/Business_Associate_Master__c.object-meta.xml
<CustomObject>
    <label>Business Associate Master</label>
    <nameField>
        <label>Business Associate Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Associate Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Associate_Master__c/fields/BAM_ASSOCIATECD__c.field-meta.xml
<CustomField>
    <fullName>BAM_ASSOCIATECD__c</fullName>
    <externalId>true</externalId>
    <label>BAM_ASSOCIATECD</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Business_Associate_Master__c/fields/BAM_INHOUSE__c.field-meta.xml
<CustomField>
    <fullName>BAM_INHOUSE__c</fullName>
    <label>BAM_INHOUSE</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Associate_Master__c/fields/BAM_TYPE__c.field-meta.xml
<CustomField>
    <fullName>BAM_TYPE__c</fullName>
    <label>BAM_TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>INS</fullName>
            </value>
            <value>
                <fullName>USC</fullName>
            </value>
            <value>
                <fullName>EXSRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/BusinessAssociateMasterSelector.cls
public class BusinessAssociateMasterSelector extends ADGLIB_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>  {   
            Business_Associate_Master__c.Id,
            Business_Associate_Master__c.Name,
            Business_Associate_Master__c.BAM_ASSOCIATECD__c,
            Business_Associate_Master__c.BAM_TYPE__c,
            Business_Associate_Master__c.BAM_ASSOCIATECD__c,
            Business_Associate_Master__c.BAM_INHOUSE__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Business_Associate_Master__c.sObjectType;
    }

    public LIST<Business_Associate_Master__c> selectByType(LIST<String> typeList){
       	adglib_QueryFactory query = newQueryFactory();
        
        query.setCondition('BAM_TYPE__c in:typeList');
        system.debug('typeList ' + query.toSOQL());
        return (List<Business_Associate_Master__c>) Database.query(query.toSOQL());
    }

}