force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/fields/System_Commcase__c.field-meta.xml
<CustomField>
    <fullName>System_Commcase__c</fullName>
    <label>System Commcase</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/StockVehicleMasterSelector.cls
public inherited sharing class StockVehicleMasterSelector extends ADGLIB_SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Vehicle_Master2__c.Id,
            Vehicle_Master2__c.System_Commcase__c
		};
    }    
    
    public Schema.SObjectType getSObjectType() {
        return Vehicle_Master2__c.sObjectType;
    }    
    
    public List<Vehicle_Master2__c> selectStockVehicleMastersBySystemCommcases(Set<String> systemCommcases) {
        adglib_QueryFactory query = newQueryFactory();
        query.setCondition('System_Commcase__c In :systemCommcases');
        
        return Database.query(query.toSOQL());
    }
}