cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/Campaign_Promo_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Campaign Upsell Accessory</label>
    <nameField>
        <label>Campaign Upsell Accessories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Upsell Accessories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Upsell Accessories</relationshipLabel>
    <relationshipName>Campaign_Promo_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Promo_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Promo_Line_Item__c</fullName>
    <label>Upsell Accessory</label>
    <referenceTo>Promo_Line_Item__c</referenceTo>
    <relationshipLabel>Campaign Upsell Accessories</relationshipLabel>
    <relationshipName>Campaign_Promo_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Amount__c</fullName>
    <formula>Promo_Line_Item__r.Threshold_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Threshold Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/Promo_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Accessories tied to the Targeted Sales Promo campaigns for Upselling Accessories during DSA process.</description>
    <label>Upsell Accessory</label>
    <nameField>
        <label>Upsell Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upsell Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promo_Line_Item__c/fields/No_of_Stock__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stock__c</fullName>
    <label>No. of Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/fields/Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Amount__c</fullName>
    <label>Threshold Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CampaignPromoLineItemSelector.cls
/*******
 * Description : Selector class for Campaign Promo Line Item object
 * 
 * Change History :
 * Date(YYYYMMDD)      Name                    Description
 * 20220324         thu.phan@aodigy.com     Created Initial Version 
*******/

public class CampaignPromoLineItemSelector extends ADGLIB_SObjectSelector
{
    public Schema.SObjectType getSObjectType() 
    {
        return Campaign_Promo_Line_Item__c.sObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() 
    {
        return ADGLIB_UtilityHelper.getSObjectFieldListByObj('Campaign_Promo_Line_Item__c');
    }

    public List<Campaign_Promo_Line_Item__c> getCampaignPromoLineItemsByIds(Set<String> recordIds) 
    {
        adglib_QueryFactory query = newQueryFactory();    
        query.selectFields(new Set<String>{'Promo_Line_Item__r.No_of_Stock__c', 'Campaign__r.Owner.Email', 'Campaign__r.OwnerId', 'Promo_Line_Item__r.Threshold_Amount__c'});
        String str_filter = ' Id IN: recordIds '; 
        query.setCondition( str_filter );

        return Database.query(query.toSOQL());
    }
}