cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/Campaign_Promo_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Campaign Upsell Accessory</label>
    <nameField>
        <label>Campaign Upsell Accessories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Upsell Accessories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Promo_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Promo_Line_Item__c</fullName>
    <label>Upsell Accessory</label>
    <referenceTo>Promo_Line_Item__c</referenceTo>
    <relationshipLabel>Campaign Upsell Accessories</relationshipLabel>
    <relationshipName>Campaign_Promo_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign_Promo_Line_Item__c/fields/Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Amount__c</fullName>
    <formula>Promo_Line_Item__r.Threshold_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Threshold Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promo_Line_Item__c/Promo_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Accessories tied to the Targeted Sales Promo campaigns for Upselling Accessories during DSA process.</description>
    <label>Upsell Accessory</label>
    <nameField>
        <label>Upsell Accessory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upsell Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promo_Line_Item__c/fields/Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Amount__c</fullName>
    <label>Threshold Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/classes/CampaignPromoLineItemSelectorTest.cls
/** ******
 * Description : Test class for CampaignPromoLineItemSelector.cls
 * 
 * Change History:
 * Date(YYYYMMDD)       Name                    Description
 * 20220419             thanh.ly@aodigy         Created Initial Version. 
 * 
** ******/
@isTest
private class CampaignPromoLineItemSelectorTest{
    @TestSetup
    static void setUp(){
        User user = Test_DataFactory.createUser(true, 'Thanh', 'Ly');

        Campaign cam = Test_DataFactory.createCamp(false, 'Targeted Promo Kia', 'Promotions', 'CCK');
        cam.OwnerId = user.Id;
        insert cam;

        Promo_Line_Item__c item = Test_DataFactory.createPromoLineItem(false, 'USB', 100, 80, 'Blue', 10);
        item.Threshold_Amount__c = 100;
        insert item;
        
        Campaign_Promo_Line_Item__c camItem = Test_DataFactory.createCampaignPromoLineItem(true, cam.Id, item.Id);
    }
    
    @isTest
    static void Test_getCampaignPromoLineItemsByIds(){
        Campaign_Promo_Line_Item__c camItem = [SELECT Id FROM Campaign_Promo_Line_Item__c];

        CampaignPromoLineItemSelector camSel = new CampaignPromoLineItemSelector();
        List<Campaign_Promo_Line_Item__c> camItems = camSel.getCampaignPromoLineItemsByIds(new Set<String> {camItem.Id});
        
        System.assertEquals(1, camItems.size());
    }
}