force-app/main/default/objects/DWH_last_run_date__c/DWH_last_run_date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the date on which DWH data was migrated to SF last.</description>
    <label>DWH_last_run_date</label>
</CustomObject>

force-app/main/default/objects/DWH_last_run_date__c/fields/ServicePackage_TotalPage__c.field-meta.xml
<CustomField>
    <fullName>ServicePackage_TotalPage__c</fullName>
    <label>ServicePackage_TotalPages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Package_Item__c/Service_Package_Item__c.object-meta.xml
<CustomObject>
    <label>Service Package Item</label>
    <nameField>
        <label>Service Package Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Package Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Service_Package_Item__c/fields/DWH_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>DWH_Item_Id__c</fullName>
    <externalId>true</externalId>
    <label>DWH Item Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Package_Item__c/fields/Item_Balance__c.field-meta.xml
<CustomField>
    <fullName>Item_Balance__c</fullName>
    <label>Item Balance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Package_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Package_Item__c/fields/Item_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Item_Expiry_Date__c</fullName>
    <label>Item Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Package_Item__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Package Items</relationshipLabel>
    <relationshipName>Service_Package_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Packages__c/Service_Packages__c.object-meta.xml
<CustomObject>
    <label>Service Package</label>
    <nameField>
        <label>Service Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/ITEM_BALANCE__c.field-meta.xml
<CustomField>
    <fullName>ITEM_BALANCE__c</fullName>
    <label>ITEM BALANCE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/ITEM_DESCRIPTION__c.field-meta.xml
<CustomField>
    <fullName>ITEM_DESCRIPTION__c</fullName>
    <label>ITEM DESCRIPTION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Packages__c/fields/ITEM_EXPIRY_DATE__c.field-meta.xml
<CustomField>
    <fullName>ITEM_EXPIRY_DATE__c</fullName>
    <label>ITEM EXPIRY DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Packages__c/fields/PACKAGE_DESCRIPTION__c.field-meta.xml
<CustomField>
    <fullName>PACKAGE_DESCRIPTION__c</fullName>
    <label>PACKAGE DESCRIPTION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Packages</relationshipLabel>
    <relationshipName>Service_Packages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/classes/Test_DWH_GetServicePackage_Data.cls
@IsTest(SeeAllData=true)
global  with sharing class Test_DWH_GetServicePackage_Data 
{
     //Positive Test Scenario
    @isTest global static void testPositive()
    {
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"MP":[{"PACKAGE_NAME": "*CC17P","PACKAGE_DESCRIPTION": "Citroen Care Service Plan","RTSCODE": "CC17GP2BEHSAP","DESCRIPTION": "Lubrication (Service A)","EXPIRED_DATE": "2020-12-17T00:00:00","REMAIN_QTY": 1,"MAGIC": 322292,"DATECOST": "2018-06-18T00:00:00"}]}');
        res.setStatusCode(200);
        datetime todayt;
    DWH_GetServicePackage_Data.UpdateDataParser(res);
        DWH_GetServicePackageItem_Data.UpdateDataParser(res);
       
        List<Service_Packages__c> tempServicePackages = [Select Name,Registered_Vehicle__c,ITEM_BALANCE__c,ITEM_DESCRIPTION__c,ITEM_EXPIRY_DATE__c,PACKAGE_DESCRIPTION__c
                       From Service_Packages__c where Name like '%CC17P'];
    
        List<Service_Package_Item__c> tempServicePackagesItem = [Select Name,DWH_Item_Id__c,Item_Description__c,Item_Balance__c,Item_Expiry_Date__c
                       From Service_Package_Item__c where Name like '%Lubrication (Service A)%'];
       
       DWH_GetServicePackage_Data.ServicePackage  ServicePackageObj = new DWH_GetServicePackage_Data.ServicePackage('*CC17P', 'Citroen Care Service Plan', 'CC17GP2BEHSAP', 
                                                  'Lubrication (Service A)', todayt, 0.0, '322292','');     
      
       DWH_GetServicePackageItem_Data.ServicePackage  ServicePackageObjItem = new DWH_GetServicePackageItem_Data.ServicePackage('*CC17P', 'Citroen Care Service Plan', 'CC17GP2BEHSAP', 
                                                  'Lubrication (Service A)', todayt, 0.0, '322292','');   
       
        //System.assertEquals('*CC17P',tempServicePackages[0].Name);
       //System.assertEquals('Lubrication (Service A)',tempServicePackagesItem[0].Name);
    
    }
    
           
    
     public static testmethod void test_AllPackage() 
    {        
        //CGaylan: This is a temporary fix to get bypass too many future calls
        //Best Practice is not use seeAlldata = true 
        //we should implement a mocking framework instead
        DWH_last_run_date__c rv = DWH_last_run_date__c.getOrgDefaults();
        rv.ServicePackage_TotalPage__c = 1;
        upsert rv;
        
        
    	DWH_GetServicePackage_Data.getServicePakageData(); 
        DWH_GetServicePackageItem_Data.getServicePakageItemData();
    }
    
}