force-app/main/default/objects/DWH_last_run_date__c/DWH_last_run_date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the date on which DWH data was migrated to SF last.</description>
    <label>DWH_last_run_date</label>
</CustomObject>

force-app/main/default/objects/DWH_last_run_date__c/fields/RegVehicle_NumRecords__c.field-meta.xml
<CustomField>
    <fullName>RegVehicle_NumRecords__c</fullName>
    <inlineHelpText>Number of Record of Register Vehicle to sync per API call</inlineHelpText>
    <label>RegVehicle NumRecords</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/global_var__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>JCC Global Variables</label>
</CustomObject>

force-app/main/default/objects/global_var__c/fields/APIGateway_key__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_key__c</fullName>
    <label>APIGateway_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/fields/APIGateway_url__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_url__c</fullName>
    <label>APIGateway_url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Car_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Car_Collection_Date__c</fullName>
    <label>Car Collection Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Comm_No__c.field-meta.xml
<CustomField>
    <fullName>Comm_No__c</fullName>
    <label>Comm No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/DWH_Vehicle_ID__c.field-meta.xml
<CustomField>
    <fullName>DWH_Vehicle_ID__c</fullName>
    <externalId>true</externalId>
    <label>DWH Vehicle ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Extended_Warranty_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Extended_Warranty_End_Date__c</fullName>
    <label>Extended Warranty End Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/IU__c.field-meta.xml
<CustomField>
    <fullName>IU__c</fullName>
    <label>IU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Last_Battery_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Battery_Change__c</fullName>
    <label>Last Battery Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Last_Service_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Booking_Date__c</fullName>
    <label>Last Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Last_Service_Booking_KM__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Booking_KM__c</fullName>
    <label>Last Service KM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Manufacture_Warranty_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Manufacture_Warranty_End_Date__c</fullName>
    <label>Manufacture Warranty End Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Next_Recommended_Servi__c.field-meta.xml
<CustomField>
    <fullName>Next_Recommended_Servi__c</fullName>
    <label>Next Recommended Servi</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Next_Service_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Service_Booking_Date__c</fullName>
    <label>Next Service Rec Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Next_Service_Booking_KM__c.field-meta.xml
<CustomField>
    <fullName>Next_Service_Booking_KM__c</fullName>
    <label>Next Service Rec KM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>Registered_Date__c</fullName>
    <label>Registered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/SCR__c.field-meta.xml
<CustomField>
    <fullName>SCR__c</fullName>
    <label>SCR</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Self_Import_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Self_Import_Vehicle__c</fullName>
    <label>Self Import Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Service_Credits__c.field-meta.xml
<CustomField>
    <fullName>Service_Credits__c</fullName>
    <label>Service Credits</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Service_Credits_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Credits_Expiry_Date__c</fullName>
    <label>Service Credits Expiry Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/VehicleDataSource__c.field-meta.xml
<CustomField>
    <fullName>VehicleDataSource__c</fullName>
    <description>Maps to VEHICLE_DATASOURCE json attribute</description>
    <inlineHelpText>Maps to VEHICLE_DATASOURCE json attribute</inlineHelpText>
    <label>Vehicle Data Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/RegisteredVehicleService.cls
/**
 * @File Name          : RegisteredVehicleService.cls
 * @Description        : JIRA29
 * @Author             : jmt@aodigy.com
 * @Group              : 
 * @Last Modified By   : jmt@aodigy.com
 * @Last Modified On   : 2/24/2020, 10:27:05 AM
 * @Modification Log   : 
 * Ver      Date             Author      		     Modification
 * 1.0      02/12/2020       jmt@aodigy.com          Initial Version
 * 2.0      09/08/2020       hs@aodigy.com           Added pageNum to allow the API Callout being invoked incrementally 
**/
public inherited Sharing class RegisteredVehicleService {

    //@future(callout=true)
    public static HttpResponse getDataFromDWH(Integer pageNum, Datetime rundate) {
        HttpRequest req = new HttpRequest();
        HttpResponse resp = new HttpResponse();
        Http http = new Http();    
        
        global_var__c JCC_GlobalVar = global_var__c.getOrgDefaults();  
    
        DWH_last_run_date__c LastRunDateVar = DWH_last_run_date__c.getOrgDefaults();      
        String numRecs = LastRunDateVar.RegVehicle_NumRecords__c <> null ? String.valueOf(LastRunDateVar.RegVehicle_NumRecords__c.intValue()): '2000';
        
        // req.setEndpoint((String)JCC_GlobalVar.APIGateway_url__c+'/DWHAPI/GetRegVehicle_DWH?syncDate='+rundate.format('MM/dd/yyyy')+'&noOfRecords=0&pageNo=0');
        req.setEndpoint((String)JCC_GlobalVar.APIGateway_url__c+'/DWHAPI/GetRegVehicle_DWH?syncDate='+rundate.format('MM/dd/yyyy')+'&noOfRecords='+numRecs+'&pageNo='+String.ValueOf(pageNum));
        system.debug('Endpoint ====>: '+req.getEndpoint());
        req.setMethod('GET');
        req.setHeader('apikey', (String)JCC_GlobalVar.APIGateway_key__c); 
        req.setHeader('Content-Type', 'application/json'); 
        req.setTimeout(120000);
        try{
            resp = http.send(req);
            //RegisteredVehicleService.processResponse(resp);
            serviceDataPool.buildServiceDataPoolHttp('RegisteredVehicleCallout', 'RegisteredVehicleService', '', req, resp);
            
        }catch(Exception error){
            loggerDataPool.buildLogDataPool('RegisteredVehicleService', error);
        }

        return resp;
    }

    public static void updateDataFromDWH(HttpResponse resp){
        ADGLIB_SObjectUnitOfWork uow = new ADGLIB_SObjectUnitOfWork(new Schema.SObjectType[] {Registered_Vehicle__c.SObjectType});
        RegisteredVehicleUOWHelper updateUOW = new RegisteredVehicleUOWHelper();
        uow.registerWork(updateUOW);

        RegisteredVehicleSelector registeredVehSelector = new RegisteredVehicleSelector();
        MAP<String, Registered_Vehicle__c> magicVehicleMap = new  MAP<String, Registered_Vehicle__c>();
        Set <String> magicVehicleSet = new Set<String>();

        JSONParser parser = JSON.createParser(resp.getBody());
    
        while (parser.nextToken() != null) {   
            if (parser.getCurrentToken() == JSONToken.START_ARRAY) {
                while (parser.nextToken() != null) {
                    if (parser.getCurrentToken() == JSONToken.START_OBJECT){
                        RegisteredVehicleDWH respRow = (RegisteredVehicleDWH)parser.readValueAs(RegisteredVehicleDWH.class);
                        system.debug('Return ResponseRow:==> ' + respRow);

        
                        Registered_Vehicle__c rec = new Registered_Vehicle__c();
                        rec.DWH_Vehicle_ID__c = respRow.MAGIC_VEHICLE;
                        rec.source__c = 'DWH';  
                        rec.Service_Credits__c = respRow.SVCCRDBAL;
                        rec.Self_Import_Vehicle__c = respRow.IMMOBIL;
                        rec.Next_Service_Booking_KM__c = respRow.NEXTSMIL;
                        rec.Next_Recommended_Servi__c = respRow.NXTRECOMNDSVC;
                        rec.Last_Service_Booking_KM__c = respRow.LASTSMILE;
                        rec.IU__c = respRow.SECURENO;
                        rec.Engine_Number__c = respRow.ENGINE;
                        rec.Comm_No__c = respRow.COMM;
                        rec.vehicleDatasource__c = respRow.VEHICLE_DATASOURCE;
                        rec.registration_number__c = respRow.REGNO;
                        
                        rec.Mileage__c = decimal.valueOf(respRow.IMILEAGEU);
                        rec.SCR__c = Integer.valueof(respRow.SCRBAL);
                        rec.extended_warranty_end_date__c = isValidDate(respRow.WAREXTDT) == false ? null : respRow.WAREXTDT.date();
                        rec.last_battery_change__c = stringToDate(respRow.LASTBATTERYCHANGEdate);
                        rec.Service_Credits_Expiry_Date__c = isValidDate(respRow.SVCCRDEXPDT) == false ? null : respRow.SVCCRDEXPDT.date();
                        rec.Registered_Date__c = isValidDate(respRow.REGDATE) == false ? null : respRow.REGDATE.date();
                        rec.Next_Service_Booking_Date__c = isValidDate(respRow.NEXTSERV) == false ? null : respRow.NEXTSERV.date();
                        rec.Manufacture_Warranty_End_Date__c = isValidDate(respRow.WAREXPDT) == false ? null : respRow.WAREXPDT.date();
                        rec.Last_Service_Booking_Date__c = isValidDate(respRow.LASTSERV) == false ? null : respRow.LASTSERV.date();
                        rec.Car_Collection_Date__c = isValidDate(respRow.COLLECTIONDATE) == false ? null : respRow.COLLECTIONDATE.date();
                        magicVehicleMap.put(rec.DWH_Vehicle_ID__c, rec);
                        magicVehicleSet.add(rec.DWH_Vehicle_ID__c);
   
                    }
                }
            }
            
            if(!(magicVehicleSet.isEmpty())){
                for(Registered_Vehicle__c result : registeredVehSelector.selectByMagicVehicle(magicVehicleSet)){
                    Registered_Vehicle__c rec = magicVehicleMap.get(result.DWH_Vehicle_ID__c);
                    rec.Id = result.Id;
                    updateUOW.registerRegVehicle(rec);
                    //uow.registerDirty(rec);
                }
                uow.commitWork();
                updateUOW.logServiceDataPool();
                
            }
            
        }

        //uow.commitWork();
    }

    private static Date stringToDate(String textDate){
        Date returnDate = null;
        if(String.isNotBlank(textDate)){
            List<String> strList = textDate.split('/');
            if(strList!=null && !strList.isEmpty()){
                returnDate = Date.newInstance(Integer.valueOf(strList.get(2)), 
                    Integer.valueOf(strList.get(1)),
                    Integer.valueOf(strList.get(0)));
            }
        }
        return returnDate;
    }
    private static Boolean isValidDate(Datetime checkDate){
        Boolean returnStatus = false;
        String nullDate = '0001';
        Pattern myPattern = dateFormatMatcher();

        if(checkDate == null || String.valueOf(checkDate).startsWith(nullDate)){
            returnStatus = false;
        }else if(myPattern.matcher(String.valueOf(checkDate.date())).matches()){
            returnStatus = true;
        }

        return returnStatus;
    }
    private static Pattern dateFormatMatcher(){
        return Pattern.compile('((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])');
    }
    public class RegisteredVehicleDWH{

       public String FRANCHISE;
       public String FRANCHISECODE;
       public String REGNO;
       public String COMM;
       public String ENGINE;
       public String CHASSIS;
       public String NEXTSMIL;
       public String SECURENO;
       public String MAGIC;
       public String IMMOBIL;
       public Datetime REGDATE;
       public Datetime COLLECTIONDATE;
       public Datetime LASTSERV;
       public String LASTBATTERYCHANGEdate;
       public Datetime NEXTSERV;
       public Datetime WAREXPDT;
       public Datetime WAREXTDT;
       public Datetime SVCCRDEXPDT;
       public String SVCCRDBAL;
       public String SCRBAL;
       public String MODELYR;
       public String IMILEAGEU;
       public String EXTContactID;
       public String COLCODE;
       public String VARIANT;
       public String LASTSMILE;
       public String NXTRECOMNDSVC;
       public String MAGIC_VEHICLE;
       public String VEHICLE_DATASOURCE;
       public String MAGIC_MBPC;
       public String MAGIC_MBCV;
       public String MAGIC_MF;
       public String MAGIC_FUL;
       public String MAGIC_CUSTOMER;
    }
    
}