force-app/main/default/objects/DWH_last_run_date__c/DWH_last_run_date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the date on which DWH data was migrated to SF last.</description>
    <label>DWH_last_run_date</label>
</CustomObject>

cncProd/force-app/main/default/objects/DWH_last_run_date__c/fields/isSuccess__c.field-meta.xml
<CustomField>
    <fullName>isSuccess__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isSuccess</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/DWH_last_run_date__c/fields/No_of_Records__c.field-meta.xml
<CustomField>
    <fullName>No_of_Records__c</fullName>
    <label>No of Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DWH_last_run_date__c/fields/ServicePackage_TotalPage__c.field-meta.xml
<CustomField>
    <fullName>ServicePackage_TotalPage__c</fullName>
    <label>ServicePackage_TotalPages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DWH_last_run_date__c/fields/Time_Out__c.field-meta.xml
<CustomField>
    <fullName>Time_Out__c</fullName>
    <label>Time Out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/global_var__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>JCC Global Variables</label>
</CustomObject>

force-app/main/default/objects/global_var__c/fields/APIGateway_key__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_key__c</fullName>
    <label>APIGateway_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/fields/APIGateway_url__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_url__c</fullName>
    <label>APIGateway_url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/DWH_Vehicle_ID__c.field-meta.xml
<CustomField>
    <fullName>DWH_Vehicle_ID__c</fullName>
    <externalId>true</externalId>
    <label>DWH Vehicle ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Packages__c/Service_Packages__c.object-meta.xml
<CustomObject>
    <label>Service Package</label>
    <nameField>
        <label>Service Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Packages__c/fields/DWH_PACKAGE_ID__c.field-meta.xml
<CustomField>
    <fullName>DWH_PACKAGE_ID__c</fullName>
    <externalId>true</externalId>
    <label>DWH PACKAGE ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/ITEM_BALANCE__c.field-meta.xml
<CustomField>
    <fullName>ITEM_BALANCE__c</fullName>
    <label>ITEM BALANCE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/ITEM_DESCRIPTION__c.field-meta.xml
<CustomField>
    <fullName>ITEM_DESCRIPTION__c</fullName>
    <label>ITEM DESCRIPTION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Packages__c/fields/ITEM_EXPIRY_DATE__c.field-meta.xml
<CustomField>
    <fullName>ITEM_EXPIRY_DATE__c</fullName>
    <label>ITEM EXPIRY DATE</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/ITEM_ID__c.field-meta.xml
<CustomField>
    <fullName>ITEM_ID__c</fullName>
    <label>ITEM ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Packages__c/fields/PACKAGE_DESCRIPTION__c.field-meta.xml
<CustomField>
    <fullName>PACKAGE_DESCRIPTION__c</fullName>
    <label>PACKAGE DESCRIPTION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Packages</relationshipLabel>
    <relationshipName>Service_Packages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DWH_GetServicePackage_Data.cls
//Class for DWH service Packages 
global class DWH_GetServicePackage_Data implements Schedulable
{
Public static Integer count=0;
Public static Service_Packages__c tempServicePackages;
Public Static Boolean isSuccess  = True;
Public Static List<String> DebugLogsListSuccess = New List<String>();
Public Static List<String> DebugLogsListError = New List<String>();
   
global void execute(SchedulableContext ctx)
{getServicePakageData();}


public static void getServicePakageData()            
{
    try 
    {   
        DWH_last_run_date__c LastRunDateVar = DWH_last_run_date__c.getOrgDefaults();  
        Integer TotalPages = Integer.valueOf(LastRunDateVar.ServicePackage_TotalPage__c);      

        for(Integer i = 1; i <= TotalPages; i++) 
        {
            UpdateData(i);
        }        
    }
    catch(exception ex1)
    {
        system.debug(ex1.getMessage());
    }
}


//Create future call out method for http call    
@future (callout=true)    
public static void UpdateData(Integer PageNum)            
{
     //create http request, response objects here
    HttpRequest req = new HttpRequest();
    HttpResponse resInput = new HttpResponse();
    Http http = new Http();
    
    global_var__c JCC_GlobalVar = global_var__c.getOrgDefaults();      
    String  APIGateway_url = (String)JCC_GlobalVar.APIGateway_url__c;
    String  APIGateway_key = (String)JCC_GlobalVar.APIGateway_key__c;

    DWH_last_run_date__c LastRunDateVar = DWH_last_run_date__c.getOrgDefaults(); 
    Integer noOfRecords                 = Integer.valueOf(LastRunDateVar.No_of_Records__c);
    
    //Set properties of the  http request
    req.setEndpoint(APIGateway_url+'/DWHAPI/GetMyPackageDistinct_DWH?noOfRecords=' + String.valueOf(noOfRecords) + '&pageNo=' + String.ValueOf(PageNum));
    req.setMethod('GET');
    req.setHeader('apikey', APIGateway_key); 
    req.setHeader('Accept', 'application/json');
    req.setHeader('Content-Type','application/json;charset=UTF-8');
    
    Integer timeOut = Integer.valueOf(LastRunDateVar.Time_Out__c);
    req.setHeader('Content-Type', 'application/json'); 
    req.setTimeout(timeOut);
    //Send http request, capture response and pass the response to mothod which 
    //will then process the same and update the SFSC object
    try
    {
        resInput = http.send(req);
        UpdateDataParser(resInput);
        
        DebugLogs.getDebugLogs('DWH_GetServicePackage_Data'+PageNum,DebugLogsListSuccess,DebugLogsListError);
        serviceDataPool.buildServiceDataPoolHttp('getServicePakageData', 'DWH_GetServicePackage_Data', '', req, resInput);           
    }
    catch(exception ex1)
    {
        loggerDataPool.buildLogDataPool('DWH_GetServicePackage_Data', ex1);
        system.debug(ex1.getMessage());
    }
}
    public static void UpdateDataParser(HttpResponse res)    
    { 
    //List of objects with updated response
    list<Service_Packages__c> LstServicePackage = new list<Service_Packages__c>();
    Map<String, Service_Packages__c> LstServicePackageMAP = new Map<String, Service_Packages__c>();
    
    try 
    {        
        // Parse entire JSON response.        
        JSONParser parser = JSON.createParser(res.getBody());

        System.debug('Response::: ' + res.getBody() + ' ' + parser);
        
        while (parser.nextToken() != null) {
            // Start at the array of ServicePackages.
            if (parser.getCurrentToken() == JSONToken.START_ARRAY) {
                while (parser.nextToken() != null) {
                    // Advance to the start object marker to
                    //  find next ServicePackage object.
                    if (parser.getCurrentToken() == JSONToken.START_OBJECT) 
                    {
                        // Read entire ServicePackage object, including its array of line items.
                        ServicePackage sVar = (ServicePackage)parser.readValueAs(ServicePackage.class);
                        
                        tempServicePackages = New Service_Packages__c ();  
                        tempServicePackages.Name = sVar.PACKAGE_NAME ;
                        tempServicePackages.DWH_PACKAGE_ID__c = sVar.PACKAGE_NAME+','+sVar.MAGIC;
                        tempServicePackages.Source__c = 'DWH';
                        //tempServicePackages.ITEM_ID__c = sVar.RTSCODE;
                        //tempServicePackages.ITEM_BALANCE__c = sVar.REMAIN_QTY;
                        //tempServicePackages.ITEM_DESCRIPTION__c = sVar.DESCRIPTION ;                        
                        String dateRegEx = '((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])';
                        Pattern myPattern = Pattern.compile(dateRegEx); 
                        If(sVar.EXPIRED_DATE!=null)
                        {
                            Matcher myMatcher = myPattern.matcher(String.valueOf(sVar.EXPIRED_DATE.date())); 
                            if(myMatcher.matches())
                            {
                                tempServicePackages.ITEM_EXPIRY_DATE__c =  sVar.EXPIRED_DATE.date();
                            }         
                        }
                        tempServicePackages.PACKAGE_DESCRIPTION__c = sVar.PACKAGE_DESCRIPTION ;
                        Registered_Vehicle__c tempVeh = new Registered_Vehicle__c();                            
                        tempVeh.DWH_Vehicle_ID__c  =  sVar.MAGIC ;
                        tempServicePackages.Registered_Vehicle__r = tempVeh;
                        
                        //Add ServicePackages to list from API response.
                        LstServicePackageMAP.put(tempServicePackages.DWH_PACKAGE_ID__c, tempServicePackages);
                    }
                }
            }
        }
        
        LstServicePackage = LstServicePackageMAP.values();
        //Upsert the list of updated ServicePackages into SFSC.
        Database.UpsertResult[] results = Database.upsert(LstServicePackage, Service_Packages__c.Fields.DWH_PACKAGE_ID__c, False);       
        
        //Verify and Log the records which were created, updated and threw an error.
        for(Integer index = 0, size = results.size(); index < size; index++) 
        {
            if(results[index].isSuccess()) 
            {
                if(results[index].isCreated()) 
                {
                    System.debug(LstServicePackage[index].DWH_PACKAGE_ID__c+' was created');
                    DebugLogsListSuccess.add(LstServicePackage[index].DWH_PACKAGE_ID__c+' was created');
                } 
                else 
                {
                    System.debug(LstServicePackage[index].DWH_PACKAGE_ID__c+' was updated');
                    DebugLogsListSuccess.add(LstServicePackage[index].DWH_PACKAGE_ID__c+' was updated');
                }
            }
            else
            {
                //isSuccess = False;
                system.debug(LstServicePackage[index].DWH_PACKAGE_ID__c +' had error '+results[index].getErrors());
                DebugLogsListError.add(LstServicePackage[index].DWH_PACKAGE_ID__c +' had error '+results[index].getErrors());                
            }
        }        
    } 
    catch(System.Exception e) 
    {
        isSuccess = False;
        System.debug('System_error: '+ e);
        DebugLogsListError.add('System_error: '+e.getMessage());
    }
        DWH_last_run_date__c LastRunDateVar = DWH_last_run_date__c.getOrgDefaults(); 
        LastRunDateVar.isSuccess__c = isSuccess;
        upsert LastRunDateVar;
}
//Define ServicePackage parser class here to parse JSON values to variant fields.
public class ServicePackage {
  
    public String PACKAGE_NAME;
    public String PACKAGE_DESCRIPTION;
    public String RTSCODE;
    public String DESCRIPTION;
    public DateTime  EXPIRED_DATE;
    public Decimal REMAIN_QTY;
    public String MAGIC;
    public String DATECOST;
    
    
    
    public ServicePackage(String PACKAGE_NAMEstr, String PACKAGE_DESCRIPTIONstr, String RTSCODEstr, String DESCRIPTIONstr, 
                          DateTime  EXPIRED_DATEstr , Decimal REMAIN_QTYstr,String MAGICstr, 
                          String DATECOSTstr) 
    {
        PACKAGE_NAME = PACKAGE_NAMEstr;
        PACKAGE_DESCRIPTION = PACKAGE_DESCRIPTIONstr;
        RTSCODE = RTSCODEstr;
        DESCRIPTION = DESCRIPTIONstr;
        EXPIRED_DATE = EXPIRED_DATEstr;
        REMAIN_QTY = REMAIN_QTYstr;
        MAGIC = MAGICstr;
        DATECOST = DATECOSTstr;
        
        
    }
} 

}