force-app/main/default/objects/DWH_last_run_date__c/DWH_last_run_date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the date on which DWH data was migrated to SF last.</description>
    <label>DWH_last_run_date</label>
</CustomObject>

cncProd/force-app/main/default/objects/DWH_last_run_date__c/fields/Post_Service_Sync_From__c.field-meta.xml
<CustomField>
    <fullName>Post_Service_Sync_From__c</fullName>
    <label>Post Service Sync From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DWH_last_run_date__c/fields/Post_Service_Sync_To__c.field-meta.xml
<CustomField>
    <fullName>Post_Service_Sync_To__c</fullName>
    <label>Post Service Sync To</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/classes/DWH_AftersalesAPIResyncController.cls
/** *****
* Description : Controller class of custom action Resync.
*
* Change History
* Date(YYYYMMDD)      Name       		Description
* 20200915            huynh.hung       Created Initial Version.
*
** *****/
public class DWH_AftersalesAPIResyncController {
    @AuraEnabled
    public static void getSyncAPIAgain(Date fromDate, Date toDate)
    {
        DWH_last_run_date__c lastRunDateVar = DWH_last_run_date__c.getOrgDefaults();
		lastRunDateVar.Post_Service_Sync_From__c = fromDate;
        lastRunDateVar.Post_Service_Sync_To__c = toDate;
		update lastRunDateVar;
        //System.debug('lastRunDateVar before batch:' + lastRunDateVar.Post_Service_Sync_From__c + ',' + lastRunDateVar.Post_Service_Sync_To__c);
        BatchAftersalesServiceHeader batchable = new BatchAftersalesServiceHeader(); 
        Database.executebatch(batchable, 1);
    }
}