force-app/main/default/objects/DWH_last_run_date__c/DWH_last_run_date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the date on which DWH data was migrated to SF last.</description>
    <label>DWH_last_run_date</label>
</CustomObject>

force-app/main/default/objects/DWH_last_run_date__c/fields/Vehicle_Credit_NumberOfPages__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Credit_NumberOfPages__c</fullName>
    <label>Vehicle Credit NumberOfPages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Credit__c/Vehicle_Credit__c.object-meta.xml
<CustomObject>
    <description>Used to capture Vehicle Credit data (i.e. Service / Accessories ) from DWH</description>
    <label>Vehicle Credit</label>
    <nameField>
        <displayFormat>VCR-{0000000}</displayFormat>
        <label>Vehicle Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles Credit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/classes/DWH_GetVehicleCreditData_Sch.cls
/*******
 * Description : Scheduler class that used to sync the Vehicle Credit data from DWH
 * 
 * Change History : 
 * Date(YYYYMMDD)       Name                Description
 * 20200217             HS@aodigy           Created Initial Version 
 * 20200720             HS@aodigy           Added invokeVehicleCreditDateSync method invocation
 * 20200827             HS@aodigy           Added Database.AllowsCallouts, Database.Batchable<sObject>, Database.Stateful
 * 
*******/
global class DWH_GetVehicleCreditData_Sch implements Schedulable, Database.AllowsCallouts, Database.Batchable<sObject>, Database.Stateful {


    public Integer currentPage = 1;
    public static Boolean success = true;

    public void execute(SchedulableContext ctx)
    {
        Database.executebatch(new DWH_GetVehicleCreditData_Sch(),1);
    }

    public Iterable<sObject> start(Database.Batchablecontext BC)
    {
        VehicleCreditService.getGetCreditAccountDWHCount(null,null);
        DWH_last_run_date__c LastRunDateVar = DWH_last_run_date__c.getOrgDefaults();  
        Integer totalPages = Integer.valueOf(LastRunDateVar.Vehicle_Credit_NumberOfPages__c);
        System.debug('@@@@DEBUG DWH_GetVehicleCreditData_Sch:: START :: totalPages = '+totalPages);
        return [SELECT Id FROM Vehicle_Credit__c LIMIT :totalPages];    
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){  

        DWH_last_run_date__c LastRunDateVar = DWH_last_run_date__c.getOrgDefaults();  
        Integer totalPages = Integer.valueOf(LastRunDateVar.Vehicle_Credit_NumberOfPages__c);
        System.debug('@@@@DEBUG DWH_GetVehicleCreditData_Sch:: EXECUTE :: currentPage = ' + this.currentPage + ' / ' + totalPages + ' --- scope.size() ' + scope.size());

        if( currentPage <= totalPages)
        {
            VehicleCreditService.getVehicleCreditDataFromDWH(currentPage, null, null);
            this.currentPage = this.currentPage + 1;
        }
    }

    public void finish(Database.BatchableContext info)
    {
        VehicleCreditService.updateDWHcustomSetting( success );
    }

}