force-app/main/default/objects/AlertsRegisteredVehicle__mdt/AlertsRegisteredVehicle__mdt.object-meta.xml
<CustomObject>
    <description>Primary Use: Manual Run of Alerts</description>
    <label>AlertsRegisteredVehicle</label>
    <pluralLabel>AlertsRegisteredVehicles</pluralLabel>
</CustomObject>

force-app/main/default/objects/CustomerAlerts__c/CustomerAlerts__c.object-meta.xml
<CustomObject>
    <label>CustomerAlerts</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerAlerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CustomerAlerts (Account)</relationshipLabel>
    <relationshipName>CustomerAlerts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Alert_Description__c.field-meta.xml
<CustomField>
    <fullName>Alert_Description__c</fullName>
    <label>Alert Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isAlert__c.field-meta.xml
<CustomField>
    <fullName>isAlert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isAlert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isEmail__c.field-meta.xml
<CustomField>
    <fullName>isEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isEmail</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/isPush__c.field-meta.xml
<CustomField>
    <fullName>isPush__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPush</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isSMS__c.field-meta.xml
<CustomField>
    <fullName>isSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Service Appointment</description>
    <label>Service Appointment</label>
    <referenceTo>Service_Appointment__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>unread</fullName>
            </value>
            <value>
                <fullName>read</fullName>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
            <value>
                <fullName>eyriuwbicaueiq</fullName>
                <isActive>false</isActive>
                <label>eyriuwbicaueiq</label>
            </value>
            <value>
                <fullName>unred</fullName>
                <isActive>false</isActive>
                <label>unred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>SubType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due 1st Reminder</fullName>
            </value>
            <value>
                <fullName>Due 2nd Reminder</fullName>
            </value>
            <value>
                <fullName>Due 3rd Reminder</fullName>
            </value>
            <value>
                <fullName>Overdue 1st Reminder</fullName>
            </value>
            <value>
                <fullName>Overdue 2nd Reminder</fullName>
            </value>
            <value>
                <fullName>Overdue 3rd Reminder</fullName>
            </value>
            <value>
                <fullName>E-shop</fullName>
            </value>
            <value>
                <fullName>Notice</fullName>
            </value>
            <value>
                <fullName>Evergreen Promotion</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Paid Event</fullName>
            </value>
            <value>
                <fullName>Non-Paid Event</fullName>
            </value>
            <value>
                <fullName>Sales Targeted Promo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First Service</fullName>
            </value>
            <value>
                <fullName>Subsequent Service</fullName>
            </value>
            <value>
                <fullName>Plan/Package</fullName>
            </value>
            <value>
                <fullName>Service Credits</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
            <value>
                <fullName>Battery Change</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
            <value>
                <fullName>Accessories Credits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/recordTypes/Alert.recordType-meta.xml
<RecordType>
    <fullName>Alert</fullName>
    <active>true</active>
    <description>Customer Alert</description>
    <label>Alert</label>
</RecordType>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Last_Service_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Booking_Date__c</fullName>
    <label>Last Service Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Next_Service_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Service_Booking_Date__c</fullName>
    <label>Next Service Rec Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>Registered_Date__c</fullName>
    <label>Registered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/Service_Appointment__c.object-meta.xml
<CustomObject>
    <label>Service Appointment</label>
    <nameField>
        <label>Service Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments (Account)</relationshipLabel>
    <relationshipName>Service_Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Service_Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Date_Time__c</fullName>
    <label>Service Appointment Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <label>Service Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Code__mdt/Service_Code__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata setup for Aftersales: service code</description>
    <label>Service Code</label>
    <pluralLabel>Service Code</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service_Code__mdt/fields/Service_Description__c.field-meta.xml
<CustomField>
    <fullName>Service_Description__c</fullName>
    <label>Service Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/firstServiceNoticeReminder.cls
//Apex class for  first serice and appt reminder

global class firstServiceNoticeReminder implements Schedulable
{
    //Variable declaration 
    public static list <Registered_Vehicle__c> firstServiceObj {get;set;}
    public static list <Registered_Vehicle__c> firstServiceNoticeObj {get;set;}
    public static Date today            = date.today();
    public static DateTime todaytime    = datetime.now();
    public static Date passedThreeDays  = today.addDays(-3);
    public static Date nextFourteenDays = today.addDays(14);
    public static Date nextSevenDays    = today.addDays(7);
    public static List <CustomerAlerts__c> customerAlertList  = new  List<CustomerAlerts__c>(); 

    global void execute(SchedulableContext ctx){
        firstServiceNoticeNReminder();
        firstServiceSecondReminder();
    }
    
    //function for first service reminder  
    public static void firstServiceNoticeNReminder()
    {

        Set<String> setServiceCode = new Set<String>();           
        for(Service_Code__mdt scode : [SELECT Service_Description__c FROM Service_Code__mdt])
		{
            setServiceCode.add(scode.Service_Description__c);
        }           

        try
        {
            List <Service_Appointment__c> lstServiceAppt = new  List <Service_Appointment__c>();
            
            //fetching list of all registered vehicle with today or future service appointments    
            lstServiceAppt = [SELECT Registered_Vehicle__c 
                              FROM Service_Appointment__c
                              WHERE Service_Appointment_Date_Time__c >= today
                              AND Action__c != 'Cancel'
                              AND Service_Code__c in: setServiceCode];

            List<String> regNoList = new List<String>();
            for(Service_Appointment__c svcAppt : lstServiceAppt) {
                if( svcAppt.Registered_Vehicle__c != null ) {
                    regNoList.add(svcAppt.Registered_Vehicle__c);  
                }
            }    

            //soql query for first service reminder 3 days after delivery date .          
            firstServiceObj = [SELECT Registration_Number__c, Contact__c , Id, Branch__c, Registered_Date__c, Account__c /** PA MIGRATION : Added Account__c */
                                FROM Registered_Vehicle__c 
                                WHERE Last_Service_Booking_Date__c =:null  
                                AND Registered_Date__c = :passedThreeDays 
                                AND Id NOT IN :regNoList ];
            
            if( firstServiceObj.size()>0 ) 
            {
                for(Registered_Vehicle__c rvc : firstServiceObj)
                {
                    if( (rvc.Branch__c =='CCA' || rvc.Branch__c == 'CCK' ) && (rvc.Registered_Date__c == passedThreeDays ) )
                    {
                        String registrationnumber =  rvc.Registration_Number__c ;
                        //String message = 'The first servicing is due soon for your car '+ registrationnumber +'.';       
                        String message = 'Your car '+ registrationnumber +' is due for its first servicing at 1,000km. Book your appointment for Lubrication (Service A) now!';      
                        CustomerAlerts__c cAlert = new CustomerAlerts__c();
                        cAlert.Name = 'First service notice';
                        cAlert.Alert_Description__c = message ;
                        cAlert.Contact__c           = rvc.Contact__c;  /** PA Migration : To Remove */
                        cAlert.Date__c              = today;
                        cAlert.Datetime__c          = todaytime;
                        cAlert.isAlert__c           = true;
                        cAlert.isPush__c            = true;
                        cAlert.isSMS__c             = false;
                        cAlert.isEmail__c           = false;
                        cAlert.Type__c              = 'First Service';
                        cAlert.SubType__c           = 'Notice';
                        cAlert.Status__c            = 'unread';
                        cAlert.Account__c           = rvc.Account__c;  /** PA Migration : Newly Added */
                        cAlert.Registered_Vehicle__c = rvc.Id ;
                        customerAlertList.add( cAlert );
                    }
                }
            }
            
            //first service notice reminder for 14 days prior first service 
            firstServiceNoticeObj  = [SELECT Registration_Number__c, Contact__c ,Id, Branch__c, Next_Service_Booking_Date__c, Account__c  /** PA MIGRATION : Added Account__c */
                                      FROM Registered_Vehicle__c 
                                      WHERE Last_Service_Booking_Date__c =:null  
                                      AND Next_Service_Booking_Date__c =:nextFourteenDays 
                                      AND Id NOT IN :regNoList];
            
            if(firstServiceNoticeObj.size()>0) 
            {
                for(Registered_Vehicle__c rvc : firstServiceNoticeObj)
                {
                    //Service_Appointment__c theAppointment = new Service_Appointment__c (Registered_Vehicle__c = rvc.Id);
                    //1st first-Servicing Appt Reminder - Alert(app)
                    if( (rvc.Next_Service_Booking_Date__c == nextFourteenDays) && (rvc.Branch__c =='CCA' || rvc.Branch__c == 'CCK' ||  rvc.Branch__c =='CCI' || rvc.Branch__c == 'CCF'))
                    {
                        String registrationnumber =  rvc.Registration_Number__c ;
                        String message = '';
                        if(rvc.Branch__c =='CCI'){
                            message = 'Your car '+ registrationnumber + ' is due for its first servicing in 14 days. Book your appointment for Lubrication Service now!';
                        }
                        else{
                            message = 'Your car '+ registrationnumber + ' is due for its first servicing in 14 days. Book your appointment for Lubrication (Service A) now!';
                        }
                        //String message = 'The first servicing is due in 14 days for your car '+ registrationnumber +'.';
                        CustomerAlerts__c cAlert = new CustomerAlerts__c();
                        cAlert.Name                 = '1st First Servicing Appt Reminder';
                        cAlert.Alert_Description__c = message ;
                        cAlert.Contact__c           = rvc.Contact__c;		/** PA Migration : To Remove */
                        cAlert.Date__c              = today;
                        cAlert.Datetime__c          = todaytime;
                        cAlert.isAlert__c           = true;
                        cAlert.isPush__c            = true;
                        cAlert.isSMS__c             = false;
                        cAlert.isEmail__c           = true;
                        cAlert.Type__c              = 'First Service';
                        cAlert.SubType__c           = 'Due 1st Reminder';
                        cAlert.Status__c            = 'unread';
                        cAlert.Account__c = rvc.Account__c;  /** PA Migration : Newly Added */
                        cAlert.Registered_Vehicle__c = rvc.Id ;
                        customerAlertList.add( cAlert );
                    }  
                }
            } 
            
            //pass customer list to updert function  create customer alert 
            insertCreateCustomerAlert( customerAlertList ) ; 
            
        }
        catch(Exception e)
        {
            loggerDataPool.buildLogDataPool('firstServiceNoticeNReminder', e);
        }
    }
    

    //function for first service second reminder  
    public static void firstServiceSecondReminder()
    {
        Set<String> setServiceCode = new Set<String>();           
        for(Service_Code__mdt scode : [SELECT Service_Description__c FROM Service_Code__mdt])
		{
            setServiceCode.add(scode.Service_Description__c);
        }    

        try
        {
            List <Service_Appointment__c> lstServiceAppt = new  List <Service_Appointment__c>();
            
            //fetching list of all registered vehicle with today or future service appointments             
            lstServiceAppt = [ SELECT Registered_Vehicle__c 
                               FROM Service_Appointment__c 
					           WHERE Service_Appointment_Date_Time__c >= today 
					           AND Action__c != 'Cancel'
					           AND Service_Code__c IN :setServiceCode];						

            List<String> regNoList = new List<String>();
            for(Service_Appointment__c svcAppt:lstServiceAppt) {
                if(svcAppt.Registered_Vehicle__c!=null) {
                    regNoList.add(svcAppt.Registered_Vehicle__c);  
                }        
            }                                          
            
            //Second service notice reminder for 7 days prior first service 
            
            firstServiceNoticeObj  = [SELECT Registration_Number__c, Contact__c ,Id , Branch__c, Next_Service_Booking_Date__c, Account__c /** PA Migration : Added Account__c */
                                      FROM  Registered_Vehicle__c 
                                      WHERE Last_Service_Booking_Date__c =:null 
                                      AND Next_Service_Booking_Date__c =:nextSevenDays 
                                      AND Id NOT IN :regNoList];

            if(firstServiceNoticeObj.size()>0) 
            {
                for(Registered_Vehicle__c rvc : firstServiceNoticeObj)
                {
                    String registrationnumber =  rvc.Registration_Number__c ;
                    //String message = 'The first servicing is due next week for your car '+ registrationnumber +'.';
                    String message = '';
                    if(rvc.Branch__c =='CCI'){
                        message = 'Your car '+ registrationnumber + ' is due for its first servicing next week. Book your appointment for Lubrication Service now!';
                    }
                    else{
                        message = 'Your car '+ registrationnumber + ' is due for its first servicing next week. Book your appointment for Lubrication (Service A) now!';
                    }
                    CustomerAlerts__c cAlert = new CustomerAlerts__c();
                    cAlert.Name                 = '2nd First Servicing Appt Reminder';
                    cAlert.Alert_Description__c = message ;
                    cAlert.Contact__c           = rvc.Contact__c;			/** PA Migration : To Remove */
                    cAlert.Date__c              = today;
                    cAlert.Datetime__c          = todaytime;
                    cAlert.isAlert__c           = true;
                    cAlert.isPush__c            = true;
                    if(rvc.Branch__c == 'CCI') {
                        cAlert.isSMS__c = true;
                    }
                    else {
                        cAlert.isSMS__c = false;
                    }
                    
                    cAlert.isEmail__c           = true;
                    cAlert.Type__c              = 'First Service';
                    cAlert.SubType__c           = 'Due 2nd Reminder';
                    cAlert.Status__c            = 'unread';
                    cAlert.Account__c           = rvc.Account__c;  /** PA Migration : Newly Added */
                    cAlert.Registered_Vehicle__c = rvc.Id ;
                    customerAlertList.add( cAlert );
                }
            } 
            
            //pass customer list to updert function  create customer alert 
            insertCreateCustomerAlert( customerAlertList ) ; 
            
        }
        catch(Exception e)
        {
            loggerDataPool.buildLogDataPool('firstServiceNoticeNReminder', e);
        }
    }
    
    /*
    public static void firstServiceNoticeNReminderTEST()
    {

        Set<String> setServiceCode = new Set<String>();           
        for(Service_Code__mdt scode : [SELECT Service_Description__c FROM Service_Code__mdt])
		{
            setServiceCode.add(scode.Service_Description__c);
        }    

        try
        {
            Set<String> regVehIds = new Set<String>();
           
            for(AlertsRegisteredVehicle__mdt art : [SELECT DeveloperName FROM AlertsRegisteredVehicle__mdt]){
                regVehIds.add(art.DeveloperName);
            }                  
            
            
            List <Service_Appointment__c> tempId = new  List <Service_Appointment__c>();
            
            //fetching list of all registered vehicle with today or future service appointments             
            tempId=[Select Registered_Vehicle__c from Service_Appointment__c 
					where Service_Appointment_Date_Time__c >= today 
					and Action__c != 'Cancel'
					and Service_Code__c in: setServiceCode];

            List<String> regNoList = new List<String>();
            for(Service_Appointment__c svcAppt:tempId) 
            {
                if(svcAppt.Registered_Vehicle__c!=null)
                {
                    regNoList.add(svcAppt.Registered_Vehicle__c);  
                }        
                
            }                                          
            //soql query   for first service reminder  3 days after delivery date .          
           //PA Migration : Newly Added 
            firstServiceObj  = [Select Registration_Number__c,Contact__c ,Id, Branch__c, Registered_Date__c, Account__c
                                from Registered_Vehicle__c where Last_Service_Booking_Date__c=:null  
                                AND Registered_Date__c =:passedThreeDays AND Id NOT in : regNoList AND Name IN: regVehIds];// Id IN: regVehIds];
            
            if(firstServiceObj.size()>0) 
            {
                for(Registered_Vehicle__c rvc : firstServiceObj)
                {
                    
                    if((rvc.Branch__c =='CCA' || rvc.Branch__c == 'CCK' ) && (rvc.Registered_Date__c == passedThreeDays ))
                    {
                        String registrationnumber =  rvc.Registration_Number__c ;
                        //String message = 'The first servicing is due soon for your car '+ registrationnumber +'.';       
                        String message = 'Your car '+ registrationnumber +' is due for its first servicing at 1,000km. Book your appointment for Lubrication (Service A) now!';      
                        CustomerAlerts__c cAlert = new CustomerAlerts__c();
                        cAlert.Name = 'First service notice';
                        cAlert.Alert_Description__c = message ;
                        cAlert.Contact__c = rvc.Contact__c;			// PA Migration : To Remove 
                        cAlert.Date__c = today;
                        cAlert.Datetime__c = todaytime;
                        cAlert.isAlert__c = True;
                        cAlert.isPush__c = True;
                        cAlert.isSMS__c = False;
                        cAlert.isEmail__c = False;
                        cAlert.Type__c = 'First Service';
                        cAlert.SubType__c = 'Notice';
                        cAlert.Status__c = 'unread';
                        cAlert.Registered_Vehicle__c = rvc.Id ;
                        cAlert.Account__c = rvc.Account__c;  //PA Migration : Newly Added 
                        customerAlertList.add(cAlert);
                    }
                }
            }
            // end  
            
            //first service notice reminder for 14 days prior first service 
             //PA Migration : Newly Added 
            firstServiceNoticeObj  = [Select Registration_Number__c,Contact__c ,Id, Branch__c, Next_Service_Booking_Date__c, Account__c from Registered_Vehicle__c where Last_Service_Booking_Date__c=:null  AND  Next_Service_Booking_Date__c =:nextFourteenDays AND Id NOT in : regNoList AND Name IN: regVehIds ];//Id IN: regVehIds];
            if(firstServiceNoticeObj.size()>0) 
            {
                for(Registered_Vehicle__c rvc : firstServiceNoticeObj)
                {
                    //Service_Appointment__c theAppointment = new Service_Appointment__c (Registered_Vehicle__c = rvc.Id);
                    //1st first-Servicing Appt Reminder - Alert(app)
                    if((rvc.Next_Service_Booking_Date__c == nextFourteenDays) && (rvc.Branch__c =='CCA' || rvc.Branch__c == 'CCK' ||  rvc.Branch__c =='CCI' || rvc.Branch__c == 'CCF'))
                    {
                        String registrationnumber =  rvc.Registration_Number__c ;
                        String message = '';
                        if(rvc.Branch__c =='CCI'){
                            message = 'Your car '+ registrationnumber + ' is due for its first servicing in 14 days. Book your appointment for Lubrication Service now!';
                        }else{
                            message = 'Your car '+ registrationnumber + ' is due for its first servicing in 14 days. Book your appointment for Lubrication (Service A) now!';
                        }
                        //String message = 'The first servicing is due in 14 days for your car '+ registrationnumber +'.';
                        CustomerAlerts__c cAlert = new CustomerAlerts__c();
                        cAlert.Name = '1st First Servicing Appt Reminder';
                        cAlert.Alert_Description__c = message ;
                        cAlert.Contact__c = rvc.Contact__c;				//PA Migration : To Remove
                        cAlert.Date__c = today;
                        cAlert.Datetime__c = todaytime;
                        cAlert.isAlert__c = True;
                        cAlert.isPush__c = True;
                        cAlert.isSMS__c = False;
                        cAlert.isEmail__c = True;
                        cAlert.Type__c = 'First Service';
                        cAlert.SubType__c = 'Due 1st Reminder';
                        cAlert.Status__c = 'unread';
                        cAlert.Registered_Vehicle__c = rvc.Id ;
                        cAlert.Account__c = rvc.Account__c;  //PA Migration : Newly Added 
                        customerAlertList.add(cAlert);
                    }  
                }
            } 
            // end 
            
            //pass customer list to updert function  create customer alert 
            insertCreateCustomerAlert(customerAlertList) ; 
            
        }
        catch(Exception e)
        {
            loggerDataPool.buildLogDataPool('firstServiceNoticeNReminder', e);
        }
    }
    */

    //function for first service second reminder  
    /*
    public static void firstServiceSecondReminderTEST()
    {

        Set<String> setServiceCode = new Set<String>();           
        for(Service_Code__mdt scode : [SELECT Service_Description__c FROM Service_Code__mdt])
		{
            setServiceCode.add(scode.Service_Description__c);
        }    
		        
        try
        {
            Set<String> regVehIds = new Set<String>();
           
            for(AlertsRegisteredVehicle__mdt art : [SELECT DeveloperName FROM AlertsRegisteredVehicle__mdt]){
                regVehIds.add(art.DeveloperName);
            }   
            
            List <Service_Appointment__c> tempId = new  List <Service_Appointment__c>();
            
            //fetching list of all registered vehicle with today or future service appointments             
            tempId=[Select Registered_Vehicle__c from Service_Appointment__c 
					where Service_Appointment_Date_Time__c >= today
					and Action__c != 'Cancel'
					and Service_Code__c in: setServiceCode];		

            List<String> regNoList = new List<String>();
            for(Service_Appointment__c svcAppt:tempId) 
            {
                if(svcAppt.Registered_Vehicle__c!=null)
                {
                    regNoList.add(svcAppt.Registered_Vehicle__c);  
                }        
                
            }                                          
            
            //Second service notice reminder for 7 days prior first service 
             //PA Migration : Newly Added 
            firstServiceNoticeObj  = [SELECT Registration_Number__c, Contact__c ,Id, Branch__c, Next_Service_Booking_Date__c, Account__c
                                      FROM Registered_Vehicle__c 
                                      WHERE Last_Service_Booking_Date__c =:null 
                                      AND  Next_Service_Booking_Date__c =:nextSevenDays 
                                      AND Id NOT in : regNoList
                                      AND Name IN: regVehIds];//and id in: regVehIds];
            if(firstServiceNoticeObj.size()>0) 
            {
                for(Registered_Vehicle__c rvc : firstServiceNoticeObj)
                {
                    
                    String registrationnumber =  rvc.Registration_Number__c ;
                    //String message = 'The first servicing is due next week for your car '+ registrationnumber +'.';
                    String message = '';
                    if(rvc.Branch__c =='CCI'){
                        message = 'Your car '+ registrationnumber + ' is due for its first servicing next week. Book your appointment for Lubrication Service now!';
                    }else{
                        message = 'Your car '+ registrationnumber + ' is due for its first servicing next week. Book your appointment for Lubrication (Service A) now!';
                    }
                    CustomerAlerts__c cAlert = new CustomerAlerts__c();
                    cAlert.Name = '2nd First Servicing Appt Reminder';
                    cAlert.Alert_Description__c = message ;
                    cAlert.Contact__c = rvc.Contact__c;			 //PA Migration : To Remove
                    cAlert.Date__c = today;
                    cAlert.Datetime__c = todaytime;
                    cAlert.isAlert__c = True;
                    cAlert.isPush__c = True;
                    if(rvc.Branch__c == 'CCI')
                    {
                        cAlert.isSMS__c = True;
                    }
                    else
                    {
                        cAlert.isSMS__c = False;
                    }
                    
                    cAlert.isEmail__c = True;
                    cAlert.Type__c = 'First Service';
                    cAlert.SubType__c = 'Due 2nd Reminder';
                    cAlert.Status__c = 'unread';
                    cAlert.Registered_Vehicle__c = rvc.Id ;
                    cAlert.Account__c = rvc.Account__c;  //PA Migration : Newly Added 
                    customerAlertList.add(cAlert);
                }
                
            } 
            
            // end 
            
            //pass customer list to updert function  create customer alert 
            insertCreateCustomerAlert(customerAlertList) ; 
            
        }
        catch(Exception e)
        {
            loggerDataPool.buildLogDataPool('firstServiceNoticeNReminder', e);
        }
    }    
    */
    
    
    //function for upsert and create customer alert 
    public static void insertCreateCustomerAlert( List <CustomerAlerts__c> newCustomerAlerts )
    {
        //insert newCustomerAlerts;
        Database.UpsertResult[] results = Database.upsert( newCustomerAlerts );  
        for(Integer index = 0, size = results.size(); index < size; index++) 
        {
            if(results[index].isSuccess()) {
                if(results[index].isCreated()) {
                    System.debug(newCustomerAlerts[index].id +' was created');
                } 
            }
            else {
                system.debug(newCustomerAlerts[index].id +' had error');
            }
        }
    }
    
}