cncProd/force-app/main/default/objects/BatchDataPool__c/BatchDataPool__c.object-meta.xml
<CustomObject>
    <label>Batch Data Pool</label>
    <nameField>
        <label>Batch Data  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Data Pool</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchDataPool__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchDataPool__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <label>Batch Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/BatchDataPool__c/fields/Batches_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batches_Processed__c</fullName>
    <label>Batches Processed</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BatchDataPool__c/fields/Extended_Status__c.field-meta.xml
<CustomField>
    <fullName>Extended_Status__c</fullName>
    <label>Extended Status</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchDataPool__c/fields/Failures__c.field-meta.xml
<CustomField>
    <fullName>Failures__c</fullName>
    <label>Failures</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/BatchDataPool__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/BatchDataPool__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchDataPool__c/fields/Total_Batches__c.field-meta.xml
<CustomField>
    <fullName>Total_Batches__c</fullName>
    <label>Total Batches</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/batchDataPool.cls
/*
	Author: Hari Panneerselvam
*/
public class batchDataPool {
	
	public static void buildBatchDataPool(String batchName, Id jobId){ 
        AsyncApexJob asyncApexjob = [Select Id, ApexClassID, CompletedDate, JobType, MethodName, Status, NumberOfErrors, JobItemsProcessed, 
                                        TotalJobItems, ExtendedStatus from AsyncApexJob where Id = :jobId];
        ApexClass apexClass = [select Id, Name from ApexClass where Id = :asyncApexjob.ApexClassID];
        
        BatchDataPool__c newBatchDataPool = new BatchDataPool__c();
        newBatchDataPool.Batch_Name__c = batchName;
        newBatchDataPool.Job_Id__c = String.valueOf(asyncApexjob.Id).subString(0, 15);
        newBatchDataPool.Job_Status__c = asyncApexjob.Status;
        newBatchDataPool.Job_Type__c = asyncApexjob.JobType;
        newBatchDataPool.Extended_Status__c = asyncApexjob.ExtendedStatus;
        newBatchDataPool.ApexClass__c = apexClass.Name;
        newBatchDataPool.Total_Batches__c = asyncApexjob.TotalJobItems;
        newBatchDataPool.Batches_Processed__c = asyncApexjob.JobItemsProcessed;
        newBatchDataPool.Failures__c = asyncApexjob.NumberOfErrors;
        insert newBatchDataPool;
    }
    
}