cncProd/force-app/main/default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Lead/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Lead/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <formula>IF(Contact_Person__r.Email != null, Contact_Person__r.Email, IF(Lead__r.Email != null, Lead__r.Email, &apos;&apos;))</formula>
    <label>Customer Email</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/recordTypes/CITCV.recordType-meta.xml
<RecordType>
    <fullName>CITCV</fullName>
    <active>true</active>
    <businessProcess>OppSales</businessProcess>
    <label>CITCV</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/KIACV.recordType-meta.xml
<RecordType>
    <fullName>KIACV</fullName>
    <active>true</active>
    <businessProcess>OppSales</businessProcess>
    <label>KIACV</label>
</RecordType>

force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Reservation__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Stock Reservations</relationshipLabel>
    <relationshipName>Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Stock_Reservation__c/fields/Stock_Source__c.field-meta.xml
<CustomField>
    <fullName>Stock_Source__c</fullName>
    <label>Stock Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KIA Warehouse</fullName>
            </value>
            <value>
                <fullName>MIT Warehouse</fullName>
            </value>
            <value>
                <fullName>CIT Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/ExcludeFromWarehouse__c.field-meta.xml
<CustomField>
    <fullName>ExcludeFromWarehouse__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked to exclude consultant from warehouse list</description>
    <inlineHelpText>Checked to exclude consultant from warehouse list</inlineHelpText>
    <label>ExcludeFromWarehouse?</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/Test_restSalesConsultant.cls
@isTest
private class Test_restSalesConsultant {
    static String branch = 'CCF';
    @testSetup
    private static void testSetData(){
        User testUser = new User();
        User currentUser = [SELECT id FROM User WHERE Id = :UserInfo.getUserId()];
        System.RunAs(currentUser) {
            UserRole role = [SELECT Id, Name FROM UserRole WHERE Name LIKE '%Sales Consultant%' LIMIT 1];
            testUser = Test_DataFactory.createUser(false, 'Dummy User', 'test');
            testUser.Branch_Code__c = branch;
            testUser.email = 'test@jcc.com';
            testUser.UserRoleId = role.Id;
            testUser.ExcludeFromWarehouse__c = false;
            testUser.IsActive = true;
            insert testUser;
        }    
        
        Account personAcc = Test_DataFactory.createPerson(true, 'Test', 'Customer');
        personAcc = [SELECT Id, PersonContactId FROM Account WHERE Id = :personAcc.Id LIMIT 1];
        
        Contact personCon = new Contact(Id = personAcc.PersonContactId);
        personCon.Email = 'test@pa.com';
        
        Account ac = Test_DataFactory.createAccount(true, 'test');
        Contact c = Test_DataFactory.createContact(false, 'test', 'payment', ac.id);
        c.Email = 'test@jcc.com';
        insert c;
        
        Model_Master__c mc =  Test_DataFactory.createModelCode(true, 'testModel');
        Color_Master__c cm =  Test_DataFactory.createColorCode(true, 'testModelColor','KIAvs','CCF','CITCV'); 
        Trim_Master__c tm = Test_DataFactory.createTrimCode(true,'testTrim');
        lead ld1 = Test_DataFactory.createLead(true, 'testJcc', 'MyJcc');
        
        Opportunity op1 = Test_DataFactory.createOpportunity(false, 'test', ac.id);
        op1.OwnerId = testUser.Id;
        op1.Contact_Person__c = c.Id;
        insert op1;
        
        Stock_Reservation__c sr1 = Test_DataFactory.StockReservation(false, mc.id, cm.id, tm.id, null);
        sr1.Stock_Source__c = 'KIA Warehouse';
        sr1.Franchise_Code__c = 'KIACV';
        sr1.Opportunity__c = op1.Id;
        sr1.Customer_Email__c = 'test@jcc.com';
        sr1.OwnerId = testUser.Id;
        insert sr1;
        
        Test_Drive__c td = new Test_Drive__c();
        td.Opportunity__c = op1.Id;
        td.Date__c = Date.today().addDays(-7);
        insert td;
        
        
    }
    
    // this method is for purshase request
    @istest private static void testbatch(){
        
        Contact c = [select id,Email from Contact limit 1];
        User uc = [select id,Branch_Code__c,UserRoleId from User WHERE email = 'test@jcc.com' limit 1];
        Opportunity op1 = [SELECT ID, OwnerId,Contact_Person__c FROM Opportunity LIMIT 1];
        op1.OwnerID = uc.ID;
        Update op1;
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type', 'application/x-www-form-urlencoded');
        req.addParameter('email', 'test@jcc.com');
        req.addParameter('branch', branch);
        req.addParameter('transactiontype', 'Purchase');
        req.requestURI = 'test.salesforce.com';
        String vms =  '{"TransactionID": "","CustomerEmail" : "'+c.email+'","PaymentAmount":"1234", "InvoiceNo":"123"}';
        req.requestBody = Blob.valueOf(vms);
        RestResponse res = new RestResponse();
        res.responseBody = Blob.valueOf(vms);
        res.statusCode = 200;
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        restSalesConsultant.salesConsultantInfo();
        restSalesConsultant.isValidateParamPassed();
        Test.stopTest();
        
        
    }
    
    @istest private static void testbatch2(){
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type', 'application/x-www-form-urlencoded');
        //req.addParameter('email', 'test@jcc.com');
        req.addParameter('branch', branch);
        req.addParameter('transactiontype', 'Purchase');
        req.requestURI = 'test.salesforce.com';
        String vms =  '{"TransactionID": "","CustomerEmail" : "test@test.com","PaymentAmount":"1234", "InvoiceNo":"123"}';
        req.requestBody = Blob.valueOf(vms);
        RestResponse res = new RestResponse();
        res.responseBody = Blob.valueOf(vms);
        res.statusCode = 200;
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        restSalesConsultant.salesConsultantInfo();
        restSalesConsultant.isValidateParamPassed();
        Test.stopTest();
    }
    
    @isTest
    private static void testGetSalesConsultantInfo(){
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type', 'application/x-www-form-urlencoded');
        req.addParameter('transactiontype', 'Purchase');
        req.requestURI = 'test.salesforce.com';
        String vms =  '{"TransactionID": "","CustomerEmail" : "test@test.com","PaymentAmount":"1234", "InvoiceNo":"123"}';
        req.requestBody = Blob.valueOf(vms);
        RestResponse res = new RestResponse();
        res.responseBody = Blob.valueOf(vms);
        res.statusCode = 200;
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        restSalesConsultant.salesConsultantInfo();
        restSalesConsultant.isValidateParamPassed();
        Test.stopTest();
   }
    
}