cncProd/force-app/main/default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>NRIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Registrations (Account)</relationshipLabel>
    <relationshipName>Event_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>ContactId</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Event_Registration__c/fields/LeadId__c.field-meta.xml
<CustomField>
    <fullName>LeadId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>LeadId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Lead/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <externalId>true</externalId>
    <label>NRIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>NRIC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/Test_EventRegistration_TaskCreation.cls
@isTest
public class Test_EventRegistration_TaskCreation {
    
    static testMethod void testEvtRegWithContactId()
    {
        Test.startTest();
        Account testAcc = Test_DataFactory.createAccount(true, 'accName');
        Contact testCon = Test_DataFactory.createContact(true, 'fname', 'lname', testAcc.Id);
        Date eventDate = Date.today().addDays(2);
        Event_Registration__c TestEvnt =  new Event_Registration__c(Name='TestRunL',Event_Date__c = eventDate, ContactId__c = testCon.Id);
        insert TestEvnt;        
        EventRegistration_TaskCreation.taskCreation();
    }
    
    static testMethod void testEvtRegWithLeadId()
    {
        Test.startTest(); 
        Lead TestLead =  new Lead(LastName='TestRunL',NRIC__c='TestRunNRIC');
        insert TestLead;
        Date eventDate = Date.today().addDays(2);
        Event_Registration__c TestEvnt1 =  new Event_Registration__c(Name='TestRunL',LeadId__c=TestLead.Id,Event_Date__c = eventDate);
        insert TestEvnt1;        
        EventRegistration_TaskCreation.taskCreation();
        Test.stopTest();
    }
    //PA MIGRATION: TO-DO: Remove old test methods above//
    
    //PA MIGRATION: Newly Added -- Start //
    @isTest
    static void testCreateTaskWithRelatedPA(){
        Account personAccToInsert = Test_DataFactory.createPerson(true, 'A Cool Name', 'Customer');    
        Account personAcc = [SELECT Id, Name, PersonContactId FROM Account];

		Opportunity oppToInsert = Test_DataFactory.createOpportunity(true, 'oppName', personAcc.Id);
        Opportunity opp = [SELECT Id, OwnerId FROM Opportunity];
        
        String evtRegName = 'Dummy Event Registration';
        Date eventDate = Date.today().addDays(2);
        Event_Registration__c evtRegToInsert = new Event_Registration__c(Name = evtRegName, Account__c = personAcc.Id, Opportunity__c = opp.Id, Event_Date__c = eventDate);
        insert evtRegToInsert;
        Event_Registration__c evtReg = [SELECT Id, Name, Account__c, Account__r.PersonContactId, OwnerId FROM Event_Registration__c];

        Test.startTest();
        EventRegistration_TaskCreation.taskCreation();
        Task actualTask = [SELECT WhatId, Description, Status, WhoId  FROM Task WHERE WhatId=:evtReg.Id];
        Test.stopTest();     
        
        Task expectedTask = new Task(Description = 'Please update the Event registration record with appropriate status', Status='Open', WhatId=evtReg.Id, WhoId = evtReg.Account__r.PersonContactId);  
        System.assertEquals(expectedTask.WhatId, actualTask.WhatId);
		System.assertEquals(expectedTask.Description, actualTask.Description);
        System.assertEquals(expectedTask.Status, actualTask.Status);
        System.assertEquals(expectedTask.WhoId, actualTask.WhoId);
    }
    
    @isTest
    static void testCreateTaskWithoutOpp_ExceptionThrown(){
        Account personAccToInsert = Test_DataFactory.createPerson(true, 'A Cool Name', 'Customer');    
        Account personAcc = [SELECT Id, Name, IsPersonAccount FROM Account];
       
        String evtRegName = 'Dummy Event Registration';
        Date eventDate = Date.today().addDays(2);
        Event_Registration__c evtRegToInsert = new Event_Registration__c(Name = evtRegName, Account__c = personAcc.Id, Event_Date__c = eventDate);
        insert evtRegToInsert;
        Test.startTest();
        try{
        	EventRegistration_TaskCreation.taskCreation();
        } catch (Exception e){
            System.assertEquals(e.getMessage(), 'Upsert failed. First exception on row 0; first error: INVALID_CROSS_REFERENCE_KEY, Assigned To ID: owner cannot be blank: [OwnerId]');
        }
        Test.stopTest();     
    }  //PA MIGRATION: Newly Added -- Stop //

}