cncProd/force-app/main/default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Guests__c</fullName>
    <description>Paid Events - Maximum Number of Guests</description>
    <label>Max Number of Guests</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Campaign/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Guest Unit Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Event_Registration__c/fields/Event_Reminder_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reminder_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event Reminder Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/NumberOfGuests__c.field-meta.xml
<CustomField>
    <fullName>NumberOfGuests__c</fullName>
    <label>Total Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/PromoID__c.field-meta.xml
<CustomField>
    <fullName>PromoID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PromoID</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>PromoID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Waitlist__c.field-meta.xml
<CustomField>
    <fullName>Waitlist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to determine if registrant is wait-listed.</description>
    <inlineHelpText>Flag to determine if registrant is wait-listed.</inlineHelpText>
    <label>Waitlist?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_restCampaignInfo.cls
@isTest
global class Test_restCampaignInfo {
    Static Account acct 		     = Test_DataFactory.createAccount(true,'testRun');                   
    Static Lead testLead             = Test_DataFactory.createLead(true,'testRun','testRun'); 
    Static Opportunity opp         = Test_DataFactory.createOpportunity(false,'testRun',acct.Id);      
    Static Model__c testMod          = Test_DataFactory.createmodelId(true,'testRun','CCA','MITPC');        
    global static testMethod void test_CampaignInfo(){
        Test.startTest();           
        Campaign TestCamp2 = Test_DataFactory.createCamp(false,'testRun','Paid Event','CCF');           
        TestCamp2.Description = 'testing the test event';
        TestCamp2.UnitPrice__c = 25;
        TestCamp2.Number_of_Guests__c = 5;
        insert TestCamp2;
        
        
        Event_Registration__c tempInsertER1 = Test_DataFactory.createEventReg(false,null,TestCamp2.id,null,opp.id,testLead.id,testMod.id); // Insertion of Event_Registration__c using TestDataFactory
        tempInsertER1.Event_Reminder_Status__c=true;
        tempInsertER1.Waitlist__c = true;
        tempInsertER1.NumberOfGuests__c = 5;
        tempInsertER1.Opportunity__c = opp.id;
        Insert tempInsertER1;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/Campaign/';  
        req.addParameter('cmpId ', TestCamp2.Id);
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        
        restCampaignInfo.getCampaignDetails();
        restCampaignInfo.getDetails(TestCamp2.id);
        
        
        Test.stopTest();
    }
    global static testMethod void test_CampaignInfo1(){
        Test.startTest();           
        Campaign TestCamp2 = Test_DataFactory.createCamp(false,'testRun','Paid Event','CCF');          
        TestCamp2.Description = 'testing the test event';
        TestCamp2.UnitPrice__c = 25;
        TestCamp2.Number_of_Guests__c = 5;
        insert TestCamp2;
        
        
        Event_Registration__c tempInsertER1 = Test_DataFactory.createEventReg(false,null,TestCamp2.id,null,opp.id,testLead.id,testMod.id); // Insertion of Event_Registration__c using TestDataFactory
        tempInsertER1.Event_Reminder_Status__c=true;
        tempInsertER1.Waitlist__c = false;
        tempInsertER1.PromoID__c = TestCamp2.id;
        tempInsertER1.NumberOfGuests__c = 5;
        Insert tempInsertER1;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CampaignInfo/*';  
        req.addParameter('Id', TestCamp2.Id);
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;       
        restCampaignInfo.getCampaignDetails();
        restCampaignInfo.getDetails(TestCamp2.id);

        Test.stopTest();
    }
}