cncProd/force-app/main/default/objects/Account/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Charges_Master__c/Additional_Charges_Master__c.object-meta.xml
<CustomObject>
    <label>Additional Charges Master</label>
    <nameField>
        <displayFormat>ACM-{0000000000}</displayFormat>
        <label>Additional Charges Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges_Master__c/fields/ADM_CHRGCD__c.field-meta.xml
<CustomField>
    <fullName>ADM_CHRGCD__c</fullName>
    <externalId>true</externalId>
    <label>Charge Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges_Master__c/fields/ADM_CHRGDESC__c.field-meta.xml
<CustomField>
    <fullName>ADM_CHRGDESC__c</fullName>
    <label>Charge Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Score__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Score__c</fullName>
    <label>Opportunity Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/recordTypes/KIAPC.recordType-meta.xml
<RecordType>
    <fullName>KIAPC</fullName>
    <active>true</active>
    <businessProcess>OppSales</businessProcess>
    <label>KIAPC</label>
</RecordType>

cncProd/force-app/main/default/objects/Package_Additional_Charges__c/Package_Additional_Charges__c.object-meta.xml
<CustomObject>
    <label>Package Additional Charges</label>
    <nameField>
        <displayFormat>PAC-{0000000000}</displayFormat>
        <label>Package Additional Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package_Additional_Charges__c/fields/Additional_Charges_Master__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charges_Master__c</fullName>
    <label>Additional Charges Master</label>
    <referenceTo>Additional_Charges_Master__c</referenceTo>
    <relationshipLabel>Additional Charges Master</relationshipLabel>
    <relationshipName>Package_Additional_Charges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package_Additional_Charges__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Package Additional Charges</relationshipLabel>
    <relationshipName>Package_Additional_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package_Additional_Charges__c/fields/PKC_ADM_CHRGCD__c.field-meta.xml
<CustomField>
    <fullName>PKC_ADM_CHRGCD__c</fullName>
    <label>Charge Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Additional_Charges__c/fields/PKC_CHARGES__c.field-meta.xml
<CustomField>
    <fullName>PKC_CHARGES__c</fullName>
    <label>Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Package_Additional_Charges__c/fields/PKC_INCPRICE__c.field-meta.xml
<CustomField>
    <fullName>PKC_INCPRICE__c</fullName>
    <label>Inc Price</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Additional_Charges__c/fields/PKC_PKH_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>PKC_PKH_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/Package_Header__c.object-meta.xml
<CustomObject>
    <label>Package Header</label>
    <nameField>
        <displayFormat>PH-{0000000000}</displayFormat>
        <label>Package Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Header</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Header__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Package Header</relationshipLabel>
    <relationshipName>Package_Header</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/fields/PKH_FRN_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>PKH_FRN_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/fields/PKH_PKGPRICE__c.field-meta.xml
<CustomField>
    <fullName>PKH_PKGPRICE__c</fullName>
    <label>Package Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Package_Header__c/fields/PKH_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PKH_STATUS__c</fullName>
    <label>Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Agreements (Account)</relationshipLabel>
    <relationshipName>Sales_Agreements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch_Code</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Stock_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Stock_Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Stock Reservation</label>
    <referenceTo>Stock_Reservation__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Reservation__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Stock Reservations</relationshipLabel>
    <relationshipName>Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Package_Header_From_PickList__c.field-meta.xml
<CustomField>
    <fullName>Package_Header_From_PickList__c</fullName>
    <description>This field is a temporary field to contain the Id of the package header choose from the picklist on page 0, not a lookup field to Package_Header__c obj.</description>
    <label>Package Header From PickList</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Branch_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CCF</fullName>
    </customValue>
    <customValue>
        <fullName>CCK</fullName>
    </customValue>
    <customValue>
        <fullName>CCA</fullName>
    </customValue>
    <customValue>
        <fullName>CNC</fullName>
        <isActive>false</isActive>
        <label>CNC</label>
    </customValue>
    <masterLabel>Branch Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContentDocumentTriggerTest.cls
@isTest
private class ContentDocumentTriggerTest {

    @testSetup
    static void setUp() {
        User sysAdminUser = Test_DataFactory.createUserWithProfileID(
            true, 'SysAdm', 'LastName', 'test@sysadmin.com', [Select Id From Profile Where Name = 'System Administrator'].Id
        );
        User bsdUser = Test_DataFactory.createUserWithProfileID(
            true, 'BSDUsr', 'LastName', 'test@bsd.com', [Select Id From Profile Where Name = 'BSD'].Id
        );         
        
        Account acc = Test_DataFactory.createAccount(true, 'test account');
        /*Account acc = Test_DataFactory.createPerson(false, 'Test', 'Prospect');
        acc.PersonEmail = 'patest@mail.com';
        insert acc;
        acc = [SELECT Id, PersonContactId FROM Account WHERE ID =: acc.Id];*/

        Opportunity oppt = Test_DataFactory.createOpportunity(false,'testRun', acc.Id);
        oppt.Branch_Code__c = 'CCA';
        oppt.Opportunity_Score__c = 40;
        oppt.Account__c = acc.Id;
        //oppt.Person_Account__c = acc.Id;
        oppt.Contact_Person__c = acc.PersonContactId;
        insert oppt;

        Model_Master__c modelCode = Test_DataFactory.createModelCode(true, 'Test Model Code');
        Model_Year_Master__c modelYearCode = Test_DataFactory.createModelYearCode(true, modelCode.Id);
        Color_Master__c colorCode = Test_DataFactory.createColorCode(true, 'Test Color Code', 'Test', 'CCK', 'KIAPC');
        Trim_Master__c trimCode = Test_DataFactory.createTrimCode(true, 'Test Trim Code');
        // Create Package Header
        Package_Header__c pckHeader = new Package_Header__c(Model_Master__c = modelCode.Id, PKH_FRN_FRNCD__c = 'KIAPC', PKH_STATUS__c='A', PKH_PKGPRICE__c=1000000);
        insert pckHeader;

        Stock_Reservation__c stockReservation = Test_DataFactory.StockReservation(false, modelCode.Id, colorCode.Id, trimCode.Id, modelYearCode.Id); 
        stockReservation.Package_Header_From_PickList__c = pckHeader.Id;
        stockReservation.Opportunity__c = oppt.Id;
        insert stockReservation;

        // Additional Charges Master
		Additional_Charges_Master__c addnlChargeMaster = new Additional_Charges_Master__c(ADM_CHRGDESC__c = 'Addnl Charge Test',
                                                                                          ADM_CHRGCD__c = 'R004');
        insert addnlChargeMaster;

        // Package Addtional Charges
        List<Package_Additional_Charges__c> pckAddnlChargeList = new List<Package_Additional_Charges__c>();
        Package_Additional_Charges__c pckAddnlCharge1 = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                          Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                          Package_Header__c = pckHeader.Id,
                                                                                          PKC_ADM_CHRGCD__c ='R004',
                                                                                          PKC_CHARGES__c = 100);
        pckAddnlChargeList.add(pckAddnlCharge1);
        Package_Additional_Charges__c pckAddnlCharge2 = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                          Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                          Package_Header__c = pckHeader.Id,
                                                                                          PKC_ADM_CHRGCD__c ='R002',
                                                                                          PKC_INCPRICE__c = 'INC',
                                                                                          PKC_CHARGES__c = 100);
        pckAddnlChargeList.add(pckAddnlCharge2);
        insert pckAddnlChargeList;

		Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(true, 'CCK', 'NO9999', stockReservation.Id, 'test customer');
        
        System.runAs(sysAdminUser) {
            Test_DataFactory.attachFilesToRecord(
                new Map<Id, List<Blob>>{acc.Id => new List<Blob>{Blob.valueOf('Acc File')}},
                'Acc File',
                'pdf'
			);
        }
        
        System.runAs(bsdUser) {
            Test_DataFactory.attachFilesToRecord(
                new Map<Id, List<Blob>>{
                    acc.Id => new List<Blob>{Blob.valueOf('Account File')},
                    salesAgreement.Id => new List<Blob>{Blob.valueOf('Other File')}    
                },
                new Map<Blob, String>{
                    Blob.valueOf('Account File') => 'Account File',
                    Blob.valueOf('Other File') => 'Other File'    
				},
                new Map<Blob, String>{
                    Blob.valueOf('Account File') => 'pdf',
                    Blob.valueOf('Other File') => 'pdf'    
				}
            );             
        }       
    }
    
    @isTest
    static void Test_beforeDelete_userProfileIsAuthorizedToDeleteFiles() {
        System.runAs([Select Id From User Where FirstName = 'SysAdm' Order By CreatedDate Desc Limit 1][0]) {
            delete [Select Id From ContentDocument];
        }
    } 
    
    @isTest
    static void Test_beforeDelete_blockUnauthorizedDeletionOfAccountFile() {
        System.runAs([Select Id From User Where FirstName = 'BSDUsr' Order By CreatedDate Desc Limit 1][0]) {
            Boolean exceptionThrownOnInsufficientPrivileges = false;
            try {
                delete [Select Id From ContentDocument Where Description = 'Account File'];
            } catch(Exception e) {
                exceptionThrownOnInsufficientPrivileges = e.getMessage().contains(
                    'You are not authorized to delete this file. Please upload a new version instead.'
				);
            } finally {
                System.assert(exceptionThrownOnInsufficientPrivileges);
            }
        }
    }       
    
    @isTest
    static void Test_beforeDelete_blockUnauthorizedDeletionOfSalesAgreementFile() {
        System.runAs([Select Id From User Where FirstName = 'BSDUsr' Order By CreatedDate Desc Limit 1][0]) {
            Boolean exceptionThrownOnInsufficientPrivileges = false;
            try {
                delete [Select Id From ContentDocument Where Description = 'Other File'];
            } catch(Exception e) {
                exceptionThrownOnInsufficientPrivileges = e.getMessage().contains(
                    'You are not authorized to delete this file. Please upload a new version instead.'
				);
            } finally {
                System.assert(exceptionThrownOnInsufficientPrivileges);
            }
        }
    }

    @isTest
    private static void testBypassTrigger() {
        TriggerExclusion.excludeTrigger('ContentDocument', true);
        System.runAs([Select Id From User Where FirstName = 'SysAdm' Order By CreatedDate Desc Limit 1][0]) {
            delete [Select Id From ContentDocument];
        }      
        TriggerExclusion.excludeTrigger('ContentDocument', false);
    }
}