cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/fields/Model_Description__c.field-meta.xml
<CustomField>
    <fullName>Model_Description__c</fullName>
    <label>Model Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/fields/VSMS_Compound_Primary_Key__c.field-meta.xml
<CustomField>
    <fullName>VSMS_Compound_Primary_Key__c</fullName>
    <externalId>true</externalId>
    <label>VSMS Compound Primary Key</label>
    <length>90</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ModelMasters.cls
public class ModelMasters extends ADGLIB_SObjectDomain {
    public ModelMasters(List<Model_Master__c> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements ADGLIB_SObjectDomain.IConstructable {
		public ADGLIB_SObjectDomain construct(List<SObject> sObjectList) {
			return new ModelMasters(sObjectList);
		}
	}

    public override void onApplyDefaults() {
        for(Model_Master__c modelMaster : (List<Model_Master__c>) Records) {
            String cleanFranchiseCode = modelMaster.Franchise_Code__c == null ? '' : modelMaster.Franchise_Code__c;
			modelMaster.VSMS_Compound_Primary_Key__c = cleanFranchiseCode + modelMaster.Name;
        }
    }

    public override void onAfterInsert()
    {
        updateModelGlobalValueSet(null);
    }

    public void updateModelGlobalValueSet(Map<Id, SObject> existingRecords)
    {
        List<String> modelNames = new List<String>();

        for (Model_Master__c model : (List<Model_Master__c>) Records)
        {
            modelNames.add(model.Model_Description__c);
        }

        ToolingAPIUtility.updateModelGlobalValueSet(modelNames);
    }
}