force-app/main/default/objects/Accessories_Master__c/Accessories_Master__c.object-meta.xml
<CustomObject>
    <description>To list down the list of different Accessories for MF</description>
    <label>Accessories Master</label>
    <nameField>
        <displayFormat>AM-{0000000000}</displayFormat>
        <label>Accessories Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accessories Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accessories_Master__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Accs_Rate_Master__c/Accs_Rate_Master__c.object-meta.xml
<CustomObject>
    <description>Accessories Rate master contain the rate for accessories. Different accessories have different rate</description>
    <label>Accs Rate Master</label>
    <nameField>
        <displayFormat>ARM-{0000000000}</displayFormat>
        <label>Accs Rate Master ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accs Rate Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accs_Rate_Master__c/fields/Accessories__c.field-meta.xml
<CustomField>
    <fullName>Accessories__c</fullName>
    <label>Accessories</label>
    <referenceTo>Accessories_Master__c</referenceTo>
    <relationshipLabel>Accs Rate Master</relationshipLabel>
    <relationshipName>Accs_Rate_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Accs_Rate_Master__c/fields/ARM_EFFDT__c.field-meta.xml
<CustomField>
    <fullName>ARM_EFFDT__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Accs_Rate_Master__c/fields/ARM_SALEPRICE__c.field-meta.xml
<CustomField>
    <fullName>ARM_SALEPRICE__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/classes/AccessoriesMastersTest.cls
@isTest
private class AccessoriesMastersTest {
	@testSetup
    private static void setUp() {
        // create Accessory Master record
        Accessories_Master__c AM = new Accessories_Master__c();
        insert AM;
        // create severals Accessory Rate Master records
        Accs_Rate_Master__c[] ARMs = new Accs_Rate_Master__c[]{};
        for (integer i = 0; i < 10; i++) {
            Accs_Rate_Master__c tempARM = new Accs_Rate_Master__c(Accessories__c = AM.id, ARM_EFFDT__c = Date.today().addDays(i), ARM_SALEPRICE__c = i);
            ARMs.add(tempARM);
        }
        insert ARMs;
    }
    
    @isTest
    private static void updateRate_Test() {
        set<ID> accMasterIds = new set<ID> {[SELECT id, Rate__c FROM Accessories_Master__c].ID};
        list<Accessories_Master__c> AMs = new AccessoriesMasterSelector().selectAccsMastersWithRateMastersByIds(accMasterIds);
        system.debug(AMs);
        AccessoriesMasters domainInstance = new AccessoriesMasters(AMs);
        domainInstance.updateRate();
        Accessories_Master__c updatedAM = [SELECT id, Rate__c FROM Accessories_Master__c];
        system.assertEquals(9, updatedAM.Rate__c);
    }
}