force-app/main/default/objects/Accessories_Master__c/Accessories_Master__c.object-meta.xml
<CustomObject>
    <description>To list down the list of different Accessories for MF</description>
    <label>Accessories Master</label>
    <nameField>
        <displayFormat>AM-{0000000000}</displayFormat>
        <label>Accessories Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accessories Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accessories_Master__c/fields/ACM_ACCSCD__c.field-meta.xml
<CustomField>
    <fullName>ACM_ACCSCD__c</fullName>
    <externalId>true</externalId>
    <label>Accs Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accessories_Master__c/fields/ACM_ACCSDESC__c.field-meta.xml
<CustomField>
    <fullName>ACM_ACCSDESC__c</fullName>
    <label>Accs Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accessories_Master__c/fields/ACM_ACCSTYPE__c.field-meta.xml
<CustomField>
    <fullName>ACM_ACCSTYPE__c</fullName>
    <label>Accounts Type</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accessories_Master__c/fields/ACM_FRN_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>ACM_FRN_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accessories_Master__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Accs_Rate_Master__c/Accs_Rate_Master__c.object-meta.xml
<CustomObject>
    <description>Accessories Rate master contain the rate for accessories. Different accessories have different rate</description>
    <label>Accs Rate Master</label>
    <nameField>
        <displayFormat>ARM-{0000000000}</displayFormat>
        <label>Accs Rate Master ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accs Rate Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Accs_Rate_Master__c/fields/Accessories__c.field-meta.xml
<CustomField>
    <fullName>Accessories__c</fullName>
    <label>Accessories</label>
    <referenceTo>Accessories_Master__c</referenceTo>
    <relationshipLabel>Accs Rate Master</relationshipLabel>
    <relationshipName>Accs_Rate_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Accs_Rate_Master__c/fields/ARM_ACM_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>ARM_ACM_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges_Master__c/Additional_Charges_Master__c.object-meta.xml
<CustomObject>
    <label>Additional Charges Master</label>
    <nameField>
        <displayFormat>ACM-{0000000000}</displayFormat>
        <label>Additional Charges Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges_Master__c/fields/ADM_CHRGCD__c.field-meta.xml
<CustomField>
    <fullName>ADM_CHRGCD__c</fullName>
    <externalId>true</externalId>
    <label>Charge Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges_Master__c/fields/ADM_CHRGDESC__c.field-meta.xml
<CustomField>
    <fullName>ADM_CHRGDESC__c</fullName>
    <label>Charge Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package_Accs__c/Package_Accs__c.object-meta.xml
<CustomObject>
    <label>Package Accs</label>
    <nameField>
        <displayFormat>PA-{0000000000}</displayFormat>
        <label>Package Accs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Accs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Accs__c/fields/Accessories_Master__c.field-meta.xml
<CustomField>
    <fullName>Accessories_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessories Master</label>
    <referenceTo>Accessories_Master__c</referenceTo>
    <relationshipLabel>Accessories Master</relationshipLabel>
    <relationshipName>Package_Accs</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Accs__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Package Accs</relationshipLabel>
    <relationshipName>Package_Accs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Accs__c/fields/PKA_PKH_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>PKA_PKH_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Additional_Charges__c/Package_Additional_Charges__c.object-meta.xml
<CustomObject>
    <label>Package Additional Charges</label>
    <nameField>
        <displayFormat>PAC-{0000000000}</displayFormat>
        <label>Package Additional Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package_Additional_Charges__c/fields/Additional_Charges_Master__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charges_Master__c</fullName>
    <label>Additional Charges Master</label>
    <referenceTo>Additional_Charges_Master__c</referenceTo>
    <relationshipLabel>Additional Charges Master</relationshipLabel>
    <relationshipName>Package_Additional_Charges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package_Additional_Charges__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Package Additional Charges</relationshipLabel>
    <relationshipName>Package_Additional_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package_Additional_Charges__c/fields/PKC_ADM_CHRGCD__c.field-meta.xml
<CustomField>
    <fullName>PKC_ADM_CHRGCD__c</fullName>
    <label>Charge Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Additional_Charges__c/fields/PKC_CHARGES__c.field-meta.xml
<CustomField>
    <fullName>PKC_CHARGES__c</fullName>
    <label>Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Package_Additional_Charges__c/fields/PKC_INCPRICE__c.field-meta.xml
<CustomField>
    <fullName>PKC_INCPRICE__c</fullName>
    <label>Inc Price</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Additional_Charges__c/fields/PKC_PKH_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>PKC_PKH_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/Package_Header__c.object-meta.xml
<CustomObject>
    <label>Package Header</label>
    <nameField>
        <displayFormat>PH-{0000000000}</displayFormat>
        <label>Package Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Header</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Header__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Package Header</relationshipLabel>
    <relationshipName>Package_Header</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/fields/PKH_FRN_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>PKH_FRN_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/SA_Accessory__c.object-meta.xml
<CustomObject>
    <label>SA Accessory</label>
    <nameField>
        <displayFormat>SAA-{0000000000}</displayFormat>
        <label>SA Accesories Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SA Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/Accessories_Master__c.field-meta.xml
<CustomField>
    <fullName>Accessories_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessories Master</label>
    <referenceTo>Accessories_Master__c</referenceTo>
    <relationshipLabel>SA Accessories</relationshipLabel>
    <relationshipName>SA_Accessories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>SA Accessories</relationshipLabel>
    <relationshipName>SA_Accessories</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Additional_Charge__c/SA_Additional_Charge__c.object-meta.xml
<CustomObject>
    <label>SA Additional Charge</label>
    <nameField>
        <displayFormat>SAC-{0000000000}</displayFormat>
        <label>SA Addtional Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SA Additional Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SA_Additional_Charge__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>SA Additional Charges</relationshipLabel>
    <relationshipName>SA_Additional_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Stock_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Stock_Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Stock Reservation</label>
    <referenceTo>Stock_Reservation__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/classes/SalesAgreementTriggerTest.cls
@isTest
private class SalesAgreementTriggerTest {
	@testSetup
    static void setUp() {
        Model_Master__c modelCode = Test_DataFactory.createModelCode(true, 'Test Model Code');
        Model_Year_Master__c modelYearCode = Test_DataFactory.createModelYearCode(true, modelCode.Id);
        Color_Master__c colorCode = Test_DataFactory.createColorCode(true, 'Test Color Code', 'Test', 'CCK', 'KIAPC');
        Trim_Master__c trimCode = Test_DataFactory.createTrimCode(true, 'Test Trim Code');
        // Create Stock Reservation
        Stock_Reservation__c stockReservation = Test_DataFactory.StockReservation(false, modelCode.ID, colorCode.ID, trimCode.ID, modelYearCode.ID);
        insert stockReservation;
        // Create Package Header
		Package_Header__c pckHeader = new Package_Header__c(PKH_FRN_FRNCD__c = 'KIAPC');
        insert pckHeader;
        
        Accessories_Master__c accMaster1 = new Accessories_Master__c(ACM_FRN_FRNCD__c = 'KIAPC',
                                                                     ACM_ACCSDESC__c = 'Acc Test',
                                                                     ACM_ACCSCD__c = 'GMS5000',
                                                                     Rate__c = 5000,
                                                                     ACM_ACCSTYPE__c = 'C');
        insert accMaster1;

        // Create Accs Rate Master
		Accs_Rate_Master__c accRateMaster = new Accs_Rate_Master__c(Accessories__c = accMaster1.Id,
                                                                    ARM_ACM_FRNCD__c = 'KIAPC');
        insert accRateMaster;

        // Create Package Accessories
        List<Package_Accs__c> pckAccList = new List<Package_Accs__c>();
        for (Integer i = 0; i < 5; i++) {
            Package_Accs__c pckAcc = new Package_Accs__c(Package_Header__c = pckHeader.Id,
                                                    	Accessories_Master__c = accMaster1.Id,
                                                        PKA_PKH_FRNCD__c = 'KIAPC');
            pckAccList.add(pckAcc);
        }
		insert pckAccList;

		// Create Additional Charges Master
		Additional_Charges_Master__c addnlChargeMaster = new Additional_Charges_Master__c(ADM_CHRGDESC__c = 'Addnl Charge Test',
                                                                                          ADM_CHRGCD__c = 'R004');
        insert addnlChargeMaster;

        // Create Package Addtional Charges
        List<Package_Additional_Charges__c> pckAddnlChargeList = new List<Package_Additional_Charges__c>();
        Package_Additional_Charges__c pckAddnlCharge1 = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                         Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                         Package_Header__c = pckHeader.Id,
                                                                                         PKC_ADM_CHRGCD__c ='R002',
                                                                                         PKC_CHARGES__c = 100);
        pckAddnlChargeList.add(pckAddnlCharge1);
        Package_Additional_Charges__c pckAddnlCharge2 = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                         Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                         Package_Header__c = pckHeader.Id,
                                                                                         PKC_ADM_CHRGCD__c ='R002',
                                                                                         PKC_INCPRICE__c = 'INC',
                                                                                         PKC_CHARGES__c = 100);
        pckAddnlChargeList.add(pckAddnlCharge2);
        Package_Additional_Charges__c pckAddnlCharge3 = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                         Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                         Package_Header__c = pckHeader.Id,
                                                                                         PKC_INCPRICE__c = 'INC');
        pckAddnlChargeList.add(pckAddnlCharge3);
        for (Integer i = 0; i < 5; i++) {
			Package_Additional_Charges__c pckAddnlCharge = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                            Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                            Package_Header__c = pckHeader.Id);
            pckAddnlChargeList.add(pckAddnlCharge);
        }
		insert pckAddnlChargeList;
    }

    /**
     * Covered method in SalesAgreement.cls:
     * onApplyDefaults()
     * onAfterInsert()
     * defaultAccessoriesRelatedList()
     */
    @isTest
    static void Test_afterInsert_Case1() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
        Package_Header__c pckHeader = [SELECT Id FROM Package_Header__c];

		// Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', 'NO9999', stockReservation.ID, 'Thieu Dang Vu'); 
        salesAgreement.Package_Header__c = pckHeader.Id;
        insert salesAgreement;
    }

    /**
     * Covered method in SalesAgreement.cls:
     * onApplyDefaults()
     * onAfterInsert()
     * defaultAccessoriesRelatedList()
     */
    @isTest
    static void Test_afterInsert_Case2() {
        Model_Master__c modelCode = [SELECT Id FROM Model_Master__c];
        Model_Year_Master__c modelYearCode = [SELECT Id FROM Model_Year_Master__c];
        Color_Master__c colorCode = [SELECT Id FROM Color_Master__c];
        Trim_Master__c trimCode = [SELECT Id FROM Trim_Master__c];

        // Create Stock Reservation
        Stock_Reservation__c stockReservation2 = Test_DataFactory.StockReservation(false, modelCode.ID, colorCode.ID, trimCode.ID, modelYearCode.ID);
        stockReservation2.Registration_Type__c = 'C';
		insert stockReservation2;

        Package_Header__c pckHeader = [SELECT Id FROM Package_Header__c];

		// Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', 'NO9999', stockReservation2.ID, 'Thieu Dang Vu'); 
        salesAgreement.Package_Header__c = pckHeader.Id;
        insert salesAgreement;
    }

    /**
     * Covered method in SalesAgreement.cls:
     * onAfterUpdate()
     * updateStockReservationVehicleMaster()
     * defaultAccessoriesRelatedList()
     * upsertRelatedAccessories()
     */
    @isTest 
    static void Test_afterUpdate() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
        Accessories_Master__c accMaster = [SELECT Id FROM Accessories_Master__c];
        Additional_Charges_Master__c addnlChargeMaster = [SELECT Id FROM Additional_Charges_Master__c];

        Package_Header__c pckHeader1 = new Package_Header__c(PKH_FRN_FRNCD__c = 'KIAPC');
        insert pckHeader1;

        List<Package_Header__c> pckList = [SELECT Id FROM Package_Header__c];
        Package_Accs__c pckAcc = new Package_Accs__c(Package_Header__c = pckList[1].Id,
                                                     Accessories_Master__c = accMaster.Id,
                                                     PKA_PKH_FRNCD__c = 'KIAPC');
        insert pckAcc;
        List<Package_Additional_Charges__c> pckAddnlChargeList = new List<Package_Additional_Charges__c>();
        Package_Additional_Charges__c pckAddnlCharge1 = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                         Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                         Package_Header__c = pckList[1].Id,
                                                                                         PKC_ADM_CHRGCD__c ='R002',
                                                                                         PKC_CHARGES__c = 100);
        pckAddnlChargeList.add(pckAddnlCharge1);
        Package_Additional_Charges__c pckAddnlCharge2 = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                         Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                         Package_Header__c = pckList[1].Id,
                                                                                         PKC_ADM_CHRGCD__c ='R002',
                                                                                         PKC_INCPRICE__c = 'INC',
                                                                                         PKC_CHARGES__c = 100);
        pckAddnlChargeList.add(pckAddnlCharge2);
        Package_Additional_Charges__c pckAddnlCharge3 = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                         Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                         Package_Header__c = pckList[1].Id,
                                                                                         PKC_INCPRICE__c = 'INC');
        pckAddnlChargeList.add(pckAddnlCharge3);
        Package_Additional_Charges__c pckAddnlCharge4 = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                         Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                         Package_Header__c = pckList[1].Id);
        pckAddnlChargeList.add(pckAddnlCharge4);
        insert pckAddnlChargeList;
        
        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', '', stockReservation.ID, 'Thieu Dang Vu');
		salesAgreement.Package_Header__c = pckList[0].Id;
        insert salesAgreement;

        // Create SA Acc
        SA_Accessory__c sa = new SA_Accessory__c(Sales_Agreement__c = salesAgreement.Id,
                                                 Accessories_Master__c = accMaster.Id,
                                                 SAC_PACKAGE__c = 'Y');
        insert sa;
        // Create SA Addnl Charge
        SA_Additional_Charge__c saAddnlCharge = Test_DataFactory.createSAAdditionalCharge(true, addnlChargeMaster.Id, salesAgreement.Id);

        salesAgreement.Package_Header__c = pckList[1].Id;
        update salesAgreement;
    }

    /**
     * Covered method in SalesAgreement.cls:
     * createCOESAAcc()
     * createGMSSAAcc()
     */
    @isTest 
    static void Test_afterUpdate_Case1() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
        List<Package_Header__c> pckHeader = [SELECT Id FROM Package_Header__c];

        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', '', stockReservation.ID, 'Thieu Dang Vu');
		salesAgreement.Package_Header__c = pckHeader[0].Id;
        insert salesAgreement;
        
        salesAgreement.COE_Refund__c = 4050;
        salesAgreement.GMS_Package__c = 5000;
        update salesAgreement;
    }

    /**
     * Covered method in SalesAgreement.cls:
     * createCOESAAcc()
     * createGMSSAAcc()
     * createSVCSAAcc()
     */
    @isTest 
    static void Test_afterUpdate_Case2() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
        List<Package_Header__c> pckHeader = [SELECT Id FROM Package_Header__c];
        
        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', '', stockReservation.ID, 'Thieu Dang Vu');
		salesAgreement.Package_Header__c = pckHeader[0].Id;
        salesAgreement.COE_Refund__c = 4050;
        salesAgreement.GMS_Package__c = 5000;
        insert salesAgreement;
        
        salesAgreement.COE_Refund__c = null;
        salesAgreement.GMS_Package__c = null;
        salesAgreement.Service_Credit__c = null;
        update salesAgreement;     
    }

    /**
     * Covered method in SalesAgreement.cls:
     * createCOESAAcc()
     * createGMSSAAcc()
     * createSVCSAAcc()
     */
    @isTest 
    static void Test_afterUpdate_Case3() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
        Package_Header__c pckHeader = [SELECT Id FROM Package_Header__c];
        
        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', '', stockReservation.ID, 'Thieu Dang Vu');
		salesAgreement.Package_Header__c = pckHeader.Id;
        salesAgreement.COE_Refund__c = 4050;
        salesAgreement.GMS_Package__c = 5000;
        insert salesAgreement;

        salesAgreement.COE_Refund__c = 3050;
        salesAgreement.GMS_Package__c = 5005;
        salesAgreement.Service_Credit__c = 3000;
        update salesAgreement;     
        
          
        Test.setMock(HttpCalloutMock.class, new VSMS_CallOutToCreateACMMock());
        Test.startTest();
        VSMS_CallOutToCreateACM.callOutToCreateACM(salesAgreement.Id, salesAgreement.Branch_Code__c, 'COE4050');
        Test.stopTest();
    }

    /**
     * Covered method in SalesAgreement.cls:
     * createCOESAAcc()
     */
    @isTest
    static void Test_afterUpdate_Case4() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
        
        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', '', stockReservation.ID, 'Thieu Dang Vu');
        salesAgreement.COE_Refund__c = 4050;
        insert salesAgreement;

        salesAgreement.COE_Refund__c = 0;
        update salesAgreement;
    }

    /**
     * Covered method in SalesAgreement.cls:
     * createCOESAAcc()
     */    
    @isTest
    static void Test_afterUpdate_Case5() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
        
        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', '', stockReservation.ID, 'Thieu Dang Vu');
        salesAgreement.COE_Refund__c = 0;
        insert salesAgreement;

        salesAgreement.COE_Refund__c = 4050;
        update salesAgreement;
        
        Test.setMock(HttpCalloutMock.class, new VSMS_CallOutToCreateACMMock());
        Test.startTest();
        VSMS_CallOutToCreateACM.callOutToCreateACM(salesAgreement.Id, salesAgreement.Branch_Code__c, 'COE4050');
        Test.stopTest();
    }
    
    /**
     * Covered method in SalesAgreement.cls:
     * createSVCSAAcc()
     */
    @isTest
    static void Test_afterUpdate_Case6() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
        
        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', '', stockReservation.ID, 'Thieu Dang Vu');
        insert salesAgreement;
        
        salesAgreement.Service_Credit__c = null;
        update salesAgreement;
        
        salesAgreement.Service_Credit__c = 4050;
        update salesAgreement;
        
        Test.setMock(HttpCalloutMock.class, new VSMS_CallOutToCreateACMMock());
        Test.startTest();
        VSMS_CallOutToCreateACM.callOutToCreateACM(salesAgreement.Id, salesAgreement.Branch_Code__c, 'COE4050');
        Test.stopTest();
    }

    /**
     * Covered method in SalesAgreement.cls:
     * setVSMSKeyOfAdditionalCharges()
     */
    @isTest
    static void Test_afterUpdate_Case7() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
        Additional_Charges_Master__c addnlChargeMaster = [SELECT Id FROM Additional_Charges_Master__c];
        
        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', '', stockReservation.ID, 'Thieu Dang Vu');
        insert salesAgreement;

        salesAgreement.SOH_SONO__c = 'AK19119999';
        update salesAgreement;

        // Create SA Addnl Charge
        SA_Additional_Charge__c saAddnlCharge = Test_DataFactory.createSAAdditionalCharge(false, addnlChargeMaster.Id, salesAgreement.Id);
		insert saAddnlCharge;
    }

    /**
     * Covered method in SalesAgreement.cls:
     * updateStockReservationVehicleMaster()
     */
    @isTest
    static void Test_afterUpdate_Case8() {
        Stock_Reservation__c stockReservation = [SELECT Id FROM Stock_Reservation__c];
		/*Model_Master__c modelCode = [SELECT Id FROM Model_Master__c];
        Model_Year_Master__c modelYearCode = [SELECT Id FROM Model_Year_Master__c];
        Color_Master__c colorCode = [SELECT Id FROM Color_Master__c];
        Trim_Master__c trimCode = [SELECT Id FROM Trim_Master__c];

        // Create Stock Reservation
        Stock_Reservation__c stockReservation2 = Test_DataFactory.StockReservation(true, modelCode.ID, colorCode.ID, trimCode.ID, modelYearCode.ID);*/

        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', 'AK19115678', stockReservation.Id, 'Thieu Dang Vu');
        salesAgreement.CommcaseNo__c = '12-0059 15';
        insert salesAgreement;

        //salesAgreement.Stock_Reservation__c = stockReservation2.Id;
        salesAgreement.CommcaseNo__c = '12-0059 16';
        update salesAgreement;
    }
}