force-app/main/default/objects/Accessories_Master__c/Accessories_Master__c.object-meta.xml
<CustomObject>
    <description>To list down the list of different Accessories for MF</description>
    <label>Accessories Master</label>
    <nameField>
        <displayFormat>AM-{0000000000}</displayFormat>
        <label>Accessories Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accessories Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SA_Accessory__c/SA_Accessory__c.object-meta.xml
<CustomObject>
    <label>SA Accessory</label>
    <nameField>
        <displayFormat>SAA-{0000000000}</displayFormat>
        <label>SA Accesories Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SA Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/Acc_Code_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Acc_Code_Trigger__c</fullName>
    <description>Please do not delete.</description>
    <label>Acc Code (Trigger)</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/Accessories_Master__c.field-meta.xml
<CustomField>
    <fullName>Accessories_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessories Master</label>
    <referenceTo>Accessories_Master__c</referenceTo>
    <relationshipLabel>SA Accessories</relationshipLabel>
    <relationshipName>SA_Accessories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/AccessoriesTradable__c.field-meta.xml
<CustomField>
    <fullName>AccessoriesTradable__c</fullName>
    <formula>Accessories_Master__r.ACM_TRADABLE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accessories Tradable</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>Accessories_Master__r.ACM_ACCSDESC__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <label>Display Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/PKA_VALUE__c.field-meta.xml
<CustomField>
    <fullName>PKA_VALUE__c</fullName>
    <label>Package Value</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/Price_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Price_Trigger__c</fullName>
    <description>Please do not delete.</description>
    <label>Price (Trigger)</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/SAC_ACCSCOST__c.field-meta.xml
<CustomField>
    <fullName>SAC_ACCSCOST__c</fullName>
    <formula>Accessories_Master__r.ACM_ACCSCOST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accessories Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/SAC_ACCSTRADE__c.field-meta.xml
<CustomField>
    <fullName>SAC_ACCSTRADE__c</fullName>
    <label>Accs Trade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YN</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/SAC_ACCSVALUE__c.field-meta.xml
<CustomField>
    <fullName>SAC_ACCSVALUE__c</fullName>
    <label>Accessories Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/SAC_ACM_ACCSCD__c.field-meta.xml
<CustomField>
    <fullName>SAC_ACM_ACCSCD__c</fullName>
    <formula>Accessories_Master__r.ACM_ACCSCD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accessories Code</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/SAC_DEALERTRADECOST__c.field-meta.xml
<CustomField>
    <fullName>SAC_DEALERTRADECOST__c</fullName>
    <formula>Accessories_Master__r.ACM_DEALERTRADECOST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dealer Trade Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/SAC_INCPRICE__c.field-meta.xml
<CustomField>
    <fullName>SAC_INCPRICE__c</fullName>
    <label>Inclusive</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/SAC_LINENO__c.field-meta.xml
<CustomField>
    <fullName>SAC_LINENO__c</fullName>
    <label>Line No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/SAC_PACKAGE__c.field-meta.xml
<CustomField>
    <fullName>SAC_PACKAGE__c</fullName>
    <label>Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YN</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/SAC_PACKAGE_TRADE_REBATE__c.field-meta.xml
<CustomField>
    <fullName>SAC_PACKAGE_TRADE_REBATE__c</fullName>
    <label>Package Trade Rebate</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/SAC_PRICE__c.field-meta.xml
<CustomField>
    <fullName>SAC_PRICE__c</fullName>
    <formula>Accessories_Master__r.Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/SAC_REBATE__c.field-meta.xml
<CustomField>
    <fullName>SAC_REBATE__c</fullName>
    <label>Acc Rebate</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/SACQTY__c.field-meta.xml
<CustomField>
    <fullName>SACQTY__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/SACSETRADECOST__c.field-meta.xml
<CustomField>
    <fullName>SACSETRADECOST__c</fullName>
    <formula>Accessories_Master__r.ACM_SETRADECOST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trade Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/SAD_SOH_SONO__c.field-meta.xml
<CustomField>
    <fullName>SAD_SOH_SONO__c</fullName>
    <formula>Sales_Agreement__r.SOH_SONO__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Agreement No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>SA Accessories</relationshipLabel>
    <relationshipName>SA_Accessories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/fields/SOH_ACCSAMT__c.field-meta.xml
<CustomField>
    <fullName>SOH_ACCSAMT__c</fullName>
    <formula>Accessories_Master__r.AccsRateMaster__r.ARM_SALEPRICE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accs Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/FranchiseCode__c.field-meta.xml
<CustomField>
    <fullName>FranchiseCode__c</fullName>
    <formula>/*TEXT(Owner:User.Franchise_Code__c)*/
TEXT( Stock_Reservation__r.Model_Code__r.Franchise_Code__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Franchise Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/UniqueBranchCode__c.field-meta.xml
<CustomField>
    <fullName>UniqueBranchCode__c</fullName>
    <formula>CASE(TEXT( Branch_Code__c ), 
&quot;CCK&quot; , &quot;CCLCCKSGDCCK003&quot;,
&quot;CCF&quot; , &quot;CCLCCFSGDCCF005&quot;,
&quot;CCA&quot; , &quot;CCLCCASGDCNC006&quot;,
&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Branch Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/YN.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
    </customValue>
    <customValue>
        <fullName>N</fullName>
    </customValue>
    <masterLabel>YN</masterLabel>
</GlobalValueSet>

cncProd/force-app/main/default/classes/SaAccsSelector.cls
public class SaAccsSelector extends ADGLIB_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            SA_Accessory__c.Id,
            SA_Accessory__c.Name,
            SA_Accessory__c.Description__c,
            SA_Accessory__c.SAC_ACCSCOST__c,
            SA_Accessory__c.SAC_ACCSVALUE__c,
            SA_Accessory__c.SAC_PACKAGE__c,
            SA_Accessory__c.DisplayOrder__c,
            SA_Accessory__c.SAC_ACM_ACCSCD__c,
            SA_Accessory__c.Accessories_Master__c,
            SA_Accessory__c.Sales_Agreement__c,
            SA_Accessory__c.SACQTY__c,
            SA_Accessory__c.SAC_INCPRICE__c,
            SA_Accessory__c.SAC_ACCSTRADE__c,
            SA_Accessory__c.SACSETRADECOST__c,
            SA_Accessory__c.SAC_DEALERTRADECOST__c,
            SA_Accessory__c.SOH_ACCSAMT__c,   
            SA_Accessory__c.SAD_SOH_SONO__c,
            SA_Accessory__c.AccessoriesTradable__c,
            SA_Accessory__c.SAC_PRICE__c, 
            SA_Accessory__c.SAC_LINENO__c,
            SA_Accessory__c.Acc_Code_Trigger__c,  
            SA_Accessory__c.Price_Trigger__c,
            SA_Accessory__c.SAC_PACKAGE_TRADE_REBATE__c,
            SA_Accessory__c.SAC_REBATE__c,
            SA_Accessory__c.PKA_VALUE__c    
		};
    }

    public Schema.SObjectType getSObjectType() {
        return SA_Accessory__c.sObjectType;
    }

    public override String getOrderBy() {
    	return 'DisplayOrder__c';
    }

    public List<SA_Accessory__c> selectAccBySalesAgreementId(Set<Id> salesAgreementIds){
       	adglib_QueryFactory query = newQueryFactory();
        query.setCondition('SAC_PACKAGE__c = \'Y\' AND Sales_Agreement__c in: salesAgreementIds');
        //system.debug(query.toSOQL());
        
        return (List<SA_Accessory__c>) Database.query(query.toSOQL());
    }

    public List<SA_Accessory__c> selectAddonAccBySalesAgreementId(Set<Id> salesAgreementIds){
       	adglib_QueryFactory query = newQueryFactory();
        //query.setCondition('Sales_Agreement__c in: salesAgreementIds');
        query.setCondition('SAC_PACKAGE__c != \'Y\' AND Sales_Agreement__c in: salesAgreementIds');
        
        return (List<SA_Accessory__c>) Database.query(query.toSOQL());
    }
    
    public SA_Accessory__c selectAccsBySaIdandAccCode (ID saId, String accCode) {
        adglib_QueryFactory query = newQueryFactory();
        SA_Accessory__c sAAcc;
        query.setCondition('Sales_Agreement__c =: saId AND (Acc_Code_Trigger__c =: accCode OR SAC_ACM_ACCSCD__c =: accCode)');
        query.selectFields(new List<String> {'Sales_Agreement__r.UniqueBranchCode__c', 'Sales_Agreement__r.FranchiseCode__c'});

        List<SA_Accessory__c> sAAccs = Database.query(query.toSOQL());
        
        if (!sAAccs.isEmpty()) {
            sAAcc = sAAccs[0];
        }
        return sAAcc;
    }

    public List<SA_Accessory__c> selectAccessoriesBySalesAgreementId(Id salesAgreementId) {
        List<String> queryFields = new List<String> {'Sales_Agreement__r.UniqueBranchCode__c', 'Sales_Agreement__r.FranchiseCode__c'};
        adglib_QueryFactory query = newQueryFactory();
        query.setCondition('Sales_Agreement__c =: salesAgreementId');
        query.selectFields(queryFields);
        return (List<SA_Accessory__c>) Database.query(query.toSOQL());
    }

    public SA_Accessory__c selectOffpeakRecord(Id salesAgreementId, Id offpeakId) {
        adglib_QueryFactory query = newQueryFactory();
        query.setCondition('Sales_Agreement__c =: salesAgreementId AND Accessories_Master__c =: offpeakId');
        query.setLimit(1);
        return Database.query(query.toSOQL());
    }
}