force-app/main/default/objects/Accessories_Master__c/Accessories_Master__c.object-meta.xml
<CustomObject>
    <description>To list down the list of different Accessories for MF</description>
    <label>Accessories Master</label>
    <nameField>
        <displayFormat>AM-{0000000000}</displayFormat>
        <label>Accessories Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accessories Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accessories_Master__c/fields/ACM_ACCSCD__c.field-meta.xml
<CustomField>
    <fullName>ACM_ACCSCD__c</fullName>
    <externalId>true</externalId>
    <label>Accs Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accessories_Master__c/fields/ACM_ACCSDESC__c.field-meta.xml
<CustomField>
    <fullName>ACM_ACCSDESC__c</fullName>
    <label>Accs Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accessories_Master__c/fields/ACM_ACCSTYPE__c.field-meta.xml
<CustomField>
    <fullName>ACM_ACCSTYPE__c</fullName>
    <label>Accounts Type</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accessories_Master__c/fields/ACM_FRN_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>ACM_FRN_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accessories_Master__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Model_Rate_Master__c/Model_Rate_Master__c.object-meta.xml
<CustomObject>
    <label>Model Rate Master</label>
    <nameField>
        <displayFormat>MRM-{0000}</displayFormat>
        <label>Model Rate Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Model Rate Masters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Rate_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Rate Masters</relationshipLabel>
    <relationshipName>Model_Rate_Masters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Model_Rate_Master__c/fields/MRM_MYM_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>MRM_MYM_FRNCD__c</fullName>
    <label>MRM_MYM_FRNCD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Score__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Score__c</fullName>
    <label>Opportunity Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/recordTypes/KIAPC.recordType-meta.xml
<RecordType>
    <fullName>KIAPC</fullName>
    <active>true</active>
    <businessProcess>OppSales</businessProcess>
    <label>KIAPC</label>
</RecordType>

force-app/main/default/objects/Package_Accs__c/Package_Accs__c.object-meta.xml
<CustomObject>
    <label>Package Accs</label>
    <nameField>
        <displayFormat>PA-{0000000000}</displayFormat>
        <label>Package Accs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Accs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Accs__c/fields/Accessories_Master__c.field-meta.xml
<CustomField>
    <fullName>Accessories_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessories Master</label>
    <referenceTo>Accessories_Master__c</referenceTo>
    <relationshipLabel>Accessories Master</relationshipLabel>
    <relationshipName>Package_Accs</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Accs__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Package Accs</relationshipLabel>
    <relationshipName>Package_Accs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Additional_Charges__c/Package_Additional_Charges__c.object-meta.xml
<CustomObject>
    <label>Package Additional Charges</label>
    <nameField>
        <displayFormat>PAC-{0000000000}</displayFormat>
        <label>Package Additional Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package_Additional_Charges__c/fields/Additional_Charges_Master__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charges_Master__c</fullName>
    <label>Additional Charges Master</label>
    <referenceTo>Additional_Charges_Master__c</referenceTo>
    <relationshipLabel>Additional Charges Master</relationshipLabel>
    <relationshipName>Package_Additional_Charges</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package_Additional_Charges__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Package Additional Charges</relationshipLabel>
    <relationshipName>Package_Additional_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/Package_Header__c.object-meta.xml
<CustomObject>
    <label>Package Header</label>
    <nameField>
        <displayFormat>PH-{0000000000}</displayFormat>
        <label>Package Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Header</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Header__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Package Header</relationshipLabel>
    <relationshipName>Package_Header</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/fields/PKH_FRN_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>PKH_FRN_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Header__c/fields/PKH_PKGNO__c.field-meta.xml
<CustomField>
    <fullName>PKH_PKGNO__c</fullName>
    <externalId>true</externalId>
    <label>Package No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Header__c/fields/PKH_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PKH_STATUS__c</fullName>
    <label>Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SA_Accessory__c/SA_Accessory__c.object-meta.xml
<CustomObject>
    <label>SA Accessory</label>
    <nameField>
        <displayFormat>SAA-{0000000000}</displayFormat>
        <label>SA Accesories Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SA Accessories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/SA_Accessory__c/fields/Accessories_Master__c.field-meta.xml
<CustomField>
    <fullName>Accessories_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessories Master</label>
    <referenceTo>Accessories_Master__c</referenceTo>
    <relationshipLabel>SA Accessories</relationshipLabel>
    <relationshipName>SA_Accessories</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Agreement__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch_Code</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Stock_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Stock_Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Stock Reservation</label>
    <referenceTo>Stock_Reservation__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Reservation__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Package_Header_From_PickList__c.field-meta.xml
<CustomField>
    <fullName>Package_Header_From_PickList__c</fullName>
    <description>This field is a temporary field to contain the Id of the package header choose from the picklist on page 0, not a lookup field to Package_Header__c obj.</description>
    <label>Package Header From PickList</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Branch_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CCF</fullName>
    </customValue>
    <customValue>
        <fullName>CCK</fullName>
    </customValue>
    <customValue>
        <fullName>CCA</fullName>
    </customValue>
    <customValue>
        <fullName>CNC</fullName>
        <isActive>false</isActive>
        <label>CNC</label>
    </customValue>
    <masterLabel>Branch Code</masterLabel>
</GlobalValueSet>

cncProd/force-app/main/default/classes/SalesAgreementServiceTest.cls
@isTest
private class SalesAgreementServiceTest 
{
	@testSetup
    static void setUp() 
    {     
        //Create Account and Opportunity
        Account personAcc = Test_DataFactory.createPerson(true, 'Test', 'Customer');
        Opportunity oppt = Test_DataFactory.createOpportunity(false,'testRun', personAcc.Id);
        oppt.Branch_Code__c = 'CCA';
        oppt.Opportunity_Score__c = 40;
        insert oppt;
        
        // Create master data
        Model_Master__c modelCode = Test_DataFactory.createModelCode(true, 'Test Model Code');
        Model_Rate_Master__c modelRateMaster = new Model_Rate_Master__c(Model_Master__c = modelCode.Id,
                                                                       	MRM_MYM_FRNCD__c = 'KIAPC');
        insert modelRateMaster;

        Model_Year_Master__c modelYearCode = Test_DataFactory.createModelYearCode(true, modelCode.Id);
        Color_Master__c colorCode = Test_DataFactory.createColorCode(true, 'Test Color Code', 'Test', 'CCK', 'KIAPC');
        Trim_Master__c trimCode = Test_DataFactory.createTrimCode(true, 'Test Trim Code');
        Accessories_Master__c accMaster = new Accessories_Master__c(ACM_FRN_FRNCD__c = 'KIAPC',
                                                                    ACM_ACCSDESC__c = 'Acc Master Test',
                                                                    ACM_ACCSCD__c = 'GRABSVC1',
                                                                    Rate__c = 5000,
                                                                    ACM_ACCSTYPE__c = 'F');
        insert accMaster;

        Additional_Charges_Master__c addnlChargeMaster = Test_DataFactory.createAdditionalChargesMaster(true, 'R004');
        
        // Create Package Header
		Package_Header__c pckHeader = new Package_Header__c(PKH_FRN_FRNCD__c = 'KIAPC',
                                                           	Model_Master__c = modelCode.Id,
                                                           	PKH_PKGNO__c = '99',
                                                           	PKH_STATUS__c = 'A');
        insert pckHeader;

        // Create Stock Reservation
        Stock_Reservation__c stockReservation1 = Test_DataFactory.StockReservation(false, modelCode.ID, colorCode.ID, trimCode.ID, modelYearCode.ID);
        stockReservation1.Package_Header_From_PickList__c = pckHeader.Id;
        stockReservation1.Opportunity__c                  = oppt.Id;
		insert stockReservation1;
        Stock_Reservation__c stockReservation2 = Test_DataFactory.StockReservation(false, modelCode.ID, colorCode.ID, trimCode.ID, modelYearCode.ID);
        stockReservation2.Package_Header_From_PickList__c = pckHeader.Id;
        stockReservation2.Opportunity__c                  = oppt.Id;
		insert stockReservation2;
   
        // Create Sales Agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', 'NO9999', stockReservation1.ID, 'Thieu Dang Vu');
        salesAgreement.Package_Header__c = pckHeader.Id;
        insert salesAgreement;
	}

    @isTest
    static void Test_getSalesAgrmnt() {
        Sales_Agreement__c salesAgreement = [SELECT Id, Package_Header__r.PKH_PKGNO__c, Finance_Company_Lookup__r.BAM_ASSOCIATECD__c,
                                             		Stock_Reservation__r.Model_Code__c, Insurance_Company_Lookup__r.BAM_ASSOCIATECD__c
                                             FROM Sales_Agreement__c];
        Sales_Agreement__c sa = SalesAgreementService.getSalesAgrmnt(salesAgreement.Id);

        System.assertNotEquals(null, sa);
    }

    @isTest
    static void Test_getSaAccs() {
        Sales_Agreement__c salesAgreement = [SELECT Id FROM Sales_Agreement__c];
        Accessories_Master__c accMaster = [SELECT Id FROM Accessories_Master__c];

        List<SA_Accessory__c> saAccList = new List<SA_Accessory__c>();
        for (Integer i = 0; i < 5; i++) {
            SA_Accessory__c saAcc = new SA_Accessory__c(Sales_Agreement__c = salesAgreement.Id,
                                                    	Accessories_Master__c = accMaster.Id);
            saAccList.add(saAcc);
        }
		insert saAccList;
        List<SA_Accessory__c> saAccs = SalesAgreementService.getSaAccs(salesAgreement.Id);

        System.assertEquals(5, saAccs.size());
    }

    @isTest
    static void Test_getSaAddnlCharges() {
        Sales_Agreement__c salesAgreement = [SELECT Id FROM Sales_Agreement__c];
        Additional_Charges_Master__c addnlChargeMaster = [SELECT Id FROM Additional_Charges_Master__c];
        SA_Additional_Charge__c saAdditionalCharge = Test_DataFactory.createSAAdditionalCharge(true, addnlChargeMaster.Id, salesAgreement.Id);
        List<SA_Additional_Charge__c> saAddnlCharges = SalesAgreementService.getSaAddnlCharges(salesAgreement.Id);

        System.assertEquals(1, saAddnlCharges.size());
    }
 
    @isTest
    static void Test_getPackageAddnlCharges() {
        Package_Header__c pckHeader = [SELECT Id FROM Package_Header__c];
        Additional_Charges_Master__c addnlChargeMaster = [SELECT Id FROM Additional_Charges_Master__c];

        List<Package_Additional_Charges__c> pckAddnlChargeList = new List<Package_Additional_Charges__c>();
        for (Integer i = 0; i < 5; i++) {
			Package_Additional_Charges__c pckAddnlCharge = new Package_Additional_Charges__c(PKC_PKH_FRNCD__c = 'KIAPC',
                                                                                            Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                            Package_Header__c = pckHeader.Id);
            pckAddnlChargeList.add(pckAddnlCharge);
        }
		insert pckAddnlChargeList;
        List<Package_Additional_Charges__c> pckAddnlCharges = SalesAgreementService.getPackageAddnlCharges(pckHeader.Id);

        System.assertEquals(5, pckAddnlCharges.size());
    }

    @isTest
    static void Test_getPkgAccs() {
        Package_Header__c pckHeader = [SELECT Id FROM Package_Header__c];
        Accessories_Master__c accMaster = [SELECT Id FROM Accessories_Master__c];

        List<Package_Accs__c> pckAccList = new List<Package_Accs__c>();
        for (Integer i = 0; i < 5; i++) {
            Package_Accs__c pckAcc = new Package_Accs__c(Package_Header__c = pckHeader.Id,
                                                         Accessories_Master__c = accMaster.Id,
                                                         PKA_PKH_FRNCD__c = 'KIAPC');
            pckAccList.add(pckAcc);
        }
		insert pckAccList;
        List<Package_Accs__c> pckAccs = SalesAgreementService.getPkgAccs(pckHeader.Id);

        System.assertEquals(5, pckAccs.size());
    }

    @isTest
    static void Test_getAccsMaster() {
        Accessories_Master__c accessoriesMaster = [SELECT Id FROM Accessories_Master__c];
        Accessories_Master__c accMaster = SalesAgreementService.getAccsMaster(accessoriesMaster.Id);

        System.assertNotEquals(null, accMaster);
    }

    @isTest
    static void Test_getModelRateMaster() {
        //Model_Rate_Master__c modelRateMaster = [SELECT Id FROM Model_Rate_Master__c];
        Model_Master__c modelCode = [SELECT Id FROM Model_Master__c];
        List<Model_Rate_Master__c> modelRateMasters = SalesAgreementService.getModelRateMaster(modelCode.Id);

        System.assertEquals(1, modelRateMasters.size());
    }

    @isTest
    static void Test_getSaAccsBySaIdandAccCode() {
        Sales_Agreement__c salesAgreement = [SELECT Id FROM Sales_Agreement__c];
        SA_Accessory__c saAccSVC = new SA_Accessory__c(Sales_Agreement__c = salesAgreement.Id,
                                                       Acc_Code_Trigger__c = 'SVC2000');
        insert saAccSVC;
        SA_Accessory__c saAcc = SalesAgreementService.getSaAccsBySaIdandAccCode(salesAgreement.Id, 'SVC2000');

        System.assertEquals('SVC2000', saAcc.Acc_Code_Trigger__c);
    }

    @isTest
    static void Test_processOffPeakCar() {
        // Previous Sales Agreement
        Sales_Agreement__c prevSalesAgreement = [SELECT Id FROM Sales_Agreement__c];
        prevSalesAgreement.Registration_Number_Type__c = 'Normal';
        prevSalesAgreement.SOH_SONO__c = 'AK123456';
        update prevSalesAgreement;
        // Create current Sales Agreement
        List<Stock_Reservation__c> stockReservations = [SELECT Id FROM Stock_Reservation__c];
        Sales_Agreement__c currSalesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', 'AK654321', stockReservations[1].ID, 'Thieu Dang Vu');
		currSalesAgreement.Registration_Number_Type__c = 'Off Peak Car';
        insert currSalesAgreement;

        Sales_Agreement__c sa = SalesAgreementService.processOffPeakCar(prevSalesAgreement, currSalesAgreement);
        System.assertEquals('O', sa.SOH_RTM_REGTYPECD__c);
        System.assertEquals('AK654321', sa.SOH_SONO__c);
    }

    @isTest
    static void Test_getStockReservationInformation() {
        List<Stock_Reservation__c> stockReservations = [SELECT Id FROM Stock_Reservation__c];
        Set<Id> stockResIds = new Set<Id>();
        for (Stock_Reservation__c stock : stockReservations) {
            stockResIds.add(stock.Id);
        }
        Map<Id, Stock_Reservation__c> stockMap = SalesAgreementService.getStockReservationInformation(stockResIds);

        System.assertEquals(2, stockMap.size());
    }

    @isTest
    static void Test_getPackageHeaderIdBasedOnModel() {
        List<Stock_Reservation__c> stockReservations = [SELECT Id, Model_Code__c FROM Stock_Reservation__c];
        Map<String, Id> pckAndModelMap = SalesAgreementService.getPackageHeaderIdBasedOnModel(stockReservations);

        //Return 1 because 2 stock reservation belongs to 1 model master
        System.assertEquals(1, pckAndModelMap.size());
    }

    //Start of RN2020Q1010 
    @isTest
    static void Test_getPackageHeadersBasedOnModel () {
        List<Stock_Reservation__c> stockReservations = [SELECT Id, Model_Code__c FROM Stock_Reservation__c];
        Map<String, Package_Header__c> pckAndModelMap = SalesAgreementService.getPackageHeadersBasedOnModel(stockReservations);
        System.assertEquals(1, pckAndModelMap.size());
    }

    static void Test_processCalculation() {
        List<Stock_Reservation__c> stockReservations = [SELECT Id FROM Stock_Reservation__c];
        Sales_Agreement__c currSalesAgreement = Test_DataFactory.createSalesAgreement(true, 'CCK', 'AK654321', stockReservations[1].ID, 'Thieu Dang Vu');
		currSalesAgreement.Package_List_Price__c = 1000000;
        update currSalesAgreement;

        System.assertEquals(currSalesAgreement.Package_List_Price__c, currSalesAgreement.Vehicle_Purchase_Price__c);

    }
    
    //End of RN2020Q1010 

    @isTest
    static void Test_retrieveDeleteAccessories() {
		Sales_Agreement__c salesAgreement = [SELECT Id, Package_Header__c FROM Sales_Agreement__c];
        Package_Header__c pckHeader = [SELECT Id FROM Package_Header__c];
        Accessories_Master__c accMaster = [SELECT Id FROM Accessories_Master__c];

        List<SA_Accessory__c> saAccList = new List<SA_Accessory__c>();
        for (Integer i = 0; i < 5; i++) {
            SA_Accessory__c saAcc = new SA_Accessory__c(Sales_Agreement__c = salesAgreement.Id,
                                                    	Accessories_Master__c = accMaster.Id,
                                                        SAC_PACKAGE__c = 'Y');
            saAccList.add(saAcc);
        }
		insert saAccList;

        Map<Id, List<SA_Accessory__c>> saAccsToBeDeleted = SalesAgreementService.retrieveDeleteAccessories(new Map<Id, Id>{salesAgreement.Id => pckHeader.Id});
        System.assertEquals(5, saAccsToBeDeleted.get(salesAgreement.Id).size());
    }

    @isTest
    static void Test_retrieveNewAccessories() {
        Sales_Agreement__c salesAgreement = [SELECT Id, Package_Header__c FROM Sales_Agreement__c];
        Package_Header__c pckHeader = [SELECT Id FROM Package_Header__c];
        Accessories_Master__c accMaster = [SELECT Id FROM Accessories_Master__c];
        List<Package_Accs__c> pckAccList = new List<Package_Accs__c>();
        for (Integer i = 0; i < 5; i++) {
            Package_Accs__c pckAcc = new Package_Accs__c(Package_Header__c = pckHeader.Id,
                                                         Accessories_Master__c = accMaster.Id,
                                                         PKA_PKH_FRNCD__c = 'KIAPC');
            pckAccList.add(pckAcc);
        }
		insert pckAccList;
        Map<Id, List<Package_Accs__c>> pckAccMap = SalesAgreementService.retrieveNewAccessories(new Map<Id, Id>{salesAgreement.Id => pckHeader.Id});
        system.debug(pckAccMap.get(pckHeader.Id));
        System.assertEquals(5, pckAccMap.get(pckHeader.Id).size());
    }

    @isTest
    static void Test_retrieveDeleteAdditionCharges() {
		Sales_Agreement__c salesAgreement = [SELECT Id, Package_Header__c FROM Sales_Agreement__c];
        Package_Header__c pckHeader = [SELECT Id FROM Package_Header__c];
        Additional_Charges_Master__c addnlChargeMaster = [SELECT Id FROM Additional_Charges_Master__c];
		List<SA_Additional_Charge__c> saAddnlChrages = new List<SA_Additional_Charge__c>();
        for (Integer i = 0; i < 5; i++) {
            SA_Additional_Charge__c saAddnlCharge = new SA_Additional_Charge__c(Sales_Agreement__c = salesAgreement.Id,
                                                                                AdditionalChargesMaster__c = addnlChargeMaster.Id);
            saAddnlChrages.add(saAddnlCharge);
        }
		insert saAddnlChrages;
        Map<Id, List<SA_Additional_Charge__c>> saAddnlChargeToBeDeleted = SalesAgreementService.retrieveDeleteAdditionCharges(new Map<Id, Id>{salesAgreement.Id => pckHeader.Id});
        System.assertEquals(5, saAddnlChargeToBeDeleted.get(salesAgreement.Id).size());        
    }

    @isTest
    static void Test_retrieveNewAdditionalCharges() {
		Sales_Agreement__c salesAgreement = [SELECT Id, Package_Header__c FROM Sales_Agreement__c];
        Package_Header__c pckHeader = [SELECT Id FROM Package_Header__c];
        Additional_Charges_Master__c addnlChargeMaster = [SELECT Id FROM Additional_Charges_Master__c];
        List<Package_Additional_Charges__c> pckAddnlCharges = new List<Package_Additional_Charges__c>();
        for (Integer i = 0; i < 5; i++) {
            Package_Additional_Charges__c pckAddnlCharge = new Package_Additional_Charges__c(Package_Header__c = pckHeader.Id,
                                                                                             Additional_Charges_Master__c = addnlChargeMaster.Id,
                                                                                             PKC_PKH_FRNCD__c = 'KIAPC');
            pckAddnlCharges.add(pckAddnlCharge);
        }
		insert pckAddnlCharges;
        Map<Id, List<Package_Additional_Charges__c>> pckAddnlChargeMap = SalesAgreementService.retrieveNewAdditionalCharges(new Map<Id, Id>{salesAgreement.Id => pckHeader.Id});

        System.assertEquals(5, pckAddnlChargeMap.get(pckHeader.Id).size());        
    }

    @isTest
    static void Test_findPackagesBasedOnSalesAgreement() {
        Sales_Agreement__c sa = [SELECT Id, Package_Header__c FROM Sales_Agreement__c];
        Package_Header__c pckHeader = new Package_Header__c(PKH_FRN_FRNCD__c = 'MITPC');
        insert pckHeader;
        Sales_Agreement__c saClone = sa.Clone();
        sa.Package_Header__c = pckHeader.Id;
        update sa;
		Map<Id, Id> changedPackageHeader = SalesAgreementService.findPackagesBasedOnSalesAgreement(new Map<Id, SObject>{sa.Id => saClone}, new List<Sales_Agreement__c>{sa});

        System.assertNotEquals(saClone.Package_Header__c, sa.Package_Header__c);
    }

    @isTest
    static void Test_getACMByBranchCodeandAccCode() {
        Accessories_Master__c currAccMaster = new Accessories_Master__c(ACM_FRN_FRNCD__c = 'KIAPC',
                                                                        ACM_ACCSDESC__c = 'Acc Master Test',
                                                                        ACM_ACCSCD__c = 'SER2000',
                                                                        Rate__c = 5000,
                                                                        ACM_ACCSTYPE__c = 'F',
                                                                        ACM_MNM_MAJGROUPCD__c = 'FREE_ACC');
        insert currAccMaster;
        Accessories_Master__c accMaster = SalesAgreementService.getACMByBranchCodeandAccCode('CCK', 'SER2000');

        System.assertEquals('CCK', accMaster.BranchCode__c);
    }
    
    @isTest
    static void Test_getACMByVSMSCompoundPrimaryKey() {
        Accessories_Master__c currAccMaster = new Accessories_Master__c(ACM_FRN_FRNCD__c = 'KIAPC',
                                                                        ACM_ACCSDESC__c = 'Acc Master Test 2',
                                                                        ACM_ACCSCD__c = 'SER5000',
                                                                        Rate__c = 5000,
                                                                        ACM_ACCSTYPE__c = 'F',
                                                                        ACM_MNM_MAJGROUPCD__c = 'FREE_ACC',
                                                                        ACM_BRM_UNIQUEBRCD__c = 'CCLCCKSGDCCK003');
        insert currAccMaster;
        Accessories_Master__c accMaster = SalesAgreementService.getACMByVSMSCompoundPrimaryKey('KIAPC', 'SER5000', 'CCLCCKSGDCCK003');

        System.assertEquals('CCLCCKSGDCCK003', accMaster.ACM_BRM_UNIQUEBRCD__c);   
    }  
}