cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/Courtesy_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Courtesy Vehicles (Test Drive, Loan, Showroom)</description>
    <label>Courtesy Vehicle</label>
    <nameField>
        <label>Courtesy Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courtesy Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Courtesy_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Loan (Test Drive)</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Loaned Out</fullName>
            </value>
            <value>
                <fullName>Loaned In</fullName>
                <isActive>false</isActive>
                <label>Loaned In</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/MB_Test_Drive_Daily_Log__c/MB_Test_Drive_Daily_Log__c.object-meta.xml
<CustomObject>
    <description>Daily log for MB Test Drive Vehicles</description>
    <label>MB Test Drive Daily Log</label>
    <nameField>
        <displayFormat>DL-{000000}</displayFormat>
        <label>Daily Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Test Drive Daily Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Test_Drive_Daily_Log__c/fields/Courtesy_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Courtesy_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Courtesy Vehicle</label>
    <referenceTo>Courtesy_Vehicle__c</referenceTo>
    <relationshipName>Vehicle_Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MB_Test_Drive_Daily_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MBTestDriveDailyLogSelector.cls
/** *****
 * Description : Selector Class for MB Test Drive Daily Log object
 * 
 * Change History
 * Date(YYYYMMDD)       Name                   Description
 * 20211019           TPhan@aodigy        Created Initial Version. 
 * ** *****/

public class MBTestDriveDailyLogSelector extends ADGLIB_SObjectSelector
{
    public Schema.SObjectType getSObjectType() 
    {
        return MB_Test_Drive_Daily_Log__c.sObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() 
    {
        return ADGLIB_UtilityHelper.getSObjectFieldListByObj('MB_Test_Drive_Daily_Log__c');
    }

    public List<MB_Test_Drive_Daily_Log__c> selectMBTDDailyLogsByCreatedDateAndStatusAndVehicles (String queryDate, String status, Set<Id> courtesyVehIds,
                                                                                                  String dateComparator, String fieldOrdering, Boolean orderingDESC)
    {
        adglib_QueryFactory query = newQueryFactory();    
        String str_filter = '';
        
        if (String.isNotBlank(queryDate))
        {
            Date createdDate = Date.valueOf(queryDate);
            str_filter += ' DAY_ONLY(CreatedDate) ' + dateComparator + ' : createdDate ';
        }

        if (String.isNotBlank(status))
        {
            str_filter += String.isNotBlank(str_filter) ? ' AND Status__c =: status ' : ' Status__c =: status '; 
        }

        if (courtesyVehIds <> null && courtesyVehIds.size() > 0)
        {
            str_filter += String.isNotBlank(str_filter) ? ' AND Courtesy_Vehicle__c IN: courtesyVehIds ' : ' Courtesy_Vehicle__c IN: courtesyVehIds '; 
        }

        System.debug('@@@MBTestDriveDailyLogSelector Query : ' + str_filter);

        query.setCondition(str_filter);
        if (orderingDESC <> null)
        {
            if (orderingDESC)
            {
                query.setOrdering(fieldOrdering, ADGLIB_QueryFactory.SortOrder.DESCENDING);
            }
            else
            {
                query.setOrdering(fieldOrdering, ADGLIB_QueryFactory.SortOrder.ASCENDING);
            }
        }

        return Database.query(query.toSOQL());
    }
}