cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/Courtesy_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Courtesy Vehicles (Test Drive, Loan, Showroom)</description>
    <label>Courtesy Vehicle</label>
    <nameField>
        <label>Courtesy Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courtesy Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Courtesy_Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Courtesy Vehicles</relationshipLabel>
    <relationshipName>Courtesy_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Courtesy Vehicles</relationshipLabel>
    <relationshipName>Courtesy_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courtesy_Vehicle__c/recordTypes/MB_Test_Drive.recordType-meta.xml
<RecordType>
    <fullName>MB_Test_Drive</fullName>
    <active>true</active>
    <label>MB Test Drive</label>
</RecordType>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/classes/CourtesyVehicleSelectorTest.cls
/** *****
 * Description : Test Class for CourtesyVehicleSelector
 * 
 * Change History
 * Date(YYYYMMDD)       Name                   Description
 * 20211101           TPhan@aodigy        Created Initial Version. 
 * ** *****/

@isTest
private class CourtesyVehicleSelectorTest 
{
    @isTest
    static void test_SelectCourtesyVehiclesByStatusAndBranchCode()
    {
        Model__c model = Test_DataFactory.createmodelId(true, 'MB G-Class PC', 'CCI', 'MBP');
        Variant__c variant = Test_DataFactory.createVariant(true, 'MB G 63 AMG Station Wagon Long', model.Id, 'CCI');
        Courtesy_Vehicle__c veh = Test_DataFactory.createCourtesyVehicle(true, 'MB_Test_Drive', 'Available', 'CCI', 'MBP', model.Id, variant.Id);
        CourtesyVehicleSelector sel = new CourtesyVehicleSelector();
        System.assertEquals(1, sel.selectCourtesyVehiclesByStatusAndBranchCode('MB_Test_Drive', 'Available', 'CCI', 'MBP').size());
    }
}