cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/Courtesy_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Courtesy Vehicles (Test Drive, Loan, Showroom)</description>
    <label>Courtesy Vehicle</label>
    <nameField>
        <label>Courtesy Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courtesy Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Courtesy_Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Courtesy Vehicles</relationshipLabel>
    <relationshipName>Courtesy_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courtesy_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Loan (Test Drive)</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Loaned Out</fullName>
            </value>
            <value>
                <fullName>Loaned In</fullName>
                <isActive>false</isActive>
                <label>Loaned In</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Courtesy Vehicles</relationshipLabel>
    <relationshipName>Courtesy_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courtesy_Vehicle__c/recordTypes/MB_Test_Drive.recordType-meta.xml
<RecordType>
    <fullName>MB_Test_Drive</fullName>
    <active>true</active>
    <label>MB Test Drive</label>
</RecordType>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Model__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Model__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Vehicle_Request__c/Vehicle_Request__c.object-meta.xml
<CustomObject>
    <description>Request for Test Drive, Loan, Maintainance</description>
    <label>Vehicle Request</label>
    <nameField>
        <displayFormat>VR-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicle Requests (Account)</relationshipLabel>
    <relationshipName>Vehicle_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Check_Out__c</fullName>
    <label>Check-Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vehicle_Request__c/fields/Courtesy_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Courtesy_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Courtesy Vehicle</label>
    <referenceTo>Courtesy_Vehicle__c</referenceTo>
    <relationshipLabel>Vehicle Requests</relationshipLabel>
    <relationshipName>Loan_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Advance Booking</fullName>
            </value>
            <value>
                <fullName>Loaned Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Loan Approval</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
                <isActive>false</isActive>
                <label>Checked-Out</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Test_Drive_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive_Type__c</fullName>
    <label>Test Drive Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Test Drive</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/recordTypes/MB_Test_Drive_Request.recordType-meta.xml
<RecordType>
    <fullName>MB_Test_Drive_Request</fullName>
    <active>true</active>
    <label>MB Test Drive Request</label>
</RecordType>

force-app/main/default/classes/MB_TestDrivePDFCtrlTest.cls
@isTest
private class MB_TestDrivePDFCtrlTest {
	@isTest
    static void test() {
        Model__c model = Test_DataFactory.createmodelId(true, 'MB G-Class PC', 'CCI', 'MBP');
        Variant__c variant = Test_DataFactory.createVariant(true, 'MB G 63 AMG Station Wagon Long', model.Id, 'CCI');
        Courtesy_Vehicle__c veh = Test_DataFactory.createCourtesyVehicle(true, 'MB_Test_Drive', 'Available', 'CCI', 'MBP', model.Id, variant.Id);
		Account acc = Test_DataFactory.createPA(false, 'Test', 'email_test@mail.com', 'Prospect');
        acc.Address_Line_1__pc = 'Test';
        acc.Address_Line_2__pc = 'Test2';
        acc.Address_Line_3__pc = 'Test3';
        acc.Address_Line_4__pc = 'Test4';
        acc.Unit_No_Floor__pc = 'Test5';
        acc.Country__pc = 'Vietnam';
        insert acc;
        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req = new Vehicle_Request__c(Courtesy_Vehicle__c = veh.Id,
                                                         Status__c = 'Queued',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id);
        insert req;
        Test.startTest();
        PageReference page = Page.MB_TestDrivePDF;
        page.getParameters().put('id', req.Id);
        Test.setCurrentPage(page);
        MB_TestDrivePDFCtrl myController = new MB_TestDrivePDFCtrl();
        Test.stopTest();
    }
}