cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/Courtesy_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Courtesy Vehicles (Test Drive, Loan, Showroom)</description>
    <label>Courtesy Vehicle</label>
    <nameField>
        <label>Courtesy Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courtesy Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Courtesy_Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Courtesy Vehicles</relationshipLabel>
    <relationshipName>Courtesy_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courtesy_Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>On Loan (Test Drive)</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Loaned Out</fullName>
            </value>
            <value>
                <fullName>Loaned In</fullName>
                <isActive>false</isActive>
                <label>Loaned In</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Courtesy_Vehicle__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Courtesy Vehicles</relationshipLabel>
    <relationshipName>Courtesy_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courtesy_Vehicle__c/recordTypes/MB_Test_Drive.recordType-meta.xml
<RecordType>
    <fullName>MB_Test_Drive</fullName>
    <active>true</active>
    <label>MB Test Drive</label>
</RecordType>

cncProd/force-app/main/default/objects/MB_Test_Drive_Daily_Log__c/MB_Test_Drive_Daily_Log__c.object-meta.xml
<CustomObject>
    <description>Daily log for MB Test Drive Vehicles</description>
    <label>MB Test Drive Daily Log</label>
    <nameField>
        <displayFormat>DL-{000000}</displayFormat>
        <label>Daily Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Test Drive Daily Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Test_Drive_Daily_Log__c/fields/Courtesy_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Courtesy_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Courtesy Vehicle</label>
    <referenceTo>Courtesy_Vehicle__c</referenceTo>
    <relationshipName>Vehicle_Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Test_Drive_Daily_Log__c/fields/Opening_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Opening_Mileage__c</fullName>
    <label>Opening Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MB_Test_Drive_Daily_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Model__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Model__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Trade_Plate__c/Trade_Plate__c.object-meta.xml
<CustomObject>
    <label>Trade Plate</label>
    <nameField>
        <label>Trade Plate No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Plates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Plate__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade_Plate__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/Vehicle_Request__c.object-meta.xml
<CustomObject>
    <description>Request for Test Drive, Loan, Maintainance</description>
    <label>Vehicle Request</label>
    <nameField>
        <displayFormat>VR-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Check_Out__c</fullName>
    <label>Check-Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vehicle_Request__c/fields/Courtesy_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Courtesy_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Courtesy Vehicle</label>
    <referenceTo>Courtesy_Vehicle__c</referenceTo>
    <relationshipLabel>Vehicle Requests</relationshipLabel>
    <relationshipName>Loan_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Customer_Signature__c.field-meta.xml
<CustomField>
    <fullName>Customer_Signature__c</fullName>
    <label>Customer Signature</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Advance Booking</fullName>
            </value>
            <value>
                <fullName>Loaned Out</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Loan Approval</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
                <isActive>false</isActive>
                <label>Checked-Out</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Test_Drive_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive_Type__c</fullName>
    <label>Test Drive Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Test Drive</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/fields/Trade_Plate__c.field-meta.xml
<CustomField>
    <fullName>Trade_Plate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trade Plate</label>
    <referenceTo>Trade_Plate__c</referenceTo>
    <relationshipLabel>Vehicle Requests</relationshipLabel>
    <relationshipName>Vehicle_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Request__c/recordTypes/MB_Test_Drive_Request.recordType-meta.xml
<RecordType>
    <fullName>MB_Test_Drive_Request</fullName>
    <active>true</active>
    <label>MB Test Drive Request</label>
</RecordType>

cncProd/force-app/main/default/classes/MB_TestDriveControllerTest.cls
/** *****
 * Description : Test Class for MB_TestDriveController
 * 
 * Change History
 * Date(YYYYMMDD)       Name                   Description
 * 20211101           TPhan@aodigy        Created Initial Version. 
 * ** *****/

@isTest
private class MB_TestDriveControllerTest 
{
    @testSetup
    static void setUp() {
		Model__c model = Test_DataFactory.createmodelId(true, 'MB G-Class PC', 'CCI', 'MBP');
        Variant__c variant = Test_DataFactory.createVariant(true, 'MB G 63 AMG Station Wagon Long', model.Id, 'CCI');
		Model__c model1 = Test_DataFactory.createmodelId(true, 'MB A-Class PC', 'CCI', 'MBP');
        Variant__c variant1 = Test_DataFactory.createVariant(true, 'MB A 250 AMG', model1.Id, 'CCI');
        List<Courtesy_Vehicle__c> vehList = new List<Courtesy_Vehicle__c>();
        Courtesy_Vehicle__c veh = Test_DataFactory.createCourtesyVehicle(false, 'MB_Test_Drive', 'Available', 'CCI', 'MBP', model.Id, variant.Id);
        Courtesy_Vehicle__c veh1 = Test_DataFactory.createCourtesyVehicle(false, 'MB_Test_Drive', 'Available', 'CCI', 'MBP', model1.Id, variant.Id);
        vehList.add(veh);
		vehList.add(veh1);
        insert vehList;
    }

    @isTest
    static void test_RetrieveCourtesyVehiclesForMBTestDrive()
    { 
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];
        MB_Test_Drive_Daily_Log__c log = Test_DataFactory.createMBTestDriveDailyLog(true, 1000, null, 'Opened', vehList[0].Id);
        MB_TestDriveController.retrieveCourtesyVehiclesForMBTestDrive();
    }

    @isTest
    static void test_CreateVehicleRequest_WithNewPA()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];

        Map<String, String> info = new Map<String, String>();
        info.put('Courtesy_Vehicle__c', vehList[0].Id);
        info.put('Test_Drive_Type__c', 'Test Drive');
        info.put('Trade_Plate__c', null);
        info.put('PersonMobilePhone', '6589563257');
        info.put('PersonEmail', 'vupa984594@test.com');
        info.put('Full_Name__pc', 'Thieu Dang Vu');
        info.put('FirstName', 'Vu');
        info.put('LastName', 'Thieu');
        info.put('Status__c', 'Ongoing');
        info.put('Address_Line_1__pc', '#3-40');
        info.put('Address_Line_2__pc', 'abc bulding');
        info.put('Address_Line_3__pc', '123 Secret St');
        info.put('Customer_Signature__c', '');

        Map<String, String> frontLicense = new Map<String, String>();
        frontLicense.put('body', 'abc');
        frontLicense.put('contentType', 'image/jpeg');
        frontLicense.put('fileName', 'Front_License.jpeg');

        Map<String, String> backLicense = new Map<String, String>();
        backLicense.put('body', 'def');
        backLicense.put('contentType', 'image/jpeg');
        backLicense.put('fileName', 'Back_License.jpeg');

        TriggerExclusion.excludeTrigger('Vehicle_Request__c', true);
        MB_TestDriveController.createVehicleRequest(info, frontLicense, backLicense);
        TriggerExclusion.excludeTrigger('Vehicle_Request__c', false);
    }

	@isTest
    static void test_CreateLoanVehicleRequest_WithNewPA()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];

        Map<String, String> info = new Map<String, String>();
        info.put('Courtesy_Vehicle__c', vehList[0].Id);
        info.put('Test_Drive_Type__c', 'Loan');
        info.put('Trade_Plate__c', null);
        info.put('PersonMobilePhone', '6589563257');
        info.put('PersonEmail', 'vupa984594@test.com');
        info.put('Full_Name__pc', 'Thieu Dang Vu');
        info.put('FirstName', 'Vu');
        info.put('LastName', 'Thieu');
        info.put('Status__c', 'Ongoing');
        info.put('Address_Line_1__pc', '#3-40');
        info.put('Address_Line_2__pc', 'abc bulding');
        info.put('Address_Line_3__pc', '123 Secret St');
        info.put('Customer_Signature__c', '');

        Map<String, String> frontLicense = new Map<String, String>();
        frontLicense.put('body', 'abc');
        frontLicense.put('contentType', 'image/jpeg');
        frontLicense.put('fileName', 'Front_License.jpeg');

        Map<String, String> backLicense = new Map<String, String>();
        backLicense.put('body', 'def');
        backLicense.put('contentType', 'image/jpeg');
        backLicense.put('fileName', 'Back_License.jpeg');

        TriggerExclusion.excludeTrigger('Vehicle_Request__c', true);
        MB_TestDriveController.createVehicleRequest(info, frontLicense, backLicense);
		vehList = [SELECT ID, Status__c FROM Courtesy_Vehicle__c];
        System.assertEquals('On Loan (Test Drive)', vehList[0].Status__c);
        TriggerExclusion.excludeTrigger('Vehicle_Request__c', false);
    }

    @isTest
    static void test_CreateVehicleRequest_WithExistingPA()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];

        Account pA = Test_DataFactory.createPA(true, 'Thieu', 'vupa123@test.com', 'Customer');

        Map<String, String> info = new Map<String, String>();
        info.put('Courtesy_Vehicle__c', vehList[0].Id);
        info.put('Test_Drive_Type__c', 'Test Drive');
        info.put('Trade_Plate__c', null);
        info.put('PersonMobilePhone', '6589563258');
        info.put('PersonEmail', 'vupa123@test.com');
        info.put('Full_Name__pc', 'Thieu Dang Vu');
        info.put('FirstName', 'Vu');
        info.put('LastName', 'Thieu');
        info.put('Status__c', 'Ongoing');
        info.put('Address_Line_1__pc', '#3-40');
        info.put('Address_Line_2__pc', 'abc bulding');
        info.put('Address_Line_3__pc', '123 Secret St');
        info.put('Customer_Signature__c', '');
        info.put('__matchPA', pA.Id);

        Map<String, String> frontLicense = new Map<String, String>();
        frontLicense.put('body', 'abc');
        frontLicense.put('contentType', 'image/jpeg');
        frontLicense.put('fileName', 'Front_License.jpeg');

        Map<String, String> backLicense = new Map<String, String>();
        backLicense.put('body', 'def');
        backLicense.put('contentType', 'image/jpeg');
        backLicense.put('fileName', 'Back_License.jpeg');

        MB_TestDriveController.createVehicleRequest(info, frontLicense, backLicense);
    }

    @isTest
    static void test_UpsertMBTDDailyLogs()
    {
        List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];
        MB_TestDriveController.upsertMBTDDailyLogs(new List<MB_Test_Drive_Daily_Log__c>{new MB_Test_Drive_Daily_Log__c(Status__c = 'Opened', Opening_Mileage__c = 1000, Courtesy_Vehicle__c = vehList[0].Id)});
    }

    @isTest
    static void test_constructTestDriveWrapper()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];

        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req1 = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Queued',
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP');
        insert req1;
        Vehicle_Request__c req2 = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Ongoing',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP');
        insert req2;
        MB_TestDriveController.constructTestDriveWrapper();
    }

    @isTest
    static void test_getTradePlates()
    {
        insert new Trade_Plate__c(Name = 'TESTPL',
                                 Active__c = true,
                                 Branch_Code__c = 'CCI');
        MB_TestDriveController.getTradePlates();
    }

    @isTest
    static void test_checkDailyLogExist()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];
        
        MB_Test_Drive_Daily_Log__c log = Test_DataFactory.createMBTestDriveDailyLog(true, 1000, null, 'Opened', vehList[0].Id);
		Boolean exist = MB_TestDriveController.checkDailyLogExist(vehList[0].Id);
        System.assertEquals(true, exist);
    }

    @isTest
    static void test_getProfile()
    {
        String profileNm = MB_TestDriveController.getProfile();
        System.assertEquals('System Administrator', profileNm);
    }

	@isTest
    static void test_searchPersonAccount()
    {
		Account acc = Test_DataFactory.createPA(true, 'Test', 'email_test@mail.com', 'Prospect');
		List<Account> accs = MB_TestDriveController.searchPersonAccount(null, 'email_test@mail.com', null);
        System.assertEquals(1, accs.size());
    }

    @isTest
    static void test_generateIndemnityForm()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];		
        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Ongoing',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP');
        insert req;
        MB_TestDriveController.generateIndemnityForm(req.Id);
    }

    @isTest
    static void test_getHistoryRequest()
    {
        List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];		
        
		Account acc = Test_DataFactory.createPA(true, 'Test', 'email_test@mail.com', 'Prospect');
        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Completed',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id);
        insert req;
        Test.startTest();
        List<Vehicle_Request__c> historyReqs = MB_TestDriveController.getHistoryRequest(vehList[0].Id, acc.Id);
        Test.stopTest();
        System.assertEquals(1, historyReqs.size());
    }

    @isTest
    static void test_processRequest_Check_Out()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];
		Account acc = Test_DataFactory.createPA(true, 'Test', 'email_test@mail.com', 'Prospect');
        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Queued',
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id);
        insert req;
        Test.startTest();
        MB_TestDriveController.processVehicleRequest('Check Out', req.Id);
        Test.stopTest();
    }

    @isTest
    static void test_processRequest_Check_In()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];
		Account acc = Test_DataFactory.createPA(true, 'Test', 'email_test@mail.com', 'Prospect');
        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Ongoing',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id);
        insert req;
        Test.startTest();
        MB_TestDriveController.processVehicleRequest('Check In', req.Id);
        Test.stopTest();
    }

    @isTest
    static void test_processRequest_Cancel()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];
		Account acc = Test_DataFactory.createPA(true, 'Test', 'email_test@mail.com', 'Prospect');
        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Queued',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id);
        insert req;
        Test.startTest();
        MB_TestDriveController.processVehicleRequest('Cancel', req.Id);
        Test.stopTest();
    }

    @isTest
    static void test_processRequest_Check_Out_Have_Ongoing_Req()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];        
		Account acc = Test_DataFactory.createPA(true, 'Test', 'email_test@mail.com', 'Prospect');
        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req1 = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Ongoing',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id);
        insert req1;
        Vehicle_Request__c req2 = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Queued',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id);
        insert req2;
        Test.startTest();
        try {
			MB_TestDriveController.processVehicleRequest('Check Out', req2.Id);
        } catch (Exception e) {
            System.assert(true, e.getMessage().contains('being checked-out'));
        }
        Test.stopTest();
    }

    @isTest
    static void test_processRequest_Check_Out_Not_In_Turn()
    {
		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];
		Account acc = Test_DataFactory.createPA(true, 'Test', 'email_test@mail.com', 'Prospect');
        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req1 = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Queued',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id);
        insert req1;
        Vehicle_Request__c req2 = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Queued',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id);
        insert req2;
        Test.startTest();
        try {
			MB_TestDriveController.processVehicleRequest('Check Out', req2.Id);
        } catch (Exception e) {
            System.assert(true, e.getMessage().contains('your turn to check-out!'));
        }
        Test.stopTest();
    }

    @isTest
    static void test_processRequest_Booking_TP_In_Used()
    {
        Trade_Plate__c tp =  new Trade_Plate__c(Name = 'TESTPL',
                                 				Active__c = true,
                                                Branch_Code__c = 'CCI');
        insert tp;

		List<Courtesy_Vehicle__c> vehList = [SELECT ID FROM Courtesy_Vehicle__c];        
		Account acc = Test_DataFactory.createPA(true, 'Test', 'email_test@mail.com', 'Prospect');
        String recordTypeId  = Schema.SObjectType.Vehicle_Request__c.getRecordTypeInfosByDeveloperName().get('MB_Test_Drive_Request').getRecordTypeId();
        Vehicle_Request__c req1 = new Vehicle_Request__c(Courtesy_Vehicle__c = vehList[0].Id,
                                                         Status__c = 'Ongoing',
                                                         Check_Out__c = DateTime.now(),
                                                         RecordTypeId = recordTypeId,
                                                         Test_Drive_Type__c = 'Test Drive',
                                                         Branch_Code__c = 'CCI',
                                                         Franchise_Code__c = 'MBP',
                                                       	 Account__c = acc.Id,
                                                         Trade_Plate__c = tp.Id);
        insert req1;
        Map<String, String> info = new Map<String, String>();
        info.put('Courtesy_Vehicle__c', vehList[1].Id);
        info.put('Test_Drive_Type__c', 'Loan');
        info.put('Trade_Plate__c', tp.Id);
        info.put('PersonMobilePhone', '6589563257');
        info.put('PersonEmail', 'vupa984594@test.com');
        info.put('Full_Name__pc', 'Thieu Dang Vu');
        info.put('FirstName', 'Vu');
        info.put('LastName', 'Thieu');
        info.put('Status__c', 'Ongoing');
        info.put('Address_Line_1__pc', '#3-40');
        info.put('Address_Line_2__pc', 'abc bulding');
        info.put('Address_Line_3__pc', '123 Secret St');
        info.put('Customer_Signature__c', '');

        TriggerExclusion.excludeTrigger('Vehicle_Request__c', true);
        try {
			MB_TestDriveController.createVehicleRequest(info, null, null);
        } catch (Exception e) {
            System.assert(true, e.getMessage().contains('Trade Plate has been used'));
        }
        TriggerExclusion.excludeTrigger('Vehicle_Request__c', false);
    }
}