force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Model__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model__c/fields/DWH_Model_ID__c.field-meta.xml
<CustomField>
    <fullName>DWH_Model_ID__c</fullName>
    <externalId>true</externalId>
    <label>DWH Model ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Model__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showroom__c/Showroom__c.object-meta.xml
<CustomObject>
    <label>Showroom</label>
    <nameField>
        <label>Showroom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showrooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Showroom__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Variant__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>Franchise__c</fullName>
    <label>Franchise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Model_ID__c.field-meta.xml
<CustomField>
    <fullName>Model_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model_ID</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>Vehicle Master</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Vehicle Masters</relationshipLabel>
    <relationshipName>Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master__c/fields/Showroom__c.field-meta.xml
<CustomField>
    <fullName>Showroom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom</label>
    <referenceTo>Showroom__c</referenceTo>
    <relationshipLabel>Vehicle Masters</relationshipLabel>
    <relationshipName>Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Vehicle Masters</relationshipLabel>
    <relationshipName>Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_ModelVarient_Showroom_Holiday.cls
@isTest(seeAllData=true)
public class Test_ModelVarient_Showroom_Holiday {
Public static testMethod void testGetData()
    {
        Test.startTest();
        Model__c TestMod =  new Model__c(Name='TestMod',Branch_Code__c='CCK',Franchise_Code__c='KIAPC',DWH_Model_ID__c='abc12345');
        insert TestMod;
        Variant__c TestVar =  new Variant__c(Name='TestVar',Branch__c='CCK',Franchise__c='KIAPC',Model_ID__c=TestMod.Id);
        insert TestVar;
        Showroom__c TestShow =  new Showroom__c(Name='TestShow',City__c='SG',Country__c='SG',Address_Line_1__c='TestAdd');
        insert TestShow;
        Vehicle_Master__c TestVm =  new Vehicle_Master__c(Name='TestVM',Model__c=TestMod.Id,Variant__c=TestVar.Id,Showroom__c=TestShow.Id);
        insert TestVm;
        /*Event TestEvent =  new Event(Type='ShowroomHoliday',WhatId=TestShow.Id);
        insert TestEvent;*/
 
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri ='services/apexrest/ShowroomHoliday/v1/';
        request.httpMethod = 'POST';
        RestContext.request = request;
        RestContext.response = response ;
        
        ModelVarient_Showroom_Holiday_Selector.getShowroombyVarient(TestVar.Id,'','SG','SG');
        ModelVarient_Showroom_Holiday_Selector.getShowroombyVarient('',TestMod.Id,'SG','SG');
        Test.stopTest();
    }
    
    Public static testMethod void testErrorData()
    {
        Test.startTest();             
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri ='services/apexrest/ShowroomHoliday/v1/';
        request.httpMethod = 'POST';
        RestContext.request = request;
        RestContext.response = response ;
        
        ModelVarient_Showroom_Holiday_Selector.getShowroombyVarient('','','SG','SG');
        Test.stopTest();
    }
    
    Public static testMethod void testNoData()
    {
        Test.startTest();              
        
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri ='services/apexrest/ShowroomHoliday/v1/';
        request.httpMethod = 'POST';
        RestContext.request = request;
        RestContext.response = response ;
        
        ModelVarient_Showroom_Holiday_Selector.getShowroombyVarient('abc','abc','SG','SG');
        Test.stopTest();
    }
    
}