force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Model__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/Shipment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Shipment Line Item</label>
    <nameField>
        <displayFormat>SLI-{YYYYMM}-{00000}</displayFormat>
        <label>Shipment Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Chassis No.</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Colour_Code__c.field-meta.xml
<CustomField>
    <fullName>Colour_Code__c</fullName>
    <label>Colour Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Engine No.</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Franchise_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Manufacturer_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Ref_No__c</fullName>
    <description>For CIT</description>
    <label>Manufacturer Ref. No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Model_Year__c</fullName>
    <label>Model Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Production_Month__c.field-meta.xml
<CustomField>
    <fullName>Production_Month__c</fullName>
    <label>Production Month</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Trim__c.field-meta.xml
<CustomField>
    <fullName>Trim__c</fullName>
    <label>Trim</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Vehicle_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Shipment__c</fullName>
    <label>Vehicle Shipment</label>
    <referenceTo>Vehicle_Shipment__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/fields/Chassis__c.field-meta.xml
<CustomField>
    <fullName>Chassis__c</fullName>
    <label>Chassis</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No.</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Manufacturer_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Ref_No__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Manufacturer Ref. No.</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Code</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Year_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Year_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Year Code</label>
    <referenceTo>Model_Year_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Production_Month__c.field-meta.xml
<CustomField>
    <fullName>Production_Month__c</fullName>
    <label>Production Month</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/ProductionMonth__c.field-meta.xml
<CustomField>
    <fullName>ProductionMonth__c</fullName>
    <label>Production Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Shipment_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment Line Item</label>
    <referenceTo>Shipment_Line_Item__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Vehicle_Purchase_Status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Purchase_Status__c</fullName>
    <label>Vehicle Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
                <default>true</default>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>In Shipment</fullName>
            </value>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>SCL_Cancel</fullName>
                <label>SCL (Cancel)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Vehicle_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Shipment</label>
    <referenceTo>Vehicle_Shipment__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Status__c</fullName>
    <label>Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FREE</fullName>
                <default>true</default>
                <label>FREE</label>
            </value>
            <value>
                <fullName>ORD</fullName>
            </value>
            <value>
                <fullName>SCL</fullName>
            </value>
            <value>
                <fullName>RESRV</fullName>
            </value>
            <value>
                <fullName>ALLOC</fullName>
            </value>
            <value>
                <fullName>SOLD</fullName>
            </value>
            <value>
                <fullName>CONF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Shipment__c/Vehicle_Shipment__c.object-meta.xml
<CustomObject>
    <label>Vehicle Shipment</label>
    <nameField>
        <displayFormat>Ship-{YYYYMM}-{00000}</displayFormat>
        <label>Vehicle Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Shipment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Document Uploaded</fullName>
            </value>
            <value>
                <fullName>Partially_Matched</fullName>
                <label>Partially Matched</label>
            </value>
            <value>
                <fullName>Matching_Completed</fullName>
                <label>Matching Completed</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Franchise_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CITCV</fullName>
    </customValue>
    <customValue>
        <fullName>CITPC</fullName>
    </customValue>
    <customValue>
        <fullName>KIACV</fullName>
    </customValue>
    <customValue>
        <fullName>KIAPC</fullName>
    </customValue>
    <customValue>
        <fullName>MITCV</fullName>
    </customValue>
    <customValue>
        <fullName>MITPC</fullName>
    </customValue>
    <customValue>
        <fullName>MBCV</fullName>
    </customValue>
    <customValue>
        <fullName>MBPC</fullName>
    </customValue>
    <masterLabel>Franchise Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ShipmentLineItemsMatchingController.cls
/*==========================================================================================================================================================================
 * Controller class for Shipment Matching component
 * Created By: Aodigy Team
 * Create Date: Aug 2022
 * History
 *          DATE::                              BY::                                TICKET::                                            CHANGELOG
 *          18 Aug 2022                         dangphap.mai@aodigy.com             US-Ship-000008                                      init
 *          13 Oct 2022                         dangphap.mai@aodigy.com             LOG-0018                                            added shipmentUnmatchingById
 * ========================================================================================================================================================================== 
 */
public with sharing class ShipmentLineItemsMatchingController
{
    /**
     * ============================================================================================
     * Get vehicle shipment details on component init
     * @param shipmentIds: target vehicle shipment ids
     * History
     *          DATE::                              BY::                                CHANGELOG
     *          18 Aug 2022                         dangphap.mai@aodigy.com             init
     * ============================================================================================
     */
    @AuraEnabled(cacheable=true)
    public static VehicleShipmentDetail init(String vehicleShipmentId)
    {
        try
        {
            VehicleShipmentDetail result = new VehicleShipmentDetail();

            Vehicle_Shipment__c shipment = [SELECT Id, Name, Franchise_Code__c, Stage__c FROM Vehicle_Shipment__c WHERE Id = :vehicleShipmentId];

            List<Shipment_Line_Item__c> shipmentLineItems= [SELECT  Name, Model__c, Model_Year__c, Colour_Code__c, Trim__c, Engine_No__c, Chassis_No__c, 
                                                                    Franchise_Code__c, Manufacturer_Ref_No__c, Production_Month__c
                                                            FROM Shipment_Line_Item__c
                                                            WHERE Vehicle_Shipment__c = :shipment.Id
                                                            ORDER BY CreatedDate ASC
                                                            ];
            //
            List<Vehicle_Master2__c> shipmentMatchedStocks = [ SELECT   Name, Model_Code__c, Model_Year_Code__c, Color_Description__c, Trim_Description__c,
                                                                        Engine_No__c, Chassis__c, Franchise_Code__c, Manufacturer_Ref_No__c, ProductionMonth__c, 
                                                                        Shipment_Line_Item__c, Vehicle_Status__c, Vehicle_Purchase_Status__c
                                                                FROM Vehicle_Master2__c
                                                                WHERE Shipment_Line_Item__r.Vehicle_Shipment__c = :shipment.Id
                                                            ];
            //
            result.shipment                 = shipment;
            result.shipmentLineItems        = shipmentLineItems;
            result.shipmentMatchedStocks    = shipmentMatchedStocks;

            return result;
        }
        catch(Exception e)
        {
            System.debug('ShipmentLineItemsMatchingController :: init :: Exception Message > ' + e.getMessage());
            System.debug('ShipmentLineItemsMatchingController :: init :: Exception Stack Trace > ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
        
    }

    /**
     * ============================================================================================
     * Manual match shipment line item and stock vehicle master by Id
     * @param shipmentLineItemId: shipment line item id for matching
     * @param stockVehicleMasterId: stock vehicle master id for matching
     * History
     *          DATE::                              BY::                                CHANGELOG
     *          18 Aug 2022                         dangphap.mai@aodigy.com             init
     * ============================================================================================
     */
    @AuraEnabled
    public static void shipmentManualMatchById(String shipmentLineItemId, String stockVehicleMasterId)
    {
        try
        {
            VehicleShipmentServices.shipmentManualMatchById(shipmentLineItemId, stockVehicleMasterId);
        }
        catch (Exception e)
        {
            System.debug('ShipmentLineItemsMatchingController :: shipmentManualMatchById :: Exception Message > ' + e.getMessage());
            System.debug('ShipmentLineItemsMatchingController :: shipmentManualMatchById :: Exception Stack Trace > ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * ============================================================================================
     * Unmatch a shipment line item from stock vehicle master and revert the post matching logic
     * @param shipmentLineItemId: shipment line item id for unmatching
     * @param stockVehicleMasterId: stockv vehicle id for unmatching
     * History
     *          DATE::                              BY::                                CHANGELOG
     *          13 Oct 2022                         dangphap.mai@aodigy.com             init
     * ============================================================================================
     */
    @AuraEnabled
    public static void shipmentUnmatchingById(String shipmentLineItemId, String stockVehicleMasterId)
    {
        try
        {
            VehicleShipmentServices.shipmentUnmatchingById(shipmentLineItemId, stockVehicleMasterId);
        }
        catch (Exception e)
        {
            System.debug('ShipmentLineItemsMatchingController :: shipmentUnmatchingById :: Exception Message > ' + e.getMessage());
            System.debug('ShipmentLineItemsMatchingController :: shipmentUnmatchingById :: Exception Stack Trace > ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * ============================================================================================
     * Auto match shipment line items
     * @param vehicleShipmentId: shipment id to match
     * History
     *          DATE::                              BY::                                CHANGELOG
     *          18 Aug 2022                         dangphap.mai@aodigy.com             init
     * ============================================================================================
     */
    @AuraEnabled
    public static String shipmentsAutoMatching(String vehicleShipmentId)
    {
        try
        {
            return VehicleShipmentServices.shipmentsAutoMatching(new Set<String> { vehicleShipmentId });
        }
        catch (Exception e)
        {
            System.debug('ShipmentLineItemsMatchingController :: shipmentsAutoMatching :: Exception Message > ' + e.getMessage());
            System.debug('ShipmentLineItemsMatchingController :: shipmentsAutoMatching :: Exception Stack Trace > ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class VehicleShipmentDetail
    {
        @AuraEnabled
        public Vehicle_Shipment__c shipment;

        @AuraEnabled
        public List<Shipment_Line_Item__c> shipmentLineItems = new List<Shipment_Line_Item__c>();

        @AuraEnabled
        public List<Vehicle_Master2__c> shipmentMatchedStocks = new List<Vehicle_Master2__c>();
    }
}