force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Alert_Subscription__c/Model_Alert_Subscription__c.object-meta.xml
<CustomObject>
    <description>Model Alert Subscription Transaction Data for Republic Auto</description>
    <label>Model Alert Subscription</label>
    <nameField>
        <displayFormat>MAS-{00000000}</displayFormat>
        <label>Model Subscribed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Model Alert Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Alert_Subscription__c/fields/Subscription_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Expiry_Date__c</fullName>
    <label>Subscription Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Model_Alert_Subscription__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Unsubscribed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Subscribed__c/Model_Subscribed__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Model Subscribed Transaction Data for the Used Car</description>
    <label>Model Subscribed</label>
    <nameField>
        <displayFormat>MS-{0000000}</displayFormat>
        <label>Model_Subscribed_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Model Subscribed</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Subscribed__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <description>Brand</description>
    <label>Make</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Model_Subscribed__c/fields/Model_Alert_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Model_Alert_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model Alert Subscription</label>
    <referenceTo>Model_Alert_Subscription__c</referenceTo>
    <relationshipLabel>Model Subscribed</relationshipLabel>
    <relationshipName>Model_Subscribed</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Subscribed__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <formula>TEXT(Model_Alert_Subscription__r.Subscription_Status__c)</formula>
    <label>Subscription Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Model_Subscribed_Staging__c/Model_Subscribed_Staging__c.object-meta.xml
<CustomObject>
    <description>Junction object of Used Car Vehicle Stock &amp; Model Subscribed</description>
    <label>Model Subscribed Staging</label>
    <nameField>
        <displayFormat>MSS-{0000000}</displayFormat>
        <label>Model Subscribed Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Model Subscribed Staging</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Subscribed_Staging__c/fields/Model_Subscribed__c.field-meta.xml
<CustomField>
    <fullName>Model_Subscribed__c</fullName>
    <label>Model Subscribed</label>
    <referenceTo>Model_Subscribed__c</referenceTo>
    <relationshipLabel>Model Subscribed Staging</relationshipLabel>
    <relationshipName>Model_Subscribed_Staging</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Subscribed_Staging__c/fields/Used_Car_Vehicle_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Car_Vehicle_Stock__c</fullName>
    <label>Used Car Vehicle Stock</label>
    <referenceTo>Used_Car_Vehicle_Stock__c</referenceTo>
    <relationshipLabel>Model Subscribed Staging</relationshipLabel>
    <relationshipName>Model_Subscribed_Staging</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Model_Subscribed_Staging__c/recordTypes/RA_Model_Subscribed_Staging_RT.recordType-meta.xml
<RecordType>
    <fullName>RA_Model_Subscribed_Staging_RT</fullName>
    <active>true</active>
    <label>RA Model Subscribed Staging RT</label>
</RecordType>

cncProd/force-app/main/default/objects/Used_Car_Vehicle_Stock__c/Used_Car_Vehicle_Stock__c.object-meta.xml
<CustomObject>
    <description>Vehicle Stock Master for Republic Auto (RA) Used Car</description>
    <label>Used Car Vehicle Stock</label>
    <nameField>
        <displayFormat>UCVS-{0000000}</displayFormat>
        <label>Used Car Vehicle Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Used Car Vehicle Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Used_Car_Vehicle_Stock__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <description>Brand</description>
    <inlineHelpText>Brand</inlineHelpText>
    <label>Make</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Vehicle_Stock__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Vehicle_Stock__c/fields/Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Status__c</fullName>
    <label>Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RA_Vehicle_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RA_Vehicle_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Booked</fullName>
    </customValue>
    <customValue>
        <fullName>Sold</fullName>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <default>true</default>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Damaged</fullName>
        <isActive>false</isActive>
        <label>Damaged</label>
    </customValue>
    <description>RA - Vehicle Status</description>
    <masterLabel>RA-Vehicle Status</masterLabel>
</GlobalValueSet>

cncProd/force-app/main/default/classes/RA_UpdateModelAlertBatch.cls
/** *****
* Description : Daily Batch for Updating RA Used Car Model Alert and Insert Model modelSubscr Staging
*
* Change History
* Date(YYYYMMDD)        Name                         Description
* 20210316              khanh.do@aodigy.com          Created Initial Version.
*
** *****/
global with sharing class RA_UpdateModelAlertBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    
    private List<String> errMsgs = new List<String>();
    private Set<Id> setModelAlertSubIds = new Set<Id>();
    private Set<Id> setModelSubcribedIds = new Set<Id>();
    private String strRelativeDate = 'YESTERDAY';

    public void execute(SchedulableContext ctx)
    {
        Database.executebatch(new RA_UpdateModelAlertBatch(), 200);
    }

    public RA_UpdateModelAlertBatch() { }

    public RA_UpdateModelAlertBatch( Set<Id> setModelAlertSubIds, Set<Id> setModelSubcribedIds, String strRelativeDate )
    {
        this.setModelAlertSubIds = setModelAlertSubIds;
        this.setModelSubcribedIds = setModelSubcribedIds;
        this.strRelativeDate = String.isNotBlank(strRelativeDate) ? strRelativeDate : this.strRelativeDate;
    }

    global Iterable<sObject> start(Database.Batchablecontext BC)
    {
        String queryString =  ' SELECT Id, Make__c, Model_Name__c, Model_Alert_Subscription__c, Model_Alert_Subscription__r.Subscription_Expiry_Date__c '
                              + ' FROM Model_Subscribed__c'
                              + ' WHERE Model_Alert_Subscription__r.Subscription_Status__c = \'Open\'' ;


        if( setModelSubcribedIds <> null && !setModelSubcribedIds.isEmpty() ) {
            queryString += ' AND ID IN :setModelSubcribedIds ';
        }
        else if( setModelAlertSubIds <> null && !setModelAlertSubIds.isEmpty() ) {
            queryString += ' AND Model_Alert_Subscription__c IN : setModelAlertSubIds ';
        }
        queryString += ' ORDER BY Model_Alert_Subscription__c ';

        System.debug('@@@ DEBUG ==== RA_UpdateModelAlertBatch.start() queryString = ' + queryString);
        return Database.getQueryLocator( queryString );
    }

    global void execute(Database.BatchableContext BC, List<Model_Subscribed__c> scope)
    {
        try 
        {
            System.debug('@@@ DEBUG ==== RA_UpdateModelAlertBatch.execute() scope = ' + scope.size() + ' --- ' + scope );
            if(scope.size() > 0) 
            {
                ADGLIB_SObjectUnitOfWork uow = new ADGLIB_SObjectUnitOfWork(new Schema.SObjectType[]{ Model_Alert_Subscription__c.SObjectType, Model_Subscribed_Staging__c.SObjectType } );
                List<Model_Alert_Subscription__c> lstExpiredModelAlertSubs = new List<Model_Alert_Subscription__c>();
                List<Model_Subscribed_Staging__c> lstStagingsToInsert = new List<Model_Subscribed_Staging__c>();
                Set<String> makes = new Set<String>();
                Set<String> models = new Set<String>();
                Set<String> makeAndModelKeys = new Set<String>();

                Map<String, List<Model_Subscribed__c>> mapModelSubscribed = new Map<String, List<Model_Subscribed__c>>();

                for(Model_Subscribed__c modelSubscr: scope) 
                {
                    if( modelSubscr.Model_Alert_Subscription__r.Subscription_Expiry_Date__c <= Date.today() ) {
                        lstExpiredModelAlertSubs.add( 
                            new Model_Alert_Subscription__c( Id = modelSubscr.Model_Alert_Subscription__c , Subscription_Status__c = 'Completed' ) 
                        );
                    }
                    else {
                        makes.add(modelSubscr.Make__c);           //Used for Query VehicleStock
                        models.add(modelSubscr.Model_Name__c);    //Used for Query VehicleStock

                        String key = modelSubscr.Make__c + '||' + modelSubscr.Model_Name__c;
                        makeAndModelKeys.add(key);
                        if( !mapModelSubscribed.containsKey(key) ) {
                            mapModelSubscribed.put( key, new List<Model_Subscribed__c>{modelSubscr} );
                        } 
                        else {
                            mapModelSubscribed.get(key).add( modelSubscr );
                        }
                    }
                }
                System.debug('@@@ DEBUG ==== RA_UpdateModelAlertBatch.execute() makeAndModelKeys : ' + makeAndModelKeys.size() + ' === ' + makeAndModelKeys);
                System.debug('@@@ DEBUG ==== RA_UpdateModelAlertBatch.execute() mapModelSubscribed : ' + mapModelSubscribed.size() + ' === ' + mapModelSubscribed);

                if( mapModelSubscribed.size() > 0) 
                {

                    Map<String, List<Used_Car_Vehicle_Stock__c>> mapVehicleStock = new Map<String, List<Used_Car_Vehicle_Stock__c>>();

                    String strUCVS_SOQL = ' SELECT Id, Make__c, Model__c '+
                                          ' FROM Used_Car_Vehicle_Stock__c '+
                                          ' WHERE CreatedDate = ' + strRelativeDate +
                                          ' AND Vehicle_Status__c = \'Open\' '+
                                          ' AND Make__c IN :makes '+
                                          ' AND Model__c IN :models ';
                    for(Used_Car_Vehicle_Stock__c vehicle: Database.query( strUCVS_SOQL ) ) 
                    {
                        String key = vehicle.Make__c + '||' + vehicle.Model__c;
                        if( makeAndModelKeys.contains(key) ) {
                            if( !mapVehicleStock.containsKey(key) ) {
                                mapVehicleStock.put(key, new List<Used_Car_Vehicle_Stock__c>{vehicle});
                            } 
                            else {
                                mapVehicleStock.get( key ).add( vehicle );
                            }
                        }                
                    }
                    System.debug('@@@ DEBUG ==== RA_UpdateModelAlertBatch.execute() mapVehicleStock = ' + mapVehicleStock.size() + ' === ' + mapVehicleStock);


                    if( mapVehicleStock.size() > 0 ) {
                        Id raStagingTypeId = Schema.SObjectType.Model_Subscribed_Staging__c.getRecordTypeInfosByDeveloperName().get('RA_Model_Subscribed_Staging_RT').getRecordTypeId();
                        
                        for(String key: makeAndModelKeys) {
                            if( mapModelSubscribed.containsKey(key) && mapVehicleStock.containsKey(key) ) {

                                for(Used_Car_Vehicle_Stock__c vehicleStock: mapVehicleStock.get(key) ) {
                                    for(Model_Subscribed__c modelSubscribed: mapModelSubscribed.get(key) ) {
                                        Model_Subscribed_Staging__c newStaging = new Model_Subscribed_Staging__c();
                                        newStaging.RecordTypeId                = raStagingTypeId;
                                        newStaging.Used_Car_Vehicle_Stock__c   = vehicleStock.Id;
                                        newStaging.Model_Subscribed__c         = modelSubscribed.Id;
                                        lstStagingsToInsert.add(newStaging);
                                    }                                
                                }
                            }                            
                        }

                    }
                } 
                else {
                    System.debug('@@@ No Vehicle Stock found');
                }
                

                System.debug('@@@ DEBUG ==== RA_UpdateModelAlertBatch.execute() lstExpiredModelAlertSubs = ' + lstExpiredModelAlertSubs.size() + ' === ' + lstExpiredModelAlertSubs);
                System.debug('@@@ DEBUG ==== RA_UpdateModelAlertBatch.execute() stagingsToInsert = ' + lstStagingsToInsert.size() + ' === ' + lstStagingsToInsert);

                if( !lstExpiredModelAlertSubs.isEmpty() ) {
                    uow.registerDirty( lstExpiredModelAlertSubs );    
                }
                
                if( !lstStagingsToInsert.isEmpty() ){
                    uow.registerNew( lstStagingsToInsert );
                }
                uow.commitWork();
                
            } 
            else {
                System.debug('@@@ No Model_Subscribed__c found');
            }
            

        }  
        catch (Exception ex) {
            System.debug('@@@ Exception ex: ' + ex.getCause() + ' -- ' + ex.getMessage() + ' -- At line: #' + ex.getLineNumber() );
            errMsgs.add( ex.getCause() + ' -- ' + ex.getMessage() + ' -- At line: #' + ex.getLineNumber() );
            loggerDataPool.buildLogDataPool('RA_UpdateModelAlertBatch', ex);
        }
    }

    global void finish(Database.BatchableContext bc)
    {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        //String[] toAddresses = new String[] {'khanh.do@aodigy.com'};
        //mail.setToAddresses( toAddresses );
        mail.setTargetObjectId( UserInfo.getUserId() );
        mail.saveAsActivity = false;
        String body;
        if(!errMsgs.isEmpty()){
            for(Integer i = 0; i < errMsgs.size(); i++){
                body += (String.valueof(i+1)+' '+errMsgs[i]+ '\r\n');
            }
        }
        else{
            body = 'RA_UpdateModelAlertBatch Processed Successfully !!!';
        }
        mail.setPlainTextBody(body);
        //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }

}