force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>Vehicle Master</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Vehicle Masters</relationshipLabel>
    <relationshipName>Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Vehicle Masters</relationshipLabel>
    <relationshipName>Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/classes/vehiSetBranchNFranchiseCodeTest.cls
@isTest
private class vehiSetBranchNFranchiseCodeTest {
    
    @isTest
    private static void testBypassTrigger() {
        TriggerExclusion.excludeTrigger('Vehicle_Master__c', true);
        Model__c TestMod = Test_DataFactory.createmodelId(true,'testRun','CCA','MITPC');        
        Variant__c TestVar = Test_DataFactory.createVariant(true,'testRun',TestMod.Id,'CCA'); 
        Vehicle_Master__c testVh = Test_DataFactory.createVehicleMaster(true,'test123',TestVar.id,TestMod.id);
    } 
    
	@isTest
    private static void testOnInsert() {
        Model__c TestMod = Test_DataFactory.createmodelId(true,'testRun','CCA','MITPC');        
        Variant__c TestVar = Test_DataFactory.createVariant(true,'testRun',TestMod.Id,'CCA'); 
        Vehicle_Master__c testVh = Test_DataFactory.createVehicleMaster(true,'test123',TestVar.id,TestMod.id);
    }
}