cncProd/force-app/main/default/objects/MB_Stock_Vehicle_Master__c/MB_Stock_Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>MB Stock Vehicle Master</label>
    <nameField>
        <displayFormat>MBSVM-{000000}</displayFormat>
        <label>MB Stock Vehicle Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Stock Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Warehouse_Parking_Lot__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Parking_Lot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Parking Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Warehouse_Parking_Lot__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Warehouse_Parking_Lot__c</referenceTo>
    <relationshipLabel>MB Stock Vehicle Masters</relationshipLabel>
    <relationshipName>MB_Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Warehouse_Parking_Lot__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Parking_Lot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Parking Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Warehouse_Parking_Lot__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Warehouse_Parking_Lot__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Parking_Lot__c/Warehouse_Parking_Lot__c.object-meta.xml
<CustomObject>
    <label>Warehouse Parking Lot</label>
    <nameField>
        <label>Warehouse Parking Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Parking Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/classes/WHParkingLotService.cls
public with sharing class WHParkingLotService {
    /**
     * This method to check duplicate Warehouse Parking Lot
     * If any Warehouse Parking Lot already has MB Stock Vehicle Master/Stock Vehicle Master
     * Then no other Stock Vehicle Masters can be assigned to that Warehouse Parking Lot
     */
    public static void checkDuplicateWHParkingLot(Map<String, MB_Stock_Vehicle_Master__c> mbSVMByWHParkingLotIds, Map<String, Vehicle_Master2__c> mfSVMByWHParkingLotIds) {
        List<String> whParkingLotIds = new List<String>();
        if (mbSVMByWHParkingLotIds != null) whParkingLotIds.addAll(mbSVMByWHParkingLotIds.keySet());
        if (mfSVMByWHParkingLotIds != null) whParkingLotIds.addAll(mfSVMByWHParkingLotIds.keySet());
        List<Warehouse_Parking_Lot__c> records = [SELECT Id,
                                                  (SELECT Id FROM MB_Stock_Vehicle_Masters__r),
                                                  (SELECT Id FROM Stock_Vehicle_Masters__r)
                                                  FROM Warehouse_Parking_Lot__c
                                                  WHERE Id IN :whParkingLotIds];

        String errorMsg = 'Another Stock Vehicle Master has been assigned to this Warehouse Parking Lot. Please check again!';
        for (Warehouse_Parking_Lot__c whParkingLot : records) {
            Boolean isErrorRecord = false;
            if (whParkingLot.MB_Stock_Vehicle_Masters__r != null && whParkingLot.MB_Stock_Vehicle_Masters__r.size() > 0) {
                isErrorRecord = true;
            } else if (whParkingLot.Stock_Vehicle_Masters__r != null && whParkingLot.Stock_Vehicle_Masters__r.size() > 0) {
                isErrorRecord = true;
            }
            if (isErrorRecord) {
                if (mbSVMByWHParkingLotIds != null) {
                    MB_Stock_Vehicle_Master__c mbSVM = mbSVMByWHParkingLotIds.get(whParkingLot.Id);
                    mbSVM.addError(errorMsg);
                } else if (mfSVMByWHParkingLotIds != null) {
                    Vehicle_Master2__c svm = mfSVMByWHParkingLotIds.get(whParkingLot.Id);
                    svm.addError(errorMsg);
                }
            }
        }
    }
}