force-app/main/default/objects/File_Requirements__mdt/File_Requirements__mdt.object-meta.xml
<CustomObject>
    <label>File Requirements</label>
    <pluralLabel>File Requirements</pluralLabel>
</CustomObject>

force-app/main/default/objects/File_Requirements__mdt/fields/Condition_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Condition_Field_API_Name__c</fullName>
    <description>If value of this field is true, file upload component will appear on record page</description>
    <inlineHelpText>If value of this field is true, file upload component will appear on record page</inlineHelpText>
    <label>Condition Field API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/FileRequirementsServiceTest.cls
@isTest
private class FileRequirementsServiceTest {

    @TestSetup
    static void setUp(){
        Account acc = Test_DataFactory.createAccount(true, 'test');
    }	    
    
    @isTest
    static void Test_getConditionalFileRequirements() {
        FileRequirementsService.mockFileRequirements = new List<File_Requirements__mdt>{
            new File_Requirements__mdt(
                Condition_Field_API_Name__c = 'PersonDoNotCall'
            )
        };
            
		FileRequirementsService.getConditionalFileRequirements([Select Id, PersonDoNotCall From Account].Id);		            
    }
    
}