force-app/main/default/objects/Branch_Code_Name_Mapping__c/Branch_Code_Name_Mapping__c.object-meta.xml
<CustomObject>
    <label>Branch Code Name Mapping</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Code Name Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch_Code_Name_Mapping__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Branch_Code_Name_Mapping__c/fields/CV_Code__c.field-meta.xml
<CustomField>
    <fullName>CV_Code__c</fullName>
    <description>Commercial Vehicle Code</description>
    <label>CV Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch_Code_Name_Mapping__c/fields/PC_Code__c.field-meta.xml
<CustomField>
    <fullName>PC_Code__c</fullName>
    <label>PC Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/GetBranchCodeNameMapping.cls
//Apex class to Get All models
@RestResource(urlMapping='/GetBranchCodeNameMapping/v1/*')
global with sharing class GetBranchCodeNameMapping {
@HttpGet
//CallOut method for Expose API
global static void getBranchCodeNameMapping() 
{   
    //Get Country from request URL
    RestRequest request = RestContext.request;
    String errorMsg='';
    List<SObject>  returnObject = new List<SObject>();
    RestResponse res = RestContext.response;
        try
        {
              
            returnObject=[SELECT Name, Branch_Code__c, CV_Code__c, PC_Code__c from Branch_Code_Name_Mapping__c];
            res.statusCode = 200; 
        }
        //Catch the error If any
        catch (DmlException e)
        { 
            
            res = RestContext.response;
            res.statusCode=400;
            throw e;
        }
    
    
     //Return List of Models 
     RestContext.response = res;
        res.addHeader('Content-Type', 'application/json');
        res.responseBody = Blob.valueOf(JSON.serialize(returnObject));
        res.statusCode = 200;
  
}
}