cncProd/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>Customer&apos;s Reward Credit 
- per Reward Type
- per Registered Vehicle
- per Expiry Date</description>
    <label>Reward</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Reward__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/fields/Expiry__c.field-meta.xml
<CustomField>
    <fullName>Expiry__c</fullName>
    <label>Expiry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Reward_Profile__c.field-meta.xml
<CustomField>
    <fullName>Reward_Profile__c</fullName>
    <label>Reward Profile</label>
    <referenceTo>Reward_Profile__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Provisioning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/Reward_Profile__c.object-meta.xml
<CustomObject>
    <label>Reward Profile</label>
    <nameField>
        <label>Reward Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_Profile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Boutique</fullName>
            </value>
            <value>
                <fullName>Birthday Voucher</fullName>
            </value>
            <value>
                <fullName>Grooming Package</fullName>
            </value>
            <value>
                <fullName>Service Credit Voucher</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>Discount Voucher</fullName>
            </value>
            <value>
                <fullName>Service Credit</fullName>
            </value>
            <value>
                <fullName>Accessories Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Business Account (Staff, Leasing), Person Account</description>
    <label>C&amp;C Fleet</label>
</RecordType>

cncProd/force-app/main/default/objects/Reward_Usage__c/Reward_Usage__c.object-meta.xml
<CustomObject>
    <label>Reward Usage</label>
    <nameField>
        <label>Reward Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward_Usage__c.field-meta.xml
<CustomField>
    <fullName>Reward_Usage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Reference to Debit Reward Usage record</description>
    <label>Reward Usage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Reward_Usage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Debit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Reward_Usage__c</referenceTo>
    <relationshipLabel>Credit Usages</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expired</fullName>
                <color>#BBBBBB</color>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Hold</fullName>
                <color>#FFFF66</color>
                <label>Hold</label>
            </value>
            <value>
                <fullName>Issued</fullName>
                <color>#57F17C</color>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Provisioning</fullName>
                <color>#FFFF66</color>
                <label>Provisioning</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#BBBBBB</color>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Utilised</fullName>
                <color>#FF0000</color>
                <label>Utilised</label>
            </value>
            <value>
                <fullName>Write-Back</fullName>
                <color>#6666CC</color>
                <label>Write-Back</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Expiry</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Credit to Customer (i.e. Refund/Adjustment/etc.)</description>
    <label>Credit</label>
</RecordType>

force-app/main/default/classes/CMBatchUpdateRewardStatusTest.cls
/** ******
 * Description : Test Class for CMBatchUpdateRewardStatus.cls and CMBatchUpdateRewardStatusSchedule
 *  
 * Change History:
 * Date(YYYYMMDD)       Name                                Description
 * 20200708             khanh.do@aodigy.com                  Created Initial Version. 
 * 
***** **/
@isTest
private class CMBatchUpdateRewardStatusTest {

    static Date expiryDate = Date.today().addDays(-30);
    static Integer noExpiredRecord = 20;

    @testSetup
    private static void setup() {
        Reward_Profile__c rewardProfile = Test_DataFactory.createRewardProfile(true, 'Fleet', 'CCK', 'KIA', 'Accessories Credit');
        List<Reward__c> rewards = new List<Reward__c>();
        for(Integer i = 0; i < noExpiredRecord; i++) {
            Reward__c reward = Test_DataFactory.createReward(false, rewardProfile.Id, rewardProfile.Type__c, 'Valid', expiryDate);
        	reward.Credit__c = 20000;
            rewards.add(reward);
        }        
        insert rewards;
    }
    
    @isTest
    private static void testCMBatchUpdateRewardStatus_noSpecifyRecordId_UpdateAllExpiredRecords() {
        System.Test.startTest();
            Database.executeBatch(new CMBatchUpdateRewardStatus());
        System.Test.stopTest();
        List<Reward__c> updatedRewards = [SELECT Id, Status__c, Expiry__c FROM Reward__c WHERE Expiry__c = :expiryDate AND Status__c = 'Expired'];
        List<Reward_Usage__c> createdRewardUsages = [SELECT Id FROM Reward_Usage__c];
        System.assertEquals(noExpiredRecord, updatedRewards.size());
        System.assertEquals(noExpiredRecord, createdRewardUsages.size());
    }

    @isTest
    private static void testCMBatchUpdateRewardStatus_withSpecificIdSet_OnlyUpdateTheSpecifiedRecords() {
        Integer noRecordToUpdate = 10;
        Map<String, Reward__c> mapIdToRewards = new Map<String, Reward__c>([SELECT Id FROM Reward__c LIMIT :noRecordToUpdate]);
        Set<String> rewardIds = mapIdToRewards.keySet();
        System.Test.startTest();
            Database.executeBatch(new CMBatchUpdateRewardStatus(rewardIds));
        System.Test.stopTest();
        List<Reward__c> updatedRewards = [SELECT Id, Status__c, Expiry__c FROM Reward__c WHERE Expiry__c = :expiryDate AND Status__c = 'Expired'];
        List<Reward_Usage__c> createdRewardUsages = [SELECT Id FROM Reward_Usage__c];
        System.assertEquals(noRecordToUpdate, updatedRewards.size());
        System.assertEquals(noRecordToUpdate, createdRewardUsages.size());
    }
    
    @isTest
    private static void testCMBatchUpdateRewardStatusSchedule() {
        String CRON_EXP = '0 1 0 * * 2020';
        Test.startTest();
            CMBatchUpdateRewardStatusSchedule schedulableBatch = new CMBatchUpdateRewardStatusSchedule();
			schedulableBatch.execute(null);
        Test.stopTest();
        List<Reward__c> updatedRewards = [SELECT Id, Status__c, Expiry__c FROM Reward__c WHERE Expiry__c = :expiryDate AND Status__c = 'Expired'];
        List<Reward_Usage__c> createdRewardUsages = [SELECT Id FROM Reward_Usage__c];
        System.assertEquals(noExpiredRecord, updatedRewards.size());
        System.assertEquals(noExpiredRecord, createdRewardUsages.size());
    }
}