force-app/main/default/objects/Additional_Charges_Master__c/Additional_Charges_Master__c.object-meta.xml
<CustomObject>
    <label>Additional Charges Master</label>
    <nameField>
        <displayFormat>ACM-{0000000000}</displayFormat>
        <label>Additional Charges Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges_Master__c/fields/ADM_CHRGCD__c.field-meta.xml
<CustomField>
    <fullName>ADM_CHRGCD__c</fullName>
    <externalId>true</externalId>
    <label>Charge Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges_Master__c/fields/ADM_CHRGDESC__c.field-meta.xml
<CustomField>
    <fullName>ADM_CHRGDESC__c</fullName>
    <label>Charge Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Color_Master__c/fields/ColorCode__c.field-meta.xml
<CustomField>
    <fullName>ColorCode__c</fullName>
    <externalId>true</externalId>
    <label>ColorCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Model_Year_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/Package_Header__c.object-meta.xml
<CustomObject>
    <label>Package Header</label>
    <nameField>
        <displayFormat>PH-{0000000000}</displayFormat>
        <label>Package Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Header</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Header__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Package Header</relationshipLabel>
    <relationshipName>Package_Header</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/fields/PKH_FRN_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>PKH_FRN_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Header__c/fields/PKH_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PKH_STATUS__c</fullName>
    <label>Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Agreement__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch_Code</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/ColorCode__c.field-meta.xml
<CustomField>
    <fullName>ColorCode__c</fullName>
    <formula>Stock_Reservation__r.Color_Code__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/emailaddress__c.field-meta.xml
<CustomField>
    <fullName>emailaddress__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Stock_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Stock_Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Stock Reservation</label>
    <referenceTo>Stock_Reservation__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Reservation__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Package_Header_From_PickList__c.field-meta.xml
<CustomField>
    <fullName>Package_Header_From_PickList__c</fullName>
    <description>This field is a temporary field to contain the Id of the package header choose from the picklist on page 0, not a lookup field to Package_Header__c obj.</description>
    <label>Package Header From PickList</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Branch_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CCF</fullName>
    </customValue>
    <customValue>
        <fullName>CCK</fullName>
    </customValue>
    <customValue>
        <fullName>CCA</fullName>
    </customValue>
    <customValue>
        <fullName>CNC</fullName>
        <isActive>false</isActive>
        <label>CNC</label>
    </customValue>
    <masterLabel>Branch Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmailNotificationsInvocableTest.cls
@isTest
private class EmailNotificationsInvocableTest {
    @testSetup
    static void setUp() {
        // create a sales agreement record for test
        string branchCode = 'CCK';
        string agreementNo = 'ALOHA_TEST';
        string customerName = 'Imaginary Customer';

        // Create master data
        Model_Master__c modelMaster = new Model_Master__c(Name = 'Test Model Code', Branch_Code__c = branchCode, Franchise_Code__c = 'KIAPC');
        insert modelMaster;
        Color_Master__c colorMaster = new Color_Master__c(Name = 'Test Color Code', Branch_Code__c = branchCode, Franchise_Code__c = 'KIAPC', ColorCode__c = 'Z3P0');
        insert colorMaster;
        Trim_Master__c trimMaster = new Trim_Master__c(Name = 'Test Trim Code', Branch_Code__c = branchCode, Franchise_Code__c = 'KIAPC');
        insert trimMaster;
        Model_Year_Master__c modelYearMaster = new Model_Year_Master__c(Name = 'Test Model Year Code', Branch_Code__c = branchCode, Franchise_Code__c = 'KIAPC', Model_Master__c = modelMaster.ID);
        insert modelYearMaster;
        
        // Create Additional Charges Master
		Additional_Charges_Master__c addnlChargeMaster = new Additional_Charges_Master__c(ADM_CHRGDESC__c = 'Addnl Charge Test',
                                                                                          ADM_CHRGCD__c = 'R004');
        insert addnlChargeMaster;
        
        // Create Package Header
		Package_Header__c pckHeader = new Package_Header__c(PKH_FRN_FRNCD__c = 'KIAPC',
                                                            Model_Master__c = modelMaster.Id,
                                                            PKH_STATUS__c = 'A');
        insert pckHeader;
        
        // Create stock reservation from master data
        Stock_Reservation__c stockReservation = Test_DataFactory.StockReservation(false, modelMaster.ID, colorMaster.ID, trimMaster.ID, modelYearMaster.ID);
        stockReservation.Package_Header_From_PickList__c = pckHeader.Id;
        insert stockReservation;

        // Create sales agreement
        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, branchCode, agreementNo, stockReservation.ID, customerName);
        
        salesAgreement.emailaddress__c = 'test@aodigy.com';
        salesAgreement.Package_Header__c = pckHeader.Id;
        insert salesAgreement;
        salesAgreement.Branch_Code__c = branchCode;
        update salesAgreement;
    }

	@isTest
    static void Test_COE_Expiry_Email() {
        Sales_Agreement__c sa = [SELECT ID FROM Sales_Agreement__c];
        EmailNotificationsInvocable.EmailNotificationsRequest request = new EmailNotificationsInvocable.EmailNotificationsRequest();
        request.recordId = sa.Id;
        request.templateNm = 'COE_Expiry_Email';

        List<EmailNotificationsInvocable.EmailNotificationsRequest> requests = new List<EmailNotificationsInvocable.EmailNotificationsRequest>{request};
		Test.startTest();
        EmailNotificationsInvocable.sendEmailNotifications(requests);
        //Integer invocations = Limits.getEmailInvocations();
        //system.assertEquals(1, invocations, 'Send 1 email');
        Test.stopTest();
    }

    @isTest
    static void Test_Insurance_Approval_Email() {
        Sales_Agreement__c sa = [SELECT ID FROM Sales_Agreement__c];
        EmailNotificationsInvocable.EmailNotificationsRequest request = new EmailNotificationsInvocable.EmailNotificationsRequest();
        request.recordId = sa.Id;
        request.templateNm = 'Insurance_Approval_Notification';

        List<EmailNotificationsInvocable.EmailNotificationsRequest> requests = new List<EmailNotificationsInvocable.EmailNotificationsRequest>{request};
        //EmailNotificationsInvocable.sendEmailNotifications(requests);

        Test.startTest();
        EmailNotificationsInvocable.sendEmailNotifications(requests);
        Test.stopTest();
        //Integer invocations = Limits.getEmailInvocations();
        //system.assertEquals(1, Limits.getFutureCalls(), 'Send 1 email');
    }
    
    @isTest
    static void Test_Registration_Email() {
        Sales_Agreement__c sa = [SELECT ID FROM Sales_Agreement__c];
        EmailNotificationsInvocable.EmailNotificationsRequest request = new EmailNotificationsInvocable.EmailNotificationsRequest();
        request.recordId = sa.Id;
        request.templateNm = 'Registration_Email_Notification';

        List<EmailNotificationsInvocable.EmailNotificationsRequest> requests = new List<EmailNotificationsInvocable.EmailNotificationsRequest>{request};
        //EmailNotificationsInvocable.sendEmailNotifications(requests);

        Test.startTest();
        EmailNotificationsInvocable.sendEmailNotifications(requests);
		//Integer invocations = Limits.getEmailInvocations();
        //system.assertEquals(1, invocations, 'Send 1 email');
        Test.stopTest();
    }
}