force-app/main/default/objects/Additional_Charges_Master__c/Additional_Charges_Master__c.object-meta.xml
<CustomObject>
    <label>Additional Charges Master</label>
    <nameField>
        <displayFormat>ACM-{0000000000}</displayFormat>
        <label>Additional Charges Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges_Master__c/fields/ADM_CHRGCD__c.field-meta.xml
<CustomField>
    <fullName>ADM_CHRGCD__c</fullName>
    <externalId>true</externalId>
    <label>Charge Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges_Master__c/fields/ADM_CHRGDESC__c.field-meta.xml
<CustomField>
    <fullName>ADM_CHRGDESC__c</fullName>
    <label>Charge Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Color_Master__c/Color_Master__c.object-meta.xml
<CustomObject>
    <label>Color Master</label>
    <nameField>
        <label>Color Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/File_Requirements__mdt/File_Requirements__mdt.object-meta.xml
<CustomObject>
    <label>File Requirements</label>
    <pluralLabel>File Requirements</pluralLabel>
</CustomObject>

cncProd/force-app/main/default/objects/File_Requirements__mdt/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/File_Requirements__mdt/fields/Naming_Convention__c.field-meta.xml
<CustomField>
    <fullName>Naming_Convention__c</fullName>
    <description>Defines the name of the uploaded file. If the placeholder &quot;{RecordName}&quot; is used, &quot;{RecordName}&quot; will be replaced by the name of the file&apos;s parent record.</description>
    <inlineHelpText>Defines the name of the uploaded file. If the placeholder &quot;{RecordName}&quot; is used, &quot;{RecordName}&quot; will be replaced by the name of the file&apos;s parent record.</inlineHelpText>
    <label>Naming Convention</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <description>Bank Loan Application</description>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>FIN-{0000000}</displayFormat>
        <label>Loan Application</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Loan_Application__c/fields/DealerID__c.field-meta.xml
<CustomField>
    <fullName>DealerID__c</fullName>
    <label>DealerID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Loan_Application__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Master__c/Model_Master__c.object-meta.xml
<CustomObject>
    <label>Model Master</label>
    <nameField>
        <label>Model Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Model_Year_Master__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/Package_Header__c.object-meta.xml
<CustomObject>
    <label>Package Header</label>
    <nameField>
        <displayFormat>PH-{0000000000}</displayFormat>
        <label>Package Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Header</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Header__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Package Header</relationshipLabel>
    <relationshipName>Package_Header</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/fields/PKH_FRN_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>PKH_FRN_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Header__c/fields/PKH_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PKH_STATUS__c</fullName>
    <label>Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Agreement__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch_Code</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/COE_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>COE_Expiry_Date__c</fullName>
    <label>COE Expiry Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/SOH_SONO__c.field-meta.xml
<CustomField>
    <fullName>SOH_SONO__c</fullName>
    <externalId>true</externalId>
    <label>Sales Agreement No</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Stock_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Stock_Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Stock Reservation</label>
    <referenceTo>Stock_Reservation__c</referenceTo>
    <relationshipLabel>Sales Agreements</relationshipLabel>
    <relationshipName>Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Reservation__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Package_Header_From_PickList__c.field-meta.xml
<CustomField>
    <fullName>Package_Header_From_PickList__c</fullName>
    <description>This field is a temporary field to contain the Id of the package header choose from the picklist on page 0, not a lookup field to Package_Header__c obj.</description>
    <label>Package Header From PickList</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Trim_Master__c/Trim_Master__c.object-meta.xml
<CustomObject>
    <label>Trim Master</label>
    <nameField>
        <label>Trim Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trim Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Branch_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CCF</fullName>
    </customValue>
    <customValue>
        <fullName>CCK</fullName>
    </customValue>
    <customValue>
        <fullName>CCA</fullName>
    </customValue>
    <customValue>
        <fullName>CNC</fullName>
        <isActive>false</isActive>
        <label>CNC</label>
    </customValue>
    <masterLabel>Branch Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Maybank_UpdateSupportingDocumentTest.cls
/** *****
 * Description : Test Class for Maybank_UpdateSupportingDocument.cls
 * 
 * Change History : 
 * Date(YYYYMMDD)      Name                 Description
 * 20201229            HS@aodigy            Created Initial Version 
 * 
** *****/
@isTest(seeAllData=false)
private class Maybank_UpdateSupportingDocumentTest {
    
   
    @TestSetup
    static void makeData()
    {
        Test_DataFactory.createGlobalOrfDefaults(true);

        Model_Master__c modelMaster = Test_DataFactory.createModelCode(false, 'Test Model Code');
        modelMaster.Branch_Code__c = 'CCK';
        modelMaster.Franchise_Code__c = 'KIAPC';
        insert modelMaster;

        Model_Year_Master__c modelYearMaster = Test_DataFactory.createModelYearCode( false, modelMaster.Id);
        modelYearMaster.Branch_Code__c = 'CCK';
        modelYearMaster.Franchise_Code__c = 'KIAPC';
        insert modelYearMaster;

        Color_Master__c colorMaster = Test_DataFactory.createColorCode(false, 'Test Color Code', 'zCode', 'CCK', 'KIAPC');
        insert colorMaster;

        Trim_Master__c trimMaster = Test_DataFactory.createTrimCode(false, 'Test Trim Code');
        trimMaster.Branch_Code__c = 'CCK';
        trimMaster.Franchise_Code__c = 'KIAPC';
        insert trimMaster;

        Package_Header__c pckHeader = new Package_Header__c(PKH_FRN_FRNCD__c = 'KIAPC', Model_Master__c = modelMaster.Id, PKH_STATUS__c = 'A');
        insert pckHeader;

        Additional_Charges_Master__c addnlChargeMaster = new Additional_Charges_Master__c(ADM_CHRGDESC__c = 'Addnl Charge Test', ADM_CHRGCD__c = 'R004');
        insert addnlChargeMaster;

        Stock_Reservation__c stockReservation = Test_DataFactory.StockReservation(false, modelMaster.Id, colorMaster.Id, trimMaster.Id, modelYearMaster.Id);
        stockReservation.Package_Header_From_PickList__c = pckHeader.Id;
        insert stockReservation;

        Sales_Agreement__c salesAgreement = Test_DataFactory.createSalesAgreement(false, 'CCK', 'TR0507', stockReservation.Id, 'Test Customer');
        salesAgreement.Package_Header__c = pckHeader.Id;
        salesAgreement.COE_Expiry_Date__c = Date.today().addDays(30);
        insert salesAgreement;

        Loan_Application__c loanAppl = Test_DataFactory.createLoanApplication(false, null, salesAgreement.Id);
        loanAppl.DealerID__c = 'testDealerId';
        insert loanAppl;
    }

    
    @isTest
    static void updateAllSupportingDocumentTM() 
    {
        Sales_Agreement__c saObj = [SELECT Id, SOH_SONO__c FROM Sales_Agreement__c WHERE SOH_SONO__c = 'TR0507' ];
        System.assert( saObj <> null );

        InsertContentDoc( saObj.Id, saObj.SOH_SONO__c, 'Sales_Tax_Invoice;Cover_Note;Acknowledgement_Page' );

        Maybank_UpdateSupportingDocument.FlowInputs fInput = new Maybank_UpdateSupportingDocument.FlowInputs();
        fInput.salesAgreementNo = saObj.SOH_SONO__c;
        fInput.salesAgrementId  = saObj.Id;
        fInput.fileRequirementsName = 'Sales_Tax_Invoice;Cover_Note;Acknowledgement_Page';

        Test.setMock(HttpCalloutMock.class, new UpdateSupportingDocumentMock());
        System.Test.startTest();
            List<Maybank_UpdateSupportingDocument.FlowOutputs> lstFlwOutputs = new List<Maybank_UpdateSupportingDocument.FlowOutputs>();
            lstFlwOutputs = Maybank_UpdateSupportingDocument.updateSupportingDocument( new List<Maybank_UpdateSupportingDocument.FlowInputs>{ fInput } );
            // System.assert( !lstFlwOutputs.isEmpty() );
            // System.assert( lstFlwOutputs.get(0).api_returned_code == 'S' );
            // System.assert( lstFlwOutputs.get(0).fileCount == 3 );
        System.Test.stopTest();
    }


    @isTest
    static void updatePartialSupportingDocumentTM() 
    {
        Sales_Agreement__c saObj = [SELECT Id, SOH_SONO__c FROM Sales_Agreement__c WHERE SOH_SONO__c = 'TR0507' ];
        System.assert( saObj <> null );

        InsertContentDoc( saObj.Id, saObj.SOH_SONO__c, 'Sales_Tax_Invoice;Cover_Note' );

        Test.setMock(HttpCalloutMock.class, new UpdateSupportingDocumentMock());
        System.Test.startTest();
            Maybank_UpdateSupportingDocument.FlowInputs fInput = new Maybank_UpdateSupportingDocument.FlowInputs();
            fInput.salesAgreementNo = saObj.SOH_SONO__c;
            fInput.salesAgrementId  = saObj.Id;
            fInput.fileRequirementsName = 'Sales_Tax_Invoice;Cover_Note;Acknowledgement_Page';
            List<Maybank_UpdateSupportingDocument.FlowOutputs> lstFlwOutputs = new List<Maybank_UpdateSupportingDocument.FlowOutputs>();
            lstFlwOutputs = Maybank_UpdateSupportingDocument.updateSupportingDocument( new List<Maybank_UpdateSupportingDocument.FlowInputs>{ fInput } );
            // System.assert( !lstFlwOutputs.isEmpty());
            // System.assert( String.isBlank(lstFlwOutputs.get(0).api_returned_code) );
            // System.assert( lstFlwOutputs.get(0).fileCount == 2 );
        System.Test.stopTest();
    }


    public class UpdateSupportingDocumentMock implements HttpCalloutMock 
    {
        public HTTPResponse respond(HTTPRequest req) {
            string body = '{"Data":{"LOSRefNumber":"LW05050505","SalesAgreementNumber":"TR0507"},"Status":{"Code":"S","ErrorCode":"","ErrorDescription":""}}';
            HttpResponse respond = new HttpResponse();
            respond.setHeader('Content-Type', 'application/json');
            respond.setBody(body);
            respond.setStatusCode(200);
            respond.setStatus('200');
            return respond;
        }
    }


    public static void InsertContentDoc( String saID, String saNumber, String fileName )
    {
        //Insert ContentVersion
        List<ContentVersion> lstContentVersion = new List<ContentVersion>();
        for( File_Requirements__mdt fileMdt : [ SELECT Id, DeveloperName, Document_Name__c, Naming_Convention__c
                                                FROM File_Requirements__mdt
                                                WHERE DeveloperName IN :fileName.split(';') ]){
            
            String file_naming_pattern = fileMdt.Naming_Convention__c;   
            ContentVersion cv = new ContentVersion();
            cv.ContentLocation = 'S';
            cv.PathOnClient    = '/' + file_naming_pattern.replaceAll('\\{!(.*?)\\}', saNumber )+'.pdf';
            cv.Origin          = 'C';
            cv.Title           = file_naming_pattern.replaceAll('\\{!(.*?)\\}', saNumber );
            cv.VersionData     = Blob.valueOf('Testing'); 

            lstContentVersion.add(cv);
        }
        insert lstContentVersion;

        //Insert ContentDocumentLink
        List<ContentDocumentLink> lstContentDocLink = new List<ContentDocumentLink>();
        for( ContentVersion cv : [SELECT ContentDocumentId FROM ContentVersion WHERE ID IN:lstContentVersion] ){
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = cv.ContentDocumentId;
            cdl.LinkedEntityId    = (Id)saID;
            cdl.ShareType         = 'I';
            cdl.Visibility        = 'AllUsers';

            lstContentDocLink.add( cdl );
        }     
        Insert lstContentDocLink;        
    }

}