cncProd/force-app/main/default/objects/Delivery_Bay_Booking__c/Delivery_Bay_Booking__c.object-meta.xml
<CustomObject>
    <description>Represent booking of delivery bay by the sales consultant</description>
    <label>Delivery Bay Booking</label>
    <nameField>
        <displayFormat>DBB-{0000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Bay Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Delivery_Bay_Booking__c/fields/FranchiseCode__c.field-meta.xml
<CustomField>
    <fullName>FranchiseCode__c</fullName>
    <formula>IF(ISBLANK(Sales_Agreement__c), MB_Sales_Agreement__r.FranchiseCode__c, Sales_Agreement__r.FranchiseCode__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Franchise Code</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Delivery_Bay_Booking__c/fields/MB_Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>MB_Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MB Sales Agreement</label>
    <referenceTo>MB_Sales_Agreement__c</referenceTo>
    <relationshipLabel>Delivery Bay Bookings</relationshipLabel>
    <relationshipName>Delivery_Bay_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Delivery_Bay_Booking__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>Delivery Bay Bookings</relationshipLabel>
    <relationshipName>Delivery_Bay_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Bay_Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Bay_Configuration__c/Delivery_Bay_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting used for Delivery Bay Bookings.</description>
    <label>Delivery Bay Configuration</label>
</CustomObject>

force-app/main/default/objects/Delivery_Bay_Configuration__c/fields/Email_Template_Cancel_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Cancel_Delivery__c</fullName>
    <label>Email Template Cancel Delivery</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Bay_Configuration__c/fields/Email_Template_Delivery_Bay_Booking__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Delivery_Bay_Booking__c</fullName>
    <label>Email Template Delivery Bay Booking</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Delivery_Bay_Configuration__c/fields/Email_Template_Ready_for_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Ready_for_Delivery__c</fullName>
    <label>Email Template Ready for Delivery</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Delivery_Bay_In_Charge__c/Delivery_Bay_In_Charge__c.object-meta.xml
<CustomObject>
    <label>Delivery Bay In-Charge</label>
    <nameField>
        <label>Delivery Bay In-Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Bay In-Charge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Delivery_Bay_In_Charge__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Franchise_Code</valueSetName>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/MB_Sales_Agreement__c/MB_Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>MB Sales Agreement</label>
    <nameField>
        <displayFormat>MBSA-{000000}</displayFormat>
        <label>MB Sales Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/MB_Sales_Agreement__c/fields/FranchiseCode__c.field-meta.xml
<CustomField>
    <fullName>FranchiseCode__c</fullName>
    <formula>IF(TEXT(MB_Stock_Vehicle_Master__r.Variant__r.Franchise__c) == &apos;MBP&apos;, &apos;MBPC&apos;, &apos;MBCV&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Franchise Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MB_Sales_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Waiting for Confirmation</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Balance Payment</fullName>
            </value>
            <value>
                <fullName>Pending Registration</fullName>
            </value>
            <value>
                <fullName>Ready for Delivery</fullName>
            </value>
            <value>
                <fullName>Car Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>if(Opportunity__r.Lead__c != null, Opportunity__r.Lead__r.Email, IF(Opportunity__r.Contact_Person__c != null, Opportunity__r.Contact_Person__r.Email, &apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/FranchiseCode__c.field-meta.xml
<CustomField>
    <fullName>FranchiseCode__c</fullName>
    <formula>/*TEXT(Owner:User.Franchise_Code__c)*/
TEXT( Stock_Reservation__r.Model_Code__r.Franchise_Code__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Franchise Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Franchise_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CITCV</fullName>
    </customValue>
    <customValue>
        <fullName>CITPC</fullName>
    </customValue>
    <customValue>
        <fullName>KIACV</fullName>
    </customValue>
    <customValue>
        <fullName>KIAPC</fullName>
    </customValue>
    <customValue>
        <fullName>MITCV</fullName>
    </customValue>
    <customValue>
        <fullName>MITPC</fullName>
    </customValue>
    <customValue>
        <fullName>MBCV</fullName>
    </customValue>
    <customValue>
        <fullName>MBPC</fullName>
    </customValue>
    <masterLabel>Franchise Code</masterLabel>
</GlobalValueSet>

cncProd/force-app/main/default/classes/DeliveryBayBookings.cls
/** ******
* Description: 
* Change History:
* Date(YYYYMMDD)       Name                Description
* 20210714             Thang               Created Initial Version. 
** ******/
public class DeliveryBayBookings extends ADGLIB_SObjectDomain {
    
    public DeliveryBayBookings(List<Delivery_Bay_Booking__c> sObjectList) {
        super(sObjectList);
    }
    
    public class Constructor implements ADGLIB_SObjectDomain.IConstructable {
        public ADGLIB_SObjectDomain construct(List<SObject> sObjectList) {
            return new DeliveryBayBookings(sObjectList);
        }
    }
    
    
    public override void onAfterInsert() {
        validateDBB();
    }
    
    public override void onAfterUpdate(Map<Id,SObject> existingRecords){
        validateDBB();
        sendingEmailAfterBooking(existingRecords);
        sendingEmailAfterCancelBooking(existingRecords);
    }
    
    private void validateDBB(){
        Set<Id> salesAgreements = new Set<Id>();
        Set<Id> mbSalesAgreements = new Set<Id>();
        Set<Id> salesAgreementsCheck = new Set<Id>();
        Set<Id> mbSalesAgreementsCheck = new Set<Id>();
        for(Delivery_Bay_Booking__c dbb : (List<Delivery_Bay_Booking__c>)Records) { 
            salesAgreements.add(dbb.Sales_Agreement__c);
            mbSalesAgreements.add(dbb.MB_Sales_Agreement__c);
            
        }
        List<Delivery_Bay_Booking__c > dbbs = [Select Id, Status__c, Sales_Agreement__c, MB_Sales_Agreement__c from Delivery_Bay_Booking__c where (Sales_Agreement__c IN: salesAgreements OR MB_Sales_Agreement__c IN: mbSalesAgreements) And Status__c ='Booked'];
        
        for(Delivery_Bay_Booking__c dbb: dbbs){
            if(!salesAgreementsCheck.contains(dbb.Sales_Agreement__c) || !salesAgreementsCheck.contains(dbb.MB_Sales_Agreement__c)){
                salesAgreementsCheck.add(dbb.Sales_Agreement__c);
                salesAgreementsCheck.add(dbb.MB_Sales_Agreement__c);
            }else{
                dbb.addError('Delivery bay have been booked, Please check!');
            } 
        }
    }
    
    public static void setExpriedForDBB(List<Delivery_Bay_Booking__c > dbbs){
        for(Delivery_Bay_Booking__c dbb: dbbs){
            dbb.Status__c = 'Expired'; 
        }
        update dbbs;
    }
    
    public static void sendingEmailForBookingNewSlot(Set<Id> salesAgreements, Set<Id> mbSalesAgreements){
        
        OrgWideEmailAddress owa = [SELECT Id, Address, DisplayName 
                                   FROM OrgWideEmailAddress 
                                   WHERE Address = 'do-not-reply@ccc.cyclecarriage.com.sg' 
                                   LIMIT 1];
        
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        
        Map<String,String> mapNameByEmail = new Map<String, String>();
        if(salesAgreements != NULL){
            List<Sales_Agreement__c> salesAgreementList = new List<Sales_Agreement__c>([SELECT id, Name, Owner.Email FROM Sales_Agreement__c where Id IN: salesAgreements]);
            for(Sales_Agreement__c sa: salesAgreementList){
                mapNameByEmail.put(sa.Name, sa.Owner.Email);
            }
        }else if(mbSalesAgreements != NULL){
            List<MB_Sales_Agreement__c> mbSalesAgreementList = new List<MB_Sales_Agreement__c>([SELECT id, Name, Owner.Email FROM MB_Sales_Agreement__c where Id IN: mbSalesAgreements]);
            for(MB_Sales_Agreement__c mb: mbSalesAgreementList){
                mapNameByEmail.put(mb.Name, mb.Owner.Email);
            }
        }
        
        if(Test.isRunningTest()){
            mapNameByEmail.put('sa.Name', 'test@gmail.com');
        }
        Delivery_Bay_Configuration__c dbbCf = Delivery_Bay_Configuration__c.getValues('Delivery Bay Booking Config');
        //get Email Template Ready For Delivery from Custom Setting
        String emailTemplateReadyForDelivery = '';
        if(dbbCf != Null){
            emailTemplateReadyForDelivery = dbbCf.Email_Template_Ready_for_Delivery__c;
        }
        
        if(String.isNotBlank(emailTemplateReadyForDelivery)){
            EmailTemplate template = [SELECT Id, Name, Subject, HtmlValue, Body FROM EmailTemplate  WHERE Name = :emailTemplateReadyForDelivery LIMIT 1];
            String eSub, eBody ;
            if(!mapNameByEmail.isEmpty() && template != NULL){
                for(String name : mapNameByEmail.keySet()){
                    Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(template.Id, null, null);
                    mail.setOrgWideEmailAddressId(owa.Id);
                    mail.setSubject(mail.getSubject().replace('{{NAME}}', name));
                    mail.setHtmlBody(mail.getHtmlBody().replace('{{NAME}}', name));
                    String customerEmail = Test.isRunningTest() ? 'test@gmail.com' :mapNameByEmail.get(name); 
                    mail.setToAddresses(new List<String>{customerEmail});
                    mails.add(mail);
                }
            }
            
            if (mails.size() > 0){
                try {
                    Messaging.SendEmailResult[] results = Messaging.sendEmail(mails, false);
                } catch (EmailException e) {
                    loggerDataPool.buildLogDataPool('DeliveryBayBookings.sendingEmailForBookingNewSlot', e);
                }
            }
        }
    }
    
    public void sendingEmailAfterBooking(Map<Id, SObject> existingRecords){
        Set<Delivery_Bay_Booking__c> dbbs = new Set<Delivery_Bay_Booking__c>();
        for(Delivery_Bay_Booking__c dbb : (List<Delivery_Bay_Booking__c>)Records) {
            Delivery_Bay_Booking__c oldDBB = (Delivery_Bay_Booking__c)existingRecords.get(dbb.Id);
            if(dbb.Status__c  != oldDBB.Status__c  && dbb.Status__c  == 'Booked'){  
                dbbs.add(dbb);
            }
        }
        
        OrgWideEmailAddress owa = [SELECT Id, Address, DisplayName 
                                   FROM OrgWideEmailAddress 
                                   WHERE Address = 'do-not-reply@ccc.cyclecarriage.com.sg' 
                                   LIMIT 1];
        Delivery_Bay_Configuration__c dbbCf = Delivery_Bay_Configuration__c.getValues('Delivery Bay Booking Config');
        //get Email Template Delivery Bay Booking from Custom Setting
        String emailTemplateBooked = '';
        if(dbbCf != Null){
            emailTemplateBooked = dbbCf.Email_Template_Delivery_Bay_Booking__c;
        }
        if(String.isNotBlank(emailTemplateBooked)){
            EmailTemplate template = [SELECT Id, Name, Subject, HtmlValue, Body FROM EmailTemplate  WHERE Name = :emailTemplateBooked LIMIT 1];
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
            List<Delivery_Bay_In_Charge__c> dbbInCharges = [SELECT id, Franchise_Code__c, Email__c   FROM Delivery_Bay_In_Charge__c WHERE  Active__c  = TRUE];
            for(Delivery_Bay_Booking__c dbb :  dbbs){
                List<String> toAddressesList = getRecipients(dbbInCharges, dbb.FranchiseCode__c);
                if(!toAddressesList.isEmpty() && template != NULL){
                    Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(template.Id, null, dbb.Id);
                    mail.setOrgWideEmailAddressId(owa.Id);
                    mail.setToAddresses(toAddressesList);
                    mails.add(mail);
                }
            }
            if (mails.size() > 0){
                try {
                    Messaging.SendEmailResult[] results = Messaging.sendEmail(mails, false);
                } catch (EmailException e) {
                    loggerDataPool.buildLogDataPool('DeliveryBayBookings.sendingEmailAfterBooking', e);
                }
                
            }
        }
        
    }
    
    public void sendingEmailAfterCancelBooking(Map<Id, SObject> existingRecords){
        Set<Delivery_Bay_Booking__c> dbbs = new Set<Delivery_Bay_Booking__c>();
        for(Delivery_Bay_Booking__c dbb : (List<Delivery_Bay_Booking__c>)Records) {
            Delivery_Bay_Booking__c oldDBB = (Delivery_Bay_Booking__c)existingRecords.get(dbb.Id);
            if(dbb.Status__c  != oldDBB.Status__c  && dbb.Status__c  == 'Cancelled'){  
                dbbs.add(dbb);
            }
        }
        
        OrgWideEmailAddress owa = [SELECT Id, Address, DisplayName 
                                   FROM OrgWideEmailAddress 
                                   WHERE Address = 'do-not-reply@ccc.cyclecarriage.com.sg' 
                                   LIMIT 1];
        
        Delivery_Bay_Configuration__c dbbCf = Delivery_Bay_Configuration__c.getValues('Delivery Bay Booking Config');
        //get Email Template Cancel Delivery from Custom Setting
        String emailTemplateCancel = '';
        if(dbbCf != Null){
            emailTemplateCancel = dbbCf.Email_Template_Cancel_Delivery__c;
        }
        if(String.isNotBlank(emailTemplateCancel)){
            EmailTemplate template = [SELECT Id, Name, Subject, HtmlValue, Body FROM EmailTemplate WHERE Name = :emailTemplateCancel LIMIT 1];
            
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
            List<Delivery_Bay_In_Charge__c> dbbInCharges = [SELECT id, Franchise_Code__c, Email__c   FROM Delivery_Bay_In_Charge__c WHERE  Active__c  = TRUE];
            
            for(Delivery_Bay_Booking__c dbb :  dbbs){
                List<String> toAddressesList = getRecipients(dbbInCharges, dbb.FranchiseCode__c);
                if(!toAddressesList.isEmpty() && template != NULL){
                    Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(template.Id, null, dbb.Id);
                    mail.setOrgWideEmailAddressId(owa.Id);
                    mail.setToAddresses(toAddressesList);
                    mails.add(mail);
                }
            }
            if (mails.size() > 0){
                try {
                    Messaging.SendEmailResult[] results = Messaging.sendEmail(mails, false);
                } catch (EmailException e) {
                    loggerDataPool.buildLogDataPool('DeliveryBayBookings.sendingEmailAfterCancelBooking', e);
                }
                
            }
        }
        
    }
    private List<String> getRecipients(List<Delivery_Bay_In_Charge__c> dbbInCharges, String franchiseCode){
        List<String> recipients = new List<String>();
        for(Delivery_Bay_In_Charge__c dbbInCharge : dbbInCharges){
            if(dbbInCharge.Franchise_Code__c.contains(franchiseCode)){
                recipients.add(dbbInCharge.Email__c);
            }
        }
        return recipients;
    }
    
    
}