force-app/main/default/objects/Account/fields/ARCA_Number__c.field-meta.xml
<CustomField>
    <fullName>ARCA_Number__c</fullName>
    <label>ARCA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <label>Business Account</label>
</RecordType>

cncProd/force-app/main/default/objects/Contact/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <inlineHelpText>As per NRIC</inlineHelpText>
    <label>Full Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>NRIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Please enter the last 4 digits of the Customer&apos;s NRIC followed by the Date of Birth in the following format DDMMYYY. E.g. 314B10101976</inlineHelpText>
    <label>NRIC _ Passport No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/MB_Build_Spec__c/MB_Build_Spec__c.object-meta.xml
<CustomObject>
    <label>MB Build Spec</label>
    <nameField>
        <displayFormat>MBBS-{00000000}</displayFormat>
        <label>MB Build Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Build Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Build_Spec__c/fields/Highlight_Option__c.field-meta.xml
<CustomField>
    <fullName>Highlight_Option__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Highlight Option</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Build_Spec__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>MB Build Specs</relationshipLabel>
    <relationshipName>MB_Build_Specs</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Build_Spec__c/fields/Option_Code__c.field-meta.xml
<CustomField>
    <fullName>Option_Code__c</fullName>
    <label>Option Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Build_Spec__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>MB Build Specs</relationshipLabel>
    <relationshipName>MB_Build_Specs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MB_Promotion__c/MB_Promotion__c.object-meta.xml
<CustomObject>
    <description>Promotion master data for MB</description>
    <label>MB Promotion</label>
    <nameField>
        <label>MB Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MB Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Promotion__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>AND( TODAY() &gt;= Start_Date__c, TODAY() &lt;= End_Date__c)</formula>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Promotion__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Promotion__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return to Pool</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MB_Promotion__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Promotion_Stock__c/MB_Promotion_Stock__c.object-meta.xml
<CustomObject>
    <description>Junction object between Promotion__c and MB_Stock_Vehicle_Master__c</description>
    <label>MB Promotion Stock</label>
    <nameField>
        <displayFormat>MBPS-{0000000}</displayFormat>
        <label>MB Promotion Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Promotion Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/MB_Promotion_Stock__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>MB_Promotion__r.Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Promotion_Stock__c/fields/MB_Promotion__c.field-meta.xml
<CustomField>
    <fullName>MB_Promotion__c</fullName>
    <label>MB Promotion</label>
    <referenceTo>MB_Promotion__c</referenceTo>
    <relationshipLabel>MB Promotion Stocks</relationshipLabel>
    <relationshipName>MB_Stock_Vehicles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MB_Promotion_Stock__c/fields/MB_Stock_Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>MB_Stock_Vehicle_Master__c</fullName>
    <label>MB Stock Vehicle Master</label>
    <referenceTo>MB_Stock_Vehicle_Master__c</referenceTo>
    <relationshipLabel>MB Promotion Stocks</relationshipLabel>
    <relationshipName>MB_Promotions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Stock_Vehicle_Master__c/MB_Stock_Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>MB Stock Vehicle Master</label>
    <nameField>
        <displayFormat>MBSVM-{000000}</displayFormat>
        <label>MB Stock Vehicle Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Stock Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>Variant__r.Model_ID__r.Name</formula>
    <label>Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>MB Stock Vehicle Masters</relationshipLabel>
    <relationshipName>MB_Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Vehicle_ID__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID</inlineHelpText>
    <label>Vehicle ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MB_SVM_Spec__c/MB_SVM_Spec__c.object-meta.xml
<CustomObject>
    <description>MB Stock Vehicle Spec line</description>
    <label>MB SVM Spec</label>
    <nameField>
        <displayFormat>MBSVMS-{000000}</displayFormat>
        <label>MB SVM Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB SVM Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_SVM_Spec__c/fields/MB_Stock_Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>MB_Stock_Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MB Stock Vehicle Master</label>
    <referenceTo>MB_Stock_Vehicle_Master__c</referenceTo>
    <relationshipLabel>MB SVM Specs</relationshipLabel>
    <relationshipName>MB_SVM_Specs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Variant__c/fields/Allow_Indent__c.field-meta.xml
<CustomField>
    <fullName>Allow_Indent__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Allow Sales Executive to indent order for this variant</inlineHelpText>
    <label>Allow Indent</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <externalId>true</externalId>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>Franchise__c</fullName>
    <label>Franchise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Model_ID__c.field-meta.xml
<CustomField>
    <fullName>Model_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model_ID</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/classes/MB_BatchPromoAutomationTest.cls
@isTest
private class MB_BatchPromoAutomationTest {
	@testSetup
    static void setUp() {
        // Create Model
        Model__c model = Test_DataFactory.createmodelId(true, 'MB A Class Test', 'CCI', 'MBP');
        // Create Variant
        Variant__c variant = new Variant__c(Name = 'MB A 250 Test',
                                           Model_ID__c = model.Id,
                                           Franchise__c = 'MBP',
                                           Branch__c = 'CCI',
                                           Allow_Indent__c = false,
                                           Description__c = 'MB A 250 Test',
                                           Active__c = true);
        insert variant;
        // Create Indent Variant
        Variant__c indentVariant = new Variant__c(Name = 'MB A 200 Indent',
                                                   Model_ID__c = model.Id,
                                                   Franchise__c = 'MBP',
                                                   Branch__c = 'CCI',
                                                   Allow_Indent__c = true,
                                                   Description__c = 'MB A 200 Indent',
                                                   Active__c = true);
        insert indentVariant;
        
        // Create Promo
        List<MB_Promotion__c> promotions = new List<MB_Promotion__c>();
        MB_Promotion__c promo = new MB_Promotion__c(Name = 'Sample Promo',
                                                  Start_Date__c = Date.newInstance(2020, 11, 11),
                                                  End_Date__c = Date.newInstance(2022, 11, 30),
                                                  Flag__c = 'Return to Pool',
                                                  Description__c = 'Test Promo');
        // insert promo;
        promotions.add(promo);
        MB_Promotion__c promo2 = new MB_Promotion__c(Name = 'Sample Promo2',
                                                  Start_Date__c = Date.newInstance(2020, 11, 11),
                                                  End_Date__c = Date.newInstance(2022, 11, 30),
                                                  Flag__c = 'Return to Pool',
                                                  Description__c = 'Test Promo');
        // insert promo;
        promotions.add(promo2);
        insert promotions;
        // Create MB Stock Vehicle Master
        MB_Stock_Vehicle_Master__c mbSVM = new MB_Stock_Vehicle_Master__c(Vehicle_ID__c = '1',
                                                                         Status__c = 'Open',
                                                                         Variant__c = variant.Id,
                                                                         Colour__c = '787 Mountain Grey',
                                                                         Trim__C = '101 ARTICO Black');
        insert mbSVM;
        
        // Create MB Promo Stock
        List<MB_Promotion_Stock__c> promoStocks = new List<MB_Promotion_Stock__c>();
        MB_Promotion_Stock__c promoStock = new MB_Promotion_Stock__c(MB_Promotion__c = promo.Id,
                                                                     MB_Stock_Vehicle_Master__c = mbSVM.Id);
        // insert promoStock;
        promoStocks.add(promoStock);
        MB_Promotion_Stock__c promoStock2 = new MB_Promotion_Stock__c(MB_Promotion__c = promo2.Id,
                                                                     MB_Stock_Vehicle_Master__c = mbSVM.Id);
        promoStocks.add(promoStock2);
        insert promoStocks;
        // Create MB Build Spec
        MB_Build_Spec__c spec1 = new MB_Build_Spec__c(Model__c = model.Id,
                                                    Variant__c = variant.Id,
                                                    Option_Code__c = '294',
                                                    Highlight_Option__c = false);
        insert spec1;
        MB_Build_Spec__c spec2 = new MB_Build_Spec__c(Model__c = model.Id,
                                                    Variant__c = variant.Id,
                                                    Option_Code__c = '999',
                                                    Highlight_Option__c = true);
        insert spec2;
        // Create MB SVM Spec
        MB_SVM_Spec__c svmSpec = new MB_SVM_Spec__c(Product__c = '999',
                                                   MB_Stock_Vehicle_Master__c = mbSVM.Id);
        insert svmSpec;
        // Create Business Account
        Id BUSINESS_ACCOUNT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
        Account ba = new Account(RecordTypeId = BUSINESS_ACCOUNT,
                                Name = 'ABC Corp',
                                ARCA_Number__c = 'ARCA9999',
                                Type = 'Prospect');
        insert ba;
        // Create Business Contact
        Contact bc = new Contact(Full_Name__c = 'Business Contact Test',
                                NRIC_Passport_No__c = 'BC12345',
                                NRIC__c = 'BC12345',
                                Email = 'bc@test.com',
                                FirstName = 'Business Contact',
                                LastName = 'Test');
        insert bc;
        // Create Person Account
        Account acc = Test_DataFactory.createPerson(false, 'Person Account Test', 'Customer');
        acc.NRIC_Passport_No__pc = 'PA12345';
        acc.NRIC__pc = 'PA12345';
        acc.PersonMobilePhone = '651234567';
        acc.PersonEmail = 'pa@test.com';
        if (acc != null) {
            TriggerExclusion.excludeTrigger( 'Account' , true );
            insert acc;
        }
    }

    @isTest
    static void Test_Promo_Active() {
        Test.startTest();
        MB_BatchPromoAutomation b = new MB_BatchPromoAutomation();
        Id batchId = Database.executeBatch(b);
        Test.stopTest();
    }

    @isTest
    static void Test_Promo_Inactive() {
        List<MB_Promotion__c> tmpPromos = new List<MB_Promotion__c>();
        List<MB_Promotion__c> promos = [SELECT ID, Start_Date__c, End_Date__c FROM MB_Promotion__c];
        for (MB_Promotion__c promo : promos) {
            promo.Start_Date__c = Date.newInstance(2022, 10, 10);
            promo.End_Date__c = Date.newInstance(2010, 10, 10);
            tmpPromos.add(promo);
        }
        system.debug('tmp promo:: ' + tmpPromos);
        update tmpPromos;
        Test.startTest();
        MB_BatchPromoAutomation b = new MB_BatchPromoAutomation();
        Id batchId = Database.executeBatch(b);
        Test.stopTest();
    }

    @isTest
    static void Test_Promo_Inactive2() {
        List<MB_Promotion__c> tmpPromos = new List<MB_Promotion__c>();
        List<MB_Promotion__c> promos = [SELECT ID, Start_Date__c, End_Date__c FROM MB_Promotion__c];
        for (MB_Promotion__c promo : promos) {
            promo.Start_Date__c = Date.newInstance(2022, 10, 10);
            promo.End_Date__c = Date.newInstance(2010, 10, 10);
            promo.Flag__c = 'Blocked';
            tmpPromos.add(promo);
        }
        system.debug('tmp promo:: ' + tmpPromos);
        update tmpPromos;
        Test.startTest();
        MB_BatchPromoAutomation b = new MB_BatchPromoAutomation();
        Id batchId = Database.executeBatch(b);
        Test.stopTest();
    }
}