force-app/main/default/objects/ExclusionList__mdt/ExclusionList__mdt.object-meta.xml
<CustomObject>
    <description>Generic List per Module for Exclusion Logic</description>
    <label>Exclusion List</label>
    <pluralLabel>Exclusion Lists</pluralLabel>
</CustomObject>

cncProd/force-app/main/default/objects/ExclusionList__mdt/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Module of the Item to Exclude</description>
    <label>Module</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Check_In__c.field-meta.xml
<CustomField>
    <fullName>Check_In__c</fullName>
    <label>Check In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
            <value>
                <fullName>Cancel Queue</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/autoCheckIn.cls
/****************************************
* Class Name: autoCheckIn
* Description: Used for Test Drives to auto check-in,
* 				in case the consultants forgot to.
* 
* Revision History:
* Developer Name		Date 			Description
* CGaylan				05-July-2019	Auto-checkin for SC only
***************************************/ 
public without sharing class autoCheckIn Implements Schedulable
{
    //Scheduler
    public void execute(SchedulableContext sc){
        autoCheck();
    }
    
    /****************************************
    * Method Name: autoCheck
    * Description: Auto-checkin the Test Drive vehicle
    * 
    * Parameter: N/A
    * Return:	N/A
    ***************************************/ 
    public void autoCheck(){
        try{
            Set<String> excludeSet = new Set<String>();
            //get profiles to exclude
            for(ExclusionList__mdt exC : [SELECT Id, Label, Module__c 
                                          FROM ExclusionList__mdt 
                                          WHERE Module__c='autoCheckin'])
            {
                excludeSet.add(exC.Label);
            }
            
            Date today=date.today();
            List<Test_Drive__c> tstDriveList = new List<Test_Drive__c>();
            tstDriveList = [SELECT Id, 
                            Status__c, 
                            Check_In__c ,
                            Owner.Profile.Name
                            FROM Test_Drive__c 
                            WHERE Date__c= :today 
                            AND Status__c !='In' 
                           	AND Owner.Profile.Name NOT IN :excludeSet];
            
            if(!tstDriveList.isEmpty()){
                for(Test_drive__c temp : tstDriveList){
                    temp.Status__c= 'In';
                    temp.Check_In__c = DateTime.now();
                }
                update tstDriveList;
            }
        }catch(Exception e){
            loggerDataPool.buildLogDataPool('autoCheckIn', e);
        }
        
    }
}