force-app/main/default/objects/Payment_Receipt__c/Payment_Receipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Receipt__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Franchise_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Mode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Receipt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Amount__c</fullName>
    <label>Receipt Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Date__c</fullName>
    <defaultValue>Today ()</defaultValue>
    <label>Receipt Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Registered_Party__c.field-meta.xml
<CustomField>
    <fullName>Registered_Party__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Registered Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Receipts</relationshipLabel>
    <relationshipName>Payment_Receipts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Balance Payment</fullName>
            </value>
            <value>
                <fullName>Vehicle Deposit</fullName>
            </value>
            <value>
                <fullName>COE Deposit</fullName>
            </value>
            <value>
                <fullName>Refundable Deposit</fullName>
                <isActive>false</isActive>
                <label>Refundable Deposit</label>
            </value>
            <value>
                <fullName>Used Car Payment</fullName>
                <isActive>false</isActive>
                <label>Used Car Payment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Franchise_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CITCV</fullName>
    </customValue>
    <customValue>
        <fullName>CITPC</fullName>
    </customValue>
    <customValue>
        <fullName>KIACV</fullName>
    </customValue>
    <customValue>
        <fullName>KIAPC</fullName>
    </customValue>
    <customValue>
        <fullName>MITCV</fullName>
    </customValue>
    <customValue>
        <fullName>MITPC</fullName>
    </customValue>
    <customValue>
        <fullName>MBCV</fullName>
    </customValue>
    <customValue>
        <fullName>MBPC</fullName>
    </customValue>
    <masterLabel>Franchise Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentReceiptSelectorTest.cls
/*==========================================================================================================================================================================
 * Test selector class for Payment Receipt Entity
 * Created By: Aodigy Team
 * Create Date: September 2022
 * History
 *              DATE::                              BY::                                TICKET::                                            CHANGELOG
 *            21 Sep 2022                       nam@aodigy.com                   
 * ========================================================================================================================================================================== 
 */
@isTest 
public with sharing class PaymentReceiptSelectorTest 
{
    @TestSetup
    static void makeData()
    {       
         // create account supplier
         Account supplier = Test_DataFactory.createAccount(true, 'Supplier Account');

        //Create Payment Receipt
        Payment_Receipt__c paymentReceipt  = new Payment_Receipt__c
        (
            Franchise_Code__c = 'MAXUSCV',
            Payment_Mode__c = 'Credit Card',
            Receipt_Amount__c = 10000,
            Registered_Party__c = supplier.id,
            Receipt_Date__c = Date.today(),
            Type__c = 'Vehicle Deposit',
            Status__c = 'Voided'
        );
        insert paymentReceipt;     
    }

     /**
     * Get Payment Receipt together with Payment Receipt Line Item via correct PR Id
     * Expected: correct Payment Receipt retrieved together with related PRLI
     */
    @IsTest
    private static void getPaymentReceiptByIdWithLineItems_success()
    {
        Payment_Receipt__c paymentReceipt = [SELECT Id FROM Payment_Receipt__c LIMIT 1];
        PaymentReceiptSelector sel = new PaymentReceiptSelector();
        Test.startTest();
            Payment_Receipt__c result = sel.getPaymentReceiptByIdWithLineItems(paymentReceipt.Id,true);
        Test.stopTest();   
    }
}