force-app/main/default/objects/Defect__c/Defect__c.object-meta.xml
<CustomObject>
    <label>Defect</label>
    <nameField>
        <displayFormat>Defect-{000000}</displayFormat>
        <label>Defect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Defect__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Defects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Agreement__c/fields/emailaddress__c.field-meta.xml
<CustomField>
    <fullName>emailaddress__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/Service_Center_Email__c.field-meta.xml
<CustomField>
    <fullName>Service_Center_Email__c</fullName>
    <formula>CASE(TEXT(PreferredServiceCenter__c),
&apos;Alexandra&apos;, CASE(FranchiseCode__c,&apos;MITPC&apos;,&apos;alexmitdefect@cyclecarriage.com.sg&apos;,&apos;KIAPC&apos;,&apos;alexkiadefect@cyclecarriage.com.sg&apos;,
&apos;lengkeedefect@cyclecarriage.com.sg&apos;),
&apos;Eunos&apos;, &apos;eunosdefect@cyclecarriage.com.sg&apos;,
&apos;Pandan Gardens&apos;, &apos;pgdefect@cyclecarriage.com.sg&apos;,
&apos;Sin Ming&apos;, &apos;sinmingdefect@cyclecarriage.com.sg&apos;,
NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Center Email</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/SOH_SONO__c.field-meta.xml
<CustomField>
    <fullName>SOH_SONO__c</fullName>
    <externalId>true</externalId>
    <label>Sales Agreement No</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cncProd/force-app/main/default/classes/DefectFormTemplateCtrl.cls
public with sharing class DefectFormTemplateCtrl {
    @AuraEnabled
    public static void sendEmail(String recordID) {
        EmailTemplate template = getTemplate('VehicleDefectForm');
		EmailTemplate templateAdvisor = getTemplate('VehicleDefectFormAdvisor');

        Sales_Agreement__c currentSA = getSalesAgreement(recordID);
        String emailToSend = currentSA.emailaddress__c;
        String emailToSendAdvisor = currentSA.Service_Center_Email__c;

        List<String> toAddress = new List<String> {emailToSend};
        List<String> toAddressAdvisor = new List<String> {emailToSendAdvisor};

        List<Messaging.EmailFileAttachment> efaList = new List<Messaging.EmailFileAttachment>();
        List<Defect__c> defects = [SELECT Id, Name from Defect__c where Sales_Agreement__c = :recordId];
        if (defects.size() > 0) {
            efaList = getAttachments(recordID, defects);
        }

        // Send email to Customer
        Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(template.Id, null, recordID);
        mail.setSenderDisplayName(currentSA.Owner.Name);
        mail.setToAddresses(toAddress);
        if (!efaList.isEmpty()) {
			mail.setFileAttachments(efaList);
        }

        // Send email to Service Advisor
        Messaging.SingleEmailMessage mailToAdvisor = Messaging.renderStoredEmailTemplate(templateAdvisor.Id, null, recordID);
        mailToAdvisor.setSenderDisplayName(currentSA.Owner.Name);
        mailToAdvisor.setToAddresses(toAddressAdvisor);
        if (!efaList.isEmpty()){
			mailToAdvisor.setFileAttachments(efaList);
        }

        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>{mail, mailToAdvisor};
        //system.debug(allmsg);
        try {
            Messaging.SendEmailResult[] results = Messaging.sendEmail(allmsg, false);
            system.debug(results);
            if (results[0].success) {
                system.debug('Send success');
                system.debug('========= TOTAL OF SENT MAILS =========');
        		system.debug(allmsg.size());
            } else {
                system.debug('Failed to send' + results[0].errors[0].message);
            }
            return;
        } catch (Exception e) {
            system.debug(e.getMessage());
        }
    }

    private static EmailTemplate getTemplate(String templateNm) {
        EmailTemplate template = [SELECT Id, Name, Subject, HtmlValue, Body FROM EmailTemplate WHERE Name = :templateNm];
        return template;
    }

    private static Sales_Agreement__c getSalesAgreement(String recordId) {
        Sales_Agreement__c currentSA = [SELECT Owner.Name, SOH_SONO__c, emailaddress__c, Service_Center_Email__c FROM Sales_Agreement__c WHERE ID = :recordId];
        system.debug(currentSA);
        return currentSA;
    }

    private static List<Messaging.EmailFileAttachment> getAttachments(String recordId, List<Defect__c> defects) {
        // Create a Map contains defectId - defectName (1 key - 1 value)
        Map<Id, String> defectMap = new Map<Id, String>();
        for (Defect__c defect : defects) {
            defectMap.put(defect.Id, defect.Name);
        }

        // Get list files of Defect
        Set<Id> defectIdSet = defectMap.keySet();
        List<ContentDocumentLink> fileResults = [SELECT Id, LinkedEntityId, ContentDocumentId, ContentDocument.LatestPublishedVersionId, Visibility, 
                                                        IsDeleted, ShareType, ContentDocument.Title, ContentDocument.createdDate, ContentDocument.FileType 
                                                 FROM ContentDocumentLink 
                                                 WHERE LinkedEntityId IN :defectIdSet AND ContentDocument.Title LIKE '%_01%'
                                                 ORDER BY ContentDocument.createdDate DESC NULLS LAST];

        // Create a Map contains 1 LinkedEntityId - 1 ContentDocumentLink
        Map<Id, ContentDocumentLink> entityCDLMap = new Map<Id, ContentDocumentLink>();
        for (ContentDocumentLink file : fileResults) {
            if (!entityCDLMap.containsKey(file.LinkedEntityId)) {
                entityCDLMap.put(file.LinkedEntityId, file);
            }
        }

        // Create a Map contains 1 ContentDocumentId - 1 Defect Name
        Map<Id, String> cdlDefectMap = new Map<Id, String>();
        for (ContentDocumentLink file : entityCDLMap.values()) {
            cdlDefectMap.put(file.ContentDocumentId, defectMap.get(file.LinkedEntityId));
        }

        // Get list ContentVersion of ContentDocumentLink
        Set<Id> cdlDefectSet = cdlDefectMap.keySet();
        List<ContentVersion> cvs = [SELECT VersionData, ContentModifiedDate, ContentDocumentId
                                    FROM ContentVersion
                                    WHERE ContentDocumentId IN :cdlDefectSet
                                    ORDER BY ContentModifiedDate];

        // Create a Map contains 1 ContentDocumentLink - 1 VersionData
        Map<Id, Blob> cdlCVSMap = new Map<Id, Blob>();
        for (ContentVersion cv : cvs) {
            cdlCVSMap.put(cv.ContentDocumentId, cv.VersionData);
        }

        // Prepare list attachments for email 
        List<Messaging.EmailFileAttachment> efaList = new List<Messaging.EmailFileAttachment>();
        if (!entityCDLMap.isEmpty()) {
            for (ContentDocumentLink file : entityCDLMap.values()) {
                Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                efa.setFileName(cdlDefectMap.get(file.ContentDocumentId) + '.' + file.ContentDocument.FileType);
                efa.setBody(cdlCVSMap.get(file.ContentDocumentId));
                efa.setContentType('application/' + file.ContentDocument.FileType);
                efaList.add(efa);
            }
        }

        return efaList;
    }
}