cncProd/force-app/main/default/objects/Used_Car_Quote__c/Used_Car_Quote__c.object-meta.xml
<CustomObject>
    <label>Used Car Quote</label>
    <nameField>
        <displayFormat>UCQ-{000000}</displayFormat>
        <label>Used Car Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Used Car Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Used_Car_Quote__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <label>Chassis No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Customer_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID_Type__c</fullName>
    <label>Customer ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business (e.g. 51234567M)</fullName>
                <label>Business</label>
            </value>
            <value>
                <fullName>Club/Association/Organisation (e.g. T08PQ1234A)</fullName>
                <label>Club/Association/Organisation</label>
            </value>
            <value>
                <fullName>Company (e.g. 198912345K)</fullName>
                <label>Company</label>
            </value>
            <value>
                <fullName>Foreign Company (e.g. T08FC1234A)</fullName>
                <label>Foreign Company</label>
            </value>
            <value>
                <fullName>Foreign Identification Number (e.g. F/G/M1234567N)</fullName>
                <label>Foreign Identification Number</label>
            </value>
            <value>
                <fullName>Foreign Passport (e.g. 12345678)</fullName>
                <label>Foreign Passport</label>
            </value>
            <value>
                <fullName>Government (e.g. T08GA1234A)</fullName>
                <label>Government</label>
            </value>
            <value>
                <fullName>Limited Liability Partnership (e.g. T08LL1234A)</fullName>
                <label>Limited Liability Partnership</label>
            </value>
            <value>
                <fullName>Limited Partnership (e.g. T08LP1234A)</fullName>
                <label>Limited Partnership</label>
            </value>
            <value>
                <fullName>Malaysia NRIC (e.g. 200312345678)</fullName>
                <label>Malaysia NRIC</label>
            </value>
            <value>
                <fullName>Professional (e.g. T08PQ1234A)</fullName>
                <label>Professional</label>
            </value>
            <value>
                <fullName>Singapore NRIC (e.g. S1234567D)</fullName>
                <default>true</default>
                <label>Singapore NRIC</label>
            </value>
            <value>
                <fullName>Statutory Board (e.g. T08GB1234A)</fullName>
                <label>Statutory Board</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Customer_NRIC__c.field-meta.xml
<CustomField>
    <fullName>Customer_NRIC__c</fullName>
    <inlineHelpText>Input last 4 characters (e.g. 567D)</inlineHelpText>
    <label>Customer NRIC</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Intended_Deregistration_Date__c.field-meta.xml
<CustomField>
    <fullName>Intended_Deregistration_Date__c</fullName>
    <label>Intended Deregistration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Vehicle_No__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_No__c</fullName>
    <label>Vehicle No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/RAP_UpdateMachinePriceAPITest.cls
/** *****
 * Description : Test Class for RAP_UpdateMachinePriceAPI class
 * 
 * Change History
 * Date(YYYYMMDD)       Name                        Description
 * 20220425             tan.nguyen@aodigy.com       Created Initial Version. 
 * 
** *****/

@isTest
private class RAP_UpdateMachinePriceAPITest {
    @TestSetup
    private static void setUp(){
        Used_Car_Quote__c ucq = new Used_Car_Quote__c();
        ucq.recordTypeId = UsedCarQuoteService.getMFRecordTypeId();
        ucq.Chassis_No__c = '12321';
        ucq.Vehicle_No__c = 'AB423nv';
        ucq.Intended_Deregistration_Date__c = Date.today();
        ucq.Customer_ID_Type__c = Used_Car_Quote__c.Customer_ID_Type__c.getDescribe().getPicklistValues()[1].getValue();
        ucq.Customer_NRIC__c = 'HIHI';
        ucq.Status__c = 'Open';
        insert ucq;
    }

    @isTest 
    private static void testUpdateMachinePrice_Success() {
        Used_Car_Quote__c testQuote = [SELECT Id FROM Used_Car_Quote__c];
        String reqBody = '{"QuoteID": "'+ testQuote.Id +'", "MachineQuote": 70000, "Depreciation": 5000}';
        Test.startTest();
        String reqURI = '/UsedCarQuote/updateMachinePrice/*';
        Test_DataFactory.createReqSF(reqURI, 'POST', reqBody, null, 200);
        RAP_UpdateMachinePriceAPI.doPost();
        Test.stopTest();
    }

    @isTest
    private static void testUpdateMachinePrice_missingField() {
        Used_Car_Quote__c testQuote = [SELECT Id FROM Used_Car_Quote__c];
        String reqBody = '{"QuoteID": "", "MachineQuote": 70000, "Depreciation": 5000}';
        Test.startTest();
        String reqURI = '/UsedCarQuote/updateMachinePrice/*';
        Test_DataFactory.createReqSF(reqURI, 'POST', reqBody, null, 200);
        RAP_UpdateMachinePriceAPI.doPost();
        Test.stopTest();
    }

    @isTest 
    private static void testUpdateMachinePrice_invalidQuoteId() {
        Used_Car_Quote__c testQuote = [SELECT Id FROM Used_Car_Quote__c];
        String reqBody = '{"QuoteID": "a2nO000000B8Yk4IAJ", "MachineQuote": 70000, "Depreciation": 5000}';
        Test.startTest();
        String reqURI = '/UsedCarQuote/updateMachinePrice/*';
        Test_DataFactory.createReqSF(reqURI, 'POST', reqBody, null, 200);
        RAP_UpdateMachinePriceAPI.doPost();
        Test.stopTest();
    }
    
    @isTest 
    private static void testUpdateMachine_exception() {
        Used_Car_Quote__c testQuote = [SELECT Id FROM Used_Car_Quote__c];
        String reqBody = '"QuoteID": "'+ testQuote.Id +'", "MachineQuote": 70000, "Depreciation": 5000';
        Test.startTest();
        String reqURI = '/UsedCarQuote/updateMachinePrice/*';
        Test_DataFactory.createReqSF(reqURI, 'POST', reqBody, null, 200);
        RAP_UpdateMachinePriceAPI.doPost();
        Test.stopTest();
    }
}