cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Chasis_Number__c.field-meta.xml
<CustomField>
    <fullName>Chasis_Number__c</fullName>
    <externalId>true</externalId>
    <label>Chasis Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/InvoiceEmail_RV_VIN.cls
public class InvoiceEmail_RV_VIN {

    public String rv_id{get;set;}
    
    public String VIN_Val{
        get
        {
            List<Registered_Vehicle__c> RVList = [SELECT Chasis_Number__c FROM Registered_Vehicle__c WHERE Registration_Number__c=:rv_id];
            if(RVList <> null && RVList.size()>0)
            {
                VIN_Val = RVList[0].Chasis_Number__c;
            }
            else
            {
                VIN_Val = '';
            }
                
            return VIN_Val;
        }
        set;
    }   

    public void InvoiceEmail_RV_VIN() {}
    
}