cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>Franchise__c</fullName>
    <label>Franchise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Reg_plus_5days__c.field-meta.xml
<CustomField>
    <fullName>Reg_plus_5days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reg_plus_5days</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>Registered_Date__c</fullName>
    <label>Registered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/ReferralProgramBatchJobTest.cls
@isTest
private class ReferralProgramBatchJobTest {
    
    @testSetup static void setup() {
 		//Preparing test data
       Contact testContact = new Contact (LastName = 'TestContact1');
       insert testContact;
       
       Date dt = Date.today() - 5;
        
        
       Registered_Vehicle__c testRegVehicle = new Registered_Vehicle__c( 	Registered_Date__c = dt,
                                                                       	 	Name = 'TestCar',
                                                                       		Branch__c = 'CCA',
                                                                       		Franchise__c = 'MITCV',
                                                                        	Registration_Number__c = '1232',
                                                                       		Contact__c = testContact.id);
        
        insert testRegVehicle;
        system.debug('Inserted DATE' + testRegVehicle.Registered_Date__c);  
    }
    
    static testmethod void schedulerTest(){
       
        String CRON_EXP = '0 0 0 15 3 ? *';

        Test.startTest();

            String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new ScheduleReferralProgram());
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(CRON_EXP, ct.CronExpression);
            System.assertEquals(0, ct.TimesTriggered);

        Test.stopTest();

    }
    
    static testmethod void batchExecuteTest(){
       
        String CRON_EXP = '0 0 0 15 3 ? *';

        Test.startTest();
          BatchReferralProgram batchJob = new BatchReferralProgram();
          database.executebatch(batchJob);
        Test.stopTest();
        
        LIST<Registered_Vehicle__c> result = [SELECT Id, Registered_Date__c, Reg_plus_5days__c from Registered_Vehicle__c];
  		System.assertEquals(true, result[0].Reg_plus_5days__c);
    }

}