cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/IsOwnerChanged__c.field-meta.xml
<CustomField>
    <fullName>IsOwnerChanged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to tell if Owner has Changed (aside from the Contact__c field update)</description>
    <label>Is Owner Changed?</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/OwnerChangeTimeStamp__c.field-meta.xml
<CustomField>
    <fullName>OwnerChangeTimeStamp__c</fullName>
    <description>Date when last owner change was done.</description>
    <label>Owner Change Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Packages__c/Service_Packages__c.object-meta.xml
<CustomObject>
    <label>Service Package</label>
    <nameField>
        <label>Service Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Packages</relationshipLabel>
    <relationshipName>Service_Packages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status if the Service Package Item is still active.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/BatchDeactivateServicePackage.cls
/****************************************************
* Class Name: BatchDeactivateServicePackage
* Description: Batch class to set the 
*			   Service Package Status__c to Inactive
* 
****************************************************/ 
public class BatchDeactivateServicePackage implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable{

    //
    public Database.QueryLocator start(Database.BatchableContext db){
        return Database.getQueryLocator([SELECT 
        									Id, 
                                         	Status__c
                                         FROM Service_Packages__c
                                         WHERE Registered_Vehicle__c != null
                                         AND Registered_Vehicle__r.IsOwnerChanged__c = true
                                         AND Registered_Vehicle__r.OwnerChangeTimeStamp__c = TODAY 
                                         ]);
    }
    
    public void execute(Database.BatchableContext db, List<Service_Packages__c> scope){
        if(scope != null && !scope.isEmpty()){
            try{
                for(Service_Packages__c sPack : scope){
                    sPack.Status__c = 'Inactive';
                }
                
                update scope;
            }catch(Exception e){
                loggerDataPool.buildLogDataPool('BatchDeactivateServicePackage', e);
            }

        }     
    }
    
    public void finish(Database.BatchableContext db){
        batchDataPool.buildBatchDataPool('BatchDeactivateServicePackage', db.getJobId());
    }
    
    
    //execute Schedule
    public void execute (SchedulableContext ctx){   
        //Set Initial Test Run
        //Batch Set to Run at Default Batch Size.
        try{
            BatchManager bm = new BatchManager('BatchDeactivateServicePackage',null);
        }catch(Exception e){
            loggerDataPool.buildLogDataPool('BatchDeactivateServicePackage', e);
        }
        
    }     
}