cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Preferred_Car_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Car_Name__c</fullName>
    <label>Preferred Car Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Variant__c/fields/Variant_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Variant_Display_Name__c</fullName>
    <label>Variant Display Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdatePrefCarName.cls
global class UpdatePrefCarName implements Schedulable{

global void execute(SchedulableContext ctx)
{GetData();}


public static void GetData()            
{
    List<Registered_Vehicle__c> regVehList = [Select id, Preferred_Car_Name__c, Variant__r.Variant_Display_Name__c from Registered_Vehicle__c where Preferred_Car_Name__c = null LIMIT 10000];
    for(Registered_Vehicle__c regVeh : regVehList) {
        if(regVeh.Variant__r != null && regVeh.Variant__r.Variant_Display_Name__c != null) {
        regVeh.Preferred_Car_Name__c = regVeh.Variant__r.Variant_Display_Name__c;
        }
    }
    update regVehList;    
} 

}