cncProd/force-app/main/default/objects/MB_Sales_Agreement__c/MB_Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>MB Sales Agreement</label>
    <nameField>
        <displayFormat>MBSA-{000000}</displayFormat>
        <label>MB Sales Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/MB_Sales_Agreement__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <formula>MB_Stock_Vehicle_Master__r.Colour__c</formula>
    <label>Colour</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MB_Sales_Agreement__c/fields/MB_Stock_Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>MB_Stock_Vehicle_Master__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MB Stock Vehicle Master</label>
    <referenceTo>MB_Stock_Vehicle_Master__c</referenceTo>
    <relationshipLabel>MB Sales Agreements</relationshipLabel>
    <relationshipName>MB_Sales_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MB_Sales_Agreement__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>MB_Stock_Vehicle_Master__r.Model__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MB_Sales_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Waiting for Confirmation</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Balance Payment</fullName>
            </value>
            <value>
                <fullName>Pending Registration</fullName>
            </value>
            <value>
                <fullName>Ready for Delivery</fullName>
            </value>
            <value>
                <fullName>Car Collected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/MB_Sales_Agreement__c/fields/Trim__c.field-meta.xml
<CustomField>
    <fullName>Trim__c</fullName>
    <formula>MB_Stock_Vehicle_Master__r.Trim__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trim</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Sales_Agreement__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <formula>MB_Stock_Vehicle_Master__r.VariantDescription__c</formula>
    <label>Variant</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Stock_Vehicle_Master__c/MB_Stock_Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>MB Stock Vehicle Master</label>
    <nameField>
        <displayFormat>MBSVM-{000000}</displayFormat>
        <label>MB Stock Vehicle Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Stock Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>Variant__r.Model_ID__r.Name</formula>
    <label>Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>MB Stock Vehicle Masters</relationshipLabel>
    <relationshipName>MB_Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Vehicle_ID__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID</inlineHelpText>
    <label>Vehicle ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Variant__c/fields/Allow_Indent__c.field-meta.xml
<CustomField>
    <fullName>Allow_Indent__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Allow Sales Executive to indent order for this variant</inlineHelpText>
    <label>Allow Indent</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <externalId>true</externalId>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>Franchise__c</fullName>
    <label>Franchise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Model_ID__c.field-meta.xml
<CustomField>
    <fullName>Model_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model_ID</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/WM_Form__mdt/WM_Form__mdt.object-meta.xml
<CustomObject>
    <label>WM Form</label>
    <pluralLabel>WM Forms</pluralLabel>
</CustomObject>

force-app/main/default/classes/WMFormCtrlTest.cls
@isTest
private class WMFormCtrlTest {
    @testSetup
    static void setUp() {
        // Create Model
        Model__c model = Test_DataFactory.createmodelId(true, 'MB A Class Test', 'CCI', 'MBP');
        // Create Variant
        Variant__c variant = new Variant__c(Name = 'MB A 250 Test',
                                           Model_ID__c = model.Id,
                                           Franchise__c = 'MBP',
                                           Branch__c = 'CCI',
                                           Allow_Indent__c = false,
                                           Description__c = 'MB A 250 Test',
                                           Active__c = true);
        insert variant;
        // Create MB Stock Vehicle Master
        MB_Stock_Vehicle_Master__c mbSVM = new MB_Stock_Vehicle_Master__c(Vehicle_ID__c = '1',
                                                                         Status__c = 'Open',
                                                                         Variant__c = variant.Id,
                                                                         Colour__c = '787 Mountain Grey',
                                                                         Trim__C = '101 ARTICO Black');
        insert mbSVM;
        MB_Sales_Agreement__c mbSA = new MB_Sales_Agreement__c();
        mbSA.MB_Stock_Vehicle_Master__c = mbSVM.Id;
        insert mbSA;
    }

	@isTest
    static void Test_getForms() {
        MB_Sales_Agreement__c mbSA = [SELECT ID, Name FROM MB_Sales_Agreement__c];
        Test.startTest();
        List<WM_Form__mdt> wmFormMdts = WMFormCtrl.getForms(mbSA.Id);
        system.assert(wmFormMdts.size() > 0);
        Test.stopTest();
    }

    @isTest
    static void Test_generateForm() {
        MB_Sales_Agreement__c mbSA = [SELECT ID, Name FROM MB_Sales_Agreement__c];
        Test.startTest();
        Boolean mergeSuccess = WMFormCtrl.generateForm(mbSA.Id, '');
        system.assertEquals(true, mergeSuccess);
        Test.stopTest();
    }

}