force-app/main/default/objects/Package_Accs__c/Package_Accs__c.object-meta.xml
<CustomObject>
    <label>Package Accs</label>
    <nameField>
        <displayFormat>PA-{0000000000}</displayFormat>
        <label>Package Accs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Accs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Accs__c/fields/Package_Header__c.field-meta.xml
<CustomField>
    <fullName>Package_Header__c</fullName>
    <label>Package Header</label>
    <referenceTo>Package_Header__c</referenceTo>
    <relationshipLabel>Package Accs</relationshipLabel>
    <relationshipName>Package_Accs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/Package_Header__c.object-meta.xml
<CustomObject>
    <label>Package Header</label>
    <nameField>
        <displayFormat>PH-{0000000000}</displayFormat>
        <label>Package Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Header</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Header__c/fields/PKH_FRN_FRNCD__c.field-meta.xml
<CustomField>
    <fullName>PKH_FRN_FRNCD__c</fullName>
    <label>Franchise Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Package_Header__c/fields/PKH_PKGPRICE__c.field-meta.xml
<CustomField>
    <fullName>PKH_PKGPRICE__c</fullName>
    <label>Package Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Package_Header__c/fields/PKH_STATUS__c.field-meta.xml
<CustomField>
    <fullName>PKH_STATUS__c</fullName>
    <label>Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/PackageAccsSelectorTest.cls
@isTest
private class PackageAccsSelectorTest {
    @testSetup
    static void setUp() {
        Package_Header__c pckHeader = new Package_Header__c(PKH_FRN_FRNCD__c = 'KIAPC', PKH_STATUS__c='A',PKH_PKGPRICE__c=1000000);
        insert pckHeader;
        
        Package_Accs__c pckAcc = new Package_Accs__c(Package_Header__c = pckHeader.Id);
        insert pckAcc;
    }
    
    @isTest
    static void testSelectByPackageHeaderId() {
        Package_Header__c pckHeader = [Select Id from Package_Header__c];
        PackageAccsSelector pckAccsSel = new PackageAccsSelector();
        List<Package_Accs__c> pckAcc = pckAccsSel.selectByPackageHeaderId(pckHeader.Id);
        System.assertEquals(1, pckAcc.size());
    }
    
    @isTest
    static void testSelectByPackageHeaderIds() {
        Package_Header__c pckHeader = [Select Id from Package_Header__c];
        Set<Id> ids = new Set<Id>();
        ids.add(pckHeader.Id);
        PackageAccsSelector pckAccsSel = new PackageAccsSelector();
        List<Package_Accs__c> pckAcc = pckAccsSel.selectByPackageHeaderIds(ids);
        System.assertEquals(1, pckAcc.size());
    }
}