force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancel Remarks</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Re_Reserve_To_VSMS__c.field-meta.xml
<CustomField>
    <fullName>Re_Reserve_To_VSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-Reserve To VSMS?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Status__c</fullName>
    <label>Stock Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reserve</fullName>
                <default>true</default>
                <label>Reserve</label>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Indent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchToReReserveStockReservation.cls
/*
	Author: Hari Panneerselvam
*/
global class BatchToReReserveStockReservation implements Database.Batchable<sObject>, Schedulable, Database.Stateful{
	
	public String queryString = '';
	public String batchForDataPool = '';
	
	public BatchToReReserveStockReservation(String batchFor){
		batchForDataPool = batchFor;
		queryString = Queries.reReserveStockReservation;
	}
	
	global Database.QueryLocator start(Database.BatchableContext bc){
		return database.getQueryLocator(queryString);
	}
	 
	global void execute(Database.BatchableContext bc, list<Stock_Reservation__c> lstStockReservation){ 
		for(Stock_Reservation__c itr : lstStockReservation){
			itr.Reservation_Status__c = 'Reserve';
			itr.Cancellation_Reason__c = '';
			itr.Re_Reserve_To_VSMS__c = true;
		}
		update lstStockReservation; 
	}
	
	global void finish(Database.BatchableContext bc){
		JSONGenerator jsonGen = JSON.createGenerator(true);//Pass empty JSON if parameter is not required.
		new BatchManager('BatchToUpdateSRToVSMS', jsonGen);
    	batchDataPool.buildBatchDataPool(batchForDataPool, bc.getJobId());
    }
    
    global void execute(SchedulableContext sc){
	 	JSONGenerator jsonGen = JSON.createGenerator(true);//Pass empty JSON if parameter is not required.
        new BatchManager('BatchToReReserveStockReservation', jsonGen);
	}
    
}