force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Reservation__c/fields/Agreement_No__c.field-meta.xml
<CustomField>
    <fullName>Agreement_No__c</fullName>
    <label>Agreement No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancel Remarks</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Color Code</label>
    <referenceTo>Color_Master__c</referenceTo>
    <relationshipLabel>Stock Reservations</relationshipLabel>
    <relationshipName>Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Code</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Stock Reservations</relationshipLabel>
    <relationshipName>Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Model_Year_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Year_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Year Code</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Model_Year_Master__c.Model_Master__c</field>
            <operation>equals</operation>
            <valueField>$Source.Model_Code__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Model_Year_Master__c</referenceTo>
    <relationshipLabel>Stock Reservations</relationshipLabel>
    <relationshipName>Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Status__c</fullName>
    <label>Stock Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reserve</fullName>
                <default>true</default>
                <label>Reserve</label>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Indent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/fields/Trim_Code__c.field-meta.xml
<CustomField>
    <fullName>Trim_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trim Code</label>
    <referenceTo>Trim_Master__c</referenceTo>
    <relationshipLabel>Stock Reservations</relationshipLabel>
    <relationshipName>Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Stock_Reservation__c/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Master</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Vehicle_Master2__c.Color_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Color_Code__c</valueField>
        </filterItems>
        <filterItems>
            <field>Vehicle_Master2__c.Model_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Model_Code__c</valueField>
        </filterItems>
        <filterItems>
            <field>Vehicle_Master2__c.Trim_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Trim_Code__c</valueField>
        </filterItems>
        <filterItems>
            <field>Vehicle_Master2__c.Model_Year_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Model_Year_Code__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vehicle_Master2__c</referenceTo>
    <relationshipLabel>Stock Reservations</relationshipLabel>
    <relationshipName>Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Color Code</label>
    <referenceTo>Color_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Code</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Year_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Year_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Year Code</label>
    <referenceTo>Model_Year_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Reservation_No__c.field-meta.xml
<CustomField>
    <fullName>Reservation_No__c</fullName>
    <label>Reservation No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/System_Commcase__c.field-meta.xml
<CustomField>
    <fullName>System_Commcase__c</fullName>
    <label>System Commcase</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Trim_Code__c.field-meta.xml
<CustomField>
    <fullName>Trim_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trim Code</label>
    <referenceTo>Trim_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>Vehicle Master</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/StockReservationPost.cls
@RestResource(urlMapping='/StockReservation/*')
global without sharing class StockReservationPost {
    @HttpPost
    global static void getPost(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.responseBody = Blob.valueOf('NOT OK, Action not recognize');
        
        HttpResponse rese=new HttpResponse();
        
        String Action = req.params.get('Action');
        String ID = req.params.get('ID');
        String Status = req.params.get('Status');
        String AgreementNo = req.params.get('AgreementNo');
        String CommCase = req.params.get('CommCase');
        String CancelReason = req.params.get('CancelReason');
        
        Stock_Reservation__c SR=new Stock_Reservation__c();
        List<Stock_Reservation__c> CMList =[select Id from Stock_Reservation__c where id=:ID];
        if (Action=='Update' || Action=='Change'){
            if(CMList.size()<= 0){
                res.responseBody = Blob.valueOf('NOT OK,No Record To Update');
            }
        }
        try{
            if (Action=='Update'){
                //just update
                SR=[select id,Reservation_Status__c,Agreement_No__c from Stock_Reservation__c where id=:ID];
                SR.Reservation_Status__c=Status;
                SR.Agreement_No__c=AgreementNo;
                if (Status=='Cancel'){
                    SR.Cancellation_Reason__c=CancelReason;
                }
                update SR;
                res.responseBody = Blob.valueOf('OK');
            }
            if (Action=='Change'){
                //update and change the vehicle
                SR=[select id,Reservation_Status__c,Agreement_No__c,Vehicle_Master__c,Name,Model_Code__c,Model_Year_Code__c,Trim_Code__c,Color_Code__c,Cancellation_Reason__c from Stock_Reservation__c where id=:ID];
                SR.Reservation_Status__c=Status;
                SR.Agreement_No__c=AgreementNo;
                //List <Vehicle_Master2__c> lsvm=[select id,Reservation_No__c from Vehicle_Master2__c where System_Commcase__c=:CommCase and Reservation_No__c!=''];
                List <Vehicle_Master2__c> lsvm=[select id,Reservation_No__c from Vehicle_Master2__c where System_Commcase__c=:CommCase];
                if (lsvm.size()>0){
                    if (lsvm[0].Reservation_No__c!=null){
                        res.responseBody = Blob.valueOf('COMCASE '+CommCase+' alredy in use.');
                    }else{
                        List <Vehicle_Master2__c> listToUpdate=new List <Vehicle_Master2__c>();
                        
                        if (SR.Vehicle_Master__c!=null){
                            Vehicle_Master2__c ovm=[select id,Reservation_No__c,Model_Code__c,Model_Year_Code__c,Trim_Code__c,Color_Code__c from Vehicle_Master2__c where id=:SR.Vehicle_Master__c];
                            ovm.Reservation_No__c='';
                            listToUpdate.add(ovm);
                        }
                        
                        Vehicle_Master2__c nvm=[select id,Reservation_No__c,Model_Code__c,Model_Year_Code__c,Trim_Code__c,Color_Code__c from Vehicle_Master2__c where System_Commcase__c=:CommCase limit 1];
                        nvm.Reservation_No__c=SR.Name;
                        listToUpdate.add(nvm);
                        
                        SR.Model_Code__c=nvm.Model_Code__c;
                        SR.Model_Year_Code__c=nvm.Model_Year_Code__c;
                        SR.Trim_Code__c=nvm.Trim_Code__c;
                        SR.Color_Code__c=nvm.Color_Code__c;
                        SR.Vehicle_Master__c=nvm.id;
                        if (Status=='Cancel'){
                            SR.Cancellation_Reason__c=CancelReason;
                        }
                        update listToUpdate; 
                        update SR;
                        res.responseBody = Blob.valueOf('OK');
                    }
                }else{
                    //res.responseBody = Blob.valueOf('COMCASE '+CommCase+' alredy in use.');
                    res.responseBody = Blob.valueOf('No Vehicle with this commcase '+CommCase);
                }
            }   
        }catch(Exception e) {
            res.responseBody = Blob.valueOf('The following exception has occurred: ' + e.getMessage());
            System.debug('The following exception has occurred: ' + e.getMessage());
            //send email eror
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            List<String> idList = new List<String>();
            List<String> mailToAddresses = new List<String>();
            Group g = [SELECT (select userOrGroupId from groupMembers) FROM group WHERE name = 'VSMS Admin'];
            for (GroupMember gm : g.groupMembers) {
                idList.add(gm.userOrGroupId);
            }
            User[] usr = [SELECT email FROM user WHERE id IN :idList];
            for(User u : usr) {
                mailToAddresses.add(u.email);
            }
            mail.setToAddresses(mailToAddresses);
            mail.setSubject('Stock Reservation Eror');
            mail.setPlainTextBody(e.getMessage());
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}