cncProd/force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>false</active>
    <description>Business Account Fleet</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{YYMM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Invoice__c/recordTypes/E_Shop_Payment_RT.recordType-meta.xml
<RecordType>
    <fullName>E_Shop_Payment_RT</fullName>
    <active>true</active>
    <label>E-Shop Payment RT</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>OrderID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <label>Shop</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MIT e-shop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/recordTypes/C_C_E_Shop.recordType-meta.xml
<RecordType>
    <fullName>C_C_E_Shop</fullName>
    <active>true</active>
    <description>C&amp;C E-Shop</description>
    <label>C&amp;C E-Shop</label>
</RecordType>

cncProd/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>Customer&apos;s Reward Credit 
- per Reward Type
- per Registered Vehicle
- per Expiry Date</description>
    <label>Reward</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward__c/fields/Reward_Profile__c.field-meta.xml
<CustomField>
    <fullName>Reward_Profile__c</fullName>
    <label>Reward Profile</label>
    <referenceTo>Reward_Profile__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/Reward_Profile__c.object-meta.xml
<CustomObject>
    <label>Reward Profile</label>
    <nameField>
        <label>Reward Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_Profile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Boutique</fullName>
            </value>
            <value>
                <fullName>Birthday Voucher</fullName>
            </value>
            <value>
                <fullName>Grooming Package</fullName>
            </value>
            <value>
                <fullName>Service Credit Voucher</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>Discount Voucher</fullName>
            </value>
            <value>
                <fullName>Service Credit</fullName>
            </value>
            <value>
                <fullName>Accessories Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Business Account (Staff, Leasing), Person Account</description>
    <label>C&amp;C Fleet</label>
</RecordType>

cncProd/force-app/main/default/objects/Reward_Usage__c/Reward_Usage__c.object-meta.xml
<CustomObject>
    <label>Reward Usage</label>
    <nameField>
        <label>Reward Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_Usage__c/fields/Autoline_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Autoline_Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <label>Autoline Invoice Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eShop</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward_Usage__c.field-meta.xml
<CustomField>
    <fullName>Reward_Usage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Reference to Debit Reward Usage record</description>
    <label>Reward Usage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Reward_Usage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Debit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Reward_Usage__c</referenceTo>
    <relationshipLabel>Credit Usages</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Expiry</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Credit to Customer (i.e. Refund/Adjustment/etc.)</description>
    <label>Credit</label>
</RecordType>

force-app/main/default/objects/Reward_Usage__c/recordTypes/Debit.recordType-meta.xml
<RecordType>
    <fullName>Debit</fullName>
    <active>true</active>
    <description>Debit from Customer (i.e. Credit Deduction)</description>
    <label>Debit</label>
</RecordType>

cncProd/force-app/main/default/classes/PaymentSelector_Test.cls
/** ******
 * Description : Test class for PaymentSelector.cls
 * 
 * Change History:
 * Date(YYYYMMDD)       Name            Description
 * 20200708             TP@aodigy       Created Initial Version. 
 * 
** ******/
@isTest
private class PaymentSelector_Test 
{   
    @testSetup
    static void setUp(){
        Account acct = Test_DataFactory.createAccount(true, 'Company');
        Contact con = Test_DataFactory.createContact(true, 'Test', 'Test', acct.Id);
        
        Order__c order = Test_DataFactory.createOrder(Schema.SObjectType.Order__c.getRecordTypeInfosByDeveloperName().get('C_C_E_Shop').getRecordTypeId());
        order.Shop__c = 'KIA';
        insert order;
        
        Reward_Profile__c rewardProfile = Test_DataFactory.createRewardProfile(true, 'Fleet', 'CCK', 'KIA', 'Accessories Credit');
        Reward__c reward = Test_DataFactory.createReward(true, rewardProfile.Id, rewardProfile.Type__c, 'Valid', Date.today().addDays(15));
        Reward_Usage__c rewardUsage = Test_DataFactory.createRewardUsage(false, reward.Id, 'Utilised', 'Debit');
        rewardUsage.Order__c = order.id;
        rewardUsage.Autoline_Invoice_Number__c = 'ABC123456';
        rewardUsage.Channel__c = 'eShop';
        insert rewardUsage;   
    }
    
    @isTest
    static void Test_selectPaymentsByIds()
    {
        Reward_Usage__c usage = [Select id, Payment__c from Reward_Usage__c];
        PaymentSelector sel = new PaymentSelector();
        sel.selectPaymentsByIds(new Set<Id> {usage.Payment__c});
    }
    
    @isTest
    static void Test_selectPaymentsByOrderId()
    {
        Reward_Usage__c usage = [Select id, Order__r.OrderID__c from Reward_Usage__c];
        PaymentSelector sel = new PaymentSelector();
        sel.selectPaymentsByOrderId(usage.Order__r.OrderID__c);
    }
    
    @isTest
    static void Test_selectPaymentsByTypeAndDateFiters()
    {
        PaymentSelector sel = new PaymentSelector();
        List<Invoice__c> payments = sel.selectPaymentsByTypeAndDateFiters(new Set<Id>{Schema.SObjectType.Invoice__c.getRecordTypeInfosByDeveloperName().get('E_Shop_Payment_RT').getRecordTypeId()}, 
                                              new Set<String>{'Accessories Credit'}, new Set<String>{'Purchase'}, Date.today().addDays(-15));
        System.assertEquals(1, payments.size());
    }

}