cncProd/force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>false</active>
    <description>Business Account Fleet</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>Customer&apos;s Reward Credit 
- per Reward Type
- per Registered Vehicle
- per Expiry Date</description>
    <label>Reward</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Reward__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Reward_Profile__c.field-meta.xml
<CustomField>
    <fullName>Reward_Profile__c</fullName>
    <label>Reward Profile</label>
    <referenceTo>Reward_Profile__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/Reward_Profile__c.object-meta.xml
<CustomObject>
    <label>Reward Profile</label>
    <nameField>
        <label>Reward Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Reward_Profile__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only set this value for Fleet-typed profile</description>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Reward Profiles</relationshipLabel>
    <relationshipName>Reward_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Boutique</fullName>
            </value>
            <value>
                <fullName>Birthday Voucher</fullName>
            </value>
            <value>
                <fullName>Grooming Package</fullName>
            </value>
            <value>
                <fullName>Service Credit Voucher</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>Discount Voucher</fullName>
            </value>
            <value>
                <fullName>Service Credit</fullName>
            </value>
            <value>
                <fullName>Accessories Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Business Account (Staff, Leasing), Person Account</description>
    <label>C&amp;C Fleet</label>
</RecordType>

force-app/main/default/objects/Reward_Profile__c/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <description>Business Account (Fleet)</description>
    <label>C&amp;C Individual</label>
</RecordType>

cncProd/force-app/main/default/classes/CMGetRewardProfileAPITest.cls
/** *****
 * Description : Test Class for CMGetRewardProfileAPI.cls
 * 
 * Change History
 * Date(YYYYMMDD)       Name                            Description
 * 20200706             khanh.do@aodigy.com             Created Initial Version. 
 * 
** *****/
@isTest
private class CMGetRewardProfileAPITest {
    @testSetUp
    private static void createData(){
        Account dummyAcc = Test_DataFactory.createAccount(true, 'Company');
        Contact dummyCon = Test_DataFactory.createContact(true, 'Test', 'Test', dummyAcc.Id);
       
        Registered_Vehicle__c dummyRegVeh = Test_DataFactory.createRegVehicle(true, 'Fake Name', 'CCK', 'KIAPC', 'Fake No 1', dummyCon.Id);
        
        Reward_Profile__c fleetRewardProfile = Test_DataFactory.createRewardProfile(false, 'Fleet', 'CCK', 'KIA', 'Accessories Credit');
        fleetRewardProfile.Registered_Vehicle__c = dummyRegVeh.Id;
        insert fleetRewardProfile;
        Reward__c reward = Test_DataFactory.createReward(true, fleetRewardProfile.Id, fleetRewardProfile.Type__c, 'Valid', Date.today().addDays(15));
    }
    
    @isTest
	private static void testGetRewardProfile_FleetType_HappyPath(){
        String regVehNo = [SELECT Name FROM Registered_Vehicle__c LIMIT 1].Name;
        String brand = 'KIA';
        Test.startTest();
        String reqURI = '/RewardProfiles/retrieve/*'; 
        String reqBody = '{"ProfileType": "Fleet","UserId": "","VehNumber": "'+regVehNo+'","Brand": "'+ brand +'"}}';
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CMGetRewardProfileAPI.getRewardProfiles();
        Test.stopTest();
    }
    
    @isTest
	private static void testGetRewardProfile_IndividualType_HappyPath(){
        Test.startTest();
        String reqURI = '/RewardProfiles/retrieve/*'; 
        String reqBody = '{"ProfileType": "Individual","UserId": "005O0000005JHS0IAO","VehNumber": "","Brand": "KIA"}}';
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CMGetRewardProfileAPI.getRewardProfiles();
        Test.stopTest();
    }
    
    @isTest
	private static void testGetRewardProfile_RequestWithNullProfileType_ErrorResponses(){
        String profileType = '';
        Test.startTest();
        String reqURI = '/RewardProfiles/retrieve/*'; 
        String reqBody = '{"ProfileType": "' + profileType + '","UserId": "","VehNumber": "","Brand": "KIA"}}';
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CMGetRewardProfileAPI.getRewardProfiles();
        Test.stopTest();
    }

	@isTest
	private static void testGetRewardProfile_RequestWithInvalidProfileType_ErrorResponses(){
        String profileType = 'FakeGroup';
        Test.startTest();
        String reqURI = '/RewardProfiles/retrieve/*'; 
        String reqBody = '{"ProfileType": "' + profileType + '","UserId": "","VehNumber": "","Brand": "KIA"}}';
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CMGetRewardProfileAPI.getRewardProfiles();
        Test.stopTest();
    }

    
    @isTest
	private static void testGetRewardProfile_FleetTypeWithNullVehNo_ErrorReturned(){
        Test.startTest();
        String reqURI = '/RewardProfiles/retrieve/*'; 
        String reqBody = '{"ProfileType": "Fleet","UserId": "","VehNumber": "","Brand": "KIA"}}';
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CMGetRewardProfileAPI.getRewardProfiles();
        Test.stopTest();
    }
    
    @isTest
	private static void testGetRewardProfile_IndividualTypeWithNullUserId_ErrorReturned(){
        String profileType = 'Individual';
        Test.startTest();
        String reqURI = '/RewardProfiles/retrieve/*'; 
        String reqBody = '{"ProfileType": "' + profileType + '","UserId": "","VehNumber": "","Brand": "KIA"}}';
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CMGetRewardProfileAPI.getRewardProfiles();
        Test.stopTest();
    }
    
    @isTest
	private static void testGetRewardProfile_InvalidVehNo_ErrorReturned(){
        String regVeNo = 'NONEEXIST1';
        Test.startTest();
        String reqURI = '/RewardProfiles/retrieve/*'; 
        String reqBody = '{"ProfileType": "Fleet","UserId": "","VehNumber": "'+regVeNo+'","Brand": "KIA"}}';
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CMGetRewardProfileAPI.getRewardProfiles();
        Test.stopTest();
    }
    
    @isTest
	private static void testGetRewardProfile_InvalidUserId_ErrorReturned(){
        String userId = '003O00000024OjhIAE';
        Test.startTest();
        String reqURI = '/RewardProfiles/retrieve/*'; 
        String reqBody = '{"ProfileType": "Individual","UserId": "'+userId+'","VehNumber": "","Brand": "KIA"}}';
        Test_DataFactory.createReqSF( reqURI, 'POST', reqBody, null, 200);
        CMGetRewardProfileAPI.getRewardProfiles();
        Test.stopTest();
    }
}