cncProd/force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>false</active>
    <description>Business Account Fleet</description>
    <label>Fleet</label>
</RecordType>

cncProd/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>PendingPayment</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>PendingCancellation</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>Customer&apos;s Reward Credit 
- per Reward Type
- per Registered Vehicle
- per Expiry Date</description>
    <label>Reward</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Reward_Profile__c.field-meta.xml
<CustomField>
    <fullName>Reward_Profile__c</fullName>
    <label>Reward Profile</label>
    <referenceTo>Reward_Profile__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Provisioning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/Reward_Profile__c.object-meta.xml
<CustomObject>
    <label>Reward Profile</label>
    <nameField>
        <label>Reward Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_Profile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Boutique</fullName>
            </value>
            <value>
                <fullName>Birthday Voucher</fullName>
            </value>
            <value>
                <fullName>Grooming Package</fullName>
            </value>
            <value>
                <fullName>Service Credit Voucher</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>Discount Voucher</fullName>
            </value>
            <value>
                <fullName>Service Credit</fullName>
            </value>
            <value>
                <fullName>Accessories Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Business Account (Staff, Leasing), Person Account</description>
    <label>C&amp;C Fleet</label>
</RecordType>

force-app/main/default/objects/Reward_Profile__c/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <description>Business Account (Fleet)</description>
    <label>C&amp;C Individual</label>
</RecordType>

cncProd/force-app/main/default/objects/Reward_Usage__c/Reward_Usage__c.object-meta.xml
<CustomObject>
    <label>Reward Usage</label>
    <nameField>
        <label>Reward Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_Usage__c/fields/Autoline_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Autoline_Invoice_Date__c</fullName>
    <label>Autoline Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Autoline_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Autoline_Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <label>Autoline Invoice Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(Reward__r.Brand__c)</formula>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eShop</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Amount__c</fullName>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/e_Invoice__c.field-meta.xml
<CustomField>
    <fullName>e_Invoice__c</fullName>
    <inlineHelpText>For e-shop</inlineHelpText>
    <label>e-Invoice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/e_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>e_Invoice_Date__c</fullName>
    <label>e-Invoice Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward_Usage__c.field-meta.xml
<CustomField>
    <fullName>Reward_Usage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Reference to Debit Reward Usage record</description>
    <label>Reward Usage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Reward_Usage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Debit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Reward_Usage__c</referenceTo>
    <relationshipLabel>Credit Usages</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expired</fullName>
                <color>#BBBBBB</color>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Hold</fullName>
                <color>#FFFF66</color>
                <label>Hold</label>
            </value>
            <value>
                <fullName>Issued</fullName>
                <color>#57F17C</color>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Provisioning</fullName>
                <color>#FFFF66</color>
                <label>Provisioning</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#BBBBBB</color>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Utilised</fullName>
                <color>#FF0000</color>
                <label>Utilised</label>
            </value>
            <value>
                <fullName>Write-Back</fullName>
                <color>#6666CC</color>
                <label>Write-Back</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>Used to capture :
Autoline Invoice Date, Expiry Date + 1, Extension Date for Debit Usage, 
Refund Date for Credit Usage</description>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Expiry</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Credit to Customer (i.e. Refund/Adjustment/etc.)</description>
    <label>Credit</label>
</RecordType>

force-app/main/default/objects/Reward_Usage__c/recordTypes/Debit.recordType-meta.xml
<RecordType>
    <fullName>Debit</fullName>
    <active>true</active>
    <description>Debit from Customer (i.e. Credit Deduction)</description>
    <label>Debit</label>
</RecordType>

force-app/main/default/objects/User/fields/channel__c.field-meta.xml
<CustomField>
    <fullName>channel__c</fullName>
    <label>channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/CMGetUsageTransactionsAPI.cls
/** *****
 * Description : API Class to Get Customer Reward Profile(s) 
 * 
 * Change History
 * Date(YYYYMMDD)       Name                            Description
 * 20200709             khanh.do@aodigy.com             Created Initial Version. 
 * 
** *****/

@RestResource(urlMapping ='/RewardUsage/retrieve/*')
global with sharing class CMGetUsageTransactionsAPI {
    private static RestRequest request = RestContext.request;
    private static RestResponse response = RestContext.response;
    
    private static Utility.httpErrorResponse errorResponse;
    private static RequestBody requestBody = new RequestBody();
    private static ResponseBody responseBody = new ResponseBody();
    private static List<Reward_Usage__c> results = new List<Reward_Usage__c>();
    private static Set<String> brandPicklistValues = RewardService.getPickListValues('Brand__c');

    public class RequestBody {
        public String ProfileType;
        public String UserId;
        public String VehNumber;
        public String Brand;
        public Integer PreviousMonth;
    }   

    public class ResponseBody {
        String message;
        List<RewardUsageWrapper> UsageHistory;        
    }

    @HttpPost
    global static void getRewardUsage() {
        try {
            
            processRequest();
            
        } catch(Exception ex) {
            response.statusCode = 400;
        }

        if(errorResponse != null) 
        {    
            response.addHeader('Content-Type', 'application/json');
            response.statusCode = 400;
            response.responseBody = Blob.valueOf(JSON.Serialize(errorResponse));
        }
        
        serviceDataPool.buildServiceDataPool('CMGetUsageTransactionsAPI', 'CMGetUsageTransactionsAPI', '', request, response);
    }

    public static void processRequest() {
        requestBody = (RequestBody)JSON.deserialize(request.requestBody.toString(), RequestBody.class);
        String profileType = requestBody.ProfileType;
        String userId = requestBody.UserId;
        String vehNumber = requestBody.VehNumber;
        String brand = requestBody.Brand;
        Integer previousMonth = requestBody.PreviousMonth;
        
        System.debug('profileType = ' + profileType);
        System.debug('userId = ' + userId);
        System.debug('vehNumber = ' + vehNumber);
        System.debug('brand = ' + brand);
        System.debug('previousMonth = ' + previousMonth);

        String profileTypeId;
        String contactId;
        String regVehId;

        if( String.isBlank( profileType )) 
        {
            errorResponse = new Utility.HttpErrorResponse('Request failed', 'Mandatory field is missing. Please refer API doc');
            return;
        }

        // if(profileType.equalsIgnoreCase('Fleet') && String.isBlank(vehNumber)) {            
        //     errorResponse = new Utility.HttpErrorResponse('Request failed', 'Registered Vehicle Number is required for Fleet Account. Please try again');
        //     return;
        //

        if(profileType.equalsIgnoreCase('Individual') && String.isBlank(userId)) {
            errorResponse = new Utility.HttpErrorResponse('Request failed', 'UserId is required for Individual Account type. Please try again');
            return;
        }

        if(String.isNotBlank(brand) && !brandPicklistValues.contains(brand)) {
            errorResponse = new Utility.HttpErrorResponse('Request failed', 'Invalid Brand. Please try again');
            return;
        }

        if(previousMonth != null && previousMonth < 0) {
            errorResponse = new Utility.HttpErrorResponse('Request failed', 'Invalid Number Previous Month. Please try again');
            return;
        }

        profileTypeId = Schema.SObjectType.Reward_Profile__c.getRecordTypeInfosByDeveloperName().containsKey( profileType ) ? 
            Schema.SObjectType.Reward_Profile__c.getRecordTypeInfosByDeveloperName().get( profileType ).getRecordTypeId() : null;

        if( profileTypeId == null ) {
            errorResponse = new Utility.HttpErrorResponse('Request failed', 'Invalid Profile Type. Please check again');
            return;
        }

        if(String.isNotBlank(vehNumber)) {
            regVehId = RewardProfileService.getRegVehId(vehNumber);
            if(String.isBlank(regVehId)) {
                errorResponse = new Utility.HttpErrorResponse('Request failed', 'Cannot find Registered Vehicle with the requested VehNumber. Please check again');
                return;
            }
        }

        if(String.isNotBlank(userId)) {
            if(!userId.startsWith('005')) {
                errorResponse = new Utility.HttpErrorResponse('Request failed', 'Invalid User Id. Please check again');
                return;
            }
            contactId = RewardProfileService.getPersonContactId(userId);
            if(String.isBlank(contactId)) {
                errorResponse = new Utility.HttpErrorResponse('Request failed', 'Cannot find Contact with requested UserId. Please check again');
                return;
            }  
        }

        results = RewardUsageService.getRewardUsageHistory(profileTypeId, contactId, regVehId, brand, previousMonth);
        
        System.debug('results list size = ' + results.size());
        if(results.size() > 0) {
            generateResponseBody();
        } else {
            responseBody.message = 'No Reward Usage Found';
        }    

        response.statusCode = 200;
        response.responseBody = Blob.valueOf(JSON.serialize(responseBody));
        
        response.addHeader('Content-Type', 'application/json');    

    }

    public static void generateResponseBody() {
        responseBody.message = 'Retrieve successfully';
        List<RewardUsageWrapper> rewardUsages = new List<RewardUsageWrapper>();

        for(Reward_Usage__c obj: results) {
            RewardUsageWrapper rewardUsage = new RewardUsageWrapper();
            rewardUsage.UsageId = obj.Id;
            rewardUsage.UsageRecordType = RewardUsageService.getRecordTypeNameById(obj.RecordTypeId);
            rewardUsage.Channel = obj.Channel__c;
            rewardUsage.Type = obj.Type__c;
            rewardUsage.CreditAmount = obj.Credit_Amount__c;
            rewardUsage.Status = obj.Status__c;
            rewardUsage.TransactionDate = obj.Transaction_Date__c;
            rewardUsage.eInvoiceNumber = obj.e_Invoice__c;
            rewardUsage.eInvoiceDate = obj.e_Invoice_Date__c;
            rewardUsage.AutolineInvoiceNumber = obj.Autoline_Invoice_Number__c;
            rewardUsage.AutolineInvoiceDate = obj.AutoLine_Invoice_Date__c;
            rewardUsage.RewardType = obj.Reward__r.Type__c;
            rewardUsage.RewardId = obj.Reward__c;
            rewardUsage.Brand = obj.Reward__r.Brand__c;
            
            rewardUsages.add(rewardUsage);
        }

        responseBody.UsageHistory = rewardUsages;
    }

    public class RewardUsageWrapper {
        public String UsageId;
        public String UsageRecordType;
        public String Channel;
        public String Type;        
        public Decimal CreditAmount;
        public String Status;
        public Date TransactionDate;
        public String eInvoiceNumber;
        public Date eInvoiceDate;
        public String AutolineInvoiceNumber;
        public Date AutolineInvoiceDate;
        public String RewardType;
        public String RewardId;
        public String Brand;

    }

}

// List<Reward_Usage__c> rewardUsageToInsert = new List<Reward_Usage__c>();
// for(Integer i=0; i<5; i++) {
//     Reward_Usage__c newRewardUsage = new Reward_Usage__c();
// newRewardUsage.RecordTypeId = RewardUsageService.getRecordTypeId('Debit');
// newRewardUsage.Reward__c = 'a2zO0000001CBSDIA4';
// newRewardUsage.Channel__c = 'Service';
// newRewardUsage.Status__c = 'Utilised';
// newRewardUsage.Transaction_Date__c = Date.today();
// newRewardUsage.Order__c = null;
// newRewardUsage.Order_Number__c = null;
// rewardUsageToInsert.add(newRewardUsage);
    
//     Reward_Usage__c creditUsage = new Reward_Usage__c();
// creditUsage.RecordTypeId = RewardUsageService.getRecordTypeId('Credit');
// creditUsage.Reward__c = 'a2zO0000001CBSDIA4';
// creditUsage.Channel__c = 'Service';
// creditUsage.Status__c = 'Issued';
// creditUsage.Transaction_Date__c = Date.today();
// creditUsage.Order__c = null;
// creditUsage.Order_Number__c = null;
// rewardUsageToInsert.add(creditUsage);
// }

// insert rewardUsageToInsert;