force-app/main/default/objects/CustomerAlerts__c/CustomerAlerts__c.object-meta.xml
<CustomObject>
    <label>CustomerAlerts</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerAlerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CustomerAlerts (Account)</relationshipLabel>
    <relationshipName>CustomerAlerts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/HasServiceAppointment__c.field-meta.xml
<CustomField>
    <fullName>HasServiceAppointment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to tell if Service Appointment has been booked.</description>
    <label>Has Service Appointment</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Service Appointment</description>
    <label>Service Appointment</label>
    <referenceTo>Service_Appointment__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/EmailRecipient__mdt/EmailRecipient__mdt.object-meta.xml
<CustomObject>
    <description>Email Recipients for Specific Events</description>
    <label>Email Recipient</label>
    <pluralLabel>Email Recipients</pluralLabel>
</CustomObject>

force-app/main/default/objects/EmailRecipient__mdt/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <description>Type of Event where the email address should be notified.</description>
    <label>Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailRecipient__mdt/fields/IsBCC__c.field-meta.xml
<CustomField>
    <fullName>IsBCC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recipients in BCC?</description>
    <label>Is BCC</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/EmailRecipient__mdt/fields/IsCC__c.field-meta.xml
<CustomField>
    <fullName>IsCC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recipient in CC?</description>
    <label>Is CC</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/EmailRecipient__mdt/fields/IsRecipient__c.field-meta.xml
<CustomField>
    <fullName>IsRecipient__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Email the Main Recipient?</description>
    <label>Is Recipient</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/EmailRecipient__mdt/fields/RecipientEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>RecipientEmailAddress__c</fullName>
    <description>Email Address of the Recipient</description>
    <inlineHelpText>Email Address of the Recipient</inlineHelpText>
    <label>Recipient Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/Service_Appointment__c.object-meta.xml
<CustomObject>
    <label>Service Appointment</label>
    <nameField>
        <label>Service Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments (Account)</relationshipLabel>
    <relationshipName>Service_Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerServiceReportScheduler.cls
/** *******
 * 
 * Class Name: CustomerServiceReportScheduler
 * Description : Scheduler of Service Reports (build v1 = MB)
 *
 * Change History:
 * Date(YYYYMMDD)       Developer                   Description
 * 20190522             Christian Gaylan            Created Initial version
 * 20200325             huynh.hung@aodigy           Added PA Migration - Phase 1 Changes
 * 20200831             khanh.do@aodigy.com         Added PA Migration - Phase 2 Changes
 * 
 ******* **/
public class CustomerServiceReportScheduler implements Schedulable{
    
    //Schedule
    public void execute(SchedulableContext ctx){
        customerServiceReportRunner();
    }
    
   public static void customerServiceReportRunner(){
        try
        {
            List<String> bccAddress = new List<String>();
            List<String> getRecipientsList = new List<String>();

			//get recipients
            for( EmailRecipient__mdt emt : [SELECT Id, RecipientEmailAddress__c, MasterLabel, IsBCC__c, IsCC__c, IsRecipient__c 
                                            FROM EmailRecipient__mdt 
                                            WHERE EventType__c = 'MBCustomerService'
                                            AND RecipientEmailAddress__c != null
                                            LIMIT 25])
            {
				if(emt.IsRecipient__c){
                    //Main Recipient of the Email
                    getRecipientsList.add(emt.RecipientEmailAddress__c); 
                }
                else if(emt.isBCC__c){
                    bccAddress.add(emt.RecipientEmailAddress__c);
                }
            }            
            
            List<Messaging.SingleEmailMessage> msgList = new List<Messaging.SingleEmailMessage>();
            //Loop through email Reports and templates.            
            for(EmailTemplate em : [SELECT Id, Name, DeveloperName 
                                    FROM EmailTemplate 
                                    WHERE DeveloperName ='MBCustomerServiceReport' ])
            {
                Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(em.Id, null,null);
                

				email.setToAddresses(getRecipientsList);    //Set Recipients
                email.setSubject(email.getSubject());
                email.setBccAddresses(bccAddress);          //Set BCC
                email.sethtmlBody(email.gethtmlBody());
                email.saveAsActivity = false;
                
                msgList.add(email);
            }
            
            if( !msgList.isEmpty() ){
                Messaging.sendEmail(msgList);
            }
        }
        catch(Exception e){
            loggerDataPool.buildLogDataPool('CustomerServiceReportScheduler', e);
        }    
    }

    /** *****
     * Method Name: updateCustomerAlerts 
     * Description: Given a list of Service Appt Ids, update the Customer Alerts record.
     * Note: This method will be invoked by a process.
     ***** */
    @InvocableMethod
    public static void updateCustomerAlerts(List<Id> servAppIds){
    	try{
    		if(servAppIds!=null && !servAppIds.isEmpty()){
    			Map<Id, Id> servAppToConMap = new Map<Id, Id>();
    			Map<Id, String> contactToAction = new Map<Id, String>();

    			//get Contacts from Service Appt
    			for(Service_Appointment__c srev : [ SELECT Id, Contact__c, Account__c, Action__c 
    												FROM Service_Appointment__c 
    												WHERE Id IN: servAppIds 
    												AND Contact__c != null ])
				{
					servAppToConMap.put(srev.Id, srev.Contact__c);
                    contactToAction.put(srev.Contact__c, srev.Action__c);
                }
  
				if( servAppToConMap != null && !servAppToConMap.isEmpty() && 
                        servAppToConMap.values()!=null && !(servAppToConMap.values()).isEmpty() )
                {
                    List<CustomerAlerts__c> custAlertForUpdate = new List<CustomerAlerts__c>();
                    for(CustomerAlerts__c cs : [SELECT Id, HasServiceAppointment__c, Contact__c  
                                                FROM CustomerAlerts__c 
                                                WHERE Contact__c != null 
                                                AND Contact__c IN: servAppToConMap.values() 
                                                AND Name = 'Subsequent Service Due 2nd Reminder' 
                                                AND CreatedDate >= :Date.today().addDays(-8) 
                                                ORDER BY CreatedDate DESC])
                    {
                        if( cs.HasServiceAppointment__c ) {
                            if( contactToAction.containsKey(cs.Contact__c) && contactToAction.get(cs.Contact__c) == 'Cancel' ) {
                                cs.HasServiceAppointment__c = false;
                            }
                        }
                        else {
                            cs.HasServiceAppointment__c = true;
                        }
                        custAlertForUpdate.add(cs);
                    }
                    Database.update( custAlertForUpdate , false );    
                }
            }
        }
        catch(Exception e){
    		loggerDataPool.buildLogDataPool('CustomerServiceReportScheduler.updateCustomerAlerts', e);
    	}
    } 
}