cncProd/force-app/main/default/objects/Meeting_Log_V2__c/Meeting_Log_V2__c.object-meta.xml
<CustomObject>
    <label>Meeting Log</label>
    <nameField>
        <displayFormat>Meeting-{0000}</displayFormat>
        <label>Meeting Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Log_V2__c/fields/Participant_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name__c</fullName>
    <label>Participant Name</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gordon Ho</fullName>
            </value>
            <value>
                <fullName>Kia Sales</fullName>
            </value>
            <value>
                <fullName>Kia Sales 2</fullName>
            </value>
            <value>
                <fullName>Debra Lim</fullName>
            </value>
            <value>
                <fullName>Alan Yeo</fullName>
            </value>
            <value>
                <fullName>Mason Law</fullName>
            </value>
            <value>
                <fullName>Mimi Lee</fullName>
            </value>
            <value>
                <fullName>Clement Teas</fullName>
            </value>
            <value>
                <fullName>James Law</fullName>
            </value>
            <value>
                <fullName>Winnie Yeo</fullName>
            </value>
            <value>
                <fullName>Gary Quek</fullName>
            </value>
            <value>
                <fullName>Gracie Cheng</fullName>
            </value>
            <value>
                <fullName>Kee Hing Ng</fullName>
            </value>
            <value>
                <fullName>Lance Kouk</fullName>
            </value>
            <value>
                <fullName>Derrick Soh</fullName>
            </value>
            <value>
                <fullName>Alvin Tham</fullName>
            </value>
            <value>
                <fullName>George Pang</fullName>
            </value>
            <value>
                <fullName>David Phang</fullName>
            </value>
            <value>
                <fullName>Cheng Khoon Tan</fullName>
            </value>
            <value>
                <fullName>Dawn Pan</fullName>
            </value>
            <value>
                <fullName>Mei Ting Koh</fullName>
            </value>
            <value>
                <fullName>Bryan Heng</fullName>
            </value>
            <value>
                <fullName>Melvin Lee</fullName>
            </value>
            <value>
                <fullName>Janice Mao</fullName>
            </value>
            <value>
                <fullName>Wilson Lau</fullName>
            </value>
            <value>
                <fullName>Dave Wong</fullName>
            </value>
            <value>
                <fullName>Doris Yeo</fullName>
            </value>
            <value>
                <fullName>Chantel Tae</fullName>
            </value>
            <value>
                <fullName>Albert Soo</fullName>
            </value>
            <value>
                <fullName>Jessie Choo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Meeting_Log_V2__c/fields/Participants_Name_List__c.field-meta.xml
<CustomField>
    <fullName>Participants_Name_List__c</fullName>
    <label>Participants Name List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/ExcludeFromMeetingLog__c.field-meta.xml
<CustomField>
    <fullName>ExcludeFromMeetingLog__c</fullName>
    <defaultValue>false</defaultValue>
    <description>User is excluded from Meeting Log</description>
    <inlineHelpText>Excludes User from Meeting Log</inlineHelpText>
    <label>ExcludeFromMeetingLog?</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/classes/MultiselectMeetingLogController.cls
public with sharing class MultiselectMeetingLogController {
    
    public String currentRecordId {get;set;}
    public String parameterValue {get;set;}
    
    public SelectOption[] selectedUser { get; set; }
    public SelectOption[] allUser { get; set; }
    
    public String message { get; set; }
    //public List<String> ParticipantsName = new List<String>();
    
    
    public MultiselectMeetingLogController(ApexPages.StandardController controller) {
        try {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        parameterValue = ApexPages.CurrentPage().getparameters().get('nameParam');
        
        selectedUser = new List<SelectOption>();
        allUser = new List<SelectOption>();
        List<String> ParticipantsList = new List<String>();
        List<String> selectedName = new List<String>();
        List<String> allName = new List<String>();
        List<String> allUserId = new List<String>();
        List<String> remainingName = new List<String>();
        
            
        Set<String> availableProfile = new Set<String>{'KIAPC Sales',
                                                        'KIAPC Sales Manager',
                                                        'MITPC Sales',
                                                        'MITPC Sales Manager',
                                                        'CITPC Sales',
                                                        'CITPC Sales Manager'
                                                        };
        //Get Profile Id
        String userProfileName = [SELECT Name FROM Profile WHERE Id=: UserInfo.getProfileId() LIMIT 1].Name;
        Set<Id> ProfileId = new Set<Id>();
        for(Profile item : [SELECT Id, Name 
                            FROM Profile WHERE 
                            Name IN: availableProfile])
        {
            if(userProfileName.contains('KIAPC') && item.Name.contains('KIAPC')){
                ProfileId.add(item.Id);
            }else if(userProfileName.contains('MITPC') && item.Name.contains('MITPC')){
                ProfileId.add(item.Id);
            }else if(userProfileName.contains('CITPC') && item.Name.contains('CITPC')){
                ProfileId.add(item.Id);
            }else if(userProfileName.contains('System Administrator')){
                //bypass for Admins, can see both Kia and MIT
                ProfileId.add(item.Id);
            }
            
        }
        
        List<User> mUser =[SELECT Id,name FROM User
                             WHERE ProfileId IN :ProfileId 
                             AND isActive = TRUE
                             AND ExcludeFromMeetingLog__c = False
                             ORDER BY Name ASC];
                             
        System.debug('+++++++++--user : '+mUser);
        if(mUser.size()>0)
        {
            for(User activeUser: mUser)
            {
                
                allName.add(activeUser.Name);
                allUserId.add(activeUser.Id);
                //allUser.add(new SelectOption(activeUser.Name, activeUser.Name));
            }
        }
        
        List<Meeting_Log_V2__c> pickedListValue = [SELECT Participant_Name__c,Participants_Name_List__c From Meeting_Log_V2__c WHERE Id = :currentRecordId];
        System.debug('ID : '+currentRecordId);
        System.debug('Record : '+pickedListValue);
        For(Meeting_Log_V2__c meeting: pickedListValue)
        {
            if(meeting.Participants_Name_List__c != null)
            {
                ParticipantsList = meeting.Participants_Name_List__c.split(';');
                if(ParticipantsList.size()>0)
                {
                    for(Integer i =0; i<ParticipantsList.size(); i++)
                    {
                        selectedName.add(ParticipantsList[i]);
                        selectedUser.add(new SelectOption(selectedName.get(i), selectedName.get(i)));
                    }
                    
                }
            }
        }
        
        if(selectedName.size()>0)
        {
                System.debug('All user > 0 - '+selectedName.size());
                List<User> mRemainUser =[SELECT name FROM User WHERE Id IN :allUserId AND name NOT IN:selectedName ORDER BY Name ASC];
            
            System.debug('All user > 0 - '+mRemainUser.size());
            if(mRemainUser.size()>0)
            {
                for(Integer i=0; i<mRemainUser.size(); i++)
                    {
                        allUser.add(new SelectOption(mRemainUser.get(i).name, mRemainUser.get(i).name));
                    }
            }
                    
                
        }
        else
        {
                for(Integer i=0; i<allname.size(); i++)
                {
                    allUser.add(new SelectOption(allName.get(i), allName.get(i)));
                }
        }
    }
        catch (Exception e) {
            System.debug('Exception >>> ' + e.getMessage() + ' >>> ' + e.getLineNumber());
        }
    }
    
    public PageReference save() {
        message = '';
        Boolean first = true;
        for ( SelectOption so : selectedUser ) {
            if (!first) {
                message += ';';
            }
            message += so.getValue();
            first = false;
        }
        
        Meeting_Log_V2__c item = new Meeting_Log_V2__c(Id = currentRecordId);
        item.Participants_Name_List__c = message;
        item.Participant_Name__c =  message;
        update item;
        
        PageReference tempPage = ApexPages.currentPage();            
        tempPage.setRedirect(true);
        return tempPage;
    }
}