cncProd/force-app/main/default/objects/Meeting_Log_V2__c/Meeting_Log_V2__c.object-meta.xml
<CustomObject>
    <label>Meeting Log</label>
    <nameField>
        <displayFormat>Meeting-{0000}</displayFormat>
        <label>Meeting Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Log_V2__c/fields/Participant_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name__c</fullName>
    <label>Participant Name</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gordon Ho</fullName>
            </value>
            <value>
                <fullName>Kia Sales</fullName>
            </value>
            <value>
                <fullName>Kia Sales 2</fullName>
            </value>
            <value>
                <fullName>Debra Lim</fullName>
            </value>
            <value>
                <fullName>Alan Yeo</fullName>
            </value>
            <value>
                <fullName>Mason Law</fullName>
            </value>
            <value>
                <fullName>Mimi Lee</fullName>
            </value>
            <value>
                <fullName>Clement Teas</fullName>
            </value>
            <value>
                <fullName>James Law</fullName>
            </value>
            <value>
                <fullName>Winnie Yeo</fullName>
            </value>
            <value>
                <fullName>Gary Quek</fullName>
            </value>
            <value>
                <fullName>Gracie Cheng</fullName>
            </value>
            <value>
                <fullName>Kee Hing Ng</fullName>
            </value>
            <value>
                <fullName>Lance Kouk</fullName>
            </value>
            <value>
                <fullName>Derrick Soh</fullName>
            </value>
            <value>
                <fullName>Alvin Tham</fullName>
            </value>
            <value>
                <fullName>George Pang</fullName>
            </value>
            <value>
                <fullName>David Phang</fullName>
            </value>
            <value>
                <fullName>Cheng Khoon Tan</fullName>
            </value>
            <value>
                <fullName>Dawn Pan</fullName>
            </value>
            <value>
                <fullName>Mei Ting Koh</fullName>
            </value>
            <value>
                <fullName>Bryan Heng</fullName>
            </value>
            <value>
                <fullName>Melvin Lee</fullName>
            </value>
            <value>
                <fullName>Janice Mao</fullName>
            </value>
            <value>
                <fullName>Wilson Lau</fullName>
            </value>
            <value>
                <fullName>Dave Wong</fullName>
            </value>
            <value>
                <fullName>Doris Yeo</fullName>
            </value>
            <value>
                <fullName>Chantel Tae</fullName>
            </value>
            <value>
                <fullName>Albert Soo</fullName>
            </value>
            <value>
                <fullName>Jessie Choo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Meeting_Log_V2__c/fields/Participants_Name_List__c.field-meta.xml
<CustomField>
    <fullName>Participants_Name_List__c</fullName>
    <label>Participants Name List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

cncProd/force-app/main/default/classes/MeetingLogV2GetPicklist.cls
public class MeetingLogV2GetPicklist {
    

    @AuraEnabled 
    public static List<User> getUserList(){
        List<Profile> SalesId =  [SELECT Id FROM Profile WHERE name='KIAPC Sales' or name='KIAPC Sales Manager'];
        List<Id> ProfileId = new List<Id>();
        
        for(Profile item : SalesId)
        {
            ProfileId.add(item.Id);
        }
        List<User> ParticipantList =[SELECT name FROM User WHERE ProfileId IN :ProfileId AND isActive = TRUE ORDER BY Name ASC];
        return ParticipantList;     
    } 
    
  
    
    @AuraEnabled 
    public static void saveValueButton(Id caseId, List<string> pickListValue){
        Meeting_Log_V2__c item = new Meeting_Log_V2__c(Id = caseId);
    
        String participantName ='' ;
        if(pickListValue.size()>0){
            for( integer i=0 ; i< pickListValue.size();i++){
            	if( i < pickListValue.size()-1){
                  	participantName += pickListValue[i]+ ';';
            }
                else{
                	participantName += pickListValue[i];
            }
          }
        }
        
        item.Participants_Name_List__c = participantName;
        item.Participant_Name__c =  participantName;
        update item;
    }
    
    @AuraEnabled 
   public static List<Meeting_Log_V2__c> getPicklistValues(Id caseId){ 
		
       List<Meeting_Log_V2__c> pickedListValue = [SELECT Participant_Name__c,Participants_Name_List__c From Meeting_Log_V2__c WHERE Id =: caseId];
		
  			return pickedListValue;
   }
    

}