force-app/main/default/objects/Logger_Data_Pool__c/Logger_Data_Pool__c.object-meta.xml
<CustomObject>
    <label>Logger Data Pool</label>
    <nameField>
        <label>Logger Data Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logger Data Pool</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger_Data_Pool__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

cncProd/force-app/main/default/objects/Logger_Data_Pool__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <label>Instance</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger_Data_Pool__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Logger_Data_Pool__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

cncProd/force-app/main/default/classes/loggerDataPool.cls
/*
	Author: Hari Panneerselvam
*/
public class loggerDataPool {
	
	public static void buildLogDataPool(String instance, Exception exce){ 
		Logger_Data_Pool__c newLogDataPool = new Logger_Data_Pool__c();
		newLogDataPool.Instance__c = instance;
		newLogDataPool.Cause__c = String.valueOf(exce.getCause());
		newLogDataPool.Line_Number__c = exce.getLineNumber();
		newLogDataPool.Message__c = exce.getMessage();
		newLogDataPool.Stack_Trace__c = exce.getStackTraceString();
		newLogDataPool.Type__c = exce.getTypeName();
		insert newLogDataPool;
	}
    
}