force-app/main/default/objects/FOB_Additional_Contract__c/FOB_Additional_Contract__c.object-meta.xml
<CustomObject>
    <label>FOB Additional Contract</label>
    <nameField>
        <displayFormat>FAC-{0000000}</displayFormat>
        <label>FOB Additional Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FOB Additional Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Cover_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Cover_Percentage__c</fullName>
    <formula>Forward_FOB_Contract__r.Cover_Percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cover Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Forward_FOB_Contract__c.field-meta.xml
<CustomField>
    <fullName>Forward_FOB_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forward FOB Contract</label>
    <referenceTo>Forward_FOB_Contract__c</referenceTo>
    <relationshipLabel>FOB Additional Contracts</relationshipLabel>
    <relationshipName>FOB_Additional_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Premium_Discount__c.field-meta.xml
<CustomField>
    <fullName>Premium_Discount__c</fullName>
    <formula>Forward_FOB_Contract__r.Premium_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Premium(+) / Discount(-)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Spot_Rate__c.field-meta.xml
<CustomField>
    <fullName>Spot_Rate__c</fullName>
    <label>Spot Rate (Spot Contract)</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Forward Contract Execute</fullName>
            </value>
            <value>
                <fullName>Forward Contract Sell</fullName>
            </value>
            <value>
                <fullName>Spot Rate Contract</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Completed (PO Cancel)</fullName>
            </value>
            <value>
                <fullName>PO Cancellation</fullName>
            </value>
            <value>
                <fullName>Forward Contract Buy</fullName>
                <isActive>false</isActive>
                <label>Forward Contract Buy</label>
            </value>
            <value>
                <fullName>Forward Contract Sell on Maturity</fullName>
                <isActive>false</isActive>
                <label>Forward Contract Sell on Maturity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract__c/Forward_FOB_Contract__c.object-meta.xml
<CustomObject>
    <label>Forward FOB Contract</label>
    <nameField>
        <displayFormat>FBF-{000000}</displayFormat>
        <label>Forward Contract FOB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward FOB Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forward_FOB_Contract__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipName>Forward_Contracts_FOB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract__c/fields/Spot_Rate__c.field-meta.xml
<CustomField>
    <fullName>Spot_Rate__c</fullName>
    <label>Spot Rate</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Buy</fullName>
                <isActive>false</isActive>
                <label>Buy</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Execute</fullName>
                <isActive>false</isActive>
                <label>Execute</label>
            </value>
            <value>
                <fullName>Spot Rate</fullName>
                <isActive>false</isActive>
                <label>Spot Rate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/Forward_FOB_Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Forward FOB Contract Line Item</label>
    <nameField>
        <displayFormat>FBFL-{00000000}</displayFormat>
        <label>Forward Contract FOB Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward FOB Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/fields/Forward_FOB_Contract__c.field-meta.xml
<CustomField>
    <fullName>Forward_FOB_Contract__c</fullName>
    <label>Forward FOB Contract</label>
    <referenceTo>Forward_FOB_Contract__c</referenceTo>
    <relationshipLabel>Forward FOB Contract Line Items</relationshipLabel>
    <relationshipName>Forward_Contract_FOB_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( !ISBLANK( Forward_FOB_Contract__c ) &amp;&amp; ISBLANK( FOB_Additional_Contract__c ) , &apos;Forward Contract Buy&apos; , TEXT( FOB_Additional_Contract__r.Status__c ))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Model_Rate_Master__c/Model_Rate_Master__c.object-meta.xml
<CustomObject>
    <label>Model Rate Master</label>
    <nameField>
        <displayFormat>MRM-{0000}</displayFormat>
        <label>Model Rate Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Model Rate Masters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Rate_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Rate Masters</relationshipLabel>
    <relationshipName>Model_Rate_Masters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Model_Year_Master__c/Model_Year_Master__c.object-meta.xml
<CustomObject>
    <label>Model Year Master</label>
    <nameField>
        <label>Model Year Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Year Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Model_Year_Master__c/fields/Model_Master__c.field-meta.xml
<CustomField>
    <fullName>Model_Master__c</fullName>
    <label>Model Master</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipLabel>Model Year Master</relationshipLabel>
    <relationshipName>ModelYear_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>TMS PO Group</label>
    <nameField>
        <displayFormat>TMSPO-{YYYY}{MM}-{00000}</displayFormat>
        <label>TMS Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMS PO Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>Franchise__c</fullName>
    <label>Franchise</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Franchise_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/Vehicle_Master2__c.object-meta.xml
<CustomObject>
    <label>Stock Vehicle Master</label>
    <nameField>
        <displayFormat>RVH-{YYYY}{MM}-{0000}</displayFormat>
        <label>RVH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master2__c/fields/Chassis__c.field-meta.xml
<CustomField>
    <fullName>Chassis__c</fullName>
    <label>Chassis</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Color_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Color Code</label>
    <referenceTo>Color_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master2__c/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No.</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Code</label>
    <referenceTo>Model_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Model_Year_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Year_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Model Year Code</label>
    <referenceTo>Model_Year_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Original_Commcase__c.field-meta.xml
<CustomField>
    <fullName>Original_Commcase__c</fullName>
    <label>Original Commcase</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/ProductionMonth__c.field-meta.xml
<CustomField>
    <fullName>ProductionMonth__c</fullName>
    <label>Production Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is used for Treasury Management</description>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/System_Commcase__c.field-meta.xml
<CustomField>
    <fullName>System_Commcase__c</fullName>
    <label>System Commcase</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Trim_Code__c.field-meta.xml
<CustomField>
    <fullName>Trim_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trim Code</label>
    <referenceTo>Trim_Master__c</referenceTo>
    <relationshipName>Vehicle_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master2__c/fields/Vehicle_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Shipment</label>
    <referenceTo>Vehicle_Shipment__c</referenceTo>
    <relationshipLabel>Stock Vehicle Masters</relationshipLabel>
    <relationshipName>Stock_Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Franchise_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CITCV</fullName>
    </customValue>
    <customValue>
        <fullName>CITPC</fullName>
    </customValue>
    <customValue>
        <fullName>KIACV</fullName>
    </customValue>
    <customValue>
        <fullName>KIAPC</fullName>
    </customValue>
    <customValue>
        <fullName>MITCV</fullName>
    </customValue>
    <customValue>
        <fullName>MITPC</fullName>
    </customValue>
    <customValue>
        <fullName>MBCV</fullName>
    </customValue>
    <customValue>
        <fullName>MBPC</fullName>
    </customValue>
    <masterLabel>Franchise Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StockVehicleMasterSelectorTest.cls
/*==========================================================================================================================================================================
 * Test class for Stock Vehicle Master entity
 * Created By: Aodigy Team
 * Create Date: August 2022
 * History
 *              DATE::                              BY::                                TICKET::                                            CHANGELOG
 *          7 Sep 2022                       trung@aodigy.com    
 *         14 Sep 2022                       nam@aodigy.com                                                                                 init
 *         30 Sep 2022                       quy.tan@aodigy.com                         US-WMS-000004                                       selectStockVehicleMastersByVehicleShipment_success
 * ========================================================================================================================================================================== 
 */
@isTest
private class StockVehicleMasterSelectorTest {
    @testSetup
    static void setUp() {
        // create supplier account
        //Account supplier = Test_DataFactory.createAccount(true, 'Supplier Account');

        //create Vehicle shipment
        //Vehicle_Shipment__c vehicleShipment = Test_DataFactory.createVehicleShipment(true, supplier.Id);
        // Create master data
        Model_Master__c modelCode = Test_DataFactory.createModelCode(true, 'Test Model Code');
        Model_Rate_Master__c modelRateMaster = new Model_Rate_Master__c(Model_Master__c = modelCode.Id
                                                                        );
        insert modelRateMaster;
        Model_Year_Master__c modelYearCode = Test_DataFactory.createModelYearCode(true, modelCode.Id);
        Color_Master__c colorCode = Test_DataFactory.createColorCode(true, 'Test Color Code', 'Test', 'CCK', 'KIAPC');
        Trim_Master__c trimCode = Test_DataFactory.createTrimCode(true, 'Test Trim Code');

        Purchase_Order__c po = new Purchase_Order__c(Franchise__c = 'KIAPC');
        insert po;
        Date productionMonth = Date.newInstance(2019, 08, 01);  
        Vehicle_Master2__c vMaster = new Vehicle_Master2__c(Original_Commcase__c = 'KIAPC0120190086', 
                                                            Model_Year_Code__c = modelYearCode.ID,
                                                            System_Commcase__c = 'KIAPC0120190086', 
                                                            Engine_No__c = 'ENGINE279831',
                                                            Chassis__c = 'CHAS279831', 
                                                            Model_Code__c = modelCode.ID, 
                                                            ProductionMonth__c = productionMonth,
                                                            Color_Code__c = colorCode.ID, 
                                                            Trim_Code__c = trimCode.ID,
                                                            Duty_Payment_Date__c = Date.today(),
                                                            // Vehicle_Shipment__c = vehicleShipment.id,
                                                            Purchase_Order__c = po.Id);
        insert vMaster;
         Forward_FOB_Contract__c fobContract = new Forward_FOB_Contract__c(Status__c = 'Active',
                                                                          Cover_Percentage__c = 75,
                                                                          Spot_Rate__c = 1.2345663,
                                                                          Premium_Discount__c = 1.1,
                                                                          Purchase_Order__c = po.Id);
         insert fobContract;

         FOB_Additional_Contract__c addnlFOBContract = new FOB_Additional_Contract__c(Forward_FOB_Contract__c = fobContract.Id,
                                                                                      Status__c = 'Forward Contract Sell');
         insert addnlFOBContract;

         Forward_FOB_Contract_Line_Item__c fobItem = new Forward_FOB_Contract_Line_Item__c(Forward_FOB_Contract__c = fobContract.Id,
                                                                                           FOB_Additional_Contract__c = addnlFOBContract.Id,
                                                                                           Stock_Vehicle_Master__c = vMaster.Id);
         insert fobItem;
    }

     @isTest
     static void Test_selectStockVehicleMastersBySystemCommcases() {
         StockVehicleMasterSelector svmSelector = new StockVehicleMasterSelector();
         List<Vehicle_Master2__c> vhMasters = svmSelector.selectStockVehicleMastersBySystemCommcases(new Set<String>{'KIAPC0120190086'});

         System.assertEquals(1, vhMasters.size());
     }

     @isTest
     static void selectRecordsByForUpdateER_Test(){
         Forward_FOB_Contract__c fobContract = [SELECT ID, Status__c FROM Forward_FOB_Contract__c LIMIT 1];
         Forward_FOB_Contract_Line_Item__c fobItem = [SELECT ID
                                                      FROM Forward_FOB_Contract_Line_Item__c 
                                                      WHERE Forward_FOB_Contract__c =: fobContract.Id];
         StockVehicleMasterSelector svms = new StockVehicleMasterSelector();
         svms.selectRecordsByForUpdateER(new List<Id>{fobItem.Id});
     }

    @isTest
    static void getRecordsByIds_Test(){
        Vehicle_Master2__c vm2 = [SELECT Id FROM Vehicle_Master2__c];
        StockVehicleMasterSelector svms = new StockVehicleMasterSelector();
        svms.getRecordsByIds(new List<Id>{vm2.Id});
    }

    @isTest
    static void getStockVehicleMastersForDutyRequest_Test(){
        Vehicle_Master2__c vm2 = [SELECT Id, Duty_Payment_Date__c  FROM Vehicle_Master2__c];
        StockVehicleMasterSelector svms = new StockVehicleMasterSelector();
        svms.getStockVehicleMastersForDutyRequest();
    }

    @isTest
    static void getStockVehicleMastersByInvoiceIds_success(){
        Vehicle_Master2__c vm2 = [SELECT Id,Inward_Declaration_Invoice__c   FROM Vehicle_Master2__c];
        StockVehicleMasterSelector svms = new StockVehicleMasterSelector();
        svms.getStockVehicleMastersByInvoiceIds(new Set<Id>{vm2.Id});
    }

    // @isTest
    // static void selectStockVehicleMastersByVehicleShipment_success(){
    //     Vehicle_Shipment__c vm = [SELECT Id FROM Vehicle_Shipment__c LIMIT 1];
    //     StockVehicleMasterSelector svms = new StockVehicleMasterSelector();
    //     svms.selectStockVehicleMastersByVehicleShipment(vm.id);
    // }
}