force-app/main/default/objects/FOB_Additional_Contract__c/FOB_Additional_Contract__c.object-meta.xml
<CustomObject>
    <label>FOB Additional Contract</label>
    <nameField>
        <displayFormat>FAC-{0000000}</displayFormat>
        <label>FOB Additional Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FOB Additional Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Bank_Contract_No_Sell_Execute__c.field-meta.xml
<CustomField>
    <fullName>Bank_Contract_No_Sell_Execute__c</fullName>
    <label>Bank Contract No (Sell/Execute)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Cover_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Cover_Percentage__c</fullName>
    <formula>Forward_FOB_Contract__r.Cover_Percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cover Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Effective_Date_Sell_Execute__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date_Sell_Execute__c</fullName>
    <label>Effective Date (Sell/Execute)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Forward_FOB_Contract__c.field-meta.xml
<CustomField>
    <fullName>Forward_FOB_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forward FOB Contract</label>
    <referenceTo>Forward_FOB_Contract__c</referenceTo>
    <relationshipLabel>FOB Additional Contracts</relationshipLabel>
    <relationshipName>FOB_Additional_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Spot_Rate__c.field-meta.xml
<CustomField>
    <fullName>Spot_Rate__c</fullName>
    <label>Spot Rate (Spot Contract)</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Spot_Rate_Sell_Execute__c.field-meta.xml
<CustomField>
    <fullName>Spot_Rate_Sell_Execute__c</fullName>
    <label>Spot Rate (Sell/Execute)</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Forward Contract Execute</fullName>
            </value>
            <value>
                <fullName>Forward Contract Sell</fullName>
            </value>
            <value>
                <fullName>Spot Rate Contract</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Completed (PO Cancel)</fullName>
            </value>
            <value>
                <fullName>PO Cancellation</fullName>
            </value>
            <value>
                <fullName>Forward Contract Buy</fullName>
                <isActive>false</isActive>
                <label>Forward Contract Buy</label>
            </value>
            <value>
                <fullName>Forward Contract Sell on Maturity</fullName>
                <isActive>false</isActive>
                <label>Forward Contract Sell on Maturity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FOB_Additional_Contract__c/fields/Transaction_Date_Sell_Execute__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date_Sell_Execute__c</fullName>
    <label>Transaction Date (Sell/Execute)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract__c/Forward_FOB_Contract__c.object-meta.xml
<CustomObject>
    <label>Forward FOB Contract</label>
    <nameField>
        <displayFormat>FBF-{000000}</displayFormat>
        <label>Forward Contract FOB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward FOB Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forward_FOB_Contract__c/fields/Bank_Contract_No_Sell_Execute__c.field-meta.xml
<CustomField>
    <fullName>Bank_Contract_No_Sell_Execute__c</fullName>
    <label>Bank Contract No (Sell/Execute)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract__c/fields/Effective_Date_Sell_Execute__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date_Sell_Execute__c</fullName>
    <label>Effective Date (Sell/Execute)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract__c/fields/Spot_Rate__c.field-meta.xml
<CustomField>
    <fullName>Spot_Rate__c</fullName>
    <label>Spot Rate</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Annulled</fullName>
            </value>
            <value>
                <fullName>Buy</fullName>
                <isActive>false</isActive>
                <label>Buy</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Execute</fullName>
                <isActive>false</isActive>
                <label>Execute</label>
            </value>
            <value>
                <fullName>Spot Rate</fullName>
                <isActive>false</isActive>
                <label>Spot Rate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Transaction Date (Buy)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/Forward_FOB_Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Forward FOB Contract Line Item</label>
    <nameField>
        <displayFormat>FBFL-{00000000}</displayFormat>
        <label>Forward Contract FOB Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward FOB Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/fields/Bank_Contract_No_Sell_Execute__c.field-meta.xml
<CustomField>
    <fullName>Bank_Contract_No_Sell_Execute__c</fullName>
    <formula>FOB_Additional_Contract__r.Bank_Contract_No_Sell_Execute__c</formula>
    <label>Bank Contract No (Sell/Execute)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/fields/Effective_Date_Sell_Execute__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date_Sell_Execute__c</fullName>
    <formula>FOB_Additional_Contract__r.Effective_Date_Sell_Execute__c</formula>
    <label>Effective Date (Sell/Execute)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/fields/FOB_Additional_Contract__c.field-meta.xml
<CustomField>
    <fullName>FOB_Additional_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FOB Additional Contract</label>
    <referenceTo>FOB_Additional_Contract__c</referenceTo>
    <relationshipLabel>Forward FOB Contract Line Items</relationshipLabel>
    <relationshipName>Forward_FOB_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/fields/Forward_FOB_Contract__c.field-meta.xml
<CustomField>
    <fullName>Forward_FOB_Contract__c</fullName>
    <label>Forward FOB Contract</label>
    <referenceTo>Forward_FOB_Contract__c</referenceTo>
    <relationshipLabel>Forward FOB Contract Line Items</relationshipLabel>
    <relationshipName>Forward_Contract_FOB_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( !ISBLANK( Forward_FOB_Contract__c ) &amp;&amp; ISBLANK( FOB_Additional_Contract__c ) , &apos;Forward Contract Buy&apos; , TEXT( FOB_Additional_Contract__r.Status__c ))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forward_FOB_Contract_Line_Item__c/fields/Transaction_Date_Sell_Execute__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date_Sell_Execute__c</fullName>
    <formula>FOB_Additional_Contract__r.Transaction_Date_Sell_Execute__c</formula>
    <label>Transaction Date (Sell/Execute)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ForwardFOBContract.cls
public inherited sharing class ForwardFOBContract extends ADGLIB_SObjectDomain {
    public ForwardFOBContract (List<Forward_FOB_Contract__c> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements ADGLIB_SObjectDomain.IConstructable {
        public ADGLIB_SObjectDomain construct(List<SObject> sObjectList) {
            return new ForwardFOBContract(sObjectList);
        }
    }

    public override void onAfterUpdate(Map<Id, sObject> previousRecords) {
        processAdvancePayment(previousRecords);
    }

    private void processAdvancePayment(Map<Id, sObject> previousRecords)
    {
        String transactionDateStr;
        Date transactionDate;
        Date dToday     = Date.today();
        String todayStr = dToday.year() + '-' + dToday.month() + '-' + dToday.day();

        FOB_Additional_Contract__c newAddnlContract;
        Map<Id, FOB_Additional_Contract__c> addnlContractByFOBIds = new Map<Id, FOB_Additional_Contract__c>();
        List<String> buyContractIds = new List<String>();

        for (Forward_FOB_Contract__c record : (List<Forward_FOB_Contract__c>)Records)
        {
            Forward_FOB_Contract__c oldContract = (Forward_FOB_Contract__c)previousRecords.get(record.Id);
            
            if (record.Forward_Contract_Buy_Approved__c != oldContract.Forward_Contract_Buy_Approved__c &&
                record.Forward_Contract_Buy_Approved__c == true && record.Cover_Percentage__c == 100)
            {
                buyContractIds.add(record.Id);

                transactionDate   = record.Transaction_Date__c;
                transactionDateStr = transactionDate.year() + '-' + transactionDate.month() + '-' + transactionDate.day();

                newAddnlContract = new FOB_Additional_Contract__c();

                newAddnlContract.Forward_FOB_Contract__c          = record.Id;
                newAddnlContract.Status__c                        = 'Completed';
                newAddnlContract.Bank_Contract_No_Sell_Execute__c = record.Bank_Contract_No__c;
                newAddnlContract.Effective_Date_Sell_Execute__c   = TreasuryManagementService.getDate(todayStr);
                newAddnlContract.Transaction_Date_Sell_Execute__c = TreasuryManagementService.getDate(transactionDateStr);
                newAddnlContract.Spot_Rate_Sell_Execute__c        = record.Spot_Rate__c;

                addnlContractByFOBIds.put(record.Id, newAddnlContract);
            }
        }

        Database.insert(addnlContractByFOBIds.values(), false);

        if (buyContractIds.size() > 0)
        {
            Map<Id, FOB_Additional_Contract__c> addnlContractByIds = new Map<Id, FOB_Additional_Contract__c>();

            for (FOB_Additional_Contract__c addnlContract : addnlContractByFOBIds.values())
            {
                addnlContractByIds.put(addnlContract.Id, addnlContract);
            }
    
            Map<Id, List<Forward_FOB_Contract_Line_Item__c>> lineItemsByAddnlContractIds = new Map<Id, List<Forward_FOB_Contract_Line_Item__c>>();
            
            List<sObject> lineItems = TreasuryManagementService.getRecordsByIds('Forward_FOB_Contract_Line_Item__c', TreasuryManagementController.SELECT_FIELDS_BY_OBJECT.get('Forward_FOB_Contract_Line_Item__c'),
                                                                                'Forward_FOB_Contract__c', buyContractIds);
    
            for (Forward_FOB_Contract_Line_Item__c item : (List<Forward_FOB_Contract_Line_Item__c>)lineItems)
            {
                item.FOB_Additional_Contract__c = addnlContractByFOBIds.get(item.Forward_FOB_Contract__c).Id;

                if (lineItemsByAddnlContractIds.containsKey(item.FOB_Additional_Contract__c))
                {
                    lineItemsByAddnlContractIds.get(item.FOB_Additional_Contract__c).add(item);
                }
                else
                {
                    lineItemsByAddnlContractIds.put(item.FOB_Additional_Contract__c, new List<Forward_FOB_Contract_Line_Item__c>{item});
                }
            }

            Database.update(lineItems, false);
    
            List<FOB_Additional_Contract__c> updatedFOBAddnlContracts = new List<FOB_Additional_Contract__c>();
    
            for (Id addnlContractId : lineItemsByAddnlContractIds.keySet())
            {
                List<Forward_FOB_Contract_Line_Item__c> contractLineItems = lineItemsByAddnlContractIds.get(addnlContractId);
 
                sObject addnlContract = TreasuryManagementService.calculateContractAmounts(contractLineItems, 'FOB_Additional_Contract__c', addnlContractByIds.get(addnlContractId));
    
                updatedFOBAddnlContracts.add((FOB_Additional_Contract__c)addnlContract);
            }
    
            Database.update(updatedFOBAddnlContracts, false);
        }
    }
}