force-app/main/default/objects/Contact_Staging__c/Contact_Staging__c.object-meta.xml
<CustomObject>
    <description>Contact staging is use for unchecked to contact table</description>
    <label>Contact Staging</label>
    <nameField>
        <displayFormat>Contact-{00000000}</displayFormat>
        <label>Contact Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Staging__c/fields/Contact_Key__c.field-meta.xml
<CustomField>
    <fullName>Contact_Key__c</fullName>
    <label>Contact Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactStagingTriggerTest.cls
@isTest
private class ContactStagingTriggerTest {
	@isTest
    private static void testTriggerExclusion() {
        Account account = Test_DataFactory.createAccount(true, 'accName');        
        Contact con = Test_DataFactory.createContact(false, 'fname', 'lname', account.Id);
        con.Email = 'test@gmail.com';        
        insert con;
        
        TriggerExclusion.excludeTrigger('Contact_Staging__c', true);
        
        Contact_Staging__c contactStaging = new Contact_Staging__c(Contact_Key__c = con.Id);        
        insert contactStaging;
        
    }
    
    @isTest
    private static void testBeforeInsert() {
        Account account = Test_DataFactory.createAccount(true, 'accName');        
        Contact con = Test_DataFactory.createContact(false, 'fname', 'lname', account.Id);
        con.Email = 'test@gmail.com';        
        insert con;
        
        Contact_Staging__c contactStaging = new Contact_Staging__c(Contact_Key__c = con.Id);        
        insert contactStaging;
        
    }
}