force-app/main/default/objects/Contact/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>DeviceToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/Service_Appointment__c.object-meta.xml
<CustomObject>
    <label>Service Appointment</label>
    <nameField>
        <label>Service Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Booking_ID__c.field-meta.xml
<CustomField>
    <fullName>Booking_ID__c</fullName>
    <externalId>true</externalId>
    <label>Booking ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Car_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>Car_Registration_No__c</fullName>
    <label>Car Registration No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Is_Non_Owner__c.field-meta.xml
<CustomField>
    <fullName>Is_Non_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Non Owner</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Non_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Non_Owner_Email__c</fullName>
    <label>Non-Owner Email</label>
    <type>Email</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Non_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Non_Owner_Name__c</fullName>
    <label>Non-Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Non_Owner_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Non_Owner_Phone_Number__c</fullName>
    <label>Non-Owner Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Service_Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Date_Time__c</fullName>
    <label>Service Appointment Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Service_Centre_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Centre_Location__c</fullName>
    <label>Service Centre Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Variant__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Trigger_Service_App_Booking.cls
@isTest(seeAllData=true)
public class Test_Trigger_Service_App_Booking
{
    static testMethod void testInsertTrigger()
    {
        Test.startTest();
        Date today = date.today();
        Service_Appointment__c sa = new Service_Appointment__c(Name='Production Deployment',Action__c='Create',Booking_ID__c='ProdDeployment1',Car_Registration_No__c='KA101',Contact__c='0030K00001atCxY',Registered_Vehicle__c='a0s0K000005fyV5',Service_Appointment_Date_Time__c= today,Service_Centre_Location__c='Delhi');
        insert sa;
        List<Service_Appointment__c> saq = [Select Contact__r.Email,Registered_Vehicle__r.Branch__c,Registered_Vehicle__r.Variant__r.Name,Contact__r.MobilePhone,Contact__r.Device__c,Non_Owner_Email__c,Non_Owner_Name__c,Non_Owner_Phone_Number__c,Is_Non_Owner__c from Service_Appointment__c where Name =: 'Production Deployment'];  
        system.assert(saq.size()>0, true);
        Test.stopTest();
    }
    
   
}