force-app/main/default/objects/Contact/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If is checked , it is consent</inlineHelpText>
    <label>Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Staging__c/Contact_Staging__c.object-meta.xml
<CustomObject>
    <description>Contact staging is use for unchecked to contact table</description>
    <label>Contact Staging</label>
    <nameField>
        <displayFormat>Contact-{00000000}</displayFormat>
        <label>Contact Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Staging__c/fields/Contact_Key__c.field-meta.xml
<CustomField>
    <fullName>Contact_Key__c</fullName>
    <label>Contact Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/ContactStagingHandler.cls
public class ContactStagingHandler  
{

	public static void uncheckPDPA_email(List<Contact_Staging__c> csList)
	{

		List<string> conId_List = new List<string>();
		List<string> emailAddrList = new List<string>();

		List<contact> contactList_update = new List<contact>();
		
		for(Contact_Staging__c csObj : csList)
		{
			if(csObj.Contact_Key__c.startsWith('003'))
			{
				conId_List.add(csObj.Contact_Key__c);		
			}
			else if(csObj.Contact_Key__c.contains('@'))
			{
				emailAddrList.add(csObj.Contact_Key__c);
			}
		} 

		if(conId_List.size() > 0)
		{
			for(contact con : [select id, Email__c from contact where id in: conId_List])
			{
				con.Email__c = false;
				contactList_update.add(con);

			}
		}
		if(emailAddrList.size() > 0)
		{
			for(contact con : [select id, Email__c from contact where Email in: emailAddrList])
			{
				con.Email__c = false;
				contactList_update.add(con);
			}
		}

		if(contactList_update.size() > 0)
		{
			update contactList_update;
		}

	}

}