force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Please enter the last 4 digits of the Customer&apos;s NRIC followed by the Date of Birth in the following format DDMMYYY. E.g. 314B10101976</inlineHelpText>
    <label>NRIC _ Passport No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>ContactId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_Trigger_EventRegistration_Email.cls
@isTest(seeAllData=true)
public class Test_Trigger_EventRegistration_Email {

    static testMethod void testInsertTrigger()
    {
        Test.startTest();    
        Date OppExpectedCloseDate = date.today();
        Contact TestCon =  new Contact(LastName='TestRun',NRIC_Passport_No__c='TestRunNRIC');
        insert TestCon;
        
        Event_Registration__c tempInsertER = new Event_Registration__c();
        tempInsertER.Name = 'Test_Er';
        tempInsertER.ContactId__c =TestCon.Id;         
        insert tempInsertER;
        
        tempInsertER.Name = 'Test_Er1';
        update tempInsertER;
            
        List<Event_Registration__c> ErList = [Select Id, Name from Event_Registration__c where Name =: 'Test_Er1'];  
        system.assert(ErList.size()>0, true);
        Test.stopTest();
    }
    
    
    
}