force-app/main/default/objects/Sales_Opportunity__c/Sales_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom Sales Opportunity Object</description>
    <label>Sales Opportunity</label>
    <nameField>
        <displayFormat>SO-{YYYYMM}-{000000}</displayFormat>
        <label>Sales Opportunity  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Used_Car_Vehicle_Stock__c/Used_Car_Vehicle_Stock__c.object-meta.xml
<CustomObject>
    <description>Vehicle Stock Master for Republic Auto (RA) Used Car</description>
    <label>Used Car Vehicle Stock</label>
    <nameField>
        <displayFormat>UCVS-{0000000}</displayFormat>
        <label>Used Car Vehicle Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Used Car Vehicle Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Used_Car_Vehicle_Stock__c/fields/Stock_Number__c.field-meta.xml
<CustomField>
    <fullName>Stock_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>VEHDOCNO</inlineHelpText>
    <label>Stock Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle_Stock_Reservation__c/Vehicle_Stock_Reservation__c.object-meta.xml
<CustomObject>
    <description>Stock Reservation for Non C&amp;C MF</description>
    <label>Vehicle Stock Reservation</label>
    <nameField>
        <displayFormat>STKRES-{0000000}</displayFormat>
        <label>Vehicle Stock Reservation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Stock Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Stock_Reservation__c/fields/Sales_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Sales_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Opportunity</label>
    <referenceTo>Sales_Opportunity__c</referenceTo>
    <relationshipName>RA_Used_Car_Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Stock_Reservation__c/fields/Used_Car_Vehicle_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Car_Vehicle_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Used Car Vehicle Stock</label>
    <referenceTo>Used_Car_Vehicle_Stock__c</referenceTo>
    <relationshipName>Used_Car_Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VehicleStockReservationServiceTest.cls
/** *****
 * Description : Test Class for VehicleStockReservationService class
 * 
 * Change History
 * Date(YYYYMMDD)       Name                 Description
 * 20210110             khanh.do@aodigy      Created Initial Version. 
 * 
** *****/
@isTest
private class VehicleStockReservationServiceTest {
	
    @testSetup
    private static void setup() {
        Account personAcc = Test_DataFactory.createPA(true, 'RA-Testing', 'test@ra.com', 'Prospect');
        Used_Car_Vehicle_Stock__c vehicleStock = Test_DataFactory.createSoldUsedCar(true, personAcc.Id, 'STOCK-001', 'OIYG1', 'AUDI', 'A2');
    	Sales_Opportunity__c salesOpp = Test_DataFactory.createSalesOpp(true, personAcc.Id, 'Open', 'Dummy-SC', 'dummy.sc@ra.com', '65343434');
        
        Datetime apptDatetime = Datetime.now().addDays(7);
        String location = 'Cycle & Carriage Service Centre - Sin Ming,600 Sin Ming Avenue, Singapore 575733';
        Vehicle_Stock_Reservation__c reservation = Test_DataFactory.createReservation(true, personAcc.Id, apptDatetime, location, 1000, salesOpp.Id,  vehicleStock.Id);
    }

    @isTest
    private static void testGetReservationByResevationNo() {
        Vehicle_Stock_Reservation__c reservation = [SELECT Name FROM Vehicle_Stock_Reservation__c LIMIT 1];
        Vehicle_Stock_Reservation__c result = VehicleStockReservationService.getReservationByResevationNo(reservation.Name);
        System.assertNotEquals(null, result);
    }

    @isTest
    private static void testGetReservationById() {
        Vehicle_Stock_Reservation__c reservation = [SELECT Id FROM Vehicle_Stock_Reservation__c LIMIT 1];
        Vehicle_Stock_Reservation__c result = VehicleStockReservationService.getReservationById(reservation.Id);
        System.assertNotEquals(null, result);
    }
    @isTest
    private static void testGetReservationByStockNo() {
        Vehicle_Stock_Reservation__c reservation = [SELECT Used_Car_Vehicle_Stock__r.Stock_Number__c FROM Vehicle_Stock_Reservation__c LIMIT 1];

        List<Vehicle_Stock_Reservation__c> result = VehicleStockReservationService.getReservationByStockNo(new Set<String>{reservation.Used_Car_Vehicle_Stock__r.Stock_Number__c});
        System.assertNotEquals(null, result);
    }
    
}