force-app/main/default/objects/Master_Approval__c/Master_Approval__c.object-meta.xml
<CustomObject>
    <label>Master Approval</label>
    <nameField>
        <label>Master_Approval__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Approval__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Writeback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Approval__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Approval__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>YYYYMMDD_ListViewID_Source</description>
    <inlineHelpText>YYYYMMDD_ListViewID_Source</inlineHelpText>
    <label>Unique Key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>Customer&apos;s Reward Credit 
- per Reward Type
- per Registered Vehicle
- per Expiry Date</description>
    <label>Reward</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward__c/fields/COST__c.field-meta.xml
<CustomField>
    <fullName>COST__c</fullName>
    <description>Inherited from Transaction object&apos;s COST</description>
    <label>COST</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Reward_Profile__c.field-meta.xml
<CustomField>
    <fullName>Reward_Profile__c</fullName>
    <label>Reward Profile</label>
    <referenceTo>Reward_Profile__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Consumed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Provisioning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/Reward_Profile__c.object-meta.xml
<CustomObject>
    <label>Reward Profile</label>
    <nameField>
        <label>Reward Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_Profile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Boutique</fullName>
            </value>
            <value>
                <fullName>Birthday Voucher</fullName>
            </value>
            <value>
                <fullName>Grooming Package</fullName>
            </value>
            <value>
                <fullName>Service Credit Voucher</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>Discount Voucher</fullName>
            </value>
            <value>
                <fullName>Service Credit</fullName>
            </value>
            <value>
                <fullName>Accessories Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>For Non-Fleet : Record Type ID +&apos;_&apos;+ Contact ID +&apos;_&apos;+ Brand +&apos;_&apos;+ Reward Type
For Fleet : Record Type ID +&apos;_&apos;+ Registered Vehicle ID + &apos;_&apos;+ Brand +&apos;_&apos;+ Reward Type</description>
    <inlineHelpText>For Non-Fleet : 
Record Type ID +&apos;_&apos;+ Contact ID +&apos;_&apos;+ Brand +&apos;_&apos;+ Reward Type

For Fleet : 
Record Type ID +&apos;_&apos;+ Registered Vehicle ID + &apos;_&apos;+ Brand +&apos;_&apos;+ Reward Type</inlineHelpText>
    <label>Unique Key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Business Account (Staff, Leasing), Person Account</description>
    <label>C&amp;C Fleet</label>
</RecordType>

cncProd/force-app/main/default/objects/Reward_Usage__c/Reward_Usage__c.object-meta.xml
<CustomObject>
    <label>Reward Usage</label>
    <nameField>
        <label>Reward Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(Reward__r.Brand__c)</formula>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>eShop</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/COST__c.field-meta.xml
<CustomField>
    <fullName>COST__c</fullName>
    <description>Cost Center Reference</description>
    <formula>Reward__r.COST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COST</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Amount__c</fullName>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Master_Approval__c.field-meta.xml
<CustomField>
    <fullName>Master_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup reference to Master Approval object for bulk approval process for &quot;Write-Back&quot;</description>
    <label>Master Approval</label>
    <referenceTo>Master_Approval__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward_Usage__c.field-meta.xml
<CustomField>
    <fullName>Reward_Usage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Reference to Debit Reward Usage record</description>
    <label>Reward Usage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Reward_Usage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Debit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Reward_Usage__c</referenceTo>
    <relationshipLabel>Credit Usages</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <formula>TEXT(Reward__r.Source__c)</formula>
    <label>Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expired</fullName>
                <color>#BBBBBB</color>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Hold</fullName>
                <color>#FFFF66</color>
                <label>Hold</label>
            </value>
            <value>
                <fullName>Issued</fullName>
                <color>#57F17C</color>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Provisioning</fullName>
                <color>#FFFF66</color>
                <label>Provisioning</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#BBBBBB</color>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Utilised</fullName>
                <color>#FF0000</color>
                <label>Utilised</label>
            </value>
            <value>
                <fullName>Write-Back</fullName>
                <color>#6666CC</color>
                <label>Write-Back</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>Used to capture :
Autoline Invoice Date, Expiry Date + 1, Extension Date for Debit Usage, 
Refund Date for Credit Usage</description>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Expiry</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Credit to Customer (i.e. Refund/Adjustment/etc.)</description>
    <label>Credit</label>
</RecordType>

force-app/main/default/objects/Reward_Usage__c/recordTypes/Debit.recordType-meta.xml
<RecordType>
    <fullName>Debit</fullName>
    <active>true</active>
    <description>Debit from Customer (i.e. Credit Deduction)</description>
    <label>Debit</label>
</RecordType>

force-app/main/default/classes/CMBatchCreateMasterApprovalTest.cls
@isTest
public class CMBatchCreateMasterApprovalTest {
    static Id debitUsageTypeId = Schema.SObjectType.Reward_Usage__c.getRecordTypeInfosByDeveloperName().get('Debit').getRecordTypeId();
    static Reward_Profile__c rewardProfile;
    
    @isTest
    private static void setupData() {
        rewardProfile = Test_DataFactory.createRewardProfile(true, 'Fleet', 'CCK', 'KIA', 'Accessories Credit');        
    }
    
    @isTest
    private static void testHappyPath_NoMasterApprovalExist() {
        setupData();
        Reward__c reward = Test_DataFactory.createReward(false, rewardProfile.Id, rewardProfile.Type__c, 'Valid', Date.today().addDays(5));
        reward.Credit__c = 20000;
        insert reward;
        
        List<Reward_Usage__c> debitUsages = new List<Reward_Usage__c >();
        Double totalAmount = 0;
        for(Integer i=0; i< 5; i++) {
            Reward_Usage__c debitUsage = Test_DataFactory.createRewardUsage(false, reward.Id, 'Hold', 'Debit');
            debitUsage.Credit_Amount__c = 1000 + 100*i;
            debitUsage.Status__c = 'Expired';
            debitUsage.Type__c = 'Expiry';
            debitUsages.add(debitUsage);
            totalAmount += debitUsage.Credit_Amount__c;
        }       
        insert debitUsages;
        
        //ListView listview = [SELECT Id FROM ListView WHERE SObjectType = 'Reward_Usage__c' LIMIT 1]; // AND Name = 'Expired Usages - KIA'
        String listViewId = '00xdummylistviewid';
        String query = 'SELECT Name, RecordType.Name, Reward__r.Name, Brand__c, Credit_Amount__c, toLabel(Status__c), toLabel(Channel__c), Source__c, Transaction_Date__c, CreatedBy.Name, COST__c, Id, RecordTypeId, CreatedDate, LastModifiedDate, SystemModstamp, Reward__c, CreatedBy.Id, CreatedById FROM Reward_Usage__c WHERE Status__c = \'Expired\' AND Type__c = \'Expiry\'';
        Test.startTest();
        Database.executeBatch(new CMBatchCreateMasterApproval(listViewId ,query));
    	Test.stopTest();
        List<Master_Approval__c> result = [SELECT Id, Request_Type__c, Total_Amount__c, Unique_Key__c FROM Master_Approval__c];
    	System.assertEquals(1, result.size());
        System.assertEquals('Writeback', result[0].Request_Type__c);
        System.assertEquals(totalAmount, result[0].Total_Amount__c);
        String expectedUniqueKey = String.valueOf(Date.today()) + '_' + listViewId + '_' + 'VehicleSales';        
        System.assertEquals(expectedUniqueKey, result[0].Unique_Key__c);
    }
    
    @isTest
    private static void testHappyPath_withExistingMasterApproval() {
        setupData();
        //ListView listview = [SELECT Id FROM ListView WHERE SObjectType = 'Reward_Usage__c' LIMIT 1]; //AND Name = 'Expired Usages - KIA'
        String listViewId = '00xdummylistviewid';
        String query = 'SELECT Name, RecordType.Name, Reward__r.Name, Brand__c, Credit_Amount__c, toLabel(Status__c), toLabel(Channel__c), Source__c, Transaction_Date__c, CreatedBy.Name, COST__c, Id, RecordTypeId, CreatedDate, LastModifiedDate, SystemModstamp, Reward__c, CreatedBy.Id, CreatedById FROM Reward_Usage__c AND Status__c = \'Expired\' AND Type__c = \'Expiry\'';
        
        Reward__c salesGoodWillReward = Test_DataFactory.createReward(false, rewardProfile.Id, rewardProfile.Type__c, 'Valid', Date.today().addDays(5));
        salesGoodWillReward.Credit__c = 20000;
        salesGoodWillReward.Source__c = 'Sales - Goodwill';
        insert salesGoodWillReward;
        
        String source = 'AfterSales';
        Double masterApprovalTotalAmount = 10000;
        Double expectedUpdatedTotalAmount = masterApprovalTotalAmount;
        Master_Approval__c masterApproval = Test_DataFactory.createMasterApproval(true, masterApprovalTotalAmount, String.valueOf(Date.today()) + '_' + listViewId + '_' + source);
        List<Reward_Usage__c> debitUsages = new List<Reward_Usage__c >();
        for(Integer i=0; i< 5; i++) {
            Reward_Usage__c debitUsage = Test_DataFactory.createRewardUsage(false, salesGoodWillReward.Id, 'Hold', 'Debit');
            debitUsage.Credit_Amount__c = 1000 + 100*i;
            debitUsage.Status__c = 'Expired';
            debitUsage.Type__c = 'Expiry';
            debitUsage.Master_Approval__c = masterApproval.Id;
            debitUsages.add(debitUsage);
            expectedUpdatedTotalAmount += debitUsage.Credit_Amount__c;
        }       
        insert debitUsages;
        Test.startTest();
        Database.executeBatch(new CMBatchCreateMasterApproval(listViewId ,query));
    	Test.stopTest();
        List<Master_Approval__c> result = [SELECT Id, Request_Type__c, Total_Amount__c, Unique_Key__c FROM Master_Approval__c];
        System.assertEquals(expectedUpdatedTotalAmount, result[0].Total_Amount__c);
    }

}