cncProd/force-app/main/default/objects/global_var__c/global_var__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>JCC Global Variables</label>
</CustomObject>

cncProd/force-app/main/default/objects/global_var__c/fields/APIGateway_url__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_url__c</fullName>
    <label>APIGateway_url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/global_var__c/fields/SageMakerAPIKey__c.field-meta.xml
<CustomField>
    <fullName>SageMakerAPIKey__c</fullName>
    <label>SageMaker API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/Used_Car_Quote__c.object-meta.xml
<CustomObject>
    <label>Used Car Quote</label>
    <nameField>
        <displayFormat>UCQ-{000000}</displayFormat>
        <label>Used Car Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Used Car Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Used_Car_Quote__c/fields/Actual_ARF_Paid__c.field-meta.xml
<CustomField>
    <fullName>Actual_ARF_Paid__c</fullName>
    <label>Actual ARF Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <label>Chassis No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/COE_Category__c.field-meta.xml
<CustomField>
    <fullName>COE_Category__c</fullName>
    <label>COE Category</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/fields/COE_Period_Years__c.field-meta.xml
<CustomField>
    <fullName>COE_Period_Years__c</fullName>
    <label>COE Period (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/COE_Rebate_Amount__c.field-meta.xml
<CustomField>
    <fullName>COE_Rebate_Amount__c</fullName>
    <label>COE Rebate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Customer_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID_Type__c</fullName>
    <label>Customer ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business (e.g. 51234567M)</fullName>
                <label>Business</label>
            </value>
            <value>
                <fullName>Club/Association/Organisation (e.g. T08PQ1234A)</fullName>
                <label>Club/Association/Organisation</label>
            </value>
            <value>
                <fullName>Company (e.g. 198912345K)</fullName>
                <label>Company</label>
            </value>
            <value>
                <fullName>Foreign Company (e.g. T08FC1234A)</fullName>
                <label>Foreign Company</label>
            </value>
            <value>
                <fullName>Foreign Identification Number (e.g. F/G/M1234567N)</fullName>
                <label>Foreign Identification Number</label>
            </value>
            <value>
                <fullName>Foreign Passport (e.g. 12345678)</fullName>
                <label>Foreign Passport</label>
            </value>
            <value>
                <fullName>Government (e.g. T08GA1234A)</fullName>
                <label>Government</label>
            </value>
            <value>
                <fullName>Limited Liability Partnership (e.g. T08LL1234A)</fullName>
                <label>Limited Liability Partnership</label>
            </value>
            <value>
                <fullName>Limited Partnership (e.g. T08LP1234A)</fullName>
                <label>Limited Partnership</label>
            </value>
            <value>
                <fullName>Malaysia NRIC (e.g. 200312345678)</fullName>
                <label>Malaysia NRIC</label>
            </value>
            <value>
                <fullName>Professional (e.g. T08PQ1234A)</fullName>
                <label>Professional</label>
            </value>
            <value>
                <fullName>Singapore NRIC (e.g. S1234567D)</fullName>
                <default>true</default>
                <label>Singapore NRIC</label>
            </value>
            <value>
                <fullName>Statutory Board (e.g. T08GB1234A)</fullName>
                <label>Statutory Board</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Customer_NRIC__c.field-meta.xml
<CustomField>
    <fullName>Customer_NRIC__c</fullName>
    <inlineHelpText>Input last 4 characters (e.g. 567D)</inlineHelpText>
    <label>Customer NRIC</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/fields/First_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Registration_Date__c</fullName>
    <label>First Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Intended_Deregistration_Date__c.field-meta.xml
<CustomField>
    <fullName>Intended_Deregistration_Date__c</fullName>
    <label>Intended Deregistration Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/fields/Manufacturing_Year__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Year__c</fullName>
    <label>Manufacturing Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/fields/Maximum_Power_Output__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Power_Output__c</fullName>
    <label>Maximum Power Output</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/fields/Open_Market_Value__c.field-meta.xml
<CustomField>
    <fullName>Open_Market_Value__c</fullName>
    <label>Open Market Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Original_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Original_Registration_Date__c</fullName>
    <label>Original Registration Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/fields/PARF_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>PARF_Eligibility__c</fullName>
    <label>PARF Eligibility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/PARF_Eligibility_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>PARF_Eligibility_Expiry_Date__c</fullName>
    <label>PARF Eligibility Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/PARF_Rebate_Amount__c.field-meta.xml
<CustomField>
    <fullName>PARF_Rebate_Amount__c</fullName>
    <label>PARF Rebate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/fields/QP_Paid__c.field-meta.xml
<CustomField>
    <fullName>QP_Paid__c</fullName>
    <label>QP Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/fields/Transfer_Count__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Count__c</fullName>
    <label>Transfer Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Quote__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Vehicle_No__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_No__c</fullName>
    <label>Vehicle No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Used_Car_Quote__c/fields/Vehicle_to_be_Exported__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_to_be_Exported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vehicle to be Exported</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/classes/RAP_SendVehicleDetailsAPITest.cls
/** *****
 * Description : Test Class for RAP_SendVehicleDetailsAPI class
 * 
 * Change History
 * Date(YYYYMMDD)       Name                        Description
 * 20220524             tan.nguyen@aodigy.com       Created Initial Version. 
 * 
** *****/

@isTest
private class RAP_SendVehicleDetailsAPITest {
    @TestSetup
    private static void setUp() {
        Used_Car_Quote__c testQuote = new Used_Car_Quote__c();
        testQuote.Customer_ID_Type__c = Used_Car_Quote__c.Customer_ID_Type__c.getDescribe().getPicklistValues()[1].getValue();
        testQuote.Customer_NRIC__c = 'T098';
        testQuote.Vehicle_No__c = 'VN098';
        testQuote.Vehicle_to_be_Exported__c = true;
        testQuote.Intended_Deregistration_Date__c = Date.today().addMonths(1);
        testQuote.Vehicle_Make__c = 'VM098';
        testQuote.Vehicle_Model__c = 'MER';
        testQuote.Primary_Color__c = 'Black';
        testQuote.Manufacturing_Year__c = '2022';
        testQuote.Engine_No__c = 'EN098';
        testQuote.Chassis_No__c = 'CN098';
        testQuote.Maximum_Power_Output__c = '500HP';
        testQuote.Open_Market_Value__c = 55000;
        testQuote.Original_Registration_Date__c = Date.today();
        testQuote.First_Registration_Date__c = Date.today();
        testQuote.Transfer_Count__c = 1;
        testQuote.Actual_ARF_Paid__c = 1000;
        testQuote.PARF_Eligibility__c = 'Yes';
        testQuote.PARF_Eligibility_Expiry_Date__c = Date.today().addMonths(2);
        testQuote.PARF_Rebate_Amount__c = 3000;
        testQuote.COE_Expiry_Date__c = Date.today().addYears(3);
        testQuote.COE_Category__c = 'COE Category 1';
        testQuote.COE_Period_Years__c = 10;
        testQuote.QP_Paid__c = 500;
        testQuote.COE_Rebate_Amount__c = 1200;
        testQuote.Total_Rebate_Amount__c = 2200;
        testQuote.recordTypeId = UsedCarQuoteService.getMFRecordTypeId();
        insert testQuote;
        
        global_var__c test = new global_var__c();
        test.APIGateway_url__c = 'https://www.test.com';
        test.SageMakerAPIKey__c = '123456789';
        upsert test;
    }



    @isTest
    private static void testSendVehicleDetails_Success() {
        Used_Car_Quote__c ucq = [ SELECT Id FROM Used_Car_Quote__c];
        String testQuoteId = ucq.Id;
        Test.setMock(HttpCalloutMock.class, new ADGLIB_CalloutMock());
        Test.startTest();
        RAP_SendVehicleDetailsAPI.sendVehicleDetails(testQuoteId);
        Test.stopTest();
    }

    @isTest
    private static void testSendVehicleDetails_Fail() {
        Used_Car_Quote__c ucq = [ SELECT Id FROM Used_Car_Quote__c];
        String testQuoteId = ucq.Id;
        Test.startTest();
        RAP_SendVehicleDetailsAPI.sendVehicleDetails(testQuoteId);
        Test.stopTest();
    }

    @isTest
    private static void testSendVehicleDetails_null() {
        Test.startTest();
        RAP_SendVehicleDetailsAPI.sendVehicleDetails('a2nO000000B8Yk4IAJ');
        Test.stopTest();
    }
}