cncProd/force-app/main/default/objects/global_var__c/global_var__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>JCC Global Variables</label>
</CustomObject>

cncProd/force-app/main/default/objects/global_var__c/fields/DWHDelinkedVehicleOwner__c.field-meta.xml
<CustomField>
    <fullName>DWHDelinkedVehicleOwner__c</fullName>
    <description>Default Owner of the Delinked Vehicle, or Registered Vehicles that do not have an Owner.</description>
    <label>DWH Delinked Vehicle Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/DWH_Vehicle_ID__c.field-meta.xml
<CustomField>
    <fullName>DWH_Vehicle_ID__c</fullName>
    <externalId>true</externalId>
    <label>DWH Vehicle ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/DWH_BatchDeLinkVehicles.cls
/** *******
 * Class Name: DWH_BatchDeLinkVehicles
 * Description: Batch class to remove link to a the previous owner of a Registered Vehicle that is currently not owned by anyone.
 * 
 * Date                 Developer Name				Description
 * 10-May-2019          CGaylan						Created.
 * 06-Oct-2020          HS@aodigy                   Assign the Registered Vehicle to No-One (i.e. NULL)
 * 
******* **/ 
public class DWH_BatchDeLinkVehicles implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable, Database.Stateful{
	
    public Set<String> dwhMagicList = new Set<String>();
	public Map<String, String> magicMap = new Map<String, String>();
    
    public DWH_BatchDeLinkVehicles(){
        System.enqueuejob( new DWH_QueueDeLinkVehicles() );  
    }
    
    public DWH_BatchDeLinkVehicles(Set<String> dwhMagicAPI){
        dwhMagicList = dwhMagicAPI;
    }
    
    public DWH_BatchDeLinkVehicles(Map<String, String> dwhMagicAPI ){
        magicMap = dwhMagicAPI;
    }
    
    //execute Schedule
    public void execute (SchedulableContext ctx){   
      System.enqueuejob( new DWH_QueueDeLinkVehicles() );  
    }     
    
    //Query all Registered Vehicles currently without Owner as provided by the DWH API.
    public Database.QueryLocator start(Database.BatchableContext db){
        return Database.getQueryLocator([SELECT Id, Contact__c, Account__c, Registration_Number__c, DWH_Vehicle_ID__c 
                                         FROM Registered_Vehicle__c 
                                         WHERE DWH_Vehicle_ID__c IN: magicMap.keySet()]);
    }
    
    public void execute(Database.BatchableContext db, List<Registered_Vehicle__c> scope){
		        
        if(scope != null && !scope.isEmpty())
        {
            try
            {
                global_var__c dwhVal = global_var__c.getOrgDefaults();
                //Dummy Default Owner for Registered Vehicles without Owner Info in DWH.
                String defaultOwner = dwhVal.DWHDelinkedVehicleOwner__c; 
                List<Registered_Vehicle__c> rvList = new List<Registered_Vehicle__c>();
                
                for(Registered_Vehicle__c regVeh : scope)
                {
                    if(regVeh.Contact__c != defaultOwner)
                    {

                        //regVeh.Contact__c = defaultOwner;

                        //19-Aug-2019, delinked Vehicles will have their Registration Number updated to UNKNOWN
                        regVeh.Registration_Number__c = Constants.DELINK_REGNUM;
                        
                        regVeh.Contact__c = null;
                        regVeh.Account__c = null;

                        //Commented-out for Future Purposes; as of the moment all Reg Num will be 'UNKNOWN'
                        /*
                        if( magicMap.containsKey( regVeh.DWH_Vehicle_ID__c ) ){
                            regVeh.Registration_Number__c = magicMap.get( regVeh.DWH_Vehicle_ID__c );
                        }
                        */
                        rvList.add(regVeh);
                    }
                }

                if( rvList <> null && !rvList.isEmpty() ){
                    update rvList;
                }
            }
            catch(Exception e){
                loggerDataPool.buildLogDataPool('DWH_BatchDeLinkVehicles', e);
            }

        }     
    }
    
    public void finish(Database.BatchableContext db){
        batchDataPool.buildBatchDataPool('DWH_BatchDeLinkVehicles', db.getJobId());
    }
}