cncProd/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{YYMM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Invoice__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <description>Remarks when Transaction Type = &apos;Void&apos;</description>
    <label>Remarks</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

cncProd/force-app/main/default/objects/Invoice__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>TransactionID</inlineHelpText>
    <label>Transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentVoidScheduler.cls
/******************************************************
 * Class Name: PaymentVoidScheduler
 * Description: Payment scheduler for updating Transaction Type to void.
 * 				For payment records associcated to Campaigns with Type = Promotions.
 * 			
 ******************************************************/
public class PaymentVoidScheduler implements Database.Batchable<sObject>, Schedulable{
    
    
    public void execute(SchedulableContext cx){
        //Get at least one Payment Records with Transaction Id is null and Campaign Id is present
        //This will determine if batch will run
        List<Invoice__c> invList = new List<Invoice__c>();
        invList = [SELECT Id, Remarks__c, Transaction_Type__c
                   FROM Invoice__c 
                   WHERE Transaction_ID__c = null 
                   AND Transaction_Type__c != 'Void'
                   AND Campaign__c != null
                   AND Campaign__r.Type = 'Promotions' 
                   LIMIT 1];
        
        if(invList!=null && !invList.isEmpty()){
            Database.executeBatch( new PaymentVoidScheduler() );
        }
        
    }
    
    public Database.QueryLocator start(Database.BatchableContext db){
        return Database.getQueryLocator([SELECT Id, Remarks__c, Transaction_Type__c 
                                         FROM Invoice__c 
                                         WHERE Transaction_ID__c = null 
                                         AND Transaction_Type__c != 'Void'
                                         AND Campaign__c != null
                                         AND Campaign__r.Type = 'Promotions' 
                                        ]);
    }
    
    public void execute(Database.BatchableContext db, List<Invoice__c> scope){
        for(Invoice__c inv : scope){
            inv.Transaction_Type__c = Constants.STAT_VOID;
            inv.Remarks__c = Label.PaymentVoided;
        }
        Database.update (scope, false);
    }
	
    public void finish(Database.BatchableContext db){
		//Do not create logs for Batch data pool
    }
}