cncProd/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{YYMM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Drive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stock_Reservation__c/Stock_Reservation__c.object-meta.xml
<CustomObject>
    <label>Stock Reservation</label>
    <nameField>
        <displayFormat>Res-{yyyy}{mm}{000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/classes/Constants.cls
/**************************************************
* Class Name: Constants
* Description: Handler Class for Stock Reservation Trigger
* 
* Revision History:
* Developer Name		Date			Description
* CGaylan				27-06-2019		Created.
**************************************************/ 
public without sharing class Constants {
    
    /**************** Stock Reservation ****************/
    public static final String CANCEL = 'Cancel';
    
    /*************** For Running Schedule Purge NRIC Values ****************/
    public static final List<String> SOBJ_PURGE_NRIC = new List<String>{'Invoice__c',
                														'Opportunity',
        																'Test_Drive__c',
        																'Stock_Reservation__c'};
	/*************** Payment ****************/
    public static final String STAT_VOID = 'Void';
    
    /*************** Delinking of Vehicles ****************/          
    public static final String DELINK_REGNUM = 'UNKNOWN';
}