force-app/main/default/objects/HS_Type__c/HS_Type__c.object-meta.xml
<CustomObject>
    <label>HS Code</label>
    <nameField>
        <label>HS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HS Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HS_Type__c/fields/HS_Type__c.field-meta.xml
<CustomField>
    <fullName>HS_Type__c</fullName>
    <label>HS Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manufacturer_Invoice__c/Manufacturer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Inward Declaration Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inward Declaration Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manufacturer_Invoice__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <label>Invoice No.</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manufacturer_Invoice__c/fields/Product_Code_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_Description__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CASC Product Code Description</label>
    <referenceTo>Product_Code__c</referenceTo>
    <relationshipName>Manufacturer_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturer_Invoice__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <label>TN Total Invoice Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Manufacturer_Invoice__c/fields/Total_Invoice_Amount_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount_Currency_Code__c</fullName>
    <label>TN Total Invoice Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manufacturer_Invoice__c/fields/Vehicle_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Shipment</label>
    <referenceTo>Vehicle_Shipment__c</referenceTo>
    <relationshipName>Manufacturer_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Model__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Code__c/Product_Code__c.object-meta.xml
<CustomObject>
    <description>For Inward Declaration</description>
    <label>Product Code</label>
    <nameField>
        <label>Product Code Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Code__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/Shipment_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Shipment Line Item</label>
    <nameField>
        <displayFormat>SLI-{YYYYMM}-{00000}</displayFormat>
        <label>Shipment Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Chassis No.</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Colour_Code__c.field-meta.xml
<CustomField>
    <fullName>Colour_Code__c</fullName>
    <label>Colour Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Engine No.</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Ex_Factory_Charges__c.field-meta.xml
<CustomField>
    <fullName>Ex_Factory_Charges__c</fullName>
    <label>Ex Factory Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/FOB_Amount__c.field-meta.xml
<CustomField>
    <fullName>FOB_Amount__c</fullName>
    <label>FOB Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/FOB_Amount_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>FOB_Amount_Currency_Code__c</fullName>
    <label>FOB Amount Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Franchise_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Freight_Charges__c.field-meta.xml
<CustomField>
    <fullName>Freight_Charges__c</fullName>
    <label>Freight Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Insurance_Charges__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Charges__c</fullName>
    <label>Insurance Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manufacturer Invoice No.</description>
    <label>Invoice No.</label>
    <referenceTo>Manufacturer_Invoice__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Key_No__c.field-meta.xml
<CustomField>
    <fullName>Key_No__c</fullName>
    <label>Key No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Manufacturer_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Ref_No__c</fullName>
    <description>For CIT</description>
    <label>Manufacturer Ref. No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Other_Charges__c.field-meta.xml
<CustomField>
    <fullName>Other_Charges__c</fullName>
    <label>Other Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Product_Code_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_Description__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TN CASC Product Code Description</label>
    <referenceTo>Product_Code__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Production_Month__c.field-meta.xml
<CustomField>
    <fullName>Production_Month__c</fullName>
    <label>Production Month</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/TN_HS_Code__c.field-meta.xml
<CustomField>
    <fullName>TN_HS_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TN HS Code</label>
    <referenceTo>HS_Type__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Transport_Charges__c.field-meta.xml
<CustomField>
    <fullName>Transport_Charges__c</fullName>
    <label>Transport Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Trim__c.field-meta.xml
<CustomField>
    <fullName>Trim__c</fullName>
    <label>Trim</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line_Item__c/fields/Vehicle_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Shipment__c</fullName>
    <label>Vehicle Shipment</label>
    <referenceTo>Vehicle_Shipment__c</referenceTo>
    <relationshipLabel>Shipment Line Items</relationshipLabel>
    <relationshipName>Shipment_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Shipment__c/Vehicle_Shipment__c.object-meta.xml
<CustomObject>
    <label>Vehicle Shipment</label>
    <nameField>
        <displayFormat>Ship-{YYYYMM}-{00000}</displayFormat>
        <label>Vehicle Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Shipments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Shipment__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AUD</fullName>
        <label>AUD - Australian Dollar</label>
    </customValue>
    <customValue>
        <fullName>CNY</fullName>
        <label>CNY - Chinese Yuan</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
        <label>EUR - Euro Dollar</label>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
        <label>JPY - Japanese Yen</label>
    </customValue>
    <customValue>
        <fullName>RMB</fullName>
        <label>RMB - Chinese RMB</label>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
        <label>SGD - Singapore Dollar</label>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
        <label>USD - United State Dollar</label>
    </customValue>
    <customValue>
        <fullName>THB</fullName>
        <isActive>false</isActive>
        <label>THB - Thai Bhat</label>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
        <isActive>false</isActive>
        <label>NZD - New Zealand Dollar</label>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
        <isActive>false</isActive>
        <label>MYR - Malaysian Ringgit</label>
    </customValue>
    <customValue>
        <fullName>IDR</fullName>
        <isActive>false</isActive>
        <label>IDR - Indonesia Rupiah</label>
    </customValue>
    <customValue>
        <fullName>HKD</fullName>
        <isActive>false</isActive>
        <label>HKD - Hongkong Dollar</label>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
        <isActive>false</isActive>
        <label>GBP - Great Britain Pound</label>
    </customValue>
    <customValue>
        <fullName>DEM</fullName>
        <isActive>false</isActive>
        <label>DEM - Deutsch Mark</label>
    </customValue>
    <customValue>
        <fullName>FRF</fullName>
        <isActive>false</isActive>
        <label>FRF - France</label>
    </customValue>
    <masterLabel>Currency Code</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Franchise_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CITCV</fullName>
    </customValue>
    <customValue>
        <fullName>CITPC</fullName>
    </customValue>
    <customValue>
        <fullName>KIACV</fullName>
    </customValue>
    <customValue>
        <fullName>KIAPC</fullName>
    </customValue>
    <customValue>
        <fullName>MITCV</fullName>
    </customValue>
    <customValue>
        <fullName>MITPC</fullName>
    </customValue>
    <customValue>
        <fullName>MBCV</fullName>
    </customValue>
    <customValue>
        <fullName>MBPC</fullName>
    </customValue>
    <masterLabel>Franchise Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VS_UploadShipmentLineItemsController.cls
/*==========================================================================================================================================================================
 * Controller class for vs_UploadShipmentLineItemsController LWC
 * Created By: Aodigy Team
 * Create Date: August 2022
 * History
 *              DATE::                              BY::                                TICKET::                                            CHANGELOG
 *           15 Aug 2022                       phan.thu@aodigy.com                    US-Ship-000009                                          init
 * ========================================================================================================================================================================== 
 */

public without sharing class VS_UploadShipmentLineItemsController 
{
    @AuraEnabled
    public static Integer readCSVFile(String contentDocumentId, String parentRecordId) 
    {
        ADGLIB_SObjectUnitOfWork uow;
        Map<String, Manufacturer_Invoice__c> existingInvoiceMap   = new Map<String, Manufacturer_Invoice__c>();
        Map<String, List<Shipment_Line_Item__c>> toBeCreatedItems = new Map<String, List<Shipment_Line_Item__c>>();
        Map<String, Manufacturer_Invoice__c> toBeCreatedInvoices  = new Map<String, Manufacturer_Invoice__c>();
        Map<String, HS_Type__c> hsCodeMap                         = new Map<String, HS_Type__c>();
        Map<String, Product_Code__c> productCodeMap               = new Map<String, Product_Code__c>();
        Map<String, String> itemAndHSCodeMap                      = new Map<String, String>();
        Map<String, String> itemAndProductCodeMap                 = new Map<String, String>();
        Set<String> invoiceNoSet                                  = new Set<String>();
        Set<String> hsCodeSet                                     = new Set<String>();
        Set<String> productCodeSet                                = new Set<String>();
        Integer noOfLineItemCreated = 0;

        if (contentDocumentId != null) 
        {
            // Get Content Version based on document id 
            ContentVersion cv = [SELECT Id, VersionData FROM ContentVersion WHERE ContentDocumentId = :contentDocumentId];

            // Delete the uploaded CSV
            uow = new ADGLIB_SObjectUnitOfWork(new Schema.SObjectType[] {ContentDocument.SObjectType});
            uow.registerDeleted(new ContentDocument(Id = contentDocumentId));
            uow.commitWork();
            
            // Split lines in CSV file
            List<String> lstCSVLines = cv.VersionData.toString().split('\n');
            if (lstCSVLines.size() == 1) 
            {
                throw new VS_UploadShipmentLineItemsControllerException().invalidCSV();
            }

            //Get Vehicle Shipment
            Vehicle_Shipment__c shipment = VehicleShipmentServices.getByIdWithInvoicesAndLineItemsAndSVMs(parentRecordId, false, false, false);

            for (Integer i = 1; i < lstCSVLines.size(); i++)
            {
                Shipment_Line_Item__c item            = new Shipment_Line_Item__c();
                Manufacturer_Invoice__c invoice       = new Manufacturer_Invoice__c();
                List<String> csvRowData               = new List<String>();
                String csvLine                        = lstCSVLines[i];
                Boolean isEmptyRow                    = true;
                String invoiceNo;   
                List<Shipment_Line_Item__c> tempItems;
                Integer startIndex;
                Integer endIndex;
                
                try 
                {
                    while (csvLine.indexOf('"') > -1) 
                    {
                        if (startIndex == null)
                        {
                            startIndex = csvLine.indexOf('"');
                            csvLine    = csvLine.substring(0, startIndex) + ':quotes:' + csvLine.substring(startIndex + 1, csvLine.length());
                        } 
                        else 
                        {
                            if (endIndex == null)
                            {
                                endIndex = csvLine.indexOf('"');
                                csvLine  = csvLine.substring(0, endIndex) + ':quotes:' + csvLine.substring(endIndex + 1, csvLine.length());
                            }
                        }
    
                        if (startIndex != null && endIndex != null)
                        {
                            String sub = csvLine.substring(startIndex, endIndex);
                            sub        = sub.replaceAll(',', ':comma:');
                            csvLine    = csvLine.substring(0, startIndex) + sub + csvLine.substring(endIndex, csvLine.length());
                            startIndex = null;
                            endIndex   = null;
                        }
                    }
    
                    for (String column : csvLine.split(','))
                    {
                        column = column.replaceAll(':quotes:', '').replaceAll(':comma:', ',');
                        if (String.isNotBlank(column)) isEmptyRow = false;
                        csvRowData.add(column);
                    }
                }
                catch (Exception e)
                {
                    throw new VS_UploadShipmentLineItemsControllerException().invalidRow(String.valueOf(i), e.getMessage() + ' ' + e.getLineNumber());
                }

                // Skip empty row
                if (isEmptyRow) 
                {
                    continue;
                }

                // Validate if required data are passed in
                validateInsertRow(csvRowData, String.valueOf(i + 1));

                try 
                {
                    invoiceNo = String.isNotBlank(csvRowData[16]) ? csvRowData[16].trim() : '';

                    // Get HS Codes and Product Codes
                    hsCodeSet.add(csvRowData[14]);
                    productCodeSet.add(csvRowData[15]);

                    //initiate new Manufacturer Invoice
                    if (String.isNotBlank(invoiceNo))
                    {
                        invoiceNoSet.add(invoiceNo);
                        invoice = initiateManufacturerInvoice(invoice, csvRowData, shipment.Id);
                        toBeCreatedInvoices.put(invoiceNo, invoice);
                    }
    
                    //initiate new Shipment Line Item
                    item = initiateShipmentItem(item, csvRowData, shipment, String.valueOf(i + 1));
                    noOfLineItemCreated++;

                    // Generate Shipment Line Item & HS Code Map
                    itemAndHSCodeMap.put(item.Chassis_No__c + item.Engine_No__c, csvRowData[14]);

                    // Generate Shipment Line Item & Product Code Map
                    itemAndProductCodeMap.put(item.Chassis_No__c + item.Engine_No__c, csvRowData[15]);
    
                    //Group Shipment Line Items by Invoice No
                    if (toBeCreatedItems.containsKey(invoiceNo))
                    {
                        tempItems = toBeCreatedItems.get(invoiceNo);
                        tempItems.add(item);
                        toBeCreatedItems.put(invoiceNo, tempItems);
                    }
                    else
                    {
                        toBeCreatedItems.put(invoiceNo, new List<Shipment_Line_Item__c> {item});    
                    }                   
                } 
                catch (Exception e) 
                {
                    throw new VS_UploadShipmentLineItemsControllerException().invalidRowProcessing(String.valueOf(i), e.getMessage() + ' ' + e.getLineNumber());
                }
            }

            try 
            {
                uow = new ADGLIB_SObjectUnitOfWork(new Schema.SObjectType[] {Manufacturer_Invoice__c.SObjectType, Shipment_Line_Item__c.SObjectType});

                // Get HS Codes
                if (hsCodeSet.size() > 0)
                {
                    hsCodeSet.remove('');
                    hsCodeSet.remove(null);

                    List<HS_Type__c> hsCodes = [SELECT Id, Name FROM HS_Type__c WHERE Name IN: hsCodeSet];

                    if (hsCodes <> null && !hsCodes.isEmpty())
                    {
                        for (HS_Type__c hsCode : hsCodes)
                        {
                            hsCodeMap.put(hsCode.Name, hsCode);
                        }
                    }
                }

                // Get Product Codes
                if (productCodeSet.size() > 0)
                {
                    productCodeSet.remove('');
                    productCodeSet.remove(null);

                    List<Product_Code__c> productCodes = [SELECT Id, Product_Code__c FROM Product_Code__c WHERE Product_Code__c IN: productCodeSet];

                    if (productCodes <> null && !productCodes.isEmpty())
                    {
                        for (Product_Code__c productCode : productCodes)
                        {
                            productCodeMap.put(productCode.Product_Code__c, productCode);
                        }
                    }
                }

                // Upsert Manufacturer Invoices
                if (toBeCreatedInvoices.size() > 0)
                {
                    List<Manufacturer_Invoice__c> existingInvoices = ManufacturerInvoiceService.getManufacturerInvoicesByInvoiceNos(invoiceNoSet);
                                                                
                    if (existingInvoices <> null && !existingInvoices.isEmpty())
                    {
                        for (Manufacturer_Invoice__c inv : existingInvoices)
                        {
                            existingInvoiceMap.put(inv.Invoice_No__c, inv);
                        }
    
                        for (String invoiceNo : toBeCreatedInvoices.keySet())
                        {
                            if (existingInvoiceMap.containsKey(invoiceNo))
                            {
                                // Update existing ones
                                Manufacturer_Invoice__c updatedInv = updateManufacturerInvoice(toBeCreatedInvoices.get(invoiceNo), existingInvoiceMap.get(invoiceNo));         
                                existingInvoiceMap.put(invoiceNo, updatedInv);            
                                toBeCreatedInvoices.remove(invoiceNo);
                            }
                        }
                        
                        uow.registerDirty(existingInvoiceMap.values());
                    }
                    
                    // Insert new ones
                    if (toBeCreatedInvoices.size() > 0)
                    {
                        uow.registerNew(toBeCreatedInvoices.values());
                    }
                }
    
                // Insert Shipment Line Items
                if (toBeCreatedItems.size() > 0)
                {
                    for (String key : toBeCreatedItems.keySet())
                    {
                        if (String.isBlank(key))
                        {
                            uow.registerNew(toBeCreatedItems.get(key));
                        }
                        else 
                        {
                            for (Shipment_Line_Item__c item : toBeCreatedItems.get(key))
                            {
                                if (existingInvoiceMap.containsKey(key))
                                {
                                    uow.registerNew(item, Shipment_Line_Item__c.Invoice_No__c, existingInvoiceMap.get(key));
                                }
                                else 
                                {
                                    uow.registerNew(item, Shipment_Line_Item__c.Invoice_No__c, toBeCreatedInvoices.get(key));
                                }
                            }
                        }

                        for (Shipment_Line_Item__c item : toBeCreatedItems.get(key))
                        {
                            if(hsCodeMap.containsKey(itemAndHSCodeMap.get(item.Chassis_No__c + item.Engine_No__c)))
                            {
                                uow.registerRelationship(item, 
                                                        Shipment_Line_Item__c.TN_HS_Code__c, 
                                                        hsCodeMap.get(itemAndHSCodeMap.get(item.Chassis_No__c + item.Engine_No__c)));
                            }

                            if (productCodeMap.containsKey(itemAndProductCodeMap.get(item.Chassis_No__c + item.Engine_No__c)))
                            {
                                uow.registerRelationship(item, 
                                                        Shipment_Line_Item__c.Product_Code_Description__c, 
                                                        productCodeMap.get(itemAndProductCodeMap.get(item.Chassis_No__c + item.Engine_No__c)));
                            }
                        }
                    }
                }

                uow.commitWork();
            } 
            catch (Exception e) 
            {
               throw new VS_UploadShipmentLineItemsControllerException().invalidUpsert(e.getMessage());
            }
        }

        return noOfLineItemCreated;
    }

    private static void validateInsertRow(List<String> csvRowData, String rowNo)
    {
        if (String.isBlank(csvRowData[0]))
        {
            throw new VS_UploadShipmentLineItemsControllerException().invalidProductionMonth(rowNo);
        }
        else 
        {
            String originalValue = csvRowData[0].trim();
            String regex         = '[0-9]{4}/[0-9]{0,2}';
            Pattern datePattern  = Pattern.compile(regex);
            Matcher matchDate    = datePattern.matcher(originalValue);
    
            String correctRegex      = '[0-9]{0,2}/[0-9]{4}';
            Pattern correctPattern   = Pattern.compile(correctRegex);
            Matcher matchCorrectDate = correctPattern.matcher(originalValue);

            // Check if Production Month is in yyyy/mm format. If yes, convert to mm/yyyy format.
            if (matchDate.matches())
            {
                csvRowData[0] = originalValue.substringAfter('/') + '/' + originalValue.substringBefore('/');
            }
            else if (matchCorrectDate.matches())
            {
                csvRowData[0] = originalValue;
            }
            else 
            {
                throw new VS_UploadShipmentLineItemsControllerException().invalidProductionMonthFormat(rowNo);
            } 
        }

        if (String.isBlank(csvRowData[1]))
        {
            throw new VS_UploadShipmentLineItemsControllerException().invalidModelCode(rowNo);
        }

        if (String.isBlank(csvRowData[2]))
        {
            throw new VS_UploadShipmentLineItemsControllerException().invalidColorCode(rowNo);
        }

        if (String.isBlank(csvRowData[3]))
        {
            throw new VS_UploadShipmentLineItemsControllerException().invalidTrimCode(rowNo);
        }

        if (String.isBlank(csvRowData[5]))
        {
            throw new VS_UploadShipmentLineItemsControllerException().invalidChasisNo(rowNo);
        }

        if (String.isBlank(csvRowData[6]))
        {
            throw new VS_UploadShipmentLineItemsControllerException().invalidEngineNo(rowNo);
        }

        if (String.isBlank(csvRowData[7]))
        {
            throw new VS_UploadShipmentLineItemsControllerException().invalidFOB(rowNo);
        }

        // If other fields are passed in, Invoice No must be passed in too
        if ((String.isNotBlank(csvRowData[17]) 
            || String.isNotBlank(csvRowData[18]) 
                || String.isNotBlank(csvRowData[19]))
                    && String.isBlank(csvRowData[16]))
        {
            throw new VS_UploadShipmentLineItemsControllerException().invalidInvoiceNo(rowNo);
        }

        // If Invoice No is passed in, other fields must be passed in too
        if (String.isNotBlank(csvRowData[16]))
        {
            if (String.isBlank(csvRowData[17]))
            {
                throw new VS_UploadShipmentLineItemsControllerException().invalidTotalInvoiceAmount(rowNo);
            }
    
            if (String.isBlank(csvRowData[18]))
            {
                throw new VS_UploadShipmentLineItemsControllerException().invalidTotalInvoiceAmtCurrencyCode(rowNo);
            }
    
            if (String.isBlank(csvRowData[19]))
            {
                throw new VS_UploadShipmentLineItemsControllerException().invalidInvoiceDate(rowNo);
            }
            else
            {
                String originalValue = csvRowData[19].trim();
                
                // Correct format: YYYY-MM-DD
                String regex        = '[0-9]{4}-[0-9]{0,2}-[0-9]{0,2}';
                Pattern datePattern = Pattern.compile(regex);
                Matcher matchDate   = datePattern.matcher(originalValue);

                // Check if Invoice Date is in YYYY-MM-DD format.
                if (matchDate.matches())
                {
                    csvRowData[19] = originalValue;
                }
                else 
                {
                    throw new VS_UploadShipmentLineItemsControllerException().invalidInvoiceDateFormat(rowNo);
                } 
            }
        }
    }

    private static Manufacturer_Invoice__c initiateManufacturerInvoice(Manufacturer_Invoice__c invoice, List<String> csvRowData, Id shipmentId)
    {
        invoice.Vehicle_Shipment__c                   = shipmentId;
        invoice.Invoice_No__c                         = csvRowData[16].trim();
        invoice.Total_Invoice_Amount__c               = Decimal.valueOf(csvRowData[17].replaceAll(',', '').trim());
        invoice.Total_Invoice_Amount_Currency_Code__c = csvRowData[18].trim();
        invoice.Invoice_Date__c                       = Date.valueOf(csvRowData[19]);

        return invoice;
    }

    private static Shipment_Line_Item__c initiateShipmentItem(Shipment_Line_Item__c item, List<String> csvRowData, Vehicle_Shipment__c shipment, String rowNo)
    {    
        item.Production_Month__c    = csvRowData[0];                                                            
        item.Model__c               = csvRowData[1].trim();                                                                          
        item.Colour_Code__c         = csvRowData[2].trim();                                                                             
        item.Trim__c                = csvRowData[3].trim();                                                                              
        item.Manufacturer_Ref_No__c = csvRowData[4].trim();                                                                                
        item.Chassis_No__c          = csvRowData[5].trim();             
        item.Engine_No__c           = csvRowData[6].trim();    
        item.Key_No__c              = csvRowData[13].trim();                                                                                
        item.Franchise_Code__c      = shipment.Franchise_Code__c;
        item.Vehicle_Shipment__c    = shipment.Id;   

        if (String.isNotBlank(csvRowData[7]))
        {
            item.FOB_Amount__c               = Decimal.valueOf(csvRowData[7].replaceAll(',','').trim());        
            item.FOB_Amount_Currency_Code__c = shipment.Currency_Code__c;
        }

        if (String.isNotBlank(csvRowData[8]))
        {
            item.Freight_Charges__c               = Decimal.valueOf(csvRowData[8].replaceAll(',','').trim());      
            item.Freight_Charges_Currency_Code__c = shipment.Currency_Code__c;
        }

        if (String.isNotBlank(csvRowData[9]))
        {
            item.Insurance_Charges__c               = Decimal.valueOf(csvRowData[9].replaceAll(',','').trim());     
            item.Insurance_Charges_Currency_Code__c = shipment.Currency_Code__c;   
        }

        if (String.isNotBlank(csvRowData[10]))
        {
            item.Transport_Charges__c               = Decimal.valueOf(csvRowData[10].replaceAll(',','').trim());      
            item.Transport_Charges_Currency_Code__c = shipment.Currency_Code__c;   
        }
      
        if (String.isNotBlank(csvRowData[11]))
        {
            item.Ex_Factory_Charges__c               = Decimal.valueOf(csvRowData[11].replaceAll(',','').trim());      
            item.Ex_Factory_Charges_Currency_Code__c = shipment.Currency_Code__c;   
        }
        
        if (String.isNotBlank(csvRowData[12]))
        {
            item.Other_Charges__c               = Decimal.valueOf(csvRowData[12].replaceAll(',','').trim());              
            item.Other_Charges_Currency_Code__c = shipment.Currency_Code__c;   
        }

        return item;
    }

    private static Manufacturer_Invoice__c updateManufacturerInvoice (Manufacturer_Invoice__c newInvoice, Manufacturer_Invoice__c currentInvoice)
    {
        currentInvoice.Total_Invoice_Amount__c               = newInvoice.Total_Invoice_Amount__c <> 0 ? newInvoice.Total_Invoice_Amount__c : currentInvoice.Total_Invoice_Amount__c;
        currentInvoice.Total_Invoice_Amount_Currency_Code__c = newInvoice.Total_Invoice_Amount_Currency_Code__c;
        currentInvoice.Invoice_Date__c                       = newInvoice.Invoice_Date__c;

        return currentInvoice;
    }

    @TestVisible
    private class VS_UploadShipmentLineItemsControllerException extends Exception
    {
        @TestVisible
        private Exception invalidProductionMonth(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Production Month. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidProductionMonthFormat(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: Production Month must be in YYYY/MM or MM/YYYY format. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidEngineNo(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Engine No. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidChasisNo(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Chasis No. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidColorCode(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Color Code. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidModelCode(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Model Code. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidTrimCode(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Trim Code. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidFOB(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no FOB. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidInvoiceNo(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Invoice No for creating Manufacturer Invoice. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidTotalInvoiceAmount(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Total Invoice Amount for creating Manufacturer Invoice. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidTotalInvoiceAmtCurrencyCode(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Total Invoice Amount Currency Code for creating Manufacturer Invoice. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidInvoiceDate(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: no Invoice Date for creating Manufacturer Invoice. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidInvoiceDateFormat(String rowNo)
        {
            this.setMessage(String.format('Row {0} in the uploaded file is invalid for creating a new Shipment Line Item. Reason: Invoice Date must be in YYYY-MM-DD format. Please check and upload again!', new List<String> { rowNo }));
            return this;
        }

        @TestVisible
        private Exception invalidCSV()
        {
            this.setMessage('This CSV is invalid for creating new Shipment Line Items. Reason: File is empty. Please check and upload again!');
            return this;
        }

        @TestVisible
        private Exception invalidUpsert(String error)
        {
            this.setMessage(String.format('An error has occurred when creating Manufacturer Invoices and Shipment Line Items. Reason: {0}. Please check and upload again!', new List<String> { error }));
            return this;
        }

        @TestVisible
        private Exception invalidRow(String rowNo, String error)
        {
            this.setMessage(String.format('An error has occured while uploading file. Row {0} in the uploaded file is not properly formatted. Reason: {1}, Please check and upload again!', new List<String> { rowNo, error }));
            return this;
        }

        @TestVisible
        private Exception invalidRowProcessing(String rowNo, String error)
        {
            this.setMessage(String.format('An error has occured while processing row {0} in the uploaded file. Reason: {1}, Please check and upload again!', new List<String> { rowNo, error }));
            return this;
        }
    }
}