cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>NRIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Please enter the last 4 digits of the Customer&apos;s NRIC followed by the Date of Birth in the following format DDMMYYY. E.g. 314B10101976</inlineHelpText>
    <label>NRIC _ Passport No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&quot;DWH&quot;</defaultValue>
    <description>Need to be &quot;DWH&quot; for the mobile app to work</description>
    <inlineHelpText>Need to be &quot;DWH&quot; for the mobile app to work</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Lead/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <externalId>true</externalId>
    <label>NRIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Referral</label>
    <nameField>
        <displayFormat>REFER-{0000000}</displayFormat>
        <label>Referral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Referral__c/fields/Brand_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Brand_Picklist__c</fullName>
    <inlineHelpText>This value is coming from APP (API post)</inlineHelpText>
    <label>Brand Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>DS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Referral__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>First Name, Last Name, Mobile number and Email to create Lead</description>
    <label>Referee</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Referral__c/fields/Referee_Account__c.field-meta.xml
<CustomField>
    <fullName>Referee_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referee Account (Prospect)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals (Referee Account)</relationshipLabel>
    <relationshipName>Referrals1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Referral__c/fields/Referrer__c.field-meta.xml
<CustomField>
    <fullName>Referrer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referrer reference</description>
    <label>Referrer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals (Referrer)</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Referral__c/fields/Referrer_Account__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Referrer</description>
    <label>Referrer Account (Customer)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referrals (Account Referrer)</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Expiring</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>SuccessfullyReferred</fullName>
                <label>Successfully Referred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Data_Pool__c/Service_Data_Pool__c.object-meta.xml
<CustomObject>
    <label>Service Data Pool</label>
    <nameField>
        <label>Service Data Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Data Pool</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Account_Activation_Random_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Activation_Random_Number__c</fullName>
    <label>Account Activation Random Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <description>End User derived from this Contact from JCC contact</description>
    <inlineHelpText>End User derived from this Contact from JCC contact</inlineHelpText>
    <label>ContactId (deprecated)</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/isValid__c.field-meta.xml
<CustomField>
    <fullName>isValid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isValid</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>NRIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/REFFGetReferralByCustomerDetailsAPI_Test.cls
@isTest
private class REFFGetReferralByCustomerDetailsAPI_Test {
  
    @TestSetup
    static void createData()
    {
        //Account acc = Test_DataFactory.createAccount(true, 'Test');
        Account acc = Test_DataFactory.createPA(true, 'Test', 'test2362@gmail.com', 'Prospect');
        acc         = [SELECT Id, PersonContactId FROM Account WHERE ID =: acc.Id];
        Contact con = [SELECT Id FROM Contact WHERE Id =: acc.PersonContactId];
        // Contact con = Test_DataFactory.createContact(true, 'contact', 'test', acc.Id);
        // con.NRIC_Passport_No__c = 'S12315031993';  
        // con.mobilePhone = String.valueOf('65814636');
        // con.Source__c = 'DWH';
		// con.AccountId = acc.Id;
        // update con;
        // system.debug('@@@ con: '+con);
  
        Profile endUserProfile = [SELECT Id FROM Profile WHERE Name = 'End User' LIMIT 1];
        User endUser = Test_DataFactory.createUserWithProfileID(false,'re','re','test@force.com',endUserProfile.id);
        //endUser.nric__c = 'zsdfzsdd';   
        endUser.contactId = con.id;    
        //endUser.contactId__c = con.Id;
        endUser.Account_Activation_Random_Number__c = '504503';
        endUser.isValid__c = false;
        TriggerExclusion.excludeTrigger('User', true);
        insert endUser; 
        system.debug('@@@ endUser: '+endUser);
        
        Lead ld = Test_DataFactory.createLead(true, 'Test Company', 'Test_Lead');
        
        Referral__c ref = new Referral__c();
        ref.Referrer__c = con.Id;
        ref.Referee__c = ld.Id;
        ref.Stage__c='Opened'; 
		ref.Brand_Picklist__c = 'MIT';
        insert ref;
    }
    
    @isTest
    private static void testPositive()
    {
        User us = [SELECT Id, Name/*, ContactId__c*/ FROM User WHERE LastName = 're' LIMIT 1];
        String reqURI = '/services/apexrest/GetReferallByCustomerDetails/User/'+us.Id+'/Stage/Opened'; 
        Test_DataFactory.createReqSF( reqURI, 'GET', null, null, 200);
        Test.startTest();
        REFFGetReferralByCustomerDetailsAPI.getReferralByCustomerDetails();
        Test.stopTest();
        
        System.assertEquals(1, [SELECT Count() FROM Service_Data_Pool__c]);
    }
    
    
    /** PA Migration : Newly Added */
    @isTest
    private static void testPAMigrationPositive()
    {
        Account acc = Test_DataFactory.createPerson(false, 'PA', 'Customer');
        acc.PersonEmail = 'test1212@gmail.com';
        insert acc;
        Profile endUserProfile = [SELECT Id FROM Profile WHERE Name = 'End User' LIMIT 1];
        
        Contact pCon = Test_DataFactory.createContact(false, 'contactPA', 'testPA', acc.Id);
        pCon.Account__c = acc.Id;
        pCon.NRIC_Passport_No__c = 'S12315031997';  
        pCon.mobilePhone = String.valueOf('65814636');
        pCon.Source__c = 'DWH';
        insert pCon;
      
        acc = [Select PersonContactId From Account WHERE Name = 'PA' LIMIT 1];
        System.debug(acc.PersonContactId);
        User endUser = Test_DataFactory.createUserWithProfileID(false,'re','re','test@force.com',endUserProfile.id);
        //endUser.nric__c = 'zsdfzsdd';   
        endUser.contactId = acc.PersonContactId;   
        //endUser.contactId__c = acc.PersonContactId;    
        endUser.Account_Activation_Random_Number__c = '504503';
        endUser.isValid__c = false;
        TriggerExclusion.excludeTrigger('User', true);
        insert endUser; 
        Lead ldPA = Test_DataFactory.createLead(true, 'Test Company1', 'Test_Lead1');
        Account referee = Test_DataFactory.createPerson(false, 'referee', 'Customer');
        referee.PersonEmail = 'pa84734@hotmail.com';
        referee.PersonMobilePhone = '12345678';
        insert referee;
      
        Referral__c refPA = new Referral__c();
        refPA.Referee_Account__c = referee.Id;
        refPA.Referrer_Account__c = acc.Id;
        refPA.Stage__c='Opened';
		refPA.Brand_Picklist__c = 'MIT';
        insert refPA;
           
        String reqURI = '/services/apexrest/GetReferallByCustomerDetails/User/'+endUser.Id+'/Stage/Opened'; 
        Test_DataFactory.createReqSF( reqURI, 'GET', null, null, 200);
        Test.startTest();
        REFFGetReferralByCustomerDetailsAPI.getReferralByCustomerDetails();
        Test.stopTest();
        
        System.assertEquals(1, [SELECT Count() FROM Service_Data_Pool__c]);
    }
}