cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/CustomerAlerts__c.object-meta.xml
<CustomObject>
    <label>CustomerAlerts</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerAlerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CustomerAlerts (Account)</relationshipLabel>
    <relationshipName>CustomerAlerts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Alert_Description__c.field-meta.xml
<CustomField>
    <fullName>Alert_Description__c</fullName>
    <label>Alert Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isAlert__c.field-meta.xml
<CustomField>
    <fullName>isAlert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isAlert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isEmail__c.field-meta.xml
<CustomField>
    <fullName>isEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isEmail</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/isPush__c.field-meta.xml
<CustomField>
    <fullName>isPush__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPush</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/isSMS__c.field-meta.xml
<CustomField>
    <fullName>isSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>unread</fullName>
            </value>
            <value>
                <fullName>read</fullName>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
            <value>
                <fullName>eyriuwbicaueiq</fullName>
                <isActive>false</isActive>
                <label>eyriuwbicaueiq</label>
            </value>
            <value>
                <fullName>unred</fullName>
                <isActive>false</isActive>
                <label>unred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>SubType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due 1st Reminder</fullName>
            </value>
            <value>
                <fullName>Due 2nd Reminder</fullName>
            </value>
            <value>
                <fullName>Due 3rd Reminder</fullName>
            </value>
            <value>
                <fullName>Overdue 1st Reminder</fullName>
            </value>
            <value>
                <fullName>Overdue 2nd Reminder</fullName>
            </value>
            <value>
                <fullName>Overdue 3rd Reminder</fullName>
            </value>
            <value>
                <fullName>E-shop</fullName>
            </value>
            <value>
                <fullName>Notice</fullName>
            </value>
            <value>
                <fullName>Evergreen Promotion</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Paid Event</fullName>
            </value>
            <value>
                <fullName>Non-Paid Event</fullName>
            </value>
            <value>
                <fullName>Sales Targeted Promo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First Service</fullName>
            </value>
            <value>
                <fullName>Subsequent Service</fullName>
            </value>
            <value>
                <fullName>Plan/Package</fullName>
            </value>
            <value>
                <fullName>Service Credits</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
            <value>
                <fullName>Battery Change</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
            <value>
                <fullName>Accessories Credits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Vehicle_Credit__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Credit</label>
    <referenceTo>Vehicle_Credit__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Credit__c/Vehicle_Credit__c.object-meta.xml
<CustomObject>
    <description>Used to capture Vehicle Credit data (i.e. Service / Accessories ) from DWH</description>
    <label>Vehicle Credit</label>
    <nameField>
        <displayFormat>VCR-{0000000}</displayFormat>
        <label>Vehicle Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles Credit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Vehicle_Credit__c/fields/Credit_Balance__c.field-meta.xml
<CustomField>
    <fullName>Credit_Balance__c</fullName>
    <label>Credit Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle_Credit__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Credit__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Vehicles Credit</relationshipLabel>
    <relationshipName>Vehicles_Credit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Credit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Vehicle Credit&apos;s Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Credit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Credit__c/recordTypes/Accessories_Credit.recordType-meta.xml
<RecordType>
    <fullName>Accessories_Credit</fullName>
    <active>true</active>
    <description>Accessories Credit</description>
    <label>Accessories Credit</label>
</RecordType>

force-app/main/default/classes/accessoriesCreditExpirationReminder.cls
/** *****
 * Description : Class to create new Customer Alerts for Accessories Credits Expiration
 * 
 * Change History:
 * Date(YYYYMMDD)       Developer               Details
 * 20210512            tphan@aodigy.com      Created initial version
 * 20211001            tphan@aodigy.com      Enhanced to cater more scenarios
 ** *****/

global class accessoriesCreditExpirationReminder implements Schedulable, Database.Batchable<sObject>, Database.Stateful
{
    private static List<CustomerAlerts__c> newAlerts = new List<CustomerAlerts__c>();
    private static Date today = date.today();  /*Date.newInstance(2021, 2, 28);*/
    private static Datetime todaytime  = datetime.now();
    private static Date nextMonth      = today.addMonths(1);
    private static Date nextThreeMonth = today.addMonths(3);
    private static Date nextSixMonth   = today.addMonths(6);

    private static Date lastDateOfNextMonth      = today.day() == 30 && isLastDayOfMonth(today) ? nextMonth.addDays(1) : null;
    private static Date lastDateOfNextThreeMonth = today.day() == 30 && isLastDayOfMonth(today) ? nextThreeMonth.addDays(1) : null;
    private static Date lastDateOfNextSixMonth   = today.day() == 30 && isLastDayOfMonth(today) ? nextSixMonth.addDays(1) : null;

    private static Date nextMonthTo      = today.month() == 2 ? (today.day() == 28 ? nextMonth.addDays(3)      : (today.day() == 29 ? nextMonth.addDays(2)      : null)) : null;
    private static Date nextThreeMonthTo = today.month() == 2 ? (today.day() == 28 ? nextThreeMonth.addDays(3) : (today.day() == 29 ? nextThreeMonth.addDays(2) : null)) : null;
    private static Date nextSixMonthTo   = today.month() == 2 ? (today.day() == 28 ? nextSixMonth.addDays(3)   : (today.day() == 29 ? nextSixMonth.addDays(2)   : null)) : null;

    public Set<Id> setIdsOfVehCredit = new Set<Id>();
    public String  expiryDate        = '';
    public Boolean isFeb             = false;
    
    global accessoriesCreditExpirationReminder(){}
    
    global accessoriesCreditExpirationReminder( Set<Id> setIdsOfVehicleCredit, String checkedDate )
    {
        setIdsOfVehCredit = setIdsOfVehicleCredit;
        expiryDate        = checkedDate;
        System.debug('@@@@DEBUG accessoriesCreditExpirationReminder :: setIdsOfVehCredit ' + setIdsOfVehCredit);
    }

    global void execute (SchedulableContext ctx)
    {
        System.debug('@@@@DEBUG schc.exe :: setIdsOfVehCredit ' + setIdsOfVehCredit);
        
        //invoke schc itself
        // accessoriesCreditExpirationReminder();

        //invoke batch
        Database.executebatch(new accessoriesCreditExpirationReminder( setIdsOfVehCredit, expiryDate ),200);
    }    

    //Batch Start
    public Iterable<sObject> start(Database.Batchablecontext BC)
    {
        ID vrecordTypeID = Schema.SObjectType.Vehicle_Credit__c.getRecordTypeInfosByDeveloperName().get('Accessories_Credit').getRecordTypeId();
        String strSOQL = 'SELECT Id, Expiry_Date__c, Credit_Balance__c, Registered_Vehicle__c, Registered_Vehicle__r.Registration_Number__c, Registered_Vehicle__r.Account__c, Registered_Vehicle__r.Contact__c, Registered_Vehicle__r.Contact__r.Email FROM Vehicle_Credit__c  WHERE Status__c = \'Active\' AND Type__c = \'Accessories\' AND RecordTypeId =: vrecordTypeID AND Credit_Balance__c > 0 AND Expiry_Date__c != null ';
        if( setIdsOfVehCredit <> null && !setIdsOfVehCredit.isEmpty() )
        {
            strSOQL += ' AND ID IN : setIdsOfVehCredit ';
        }
        else if (String.isNotBlank(expiryDate))
        {
            Date expiryDate = Date.valueOf(expiryDate);
            strSOQL += ' AND Expiry_Date__c =: expiryDate ';
        }
        else
        {        
            if (nextMonthTo <> null || nextThreeMonthTo <> null || nextSixMonthTo <> null)
            {
                isFeb = true;
                strSOQL += ' AND ((Expiry_Date__c >= :nextMonth AND Expiry_Date__c <= :nextMonthTo) OR (Expiry_Date__c >= :nextThreeMonth AND Expiry_Date__c <= :nextThreeMonthTo) OR (Expiry_Date__c >= :nextSixMonth AND Expiry_Date__c <= :nextSixMonthTo)) ';
            }
            else if (lastDateOfNextMonth <> null || lastDateOfNextThreeMonth <> null || lastDateOfNextSixMonth <> null)
            {
                strSOQL += ' AND (Expiry_Date__c =: nextMonth OR Expiry_Date__c =: nextThreeMonth OR Expiry_Date__c =: nextSixMonth OR Expiry_Date__c =: lastDateOfNextMonth OR Expiry_Date__c =: lastDateOfNextThreeMonth OR Expiry_Date__c =: lastDateOfNextSixMonth)';   
            }
            else 
            {
                strSOQL += ' AND (Expiry_Date__c =: nextMonth OR Expiry_Date__c =: nextThreeMonth OR Expiry_Date__c =: nextSixMonth)';
            }
        }

        return Database.query( strSOQL );
    }


    //Batch Execute
    public void execute(Database.BatchableContext BC, List<sObject> scope)
    {  
        System.debug('@@@@DEBUG batch.execute :: scope.size - ' + scope.size() );
        try 
        {   
            if (scope.size() > 0 && scope <> null)
            {
                for (Vehicle_Credit__c credit : (List<Vehicle_Credit__c>) scope)
                {
                    if (isFeb)
                    {
                        if (credit.Expiry_Date__c >= nextSixMonth && credit.Expiry_Date__c <= nextSixMonthTo)
                        {                          
                            newAlerts.add(createCustomerAlert('first', credit));
                        }
                        else if (credit.Expiry_Date__c >= nextThreeMonth && credit.Expiry_Date__c <= nextThreeMonthTo)
                        {
                            newAlerts.add(createCustomerAlert('second', credit));
                        }
                        else if (credit.Expiry_Date__c >= nextMonth && credit.Expiry_Date__c <= nextMonthTo) 
                        {
                            newAlerts.add(createCustomerAlert('third', credit));
                        }
                    }
                    else 
                    {
                        if ((credit.Expiry_Date__c == nextSixMonth) || (lastDateOfNextSixMonth <> null && credit.Expiry_Date__c == lastDateOfNextSixMonth))
                        {
                            newAlerts.add(createCustomerAlert('first', credit));
                        }
                        else if ((credit.Expiry_Date__c == nextThreeMonth) || (lastDateOfNextThreeMonth <> null && credit.Expiry_Date__c == lastDateOfNextThreeMonth))
                        {
                            newAlerts.add(createCustomerAlert('second', credit));
                        }
                        else if ((credit.Expiry_Date__c == nextMonth) || (lastDateOfNextMonth <> null && credit.Expiry_Date__c == lastDateOfNextMonth))
                        {
                            newAlerts.add(createCustomerAlert('third', credit));
                        }               
                    }
                }
    
                Database.UpsertResult[] results = Database.upsert(newAlerts);
                for(Integer index = 0, size = results.size(); index < size; index++) 
                {
                    if(results[index].isSuccess())
                    {
                        if(results[index].isCreated()) 
                        {
                            System.debug(newAlerts[index].id +' was created');
                        } 
                    }
                    else 
                    {
                        System.debug(newAlerts[index].id +' had error');
                    }
                }
                System.debug('Customer Alerts Created: ' + newAlerts.size());
            }       
        }
        catch (Exception e)
        {
            System.debug('ERROR: ' + e.getMessage() + ' ' + e.getLineNumber());
            loggerDataPool.buildLogDataPool('accessoriesCreditExpirationReminder', e);
        }       
    }

    //Batch End
    public void finish(Database.BatchableContext info){}

    public static void accessoriesCreditExpirationReminder()
    {   
        Database.executebatch(new accessoriesCreditExpirationReminder( null, null ),200);
    }

    private static CustomerAlerts__c createCustomerAlert (String alertName, Vehicle_Credit__c credit)
    {
        CustomerAlerts__c newAlert = new CustomerAlerts__c();
        String rem =  'Use them at myC&C mobile app eShop now!';

        switch on alertName {
            when 'first' 
            {
                newAlert.Name                 = 'Accessories Credit Expiration 1st Reminder';
                newAlert.Alert_Description__c = 'Your Accessories Credits for ' + credit.Registered_Vehicle__r.Registration_Number__c  + ' are expiring in 6 months. ' + rem;
                newAlert.SubType__c           = 'Due 1st Reminder';

                if ( newAlert.Registered_Vehicle__r.Contact__r.Email == null || newAlert.Registered_Vehicle__r.Contact__r.Email == '' ) 
                {
                    newAlert.isSMS__c = false;   
                }
            }
            when 'second' 
            {
                newAlert.Name                 = 'Accessories Credit Expiration 2nd Reminder';
                newAlert.Alert_Description__c = 'Your Accessories Credits for ' + credit.Registered_Vehicle__r.Registration_Number__c  + ' are expiring in 3 months. ' + rem;
                newAlert.SubType__c           = 'Due 2nd Reminder';

                if ( newAlert.Registered_Vehicle__r.Contact__r.Email == null || newAlert.Registered_Vehicle__r.Contact__r.Email == '' ) 
                {
                    newAlert.isSMS__c = true;   
                }
            }
            when 'third'
            {
                newAlert.Name                 = 'Accessories Credit Expiration 3rd Reminder';
                newAlert.Alert_Description__c = 'Your Accessories Credits for ' + credit.Registered_Vehicle__r.Registration_Number__c  + ' are expiring next month. ' + rem;
                newAlert.SubType__c           = 'Due 3rd Reminder';

                if ( newAlert.Registered_Vehicle__r.Contact__r.Email == null || newAlert.Registered_Vehicle__r.Contact__r.Email == '' ) 
                {
                    newAlert.isSMS__c = true;   
                }
            }
        }
       
        newAlert.Contact__c           = credit.Registered_Vehicle__r.Contact__c; 
        newAlert.Account__c           = credit.Registered_Vehicle__r.Account__c; 
        newAlert.Date__c              = today;
        newAlert.Datetime__c          = todaytime;
        newAlert.Status__c            = 'unread';
        newAlert.isAlert__c           = true;
        newAlert.isPush__c            = true;
        newAlert.isEmail__c           = true;
        newAlert.Type__c              = 'Accessories Credits';     
        newAlert.Registered_Vehicle__c = credit.Registered_Vehicle__c;
        newAlert.Vehicle_Credit__c    = credit.Id;

        return newAlert;
    }

    private static Boolean isLastDayOfMonth (Date checkedDate)
    {
        return checkedDate == checkedDate.addMonths(1).toStartofMonth().addDays(-1);
    }
}