cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LastNRICUpdated__c.field-meta.xml
<CustomField>
    <fullName>LastNRICUpdated__c</fullName>
    <description>Stores recent date/time NRIC is updated</description>
    <label>LastNRICUpdated?</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>NRIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Please enter the last 4 digits of the Customer&apos;s NRIC followed by the Date of Birth in the following format DDMMYYY. E.g. 314B10101976</inlineHelpText>
    <label>NRIC _ Passport No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>NRIC</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Drive</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/recordTypes/KIAPC.recordType-meta.xml
<RecordType>
    <fullName>KIAPC</fullName>
    <active>true</active>
    <businessProcess>OppSales</businessProcess>
    <label>KIAPC</label>
</RecordType>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <formula>CASESAFEID(Contact__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactID</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/IsOwnerChanged__c.field-meta.xml
<CustomField>
    <fullName>IsOwnerChanged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to tell if Owner has Changed (aside from the Contact__c field update)</description>
    <label>Is Owner Changed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Last_Battery_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Battery_Change__c</fullName>
    <label>Last Battery Change</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/OwnerChangeTimeStamp__c.field-meta.xml
<CustomField>
    <fullName>OwnerChangeTimeStamp__c</fullName>
    <description>Date when last owner change was done.</description>
    <label>Owner Change Time Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Packages__c/Service_Packages__c.object-meta.xml
<CustomObject>
    <label>Service Package</label>
    <nameField>
        <label>Service Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Packages</relationshipLabel>
    <relationshipName>Service_Packages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Packages__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status if the Service Package Item is still active.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Test_Drive__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Test Drives (Account)</relationshipLabel>
    <relationshipName>Test_Drives1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <description>This filed is to store the NRIC of the customer for the indemnity from</description>
    <label>NRIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
            <value>
                <fullName>Cancel Queue</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <description>End User derived from this Contact from JCC contact</description>
    <inlineHelpText>End User derived from this Contact from JCC contact</inlineHelpText>
    <label>ContactId (deprecated)</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/NRIC__c.field-meta.xml
<CustomField>
    <fullName>NRIC__c</fullName>
    <label>NRIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/BatchUpdateUserNRICTest.cls
/****************************************************
* Class Name: BatchUpdateUserNRICTest
* Description: Test class for BatchUpdateUserNRIC
*
* Developer Name    Date      Description
* Savita          31-July-2019    Created.
****************************************************/ 
@isTest
private class BatchUpdateUserNRICTest {

    @testSetup
    static void createData(){
        Test.startTest();
        Account at = Test_DataFactory.createAccount(true, UserInfo.getLastName());
        Contact cn = Test_DataFactory.createContact(false, 'FN',  'LN', at.Id);
        cn.LastNRICUpdated__c = Date.today();
        cn.NRIC_Passport_No__c = '123456ABCDEF';	
        insert cn;
        
        List<Registered_Vehicle__c> rvList = new List<Registered_Vehicle__c>();
        Date dt = System.today();
        Date twentytwoMonthsAgo = dt.addMonths(-22);
        Date twentythreeMonthsAgo = dt.addMonths(-23);
        
        for(Integer i=0; i<3; i++){
            Registered_Vehicle__c rv = Test_DataFactory.createregVehicle(false, 'SEBE'+i, 'CCK', 'KIAPC', 'SEBE'+i, cn.Id);
            rv.Last_Battery_Change__c = Math.mod(i, 2) == 0 ? twentytwoMonthsAgo : twentythreeMonthsAgo;
            rv.IsOwnerChanged__c = true;
            rv.OwnerChangeTimeStamp__c = Date.today();
            rvList.add(rv);
        }
        insert rvList;
        
        
        Service_Packages__c srev = new Service_Packages__c();
        srev.Registered_Vehicle__c = rvList.get(0).Id;
        srev.Status__c = 'Active';
        insert srev;
        
        
        Account pAcc = Test_DataFactory.createPerson(true, 'PA', 'Prospect');	 /** PA Migration : Newly Added */
        pAcc = [Select Id, PersonContactId, RecordType.Name From Account Where Id = :pAcc.Id];
        System.debug('testing---'+pAcc);

        Account jccAcc = Test_DataFactory.createAccount(true, 'JCCTestAccount999');
        Contact paCon = Test_DataFactory.createContact(false, 'FNPA',  'LNPA', jccAcc.Id);
        paCon.Account__c = pAcc.Id;	
        //paCon.NRIC_Passport_No__c = '12345ASDF';
        paCon.LastNRICUpdated__c = Date.today();
        insert paCon;

        Account acc = [Select PersonContactId From Account Where Id = :pAcc.Id];
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'End User' LIMIT 1];
        User u = new User(
            FirstName = 'TestFirstName',
            LastName = 'TestLastName',
            Email = 'test@user.com',
            Username = 'test@user.com',
            Alias = 'TestPA', 
            TimeZoneSidKey = 'GMT', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            ProfileId = p.Id, 
            LanguageLocaleKey = 'en_US',
            ContactId = acc.PersonContactId
            /*ContactId__c = cn.Id*/);
        insert u;
        Test.stopTest();
        
    }
    
    //Batch Test
    static testMethod void testBatch(){
        Test.startTest();
        TriggerExclusion.excludeTrigger('User', true);
        System.schedule('Schedule BatchNRIC', '0 0 0 ? * * *', new BatchUpdateUserNRIC() );
        Test.stopTest();
        //System.assertEquals(1 , [SELECT COUNT() FROM User WHERE NRIC__c = '123456ABCDEF']);

    }
    
    //Batch Test
    static testMethod void testBatteryBatch(){
        Set<String> setRegIds = new Set<String>();
        for(Registered_Vehicle__c rv : [Select Id From Registered_Vehicle__c]){
            setRegIds.add(rv.Id);
        }
        Test.startTest();
        System.schedule('Schedule BatchBattery', '0 0 0 ? * * *', new BatteryChange() );
        BatteryChange.customerAlertTest(setRegIds);
        Test.stopTest();
    }
    
    //Batch Test
    static testMethod void testAlerts(){
        Test.startTest();
        System.schedule('Schedule AlertsScheduler', '0 0 0 ? * * *', new AlertsScheduler() );
        AlertsScheduler.manualRunAlerts();
        Test.stopTest();
    }
    
    //Batch Test
    static testMethod void testInsertShare(){
        Test.startTest();
        Database.executeBatch( new InsertContactShareRecord() );
        Test.stopTest();
    }
    
    //Batch Test
    static testMethod void testDeactivateBatch(){
        Test.startTest();
        Database.executeBatch( new BatchDeactivateServicePackage() );
        Test.stopTest();
    }  
    
    //Batch Test
    static testMethod void testBatchSend(){
        Test.startTest();
        Account acc = [SELECT ID FROM Account ORDER BY CreatedDate DESC LIMIT 1];
        Contact cn = [SELECT Id FROM Contact WHERE FirstName = 'FN' AND LastName='LN'];
        Opportunity opp = Test_DataFactory.createOpportunity(true, UserInfo.getLastName(), acc.Id);
        
        Test_Drive__c td = Test_DataFactory.createTestDrive(false, opp.Id);
        td.Prospect__c = cn.Id;
        td.Status__c = 'Pending';
        td.Date__c =  date.today().addDays(-1);
        insert td;
        
        System.schedule('Schedule SendNoShow', '0 0 0 ? * * *', new SendTestDriveNoShowEmail() );
        Test.stopTest();
    }  
}