cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/global_var__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>JCC Global Variables</label>
</CustomObject>

cncProd/force-app/main/default/objects/global_var__c/fields/Cancel_Service_MC_TriggerId__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Service_MC_TriggerId__c</fullName>
    <label>Cancel Service MC TriggerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/global_var__c/fields/Create_Service_MC_TriggerId__c.field-meta.xml
<CustomField>
    <fullName>Create_Service_MC_TriggerId__c</fullName>
    <label>Create Service MC TriggerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/fields/Edit_Service_MC_TriggerId__c.field-meta.xml
<CustomField>
    <fullName>Edit_Service_MC_TriggerId__c</fullName>
    <label>Edit Service MC TriggerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/Service_Appointment__c.object-meta.xml
<CustomObject>
    <label>Service Appointment</label>
    <nameField>
        <label>Service Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments (Account)</relationshipLabel>
    <relationshipName>Service_Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Alternate_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email_Address__c</fullName>
    <label>Alternate Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Booking_ID__c.field-meta.xml
<CustomField>
    <fullName>Booking_ID__c</fullName>
    <externalId>true</externalId>
    <label>Booking ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Car_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>Car_Registration_No__c</fullName>
    <label>Car Registration No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Customer_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Customer_Remarks__c</fullName>
    <defaultValue>&apos;-&apos;</defaultValue>
    <label>Customer Remarks</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <defaultValue>&apos;-&apos;</defaultValue>
    <label>Mileage</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Service_Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Date_Time__c</fullName>
    <label>Service Appointment Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

cncProd/force-app/main/default/objects/Service_Appointment__c/fields/Service_Centre_Location__c.field-meta.xml
<CustomField>
    <fullName>Service_Centre_Location__c</fullName>
    <label>Service Centre Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <label>Service Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/fields/System_don_t_fire_MC__c.field-meta.xml
<CustomField>
    <fullName>System_don_t_fire_MC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>System don&apos;t fire MC</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Variant__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/updateAlternateEmailAddress.cls
//Apex class to Update Alternate Email Address
@RestResource(urlMapping='/updatealternateemailaddress/v1/*')

global with sharing  class updateAlternateEmailAddress 
{
    @HttpPost
    //CallOut method for Expose API
    global static Map<String, String> updateAlerts(String bookingID, String emailAddress) 
    {   
        String errorMsg='';
        List<SObject>  returnObject = new List<SObject>();
        RestResponse res = RestContext.response;
        Map<String, String> responseMap = new Map<String, String>();
        Service_Appointment__c [] serviceAppointmentList ; 
        Service_Appointment__c  serviceAppointmentObj ;
        RestContext.response = res;
        String RegistrationNumber ;
        DateTime DateValue ;
        String booking_ID ; 
        String registered_Vehicle ;
        String customerRemarks ; 
        global_var__c JCC_GlobalVar = global_var__c.getOrgDefaults();      
        String triggeredCreateSendMessageId = (String)JCC_GlobalVar.Create_Service_MC_TriggerId__c;
        String triggeredEditSendMessageId = (String)JCC_GlobalVar.Edit_Service_MC_TriggerId__c;
        String triggeredCancelSendMessageId = (String)JCC_GlobalVar.Cancel_Service_MC_TriggerId__c;
        String subcriberKey ; 
        String serviceType ;
        String formatedDate ;
        String mileage ;
        String branch ;
        String variantName ;
        String variantID ;
        String alternateEmailAddr ;
        String Location ; 
        DateTime convertedDate; 
        String dateVal ;
        String hourMinutes ;
        
        if(bookingID !='' && emailAddress != '')
        {
            try 
            { 
                Long TimeStartObj = system.currentTimeMillis();
                
                serviceAppointmentList = [SELECT Id, Flag__c, Contact__c, Action__c, Service_Code__c, Mileage__c, Account__c,
											Service_Centre_Location__c, Service_Appointment_Date_Time__c, Car_Registration_No__c,
											Registered_Vehicle__c, Registered_Vehicle__r.Branch__c, Customer_Remarks__c,
											Registered_Vehicle__r.Variant__r.Name 
                                            FROM Service_Appointment__c 
                                            WHERE Booking_ID__c = : bookingID];  
											 
                if (serviceAppointmentList != null  && serviceAppointmentList.size()>0)
                {
                    if(serviceAppointmentList[0].Service_Code__c != null) {
                        serviceType = serviceAppointmentList[0].Service_Code__c;
                    }

                    if(serviceAppointmentList[0].Service_Centre_Location__c != null) {
                        Location = serviceAppointmentList[0].Service_Centre_Location__c ;
                    }
                    
                    if(serviceAppointmentList[0].Service_Appointment_Date_Time__c != null) {
                        DateValue = serviceAppointmentList[0].Service_Appointment_Date_Time__c;
                        //convertedDate =  getUTCDateTime(DateValue);
                        dateVal = DateValue.format('dd MMMMM yyyy,EEEEE');//convertedDate.format('dd MMMMM yyyy,EEEEE');
                        hourMinutes = DateValue.format('hh:mm a');  
                    }  

                    if(serviceAppointmentList[0].Car_Registration_No__c != null) {
                        RegistrationNumber = serviceAppointmentList[0].Car_Registration_No__c ;   
                    }

                    if(serviceAppointmentList[0].Registered_Vehicle__c != null) {
                        registered_Vehicle = serviceAppointmentList[0].Registered_Vehicle__c ;   
                    }
                    
                    if(serviceAppointmentList[0].Customer_Remarks__c != null) {
                        customerRemarks = serviceAppointmentList[0].Customer_Remarks__c ;   
                    }

                    if(serviceAppointmentList[0].Mileage__c != null) {
                        mileage = serviceAppointmentList[0].Mileage__c;   
                    }
                    
                    if( serviceAppointmentList[0].Registered_Vehicle__r.Variant__r.Name != null) {
                        variantName =  serviceAppointmentList[0].Registered_Vehicle__r.Variant__r.Name;
                        variantName =  variantName.replace('\"',' \\"');
                    }   
                    
                    if( serviceAppointmentList[0].Registered_Vehicle__r.Branch__c != null) {
                        branch =  serviceAppointmentList[0].Registered_Vehicle__r.Branch__c;
                    }   
                    
                    subcriberKey = serviceAppointmentList[0].Contact__c;

					//PA MIGRATION
					if(serviceAppointmentList[0].Account__c != null) {
						subcriberKey = serviceAppointmentList[0].Account__c;
					}
					//PA MIGRATION

                    booking_ID = bookingID;

                    try
                    { 
                        serviceAppointmentObj =  serviceAppointmentList[0]; 
                        serviceAppointmentObj.Alternate_Email_Address__c = emailAddress ;
                        serviceAppointmentObj.Flag__c =  True ;
						serviceAppointmentObj.System_don_t_fire_MC__c = true;
                        
                        update serviceAppointmentObj;
                        system.debug(LoggingLevel.INFO,'Time in MS for Select & Update serviceAppointmentObj: '+String.ValueOf(system.currentTimeMillis()-TimeStartObj));
                        
                        if(serviceAppointmentList[0].Action__c == 'Create')
                        {  
                            TimeStartObj = system.currentTimeMillis();
                            //send_TriggeredEmail.sendEmail( variantName, branch, mileage, serviceType, RegistrationNumber, 
                            //                                    customerRemarks, registered_Vehicle, dateVal, hourMinutes, Location, 
                            //                                        booking_ID, emailAddress, subcriberKey, triggeredCreateSendMessageId );                    
                            system.debug(LoggingLevel.INFO,'Time in MS for Create TriggeredEmail: '+String.ValueOf(system.currentTimeMillis()-TimeStartObj));
                        }   
                        
                        if(serviceAppointmentList[0].Action__c == 'Edit')
                        {     
                            TimeStartObj = system.currentTimeMillis();
                            //send_TriggeredEmail.sendEmail( variantName, branch, mileage, serviceType, RegistrationNumber, 
                            //                                    customerRemarks, registered_Vehicle, dateVal, hourMinutes, Location, 
                            //                                        booking_ID, emailAddress, subcriberKey, triggeredEditSendMessageId );      
                            system.debug(LoggingLevel.INFO,'Time in MS for Edit TriggeredEmail: '+String.ValueOf(system.currentTimeMillis()-TimeStartObj));
                        }   
                        
                        if(serviceAppointmentList[0].Action__c == 'Cancel')
                        {   
                            TimeStartObj = system.currentTimeMillis();
                            //send_TriggeredEmail.sendEmail( variantName, branch, mileage, serviceType, RegistrationNumber, 
                            //                                    customerRemarks, registered_Vehicle, dateVal, hourMinutes, Location, 
                            //                                        booking_ID, emailAddress, subcriberKey, triggeredCancelSendMessageId );      
                            system.debug(LoggingLevel.INFO,'Time in MS for Cancel TriggeredEmail: '+String.ValueOf(system.currentTimeMillis()-TimeStartObj));
                        }     
                                                
                        res.statusCode = 200;
                        responseMap.put('Status', 'Success');
                    }
                    catch (DmlException e)
                    {
                        errorMsg = 'A system exception has occurred, Please contact your administrator.';
                        res.statusCode = 400;
                        responseMap.put('ErrorCode', 'Err04-SF');
                        responseMap.put('Message', errorMsg); 
                        responseMap.put('Status', errorMsg);
                    }  
                }
                else
                {
                    errorMsg ='No record found against booking id';
                    res.statusCode = 400;
                    responseMap.put('ErrorCode', 'Err03-SF');
                    responseMap.put('Message', errorMsg); 
                    responseMap.put('Status', errorMsg);   
                }
            }
            catch(DmlException e)
            {
                errorMsg ='A system exception has occurred, Please contact your administrator.';
                responseMap.put('ErrorCode', 'Err04-SF');
                responseMap.put('Message', errorMsg);  
                responseMap.put('Status', errorMsg);
                res.statusCode = 400;   
            }
        }
        else if(bookingID =='' && emailAddress == '')
        {
            errorMsg = 'bookingID  and emailAddress is blank';
            responseMap.put('Status',errorMsg);
            res.statusCode=400;
            responseMap.put('ErrorCode', 'Err02-SF');
            responseMap.put('Message', errorMsg);  
            
        }
        else if (bookingID !='' && emailAddress == '')
        {
            errorMsg = 'emailAddress is blank';
            responseMap.put('Status',errorMsg );
            res.statusCode=400;
            responseMap.put('ErrorCode', 'Err02-SF');
            responseMap.put('Message', errorMsg);  
            responseMap.put('Status', errorMsg);
        }
        else
        {
            errorMsg =  'bookingID is blank';
            responseMap.put('Status',errorMsg );
            res.statusCode=400;
            responseMap.put('ErrorCode', 'Err02-SF');
            responseMap.put('Message', errorMsg); 
        }   
        
        res.responseBody = Blob.valueOf(JSON.serialize(responseMap));           
        return responseMap;
    }
    //returns utc time 
	/*
    public static DateTime getUTCDateTime(DateTime dt)
	{
        Datetime GMTDate = Datetime.newInstanceGmt(
            dt.year(),
            dt.month(),
            dt.day(),
            dt.hour(),
            dt.minute(),
            dt.second());
        return GMTDate;
    }
	*/
     
   
}