cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>IF(ISPICKVAL(Branch__c, &apos;CCI&apos;) , &apos;MB&apos;,
    IF(ISPICKVAL(Branch__c, &apos;CCK&apos;), &apos;KIA&apos;,
        IF(ISPICKVAL(Branch__c, &apos;CCA&apos;), &apos;MIT&apos;,
            IF(ISPICKVAL(Branch__c, &apos;CCF&apos;), IF(AND(NOT(ISBLANK(Variant__r.Model_ID__r.Model_Display_Name__c)),BEGINS(Variant__r.Model_ID__r.Model_Display_Name__c,&apos;DS&apos;)), &apos;DS&apos;,&apos;CIT&apos;),&apos;&apos;))))</formula>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>Customer&apos;s Reward Credit 
- per Reward Type
- per Registered Vehicle
- per Expiry Date</description>
    <label>Reward</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Reward__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Reward_Profile__c.field-meta.xml
<CustomField>
    <fullName>Reward_Profile__c</fullName>
    <label>Reward Profile</label>
    <referenceTo>Reward_Profile__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/Reward_Profile__c.object-meta.xml
<CustomObject>
    <label>Reward Profile</label>
    <nameField>
        <label>Reward Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Business Account or Person Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reward Profiles</relationshipLabel>
    <relationshipName>Reward_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only set this value for Individual-typed profile</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reward Profiles</relationshipLabel>
    <relationshipName>Reward_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Profile__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only set this value for Fleet-typed profile</description>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Reward Profiles</relationshipLabel>
    <relationshipName>Reward_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/fields/Total_Remainder__c.field-meta.xml
<CustomField>
    <fullName>Total_Remainder__c</fullName>
    <inlineHelpText>Total Credit Leftover</inlineHelpText>
    <label>Total Remainder</label>
    <summarizedField>Reward__c.Remainder__c</summarizedField>
    <summaryForeignKey>Reward__c.Reward_Profile__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Boutique</fullName>
            </value>
            <value>
                <fullName>Birthday Voucher</fullName>
            </value>
            <value>
                <fullName>Grooming Package</fullName>
            </value>
            <value>
                <fullName>Service Credit Voucher</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>Discount Voucher</fullName>
            </value>
            <value>
                <fullName>Service Credit</fullName>
            </value>
            <value>
                <fullName>Accessories Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <description>Business Account (Fleet)</description>
    <label>C&amp;C Individual</label>
</RecordType>

cncProd/force-app/main/default/objects/Reward_Usage__c/Reward_Usage__c.object-meta.xml
<CustomObject>
    <label>Reward Usage</label>
    <nameField>
        <label>Reward Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(Reward__r.Brand__c)</formula>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Usage__c/fields/Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Amount__c</fullName>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward_Usage__c.field-meta.xml
<CustomField>
    <fullName>Reward_Usage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Reference to Debit Reward Usage record</description>
    <label>Reward Usage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Reward_Usage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Debit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Reward_Usage__c</referenceTo>
    <relationshipLabel>Credit Usages</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Expiry</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Credit to Customer (i.e. Refund/Adjustment/etc.)</description>
    <label>Credit</label>
</RecordType>

force-app/main/default/objects/Reward_Usage__c/recordTypes/Debit.recordType-meta.xml
<RecordType>
    <fullName>Debit</fullName>
    <active>true</active>
    <description>Debit from Customer (i.e. Credit Deduction)</description>
    <label>Debit</label>
</RecordType>

force-app/main/default/classes/CMAttachmentServiceTest.cls
/** ******
 * Description : Test class for CMAttachmentService.cls
 * 
 * Change History:
 * Date(YYYYMMDD)       Name            Description
 * 20200903             TP@aodigy       Created Initial Version. 
 * 
** ******/
@isTest
private class CMAttachmentServiceTest 
{
	@testSetup
    static void setUp()
    {
        Account paObj = Test_DataFactory.createPerson(false, 'Test-Acct', 'Customer');
        paObj.DWH_Contact_ID__pc = 'Test-Contact-DWHID1';
        insert paObj;
        paObj = [SELECT Id, PersonContactId FROM Account WHERE Id =: paObj.Id];

        Registered_Vehicle__c rvObj = Test_DataFactory.createRegVehicle(false, 'Test-RV123', 'CCK', 'KIAPC', 'Test-RV123', paObj.PersonContactId);
        rvObj.Account__c = paObj.Id;
        insert rvObj;

        Reward_Profile__c rewardProfile = Test_DataFactory.createRewardProfile(false, 'Individual', 'CCK', 'KIA', 'Accessories Credit');
        rewardProfile.Contact__c = paObj.PersonContactId;
        insert rewardProfile;

        Reward__c reward = Test_DataFactory.createReward(false, rewardProfile.Id, rewardProfile.Type__c, 'Valid', Date.today().addDays(5));
        reward.Credit__c = 1000;
        reward.Branch__c = 'CCK';
        reward.Brand__c  = 'KIA';
        reward.Registered_Vehicle__c = rvObj.Id;
        reward.Contact__c = paObj.PersonContactId;
        insert reward;
        
        Reward_Usage__c rewardUsage = Test_DataFactory.createRewardUsage(false, reward.Id, 'Hold', 'Debit');
        rewardUsage.Credit_Amount__c = 100;
        insert rewardUsage;   
    }
    
    @isTest
    static void test_generateDebitUsageAttachment()
    {
        Reward_Profile__c rewardProfile = [SELECT id, Total_Remainder__c FROM Reward_Profile__c];
        CMAttachmentService.generateDebitUsageAttachment(rewardProfile.Id, 1000, Date.today(), 'INV123456', 200, 100, 100, rewardProfile.Total_Remainder__c);
    }
    
    @isTest
    static void test_generateCreditUsageAttachment()
    {
        Reward_Profile__c rewardProfile = [SELECT id, Total_Remainder__c FROM Reward_Profile__c];
        CMAttachmentService.generateCreditUsageAttachment(rewardProfile.Id, Date.today(), 'INV123456', 'CN098765', 50, 'TEST', 950, 50);
    }
    
    @isTest
    static void test_createAttachment()
    {
        Reward_Profile__c rewardProfile = [SELECT id, Total_Remainder__c FROM Reward_Profile__c];
        CMAttachmentService.createAttachment(rewardProfile.Id, Date.today(), 'INV09876', Blob.valueOf('TEST'));
    }
    
    @isTest
    static void test_getAttachmentById()
    {
        Reward_Profile__c rewardProfile = [SELECT id, Total_Remainder__c FROM Reward_Profile__c];
        CMAttachmentService.createAttachment(rewardProfile.Id, Date.today(), 'INV09876', Blob.valueOf('TEST'));
        String attachmentName = String.valueOf(Date.today()).remove('-') + '_' +  'INV09876' + '.pdf';
        Attachment att =  [SELECT Id FROM Attachment WHERE ParentId =: rewardProfile.Id AND Name =: attachmentName];
    
        System.assertEquals(CMAttachmentService.getAttachmentById(rewardProfile.Id, 'INV09876', Date.today()).Id, att.Id);
    }
}