cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/User/fields/ExcludeFromWarehouse__c.field-meta.xml
<CustomField>
    <fullName>ExcludeFromWarehouse__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked to exclude consultant from warehouse list</description>
    <inlineHelpText>Checked to exclude consultant from warehouse list</inlineHelpText>
    <label>ExcludeFromWarehouse?</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/classes/restSalesConsultant.cls
/** ******
 * Description : API Class to get a list of consultants
 * 
 * Change History : 
 * Date(YYYYMMDD)       Name                            Description
 * 20181218             Hari Panneerselvam              Created Initial Version
 * 20200322             SJ                              Added PA Migration Changes
 * 
** ******/
@RestResource (urlMapping = '/SalesConsultant/*')
global class restSalesConsultant 
{
    
    private static RestResponse res = RestContext.response;
    private static RestRequest req = RestContext.request;
    private static Map<String, Object> mapParams = new Map<String, Object>();
    private static generatePreparedSCResponse genSCResponse;
    private static Utility.httpSuccessResponse successResponse;
    private static Utility.httpErrorResponse errorResponse;
    
    @HttpGet
    global static void salesConsultantInfo()
	{
        res.addHeader('Content-Type', 'application/json');

        try
		{
            processGetRequest();
        }
		catch(Exception ex)
		{
            loggerDataPool.buildLogDataPool('restSalesConsultant', ex);
            errorResponse = new Utility.httpErrorResponse('Failed', ex.getMessage());
        }

        if(successResponse != null)
		{
            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.Serialize(successResponse));
        }
        if(errorResponse != null)
		{
            res.statusCode = 400;
            res.responseBody = Blob.valueOf(JSON.Serialize(errorResponse));
        }
        serviceDataPool.buildServiceDataPool('salesConsultantInfo', 'restSalesConsultant', '', req, res);
    }
    
    public static void processGetRequest()
	{
        Map<Id, User> mapSCUser = new Map<Id, User>();
        List<User> lstSCUsers = new List<User>();
        List<Opportunity> lstOpportunity = new List<Opportunity>();
        String preferredConsultant = '';
        String preferredConsultantId = '';
        mapParams = req.params;
        
        mapSCUser = new Map<Id, User>([SELECT Id, Name, Branch_Code__c 
									   FROM User 
									   WHERE ExcludeFromWarehouse__c = false 
                                       AND IsActive = true 
                                       AND Branch_Code__c = :(String)mapParams.get('branch') 
									   AND UserRole.Name like '%Sales Consultant%']);
        lstSCUsers = mapSCUser.values();

        /*
        lstOpportunity = [SELECT Id, OwnerId 
                          FROM Opportunity 
                          WHERE ( (Contact_Person__r.Email = :(String)mapParams.get('email')) 
                                    OR (Lead__r.Email = :(String)mapParams.get('email'))
                                    OR (Account__r.PersonEmail =: (String)mapParams.get('email') ) ) //PA MIGRATION
						  AND Owner.UserRole.Name like '%Sales Consultant%' 
						  AND Owner.ExcludeFromWarehouse__c = false 
                          AND Owner.IsActive = true 
                          AND Branch_Code__c = :(String)mapParams.get('branch') 
                          ORDER BY CreatedDate DESC LIMIT 1];
        */
        lstOpportunity = [SELECT Id, OwnerId 
                          FROM Opportunity 
                          WHERE ( Contact_Person__r.Email = :(String)mapParams.get('email') )
						  AND Owner.UserRole.Name like '%Sales Consultant%' 
						  AND Owner.ExcludeFromWarehouse__c = false 
                          AND Owner.IsActive = true 
                          AND Branch_Code__c = :(String)mapParams.get('branch') 
					      ORDER BY CreatedDate DESC LIMIT 1];

        if(lstOpportunity != null && lstOpportunity.size() > 0)
		{
            System.debug('@@@@DEBUG processGetRequest :: lstOpportunity[0].OwnerId = ' + lstOpportunity[0].OwnerId);
            if(mapSCUser.get(lstOpportunity[0].OwnerId) != null)
			{
                preferredConsultant = mapSCUser.get(lstOpportunity[0].OwnerId).Name;
                preferredConsultantId = mapSCUser.get(lstOpportunity[0].OwnerId).Id;
            }
        }

        if(lstSCUsers != null && lstSCUsers.size() > 0)
		{
            genSCResponse = new generatePreparedSCResponse(preferredConsultant, preferredConsultantId, lstSCUsers);
            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.Serialize(genSCResponse));
        }
		else
		{
            errorResponse = new Utility.httpErrorResponse('Failed', 'No List Found.');
            res.statusCode = 400;
            res.responseBody = Blob.valueOf(JSON.Serialize(errorResponse));
        }
    }
    
    public class generatePreparedSCResponse
	{
        String PreferredSC;
        String PreferredSCId;
        List<User> UserList;
        public generatePreparedSCResponse (String preferSC, String preferScId, List<User> lstUser)
		{
            PreferredSC   = preferSC;
            PreferredSCId = preferScId;
            UserList      = lstUser;
        }
    }
    
    public static Boolean isValidateParamPassed()
	{
        String errorMessage = '';
        if(mapParams != null && mapParams.size() > 0)
		{
            if(mapParams.get('branch') == null || mapParams.get('branch') == '')
			{
                errorMessage = 'branch';
            }
            if(mapParams.get('email') == null || mapParams.get('email') == '')
			{
                errorMessage = 'email';
            }
        }
		else
		{
            errorMessage = 'mobile, email';
        }

        if(errorMessage == '')
		{
            return true;
        }
		else
		{
            errorResponse = new Utility.httpErrorResponse('Failed', 'Missing parameter: ' +errorMessage);
        }
        return false;
    }
    
}