cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Opportunity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Drive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Master</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/recordTypes/KIAPC.recordType-meta.xml
<RecordType>
    <fullName>KIAPC</fullName>
    <active>true</active>
    <businessProcess>OppSales</businessProcess>
    <label>KIAPC</label>
</RecordType>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Test_Drive__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Test Drives (Account)</relationshipLabel>
    <relationshipName>Test_Drives1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
            <value>
                <fullName>Cancel Queue</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>Vehicle Master</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Vehicle Masters</relationshipLabel>
    <relationshipName>Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Sent Back to PG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Vehicle Masters</relationshipLabel>
    <relationshipName>Vehicle_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchSendTestDriveNoShowEmailTest.cls
/****************************************************
* Class Name: BatchSendTestDriveNoShowEmailTest
* Description: Test class for BatchSendTestDriveNoShowEmail
****************************************************/ 
@isTest
private class BatchSendTestDriveNoShowEmailTest {
    @testSetup
    static void createData(){
       
    }
    
    @isTest
    static void testSendTestDriveNoShowEmailWithCustomerAccount(){        
        // Account customerAcc = Test_DataFactory.createPerson(true, 'Test', 'Customer');
        Account customerAcc = Test_DataFactory.createAccount(true, 'TestingAccount123');
        Contact testCon = Test_DataFactory.createContact(true, 'fname', 'lname', customerAcc.Id); //PA MIGRATION: To Remove
                
        Opportunity opp = Test_DataFactory.createOpportunity(true, 'oppName', customerAcc.Id);
        Model__c model = Test_DataFactory.createmodelId(true, 'modelName', 'CCK', 'KIAPC');
        Variant__c variant = Test_DataFactory.createVariant(true, 'variantName', model.Id, 'CCK');
        Vehicle_Master__c vehicleMaster = Test_DataFactory.createVehicleMaster(true, 'name', variant.Id, model.Id);
        
        Test_Drive__c testDrive = Test_DataFactory.createTestDrive(false, opp.Id);
		testDrive.Account__c = customerAcc.Id; 
        testDrive.Prospect__c = testCon.Id; //PA MIGRATION: To Remove
        testDrive.Date__c = Date.today().addDays(-1);
        testDrive.Status__c = 'Pending';
		testDrive.Model__c = vehicleMaster.Id;
        insert testDrive;
        
        Test.startTest();
        System.schedule('Rebook_Test_Drive02', '20 30 8 10 2 ? *', new BatchSendTestDriveNoShowEmail());
        Test.stopTest();
    }
    
    @isTest
    static void testSendTestDriveNoShowEmailWithProspectAccount(){        
        Account prospectAcc = Test_DataFactory.createPerson(true, 'Test', 'Prospect');
        //Lead testLead = Test_DataFactory.createLead(true, 'C&C', 'lName'); //PA MIGRATION: To Remove
        
        Opportunity opp = Test_DataFactory.createOpportunity(true, 'oppName', prospectAcc.Id);
        Model__c model = Test_DataFactory.createmodelId(true, 'modelName', 'CCK', 'KIAPC');
        Variant__c variant = Test_DataFactory.createVariant(true, 'variantName', model.Id, 'CCK');
        Vehicle_Master__c vehicleMaster = Test_DataFactory.createVehicleMaster(true, 'name', variant.Id, model.Id);
        
        Test_Drive__c testDrive = Test_DataFactory.createTestDrive(false, opp.Id);
		testDrive.Account__c = prospectAcc.Id;
        //testDrive.Lead__c = testLead.Id; //PA MIGRATION: To Remove        
        testDrive.Date__c = Date.today().addDays(-1);
        testDrive.Status__c = 'Pending';
		testDrive.Model__c = vehicleMaster.Id;
        insert testDrive;
        
        Test.startTest();
        System.schedule('Rebook_Test_Drive02', '20 30 8 10 2 ? *', new BatchSendTestDriveNoShowEmail());
        Test.stopTest();
    }
}