cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>DeviceToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/CustomerAlerts__c.object-meta.xml
<CustomObject>
    <label>CustomerAlerts</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerAlerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CustomerAlerts (Account)</relationshipLabel>
    <relationshipName>CustomerAlerts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Non_C_C_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Non_C_C_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Non C&amp;C Vehicle</label>
    <referenceTo>Non_C_C_Vehicle__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Used_Car_Vehicle_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Car_Vehicle_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Used Car Vehicle Stock</label>
    <referenceTo>Used_Car_Vehicle_Stock__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/recordTypes/Alert.recordType-meta.xml
<RecordType>
    <fullName>Alert</fullName>
    <active>true</active>
    <description>Customer Alert</description>
    <label>Alert</label>
</RecordType>

cncProd/force-app/main/default/objects/CustomerAlerts__c/recordTypes/Broadcast.recordType-meta.xml
<RecordType>
    <fullName>Broadcast</fullName>
    <active>true</active>
    <description>Broadcast-typed Customer Alert</description>
    <label>Broadcast</label>
</RecordType>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_C_C_Vehicle__c/Non_C_C_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Non C&amp;C Vehicle</label>
    <nameField>
        <label>Non C&amp;C Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non C&amp;C Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Non_C_C_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Non C&amp;C Vehicles</relationshipLabel>
    <relationshipName>Non_C_C_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Non_C_C_Vehicle__c/fields/Current_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Current_Mileage__c</fullName>
    <label>Current Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Non_C_C_Vehicle__c/fields/Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>Registered_Date__c</fullName>
    <label>Registered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Non_C_C_Vehicle__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/fields/Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>Registered_Date__c</fullName>
    <label>Registered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <externalId>true</externalId>
    <label>Registration Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Vehicle_Stock__c/Used_Car_Vehicle_Stock__c.object-meta.xml
<CustomObject>
    <description>Vehicle Stock Master for Republic Auto (RA) Used Car</description>
    <label>Used Car Vehicle Stock</label>
    <nameField>
        <displayFormat>UCVS-{0000000}</displayFormat>
        <label>Used Car Vehicle Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Used Car Vehicle Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Used_Car_Vehicle_Stock__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Used Car Vehicle Stocks</relationshipLabel>
    <relationshipName>Used_Car_Vehicle_Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Vehicle_Stock__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/classes/BroadcastControllerTest.cls
/** ******
 * Description : Test Class for BroadcastController.cls
 * 
 * Change History : 
 * Date(YYYYMMDD)      Name       Description
 * 20200402            HS         Created Initial Version
 * 20210917            TP         Modified to cater RA & Non C&C Vehicles
** ******/
@isTest(seeAllData=false)
private class BroadcastControllerTest 
{
    @TestSetup
    static void makeData()
    {
        //Create Account
        List<Account> lstAccount = new List<Account>{Test_DataFactory.createPerson( false , 'Test Account', 'Prospect' ) };
        for (Integer i = 0; i < lstAccount.size(); i++)
        {
            lstAccount[i].PersonEmail = 'patest' + i + '@hotmail.com';
        }
        insert lstAccount;

        //Create Contact
        List<Contact> lstContact = new List<Contact>();
        for( Account acct : lstAccount )
        {
            for( Integer count = 0 ; count < 10 ; count++ )
            {
                Contact tempCnt = Test_DataFactory.createContact( false, 'Test-'+count, 'Contact'+count, (String)acct.Id ); 
                tempCnt.Device__c = 'TESTDEVICETOKEN'+count;
                lstContact.add( tempCnt );
            }
        }
        if( !lstContact.isEmpty() )
        {
            insert lstContact;
        }

        //Create Model
        List<Model__c> lstModels = new List<Model__c>();
        for( Integer index = 0 ; index < lstContact.size() ; index++ )
        {
            lstModels.add( Test_DataFactory.createmodelId( false,'TEST-MODEL-'+index, 'CCK', 'KIAPC' ) );
        }
        if( !lstModels.isEmpty() )
        {
            insert lstModels;
        }

        //Create Variant
        List<Variant__c> lstVariants = new List<Variant__c>();
        for( Integer index = 0 ; index < lstModels.size() ; index++ )
        {
            lstVariants.add( Test_DataFactory.createVariant( false,'TEST-VARIANT-'+index, lstModels.get( index ).Id, 'CCK' ) );
        }
        if( !lstVariants.isEmpty() )
        {
            insert lstVariants;
        }

        //Create Registered Vehicle, Model, Variant
        List<Registered_Vehicle__c> lstRegVehicles = new List<Registered_Vehicle__c>();
        for( Integer index = 0 ; index < lstContact.size() ; index++ )
        {
            Registered_Vehicle__c rv = Test_DataFactory.createregVehicle( false, 'TEST-REGVHC-'+index, 'CCK', 'KIAPC', 'TESTREGNUM'+index, lstContact.get( index ).Id );
            rv.Variant__c = ( index < lstVariants.size() ) ? lstVariants.get( index ).Id : null;
            lstRegVehicles.add( rv );
        }
        if( !lstRegVehicles.isEmpty() )
        {
            insert lstRegVehicles;
        }

        //Create Used Car
        Used_Car_Vehicle_Stock__c usedCar = Test_DataFactory.createSoldUsedCar(true, lstAccount[0].Id, 'STOCK-001', 'OIYG1','AUDI' ,'F1');

        //Create NonC&C Car
        Non_C_C_Vehicle__c nonCCCar = new Non_C_C_Vehicle__c(Account__c = lstAccount[0].Id, Registration_Number__c = 'S1234', Current_Mileage__c = 10000, Registered_Date__c = Date.valueOf('2020-04-01'));
        insert nonCCCar;
    }

    @isTest
    static void getFilteredRegVehicles_Test()
    {

        BroadcastFilterWrapper filters = new BroadcastFilterWrapper();
        filters.vehicleType = 'Registered_Vehicle__c';
        Integer pageNumber = 1;

        List<String> tempModels = new List<String>();
        List<String> tempVariants = new List<String>();
        for( Model__c md : [SELECT Id FROM Model__c ])
        {
            tempModels.add( (String)md.Id );
        }

        for( Variant__c vr : [SELECT Id FROM Variant__c ])
        {
            tempVariants.add( (String)vr.Id );
        }

        System.Test.startTest();

            PagedResult pgResult = BroadcastController.getFilteredRegVehicles(filters, pageNumber);
            System.assert( pgResult <> null );
            System.assert( pgResult.totalItemCount == 0 );
            System.assert( pgResult.records <> null && pgResult.records.isEmpty() );

            filters.branches = new List<String>{ 'CCK' };
            pgResult = BroadcastController.getFilteredRegVehicles(filters, pageNumber);
            System.assert( pgResult <> null );
            System.assert( pgResult.totalItemCount == 10 );
            System.assert( pgResult.records <> null && !pgResult.records.isEmpty() && pgResult.records.size() == 10 );

            filters.models   = tempModels;
            filters.variants = tempVariants;
            pgResult = BroadcastController.getFilteredRegVehicles(filters, pageNumber);
            System.assert( pgResult <> null );
            System.assert( pgResult.totalItemCount == 10 );
            System.assert( pgResult.records <> null && !pgResult.records.isEmpty() && pgResult.records.size() == 10 );

            filters.branches        = new List<String>{};
            filters.bdayMonthFrom   = '1';
            filters.bdayMonthTo     = '12';
            filters.lastLoginFrom   = '1';
            filters.lastLoginTo     = '12';
            filters.carAgeFrom      = '1';
            filters.carAgeTo        = '15';
            filters.upcomingServiceDateFrom = '2020-04-01';
            filters.upcomingServiceDateTo = '2200-04-01';
            filters.lastServiceDateFrom = '2020-04-01';   
            filters.lastServiceDateTo = '2200-04-01';
            pgResult = BroadcastController.getFilteredRegVehicles(filters, pageNumber);
            System.assert( pgResult <> null );

            filters = new BroadcastFilterWrapper();
            filters.vehicleType = 'Used_Car_Vehicle_Stock__c';
            filters.registrationDateFrom = '2020-04-01';
            filters.registrationDateTo = '2020-04-01';
            filters.MileageFrom = '1000';
            filters.MileageTo   = '1000';
            pgResult = BroadcastController.getFilteredRegVehicles(filters, pageNumber);
            System.assert( pgResult <> null );

            filters.vehicleType = 'Non_C_C_Vehicle__c';
            pgResult = BroadcastController.getFilteredRegVehicles(filters, pageNumber);
            System.assert( pgResult <> null );

        System.Test.stopTest();
    }


    @isTest
    static void createBroadcastAlert_Test()
    {

        System.Test.startTest();
            BroadcastFilterWrapper filters = new BroadcastFilterWrapper();
            filters.vehicleType = 'Registered_Vehicle__c';
            filters.branches    = new List<String>{ 'CCK' };
            String resultStr = BroadcastController.createBroadcastAlert( filters, 'Testing Broadcast Alert Msg', 'E-Shop', '', 'https://google.com', 'My Alert' );
            System.debug('@@@@DEBUG createBroadcastAlert_Test :: resultStr = ' +resultStr );
        System.Test.stopTest();

        System.assert( ([SELECT Id FROM CustomerAlerts__c WHERE RecordType.DeveloperName = 'Broadcast']).size() == 10 );
    }

    @isTest
    static void getModelAsSelectOptions_Test()
    {
        
        System.Test.startTest();
        System.assert( !BroadcastController.getModelAsSelectOptions( new List<String>{'CCK'}).isEmpty() 
                            && BroadcastController.getModelAsSelectOptions( new List<String>{'CCK'}).size() == 10 );
        System.Test.stopTest();
    }


    @isTest
    static void getVariantAsSelectOptions_Test()
    {
        
        List<String> tempModels = new List<String>();
        for( Model__c md : [SELECT Id FROM Model__c ]){
            tempModels.add( (String)md.Id );
        }

        System.Test.startTest();
            System.assert( !BroadcastController.getVariantAsSelectOptions(new List<String>{'CCK'}, tempModels).isEmpty() &&  
                                BroadcastController.getVariantAsSelectOptions( new List<String>{'CCK'}, tempModels ).size() == 10 );
        System.Test.stopTest();
    } 
}