cncProd/force-app/main/default/objects/Contact/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Please enter the last 4 digits of the Customer&apos;s NRIC followed by the Date of Birth in the following format DDMMYYY. E.g. 314B10101976</inlineHelpText>
    <label>NRIC _ Passport No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Checklist__c/Daily_Checklist__c.object-meta.xml
<CustomObject>
    <label>Daily Checklist</label>
    <nameField>
        <displayFormat>DC-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Daily Checklist ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Daily_Checklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Model__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Master</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CITPC.recordType-meta.xml
<RecordType>
    <fullName>CITPC</fullName>
    <active>true</active>
    <businessProcess>OppSales</businessProcess>
    <label>CITPC</label>
</RecordType>

cncProd/force-app/main/default/objects/Opportunity/recordTypes/KIAPC.recordType-meta.xml
<RecordType>
    <fullName>KIAPC</fullName>
    <active>true</active>
    <businessProcess>OppSales</businessProcess>
    <label>KIAPC</label>
</RecordType>

cncProd/force-app/main/default/objects/Showroom_Questions_Master__c/Showroom_Questions_Master__c.object-meta.xml
<CustomObject>
    <label>Showroom Questions Master</label>
    <nameField>
        <label>Showroom Questions Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom Questions Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Showroom_Questions_Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Showroom</fullName>
            </value>
            <value>
                <fullName>General Cleanliness</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
            <value>
                <fullName>Cancel Queue</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Trade_Plate__c.field-meta.xml
<CustomField>
    <fullName>Trade_Plate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trade Plate</label>
    <referenceTo>Trade_Plate__c</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Trade_Plate__c/Trade_Plate__c.object-meta.xml
<CustomObject>
    <label>Trade Plate</label>
    <nameField>
        <label>Trade Plate No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Plates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Plate__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>Vehicle Master</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Vehicle_Master__c/fields/Comm_No__c.field-meta.xml
<CustomField>
    <fullName>Comm_No__c</fullName>
    <label>Comm No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Master__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Sent Back to PG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Showroom</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/dailyChecklistTest.cls
@isTest
public class dailyChecklistTest {
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    public static testMethod void triggerTest(){
        Test.StartTest();
        Account acd = new Account();
        acd.name='XYZ Organization';
        insert acd;
        
        Contact c2 = new Contact();
        c2.FirstName = 'abcFirst';
        c2.LastName = 'AbZLast';
        c2.Email = 'xyzmail@mail.com';
        c2.AccountId = acd.id;
        c2.NRIC_Passport_No__c='345678';
        c2.MobilePhone='7867532';
        insert c2;
        
        Opportunity op1=new Opportunity();
        op1.name='op2';
        op1.Contact_person__c=c2.id;
        op1.Rating__c='Hot';
        op1.StageName='Open';
        op1.CloseDate=Date.today().addDays(2);
        insert op1;
        
        Trade_Plate__c tp2=new Trade_Plate__c(Name='12345',Active__c=true);
        insert tp2;
        
        Vehicle_Master__c v1=new Vehicle_Master__c(Name='Test v1',Comm_No__c='',Status__c='Available',Type__c='Showroom',Branch_Code__c='CCK',Franchise_Code__c='KIAPC');
        insert v1;
        
        Logo__c a = new Logo__c(filename__c='test' ,Branch_Code__c='',Franchise_Code__c='');
        insert a;
        Logo__c b = new Logo__c(filename__c='test2' ,Branch_Code__c='CCK',Franchise_Code__c='KIAPC');
        insert b;
        Logo__c logo1 = new Logo__c(filename__c='test2' ,Branch_Code__c='CCF',Franchise_Code__c='CITPC');
        insert logo1;
        
        PageReference page2nd = Page.BookJoinQueuePage;
        ApexPages.currentPage().getParameters().put('id', v1.id);
        BookJoinController cont2nd = new BookJoinController();
        Test.setCurrentPage(page2nd);
        cont2nd.salesNRIC='';
        cont2nd.custNric='';
        cont2nd.custPost='5555';
        cont2nd.newPost=true;
        cont2nd.searchCustNric();
        cont2nd.postalChange();
        cont2nd.salesChange();
        cont2nd.searchCustPhone();
        cont2nd.searchSalesNric();
        cont2nd.oppSearch();
        cont2nd.save();
        cont2nd.cancel();
        
        Test.StopTest();
    }
    
    public static testMethod void dailyTest() {
        Test.StartTest();
        //user
        Profile p = [SELECT Id FROM Profile WHERE Name='KIA SALES'];
        User u2 = new User(Alias = 'ksa2', Branch_Code__c='CCK',Franchise_Code__c='KIAPC',Email='demo2@randomdemodomain.com',EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles', UserName='demo2@andomdemodomain.com');
        insert u2;
        //create Logo
        System.RunAs(u2) {
        Logo__c a = new Logo__c(filename__c='test' ,Branch_Code__c='',Franchise_Code__c='');
        insert a;
        Logo__c b = new Logo__c(filename__c='test2' ,Branch_Code__c='CCK',Franchise_Code__c='KIAPC');
        insert b;
        Logo__c logo1 = new Logo__c(filename__c='test2' ,Branch_Code__c='CCF',Franchise_Code__c='CITPC');
        insert logo1;
        //create vehicles master
        Vehicle_Master__c v1=new Vehicle_Master__c(Name='Test v1',Comm_No__c='',Status__c='Available',Type__c='Showroom',Branch_Code__c='CCK',Franchise_Code__c='KIAPC');
        insert v1;
        Vehicle_Master__c v2=new Vehicle_Master__c(Name='Test v2',Comm_No__c='5678',Status__c='Available',Type__c='Test Drive');
        insert v2;
        //tp plate master
        Trade_Plate__c tp1=new Trade_Plate__c(Name='12345',Active__c=true,Branch_Code__c='CCK',Franchise_Code__c='KIAPC');
        insert tp1;
        //question master
        Showroom_Questions_Master__c sq1=new Showroom_Questions_Master__c(Name='Q1 a',Active__c=true,Number__c=1,Type__c='Showroom');
        insert sq1;
        Showroom_Questions_Master__c sq2=new Showroom_Questions_Master__c(Name='Q2 a',Active__c=true,Number__c=2,Type__c='Showroom');
        insert sq2;
        Showroom_Questions_Master__c sq3=new Showroom_Questions_Master__c(Name='Q1 b',Active__c=true,Number__c=1,Type__c='General Cleanliness');
        insert sq3;
        Showroom_Questions_Master__c sq4=new Showroom_Questions_Master__c(Name='Q2 b',Active__c=true,Number__c=2,Type__c='General Cleanliness');
        insert sq4;
        
        //create account
        Account acc = new Account();
        acc.name='XYZ Organization';
        insert acc;
        
        //create postalcode
        Postal_Code__c pc1 = new Postal_Code__c();
        pc1.name='123456785';
        pc1.Address_Line_1__c='test 1';
        pc1.Address_Line_2__c='test 2';
        pc1.Address_Line_3__c='test 3';
        pc1.Country__c='test c';
        insert pc1;
        
        //create contact
        Contact c1 = new Contact();
        c1.FirstName = 'xyzFirst';
        c1.LastName = 'XyZLast';
        c1.Email = 'xyzmail@mail.com';
        c1.AccountId = acc.id;
        c1.NRIC_Passport_No__c='12345678';
        c1.Postal_Code__c=pc1.id;
        c1.MobilePhone='1234567';
        c1.Franchise_Code__c=u2.Franchise_Code__c;
        c1.Branch_Code__c=u2.Branch_Code__c;
        insert c1;
        
        Date today=date.today();
        //create test drive
        Test_Drive__c td = new Test_Drive__c();
        td.Model__c=v2.id;
        td.Prospect__c=c1.id;
        td.Date__c=today;
        td.NRIC__c='12345678';
        insert td;
        
        Attachment attach=new Attachment();     
        attach.Name='Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=td.id;
        attach.Description = td.id;
        attach.ContentType= 'img';
        insert attach; 
        
        Attachment attach2=new Attachment();     
        attach2.Name='Test Attachment';
        Blob bodyBlob2=Blob.valueOf('Unit Test Attachment Body');
        attach2.body=bodyBlob2;
        attach2.parentId=td.id;
        attach2.Description = td.id;
        attach2.ContentType= 'img';
        insert attach2; 
            
        Test_Drive__c td2 = new Test_Drive__c();
        td2.Model__c=v2.id;
        td2.Prospect__c=c1.id;
        td2.Date__c=today;
        td2.Status__c='Out';
        td2.Branch_Code__c=u2.Branch_Code__c;
        td2.Franchise_Code__c=u2.Franchise_Code__c;
        insert td2;
        
        Opportunity op=new Opportunity();
        op.name='op1';
        op.Contact_person__c=c1.id;
        op.Rating__c='Hot';
        op.StageName='Open';
        op.CloseDate=Date.today().addDays(2);
        op.Branch_Code__c=u2.Branch_Code__c;
        op.Franchise_Code__c=u2.Franchise_Code__c;
        insert op;
        
        
        Daily_Checklist__c dcc=new Daily_Checklist__c();
        
        insert dcc;
        
        PageReference pageRef = Page.DailyCheckListPage;
        DailyCheckListClass controller = new DailyCheckListClass(new ApexPages.StandardController(dcc));
        Test.setCurrentPage(pageRef);
        controller.getDailycheck();
        controller.doSubmit2();
        controller.doSubmit();
        controller.doCancel();
        
        PageReference pageNew = Page.TestDrive;
        TestDriveController cont = new TestDriveController();
        Test.setCurrentPage(pageNew);
        cont.fillList();
        cont.bookClick();
        cont.testid=td.id;
        cont.cancelClick();
        cont.outClick();
        cont.inClick();
        
        PageReference page2nd = Page.BookJoinQueuePage;
        ApexPages.currentPage().getParameters().put('id', v2.id);
        BookJoinController cont2nd = new BookJoinController();
        Test.setCurrentPage(page2nd);
        cont2nd.salesNRIC='12344321';
        cont2nd.custNric='12345678';
        cont2nd.searchSalesNric();
        cont2nd.searchCustNric();
        cont2nd.postalChange();
        cont2nd.salesChange();
        cont2nd.searchCustPhone();
        cont2nd.oppSearch();
        cont2nd.save();
        cont2nd.cancel();

        page2nd = Page.BookJoinQueuePage;
        ApexPages.currentPage().getParameters().put('id', v2.id);
        cont2nd = new BookJoinController();
        Test.setCurrentPage(page2nd);
        cont2nd.salesNRIC='';
        cont2nd.custNric='';
        cont2nd.searchSalesNric();
        cont2nd.searchCustNric();
        cont2nd.postalChange();
        cont2nd.salesChange();
        cont2nd.searchCustPhone();
        cont2nd.oppSearch();
        cont2nd.salesSearch=false;
        cont2nd.save();
        cont2nd.cancel();
        
        page2nd = Page.BookJoinQueuePage;
        ApexPages.currentPage().getParameters().put('id', v2.id);
        cont2nd = new BookJoinController();
        Test.setCurrentPage(page2nd);
        cont2nd.salesNRIC='';
        cont2nd.custNric='';
        cont2nd.searchSalesNric();
        cont2nd.searchCustNric();
        cont2nd.postalChange();
        cont2nd.salesChange();
        cont2nd.searchCustPhone();
        cont2nd.oppSearch();
        cont2nd.salesSearch=true;
        cont2nd.save();
        cont2nd.cancel();
        
        page2nd = Page.BookJoinQueuePage;
        ApexPages.currentPage().getParameters().put('id', v1.id);
        cont2nd = new BookJoinController();
        Test.setCurrentPage(page2nd);
        cont2nd.salesNRIC='12344321';
        cont2nd.custNric='12345678';
        cont2nd.searchCustNric();
        cont2nd.custPhone='';
        cont2nd.postalChange();
        //cont2nd.salesChange();
        cont2nd.searchCustPhone();
        //cont2nd.searchSalesNric();
        //cont2nd.oppSearch();
        //cont2nd.save();
        //cont2nd.cancel();
       
        VSMSHelperClass.testSend(c1.id,'Test Class','12345');
        ApexPages.currentPage().getParameters().put('id',td.id);
        ApexPages.StandardController tdd = new ApexPages.StandardController(td);
        /*TestDrivePDFext tddd  = new TestDrivePDFext(tdd);
        
        tddd.theTest.prospect__r.Country__c='Test 1';
        tddd.theTest.prospect__r.Unit_No_Floor__c='Test 1';
        tddd.theTest.prospect__r.Address_Line_3__c='Test 3';
        tddd.theTest.prospect__r.Address_Line_2__c='Test 2';
        tddd.theTest.prospect__r.Address_Line_1__c='Test 1';
        tddd.getData();
        
        Test_Drive__c tdc=new Test_Drive__c();
        tdc.status__c='Out';
        tdc.Date__c=today;
        insert tdc;
        System.schedule('ScheduleApexClassTest',CRON_EXP,new autoCheckIn());
        
        Helper_Class.AttachPDF(td2.id);
        page2nd = Page.TestDrivePDFPortal;
        ApexPages.currentPage().getParameters().put('id', tdc.id);
        TextDrivePDFPortal cont3nd = new TextDrivePDFPortal();
        cont3nd.goNext();*/
        Test.StopTest();
        }
    }
}