cncProd/force-app/main/default/objects/Contact/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Model__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Models_Interested__c/Models_Interested__c.object-meta.xml
<CustomObject>
    <label>Models Interested</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Models Interested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Models Interested</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Models_Interested__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Model</label>
    <referenceTo>Model__c</referenceTo>
    <relationshipLabel>Models Interested</relationshipLabel>
    <relationshipName>Models_Interested</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/recordTypes/KIAPC.recordType-meta.xml
<RecordType>
    <fullName>KIAPC</fullName>
    <active>true</active>
    <businessProcess>OppSales</businessProcess>
    <label>KIAPC</label>
</RecordType>

force-app/main/default/classes/ModelsInterestedServiceTest.cls
@isTest
private class ModelsInterestedServiceTest 
{
    @testSetup
    static void setUp()
    {
        Account acct = Test_DataFactory.createAccount(true, 'Test Account');
        Contact cont = Test_DataFactory.createContact(true, 'Test', 'Contact', acct.id);    
        Opportunity opp = Test_DataFactory.createOpportunity(false, 'Testing Opportunity', acct.Id);
        opp.Branch_Code__c = 'CCK';
        opp.StageName = 'Open';
        opp.Contact_Person__c = cont.Id;
        opp.CloseDate = Date.today() + 15;
        opp.OwnerId = UserInfo.getUserId();
        insert opp;
        Model__c model = Test_DataFactory.createmodelId(true,'Test Model', 'CCK', 'KIAPC');
    }
    
	@isTest
    static void test_newModelInterestedObject()
    {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Model__c model = [SELECT Id FROM Model__c LIMIT 1];
        Models_Interested__c modelInterested = ModelsInterestedService.newModelInterestedObject(opp.Id, model.Id, 'Online', 'Quick contact');
        System.assertNotEquals(null, modelInterested);
    }
}