cncProd/force-app/main/default/objects/Contact/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&quot;DWH&quot;</defaultValue>
    <description>Need to be &quot;DWH&quot; for the mobile app to work</description>
    <inlineHelpText>Need to be &quot;DWH&quot; for the mobile app to work</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Model__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Model__c/fields/DWH_Model_ID__c.field-meta.xml
<CustomField>
    <fullName>DWH_Model_ID__c</fullName>
    <externalId>true</externalId>
    <label>DWH Model ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Model__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
            <value>
                <fullName>MAXUSPC</fullName>
            </value>
            <value>
                <fullName>MAXUSCV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Model__c/fields/Model_Description__c.field-meta.xml
<CustomField>
    <fullName>Model_Description__c</fullName>
    <label>Model Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getAllModelsApi.cls
//Apex class to Get All models
@RestResource(urlMapping='/GetAllModels/v1/*')
global with sharing class getAllModelsApi {
@HttpGet
//CallOut method for Expose API
global static Void getModels() 
{   
    //Get Country from request URL
    RestRequest request = RestContext.request;
    String countryStr = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
    String errorMsg='';
    List<SObject>  returnObject = new List<SObject>();
    Map<String, String> errorRes = new Map<String, String>();
    List<Map<String, String>> errorResList = new List<Map<String, String>>();
    
    RestResponse res = RestContext.response;
    try
    {
        //Get all the models having country Singapore,SG or have no value
        
        If(countryStr == 'SG' || countryStr == 'Singapore' || countryStr == '')
        {   
            returnObject=[SELECT Id, Name, Country__c, Branch_Code__c, Franchise_Code__c, Model_Description__c, DWH_Model_ID__c FROM Model__c Where (Country__c= :'SG'  OR Country__c ='Singapore' OR Country__c ='') AND Source__c = 'DWH' ];
            res.statusCode = 200; 
        }
        //Get all the models having country valid country except singapore
        else
        {
            returnObject=[SELECT Id, Name, Country__c, Branch_Code__c, Franchise_Code__c, DWH_Model_ID__c, Model_Description__c FROM Model__c Where Country__c= :countryStr AND Source__c = 'DWH'];
            res.statusCode = 200; 
        }  
        If(returnObject.size()<=0)
        {
            errorMsg='We have no Models to display for this country or Country is Invalid';  
            res.statusCode = 400; 
            errorRes.put('ErrorCode', 'Err03-SF');
            errorRes.put('Message', errorMsg);  
            errorResList.add(errorRes);
            res.responseBody = Blob.valueOf(JSON.serialize(errorResList));
        }
         
    }
    //Catch the error If any
    catch (DmlException e)
    { 
        
        res.statusCode=400;
        errorMsg = 'A system exception has occurred, Please contact your administrator.';
        errorRes.put('ErrorCode', 'Err04-SF');
        errorRes.put('Message', errorMsg);  
        errorResList.add(errorRes);
        res.responseBody = Blob.valueOf(JSON.serialize(errorResList));
    }
    
    
    //Return List of Models 
    if(res.statusCode==200)
    {
        res.responseBody = Blob.valueOf(JSON.serialize(returnObject));
    }
    RestContext.response = res;
    res.addHeader('Content-Type', 'application/json');
    
}
}