cncProd/force-app/main/default/objects/Contact/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Drive__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CNC</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/Franchise_Code__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Code__c</fullName>
    <label>Franchise Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CITCV</fullName>
            </value>
            <value>
                <fullName>CITPC</fullName>
            </value>
            <value>
                <fullName>KIACV</fullName>
            </value>
            <value>
                <fullName>KIAPC</fullName>
            </value>
            <value>
                <fullName>MITCV</fullName>
            </value>
            <value>
                <fullName>MITPC</fullName>
            </value>
            <value>
                <fullName>MBC</fullName>
            </value>
            <value>
                <fullName>MBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Drive__c/fields/receive_idemnity_form__c.field-meta.xml
<CustomField>
    <fullName>receive_idemnity_form__c</fullName>
    <label>receive idemnity form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Helper_Class_Test.cls
/** ******
 * Description : Test Class for TriggerExclusion.cls
 * 
 * Change History:
 * Date(YYYYMMDD)       Name        				Description
 * 20200417			    HS							Created Initial Version
 * 
** ******/
@isTest
private class Helper_Class_Test {
    private static String prospectEmail = 'prospect@hotmail.com';
    private static String customerEmail = 'customer@hotmail.com';
    
    @testSetup
    private static void setup() {
        Account prospect = Test_DataFactory.createPerson(true, 'Name', 'Prospect');
        prospect = [SELECT PersonContactId FROM Account WHERE Id = :prospect.Id];
        
        Contact prospectCon = new Contact(Id = prospect.PersonContactId);
        prospectCon.Email = prospectEmail;
        update prospectCon;
        
        Account customer = Test_DataFactory.createPerson(true, 'Name', 'Customer');
        customer = [SELECT PersonContactId FROM Account WHERE Id = :customer.Id];
        
        Contact customerCon = new Contact(Id = customer.PersonContactId);
        customerCon.Email = customerEmail;
        update customerCon;
    }
    
    @isTest
    private static void testAttachPDF_KIAPC() {
        Contact prospectCon = [SELECT Id FROM Contact WHERE Email = :prospectEmail];
        Contact customerCon = [SELECT Id FROM Contact WHERE Email = :customerEmail];
        List<Test_Drive__c> testDrives = new List<Test_Drive__c>();
        
        Test_Drive__c prospectTestDrive = Test_DataFactory.createTestDrive(false, null);
        prospectTestDrive.Prospect__c = prospectCon.Id;
        prospectTestDrive.Branch_Code__c = 'CCA';
        prospectTestDrive.Franchise_Code__c = 'KIAPC';
        prospectTestDrive.Receive_idemnity_form__c = 'Yes';
        testDrives.add(prospectTestDrive);
        
        Test_Drive__c customerTestDrive = Test_DataFactory.createTestDrive(false, null);
        customerTestDrive.Prospect__c = customerCon.Id;
        customerTestDrive.Branch_Code__c = 'CCA';
        customerTestDrive.Franchise_Code__c = 'KIAPC';
        customerTestDrive.Receive_idemnity_form__c = 'Yes';
        testDrives.add(customerTestDrive);
        
        insert testDrives;
        
        for(Test_Drive__c td: testDrives) {
            Helper_Class.AttachPDF(td.Id);
        }        
    }
    
    @isTest
    private static void testAttachPDF_MITPC() {
        Contact prospectCon = [SELECT Id FROM Contact WHERE Email = :prospectEmail];
        Contact customerCon = [SELECT Id FROM Contact WHERE Email = :customerEmail];
        
        List<Test_Drive__c> testDrives = new List<Test_Drive__c>();
        
        Test_Drive__c prospectTestDrive = Test_DataFactory.createTestDrive(false, null);
        prospectTestDrive.Prospect__c = prospectCon.Id;
        prospectTestDrive.Branch_Code__c = 'CCA';
        prospectTestDrive.Franchise_Code__c = 'MITPC';
        prospectTestDrive.Receive_idemnity_form__c = 'Yes';
        testDrives.add(prospectTestDrive);
        
        Test_Drive__c customerTestDrive = Test_DataFactory.createTestDrive(false, null);
        customerTestDrive.Prospect__c = customerCon.Id;
        customerTestDrive.Branch_Code__c = 'CCA';
        customerTestDrive.Franchise_Code__c = 'MITPC';
        customerTestDrive.Receive_idemnity_form__c = 'Yes';
        testDrives.add(customerTestDrive);
        
        insert testDrives;
        
        for(Test_Drive__c td: testDrives) {
            Helper_Class.AttachPDF(td.Id);
        }        
    }
    
    @isTest
    private static void testAttachPDF_CITPC() {
        Contact prospectCon = [SELECT Id FROM Contact WHERE Email = :prospectEmail];
        Contact customerCon = [SELECT Id FROM Contact WHERE Email = :customerEmail];
    
        List<Test_Drive__c> testDrives = new List<Test_Drive__c>();
        
        Test_Drive__c prospectTestDrive = Test_DataFactory.createTestDrive(false, null);
        prospectTestDrive.Prospect__c = prospectCon.Id;
        prospectTestDrive.Branch_Code__c = 'CCA';
        prospectTestDrive.Franchise_Code__c = 'CITPC';
        prospectTestDrive.Receive_idemnity_form__c = 'Yes';
        testDrives.add(prospectTestDrive);
        
        Test_Drive__c customerTestDrive = Test_DataFactory.createTestDrive(false, null);
        customerTestDrive.Prospect__c = customerCon.Id;
        customerTestDrive.Branch_Code__c = 'CCA';
        customerTestDrive.Franchise_Code__c = 'CITPC';
        customerTestDrive.Receive_idemnity_form__c = 'Yes';
        testDrives.add(customerTestDrive);
        
        insert testDrives;
        
        for(Test_Drive__c td: testDrives) {
            Helper_Class.AttachPDF(td.Id);
        }        
    }
}