cncProd/force-app/main/default/objects/Package_Header__c/Package_Header__c.object-meta.xml
<CustomObject>
    <label>Package Header</label>
    <nameField>
        <displayFormat>PH-{0000000000}</displayFormat>
        <label>Package Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Header</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Package_Header__c/fields/PKH_PKGPRICE__c.field-meta.xml
<CustomField>
    <fullName>PKH_PKGPRICE__c</fullName>
    <label>Package Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/classes/PackageHeader.cls
//Start of RN2020Q1010 
public with sharing class PackageHeader extends ADGLIB_SObjectDomain{
    public PackageHeader(LISt<Package_Header__c> sObjectList) {
        super(sObjectList);
    }
    public class Constructor implements ADGLIB_SObjectDomain.IConstructable {
		public ADGLIB_SObjectDomain construct(List<SObject> sObjectList) {
			return new PackageHeader(sObjectList);
		}
	}

    public override void onAfterUpdate(Map<Id,SObject> existingRecords){
        Set<Id> packageIds = new Set<Id>();
        for(Package_Header__c rec : (LIST<Package_Header__c>)Records){
            if(rec.PKH_PKGPRICE__c <> ((Package_Header__c)existingRecords.get(rec.Id)).PKH_PKGPRICE__c){
                packageIds.add(rec.Id);
            }
        }

        if(packageIds.size() > 0){
            SalesAgreementService.processSalesAgreementForPriceChange(packageIds);
        }
    }

}
//End of RN2020Q1010