force-app/main/default/objects/Credit_Note__c/Credit_Note__c.object-meta.xml
<CustomObject>
    <label>Credit/Debit Note</label>
    <nameField>
        <displayFormat>DCN-{00000000}</displayFormat>
        <label>Credit/Debit Note No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit/Debit Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Note__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit/Debit Notes</relationshipLabel>
    <relationshipName>Credit_Debit_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order&apos;s Contact</description>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <label>Shop</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MIT e-shop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/recordTypes/C_C_E_Shop.recordType-meta.xml
<RecordType>
    <fullName>C_C_E_Shop</fullName>
    <active>true</active>
    <description>C&amp;C E-Shop</description>
    <label>C&amp;C E-Shop</label>
</RecordType>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registered_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registered Vehicles</relationshipLabel>
    <relationshipName>Registered_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>Customer&apos;s Reward Credit 
- per Reward Type
- per Registered Vehicle
- per Expiry Date</description>
    <label>Reward</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Reward_Profile__c.field-meta.xml
<CustomField>
    <fullName>Reward_Profile__c</fullName>
    <label>Reward Profile</label>
    <referenceTo>Reward_Profile__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/Reward_Profile__c.object-meta.xml
<CustomObject>
    <label>Reward Profile</label>
    <nameField>
        <label>Reward Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Business Account or Person Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reward Profiles</relationshipLabel>
    <relationshipName>Reward_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only set this value for Individual-typed profile</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reward Profiles</relationshipLabel>
    <relationshipName>Reward_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Profile__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only set this value for Fleet-typed profile</description>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Reward Profiles</relationshipLabel>
    <relationshipName>Reward_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Package</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Boutique</fullName>
            </value>
            <value>
                <fullName>Birthday Voucher</fullName>
            </value>
            <value>
                <fullName>Grooming Package</fullName>
            </value>
            <value>
                <fullName>Service Credit Voucher</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>Discount Voucher</fullName>
            </value>
            <value>
                <fullName>Service Credit</fullName>
            </value>
            <value>
                <fullName>Accessories Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward_Profile__c/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <description>Business Account (Fleet)</description>
    <label>C&amp;C Individual</label>
</RecordType>

cncProd/force-app/main/default/objects/Reward_Usage__c/Reward_Usage__c.object-meta.xml
<CustomObject>
    <label>Reward Usage</label>
    <nameField>
        <label>Reward Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reward Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Reward Usages</relationshipLabel>
    <relationshipName>Reward_Usages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Reward_Usage__c.field-meta.xml
<CustomField>
    <fullName>Reward_Usage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Reference to Debit Reward Usage record</description>
    <label>Reward Usage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Reward_Usage__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Debit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Reward_Usage__c</referenceTo>
    <relationshipLabel>Credit Usages</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Expiry</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Reward_Usage__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Credit to Customer (i.e. Refund/Adjustment/etc.)</description>
    <label>Credit</label>
</RecordType>

force-app/main/default/objects/Reward_Usage__c/recordTypes/Debit.recordType-meta.xml
<RecordType>
    <fullName>Debit</fullName>
    <active>true</active>
    <description>Debit from Customer (i.e. Credit Deduction)</description>
    <label>Debit</label>
</RecordType>

force-app/main/default/objects/Usage_Transaction__c/Usage_Transaction__c.object-meta.xml
<CustomObject>
    <description>Consolidated transaction records of :
- Debit Reward Usages based on Autoline Invoice # / eShop eInvoice #;
- Credit Reward Usages based on Credit Note #</description>
    <label>Usage Transaction</label>
    <nameField>
        <displayFormat>UT-{000000000}</displayFormat>
        <label>Usage Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usage Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Usage_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Usage Transactions</relationshipLabel>
    <relationshipName>Usage_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usage_Transaction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Usage Transactions</relationshipLabel>
    <relationshipName>Usage_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Usage_Transaction__c/fields/Reward_Profile__c.field-meta.xml
<CustomField>
    <fullName>Reward_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reward Profile</label>
    <referenceTo>Reward_Profile__c</referenceTo>
    <relationshipLabel>Usage Transactions</relationshipLabel>
    <relationshipName>Usage_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usage_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(Reward_Profile__r.Type__c)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Usage_Transaction__c/recordTypes/Credit.recordType-meta.xml
<RecordType>
    <fullName>Credit</fullName>
    <active>true</active>
    <description>Refund/Ajustment/etc</description>
    <label>Credit</label>
</RecordType>

cncProd/force-app/main/default/objects/Usage_Transaction__c/recordTypes/Debit.recordType-meta.xml
<RecordType>
    <fullName>Debit</fullName>
    <active>true</active>
    <description>Credit Deduction</description>
    <label>Debit</label>
</RecordType>

force-app/main/default/classes/CMUsageTransactionServiceTest.cls
/** ******
 * Description : Test class for CMUsageTransactionService.cls
 * 
 * Change History:
 * Date(YYYYMMDD)       Name                      Description
 * 20200903             khanh.do@aodigy.com       Created Initial Version. 
 * 
** **** */
@isTest
private class CMUsageTransactionServiceTest {
    private static List<Reward__c> rewards = new List<Reward__c>();
    private static List<Reward_Usage__c> creditUsages = new List<Reward_Usage__c>();
    private static List<Reward_Usage__c> debitUsages = new List<Reward_Usage__c>();    
    private static List<Reward_Usage__c> eShopUsages = new List<Reward_Usage__c>();
    private static String autolineInvoiceNo = 'ABC123456';
    
    @testSetup
    private static void setup() {
        Account personAcc = Test_DataFactory.createPerson(true, 'Test Acc', 'Customer');
        
        personAcc = [SELECT Id, PersonContactId FROM Account WHERE Id =: personAcc.Id];

        Registered_Vehicle__c regVeh = Test_DataFactory.createRegVehicle(false, 'Test-RV123', 'CCK', 'KIAPC', 'Test-RV123', personAcc.PersonContactId);
        regVeh.Account__c = personAcc.Id;
        insert regVeh;
        
        Order__c order = Test_DataFactory.createOrder(Schema.SObjectType.Order__c.getRecordTypeInfosByDeveloperName().get('C_C_E_Shop').getRecordTypeId());
        order.Shop__c = 'KIA';
        insert order;

        Reward_Profile__c rewardProfile = Test_DataFactory.createRewardProfile(false, 'Individual', 'CCK', 'KIA', 'Accessories Credit');
        rewardProfile.Contact__c = personAcc.PersonContactId;
        insert rewardProfile;

        for(Integer i=0; i< 5; i++){            
            Reward__c reward = Test_DataFactory.createReward(false, rewardProfile.Id, rewardProfile.Type__c, 'Valid', Date.today().addDays(5));
            reward.Credit__c = 5000000;
            reward.Branch__c = 'CCK';
            reward.Brand__c  = 'KIA';
            reward.Registered_Vehicle__c = regVeh.Id;
            reward.Contact__c = personAcc.PersonContactId;            
            reward.COST__c = 'CENTER_NO_1';
            rewards.add(reward);
        }
        insert rewards;
        
        for(Reward__c reward: rewards) {
            Reward_Usage__c debitUsage = Test_DataFactory.createRewardUsage(false, reward.Id, 'Hold', 'Debit');
            debitUsage.Order__c = order.Id;
            debitUsage.Credit_Amount__c = 100;
            debitUsage.Autoline_Invoice_Number__c = autolineInvoiceNo;
            debitUsage.Invoice_Amount__c = 1000;
            debitUsages.add(debitUsage);
            
            Reward_Usage__c creditUsage = Test_DataFactory.createRewardUsage(false, reward.Id, 'Issued', 'Credit');
            creditUsage.Order__c = order.Id;
            creditUsage.Credit_Amount__c = 100;
            creditUsage.Autoline_Invoice_Number__c = autolineInvoiceNo;
            creditUsage.Invoice_Amount__c = 1000;
            creditUsage.Credit_Note__c = 'CN0001';
            creditUsages.add(creditUsage);
            
            Reward_Usage__c eShopUsage = Test_DataFactory.createRewardUsage(false, reward.Id, 'Utilised', 'Debit');
            eShopUsage.Order__c = order.Id;
            eShopUsage.Credit_Amount__c = 100;
            eShopUsage.Autoline_Invoice_Number__c = autolineInvoiceNo;
            eShopUsage.Invoice_Amount__c = 1000;
            eShopUsage.Credit_Note__c = 'CN0001';
            eShopUsage.Channel__c = 'eShop';
            eShopUsage.e_Invoice__c = 'eINV001';
            eShopUsage.e_Invoice_Date__c = Date.today();
            
            eShopUsages.add(eShopUsage);
        }
        insert debitUsages;
        insert creditUsages;
        insert eShopUsages;
    }
    
    @isTest
    private static void testProcessDebitUsage() {
        Id debitRecordTypeId = Schema.SObjectType.Reward_Usage__c.getRecordTypeInfosByDeveloperName().get('Debit').getRecordTypeId();
        debitUsages = [SELECT Id, RecordTypeId, Reward__c,
                       		  Autoline_Invoice_Number__c, Autoline_Invoice_Date__c,
                       		  Invoice_Amount__c, Credit_Amount__c,
                              Outstanding_Payment_Amount__c, Payment_Type__c,
                       		  COST__c, Location__c, Channel__c, Contact__c, Order__c,
                       		  e_Invoice__c, e_Invoice_Date__c
                       FROM Reward_Usage__c
                       WHERE RecordTypeId = :debitRecordTypeId
                       AND Channel__c != 'eShop'
                      ];
        Test.startTest();
        CMUsageTransactionService.processUsageTransaction(debitUsages);
        List<Usage_Transaction__c> usageTransactions = [SELECT Id FROM Usage_Transaction__c];
        System.assertEquals(1, usageTransactions.size());
        Test.stopTest();
    }
    
    @isTest
    private static void testProcessCreditUsage() {
        Id creditRecordTypeId = Schema.SObjectType.Reward_Usage__c.getRecordTypeInfosByDeveloperName().get('Credit').getRecordTypeId();
        creditUsages = [SELECT Id, RecordTypeId, Reward__c,
                       		  Autoline_Invoice_Number__c, Autoline_Invoice_Date__c,
                       		  Invoice_Amount__c, Credit_Amount__c,
                              Credit_Note__c, Outstanding_Payment_Amount__c, Payment_Type__c,
                       		  COST__c, Location__c, Channel__c, Contact__c, Order__c,
                       		  e_Invoice__c, e_Invoice_Date__c
                       FROM Reward_Usage__c
                       WHERE RecordTypeId = :creditRecordTypeId
                      ];
        Test.startTest();
        CMUsageTransactionService.processUsageTransaction(creditUsages);
        List<Usage_Transaction__c> usageTransactions = [SELECT Id FROM Usage_Transaction__c];
        System.assertEquals(1, usageTransactions.size());
        Test.stopTest();
    }
    
    @isTest
    private static void testProcessDebitUsageFromEShop() {
        Id debitRecordTypeId = Schema.SObjectType.Reward_Usage__c.getRecordTypeInfosByDeveloperName().get('Debit').getRecordTypeId();
        eShopUsages = [SELECT Id, RecordTypeId, Reward__c,
                       		  Autoline_Invoice_Number__c, Autoline_Invoice_Date__c,
                       		  Invoice_Amount__c, Credit_Amount__c,
                              Outstanding_Payment_Amount__c, Payment_Type__c,
                       		  COST__c, Location__c, Channel__c, Contact__c, Order__c,
                       		  e_Invoice__c, e_Invoice_Date__c
                       FROM Reward_Usage__c
                       WHERE RecordTypeId = :debitRecordTypeId
                       AND Channel__c = 'eShop'
                      ];
        Test.startTest();
        CMUsageTransactionService.processUsageTransaction(eShopUsages);
        List<Usage_Transaction__c> usageTransactions = [SELECT Id FROM Usage_Transaction__c];
        System.assertEquals(1, usageTransactions.size());
        Test.stopTest();
    }
    
    
    /*@isTest
    private static void testProcessDebitUsage_DebitUsageTransactionWithSameInvoiceNumberAlreadyExist() {
        Id debitRecordTypeId = Schema.SObjectType.Reward_Usage__c.getRecordTypeInfosByDeveloperName().get('Debit').getRecordTypeId();
        debitUsages = [SELECT Id, RecordTypeId, Reward__c,
                       		  Autoline_Invoice_Number__c, Autoline_Invoice_Date__c,
                       		  Invoice_Amount__c, Credit_Amount__c,
                              Outstanding_Payment_Amount__c, Payment_Type__c,
                       		  COST__c, Location__c, Channel__c, Contact__c, Order__c,
                       		  e_Invoice__c, e_Invoice_Date__c
                       FROM Reward_Usage__c
                       WHERE RecordTypeId = :debitRecordTypeId
                      ];
        Usage_Transaction__c usageTransaction = Test_DataFactory.createUsageTransaction(true, 'Debit', autolineInvoiceNo, 1000, 800);
        Test.startTest();
        CMUsageTransactionService.processUsageTransaction(debitUsages);
        List<Usage_Transaction__c> usageTransactions = [SELECT Id FROM Usage_Transaction__c];
        System.assertEquals(1, usageTransactions.size());
        Test.stopTest();
    }
    
    @isTest
    private static void testProcessCreditUsage_CreditUsageTransactionWithSameCreditNoteAlreadyExist() {
        Id creditRecordTypeId = Schema.SObjectType.Reward_Usage__c.getRecordTypeInfosByDeveloperName().get('Credit').getRecordTypeId();
        creditUsages = [SELECT Id, RecordTypeId, Reward__c,
                       		  Autoline_Invoice_Number__c, Autoline_Invoice_Date__c,
                       		  Invoice_Amount__c, Credit_Amount__c,
                              Credit_Note__c, Outstanding_Payment_Amount__c, Payment_Type__c,
                       		  COST__c, Location__c, Channel__c, Contact__c, Order__c,
                       		  e_Invoice__c, e_Invoice_Date__c
                       FROM Reward_Usage__c
                       WHERE RecordTypeId = :creditRecordTypeId
                      ];
        Usage_Transaction__c usageTransaction = Test_DataFactory.createUsageTransaction(true, 'Credit', autolineInvoiceNo, 1000, 800);
        
        Test.startTest();
        CMUsageTransactionService.processUsageTransaction(creditUsages);
        List<Usage_Transaction__c> usageTransactions = [SELECT Id FROM Usage_Transaction__c];
        System.assertEquals(1, usageTransactions.size());
        Test.stopTest();
    }*/
}