force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Adjustment__c</fullName>
    <label>Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCK</fullName>
            </value>
            <value>
                <fullName>CCF</fullName>
            </value>
            <value>
                <fullName>CCA</fullName>
            </value>
            <value>
                <fullName>CCI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order&apos;s Contact</description>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <label>Order Created Date</label>
    <type>DateTime</type>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/fields/E_shop_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>E_shop_Order_Number__c</fullName>
    <label>E-shop Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/fields/eInvoice__c.field-meta.xml
<CustomField>
    <fullName>eInvoice__c</fullName>
    <label>eInvoice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/eInvoice_Date__c.field-meta.xml
<CustomField>
    <fullName>eInvoice_Date__c</fullName>
    <label>eInvoice Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/fields/eInvoice_URL__c.field-meta.xml
<CustomField>
    <fullName>eInvoice_URL__c</fullName>
    <label>eInvoice URL</label>
    <type>Url</type>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount__c</fullName>
    <label>Order Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/fields/Order_Amount_Before_GST__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount_Before_GST__c</fullName>
    <label>Order Amount Before GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>OrderID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <label>Shop</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MIT e-shop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <inlineHelpText>Brand</inlineHelpText>
    <label>Site Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIT</fullName>
            </value>
            <value>
                <fullName>MIT</fullName>
            </value>
            <value>
                <fullName>KIA</fullName>
            </value>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>PendingPayment</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>PendingCancellation</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Updated_Date__c</fullName>
    <label>Order Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Order_Line_Item__c/fields/Item_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Item_Adjustment__c</fullName>
    <label>Item Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Item_Category__c.field-meta.xml
<CustomField>
    <fullName>Item_Category__c</fullName>
    <label>Item Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Item_Quantity__c</fullName>
    <label>Item Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cncProd/force-app/main/default/objects/Order_Line_Item__c/fields/Item_Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Selling_Price__c</fullName>
    <label>Item Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Order_Line_Item__c/fields/Item_SKU__c.field-meta.xml
<CustomField>
    <fullName>Item_SKU__c</fullName>
    <label>Item SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Item_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Item_Sub_Category__c</fullName>
    <label>Item Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Item_Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Item_Subtotal__c</fullName>
    <label>Item Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Order_Line_Item__c/fields/Item_Total__c.field-meta.xml
<CustomField>
    <fullName>Item_Total__c</fullName>
    <label>Item Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Order_Line_Item__c/fields/Item_Variants__c.field-meta.xml
<CustomField>
    <fullName>Item_Variants__c</fullName>
    <label>Item Variants</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Item_Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Item_Vehicle_Group__c</fullName>
    <label>Item Vehicle Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Order_Line_Item__c/fields/Item_Vehicle_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Vehicle_Number__c</fullName>
    <label>Item Vehicle Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Order_Line_Item__c/fields/Item_Vehicle_Variant__c.field-meta.xml
<CustomField>
    <fullName>Item_Vehicle_Variant__c</fullName>
    <label>Item Vehicle Variant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/EShopOrderWrapper.cls
public class EShopOrderWrapper 
{
    public Order order {get; set;}
    public String UserId {get; set;}
    public String Name {get; set;}
    public String Email {get; set;}
    public string Mobile {get;set;}
    public Boolean Promotions {get;set;}
    
    public class Order
	{
        public String OrderID {get; set;}
		public String OrderNumber {get; set;}
		public String EInvoice {get; set;}
		public String EInvoiceDate {get; set;}
		public String EInvoiceURL {get; set;}
		public String TransactionDate {get; set;}
		public Decimal OrderAmount {get; set;}
		public Decimal OrderAmountBeforeGST {get; set;}
		public Decimal GST {get; set;}
		public String Branch {get; set;}
		public String SiteName {get; set;}
        public String CreatedDate {get; set;}
        public String UpdatedDate {get; set;}
        public String Status {get; set;}
        public String Shop {get; set;}
        public Decimal Subtotal {get; set;}
        public Decimal Adjustment {get; set;}
        public Decimal GrandTotal {get; set;}
        public String PersonAccount {get; set;}  
        public List<ItemWrapper> LineItems = new List<ItemWrapper>();
        
        public Order(){}
    }
    
    public class ItemWrapper
	{
        public String ItemName {get; set;}
        public Decimal ItemSellingPrice {get; set;}
        public Decimal ItemSubtotal {get; set;}
        public Decimal ItemAdjustment {get; set;}
        public Decimal ItemTotal {get; set;}
        public Decimal ItemQuantity {get; set;}
        public String ItemSKU {get; set;}
        public String ItemVariants {get; set;}
        public String ItemCategory {get; set;}
        public String ItemSubCategory {get; set;}
        public String ItemVehicleGroup {get;set;}
        public String ItemVehicleVariant {get;set;}
        public String ItemVehicleNumber {get;set;}
        
        public ItemWrapper(){}
    }
    
    public static Order__c createOrder (EShopOrderWrapper.Order order, String recordTypeId, String contactId)
	{
        Order__c newOrder = new Order__c();
        newOrder.Adjustment__c      = order.Adjustment;

		datetime cd = null;
		datetime ud = null;
		if(order.CreatedDate != null)
		{
			cd = DateTime.valueOf((order.CreatedDate).replaceAll('T',' '));
        }

		if(order.UpdatedDate != null)
		{
			ud = DateTime.valueOf((order.UpdatedDate).replaceAll('T',' '));
        }

		newOrder.Created_Date__c    = cd; //String.isBlank(order.CreatedDate) ? null : Date.valueOf(order.CreatedDate); //cd;	//
        newOrder.Grand_Total__c     = order.GrandTotal;
        newOrder.OrderID__c         = order.OrderID;
        newOrder.RecordTypeId       = recordTypeId;
        newOrder.Contact__c         = contactId;
        newOrder.Shop__c            = order.Shop;
        newOrder.Status__c          = order.Status;
        newOrder.Subtotal__c        = order.Subtotal;
        newOrder.Updated_Date__c    = ud; //String.isBlank(order.UpdatedDate) ? null : Date.valueOf(order.UpdatedDate); //ud;	//
        newOrder.Account__c         = order.PersonAccount;       		
		newOrder.Branch__c	        = order.Branch;
		newOrder.eInvoice__c	    = order.EInvoice;
		newOrder.eInvoice_Date__c	= String.isBlank(order.EInvoiceDate) ? null : Date.valueOf(order.EInvoiceDate);
		newOrder.eInvoice_URL__c	= order.EInvoiceURL;
		newOrder.E_shop_Order_Number__c	    = order.OrderNumber;
		newOrder.GST_Amount__c	            = order.GST;
		newOrder.Order_Amount__c	        = order.OrderAmount;
		newOrder.Order_Amount_Before_GST__c	= order.OrderAmountBeforeGST;
		newOrder.Site_Name__c	            = order.SiteName;
		newOrder.Transaction_Date__c	    = String.isBlank(order.TransactionDate) ? null : Date.valueOf(order.TransactionDate);

        return newOrder;
    }
    
    public static Order_Line_Item__c createOrderLineItem (EShopOrderWrapper.ItemWrapper item, String orderId)
	{  
        return new Order_Line_Item__c(  Item_Adjustment__c = item.itemAdjustment,
                                        Item_Name__c = item.itemName,
                                        Item_Quantity__c = item.itemQuantity,
                                        Item_Selling_Price__c = item.itemSellingPrice,
                                        Item_SKU__c = item.ItemSKU,
                                        Item_Subtotal__c = item.itemSubtotal,
                                        Item_Total__c = item.itemTotal,
                                        Item_Variants__c = item.itemVariants,
                                        Item_Sub_Category__c = item.itemSubCategory,
                                        Item_Category__c = item.itemCategory,
                                        Order__c = orderId,
                                        Item_Vehicle_Group__c = item.ItemVehicleGroup,
                                        Item_Vehicle_Number__c = item.ItemVehicleNumber,
                                        Item_Vehicle_Variant__c = item.ItemVehicleVariant );
    }
    
}