force-app/main/default/objects/Campaign_Member_Vehicle__c/Campaign_Member_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Campaign Member and Vehicles</label>
    <nameField>
        <label>Campaign Member  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member and Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated in case of Sales Targeted Promo</description>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/ClashDeal__c/ClashDeal__c.object-meta.xml
<CustomObject>
    <description>Temporary Storage of Clash Deals Notification for End of Day Reporting</description>
    <label>Clash Opportunity</label>
    <nameField>
        <displayFormat>CLASH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clash Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Share__c.field-meta.xml
<CustomField>
    <fullName>Share__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Share?</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/ContactHobby__c/ContactHobby__c.object-meta.xml
<CustomObject>
    <label>Contact Hobby</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>ContactHobbyID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Hobbies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Custom_Quote__c/Custom_Quote__c.object-meta.xml
<CustomObject>
    <label>Custom Quote</label>
    <nameField>
        <label>Custom Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerAlerts__c/CustomerAlerts__c.object-meta.xml
<CustomObject>
    <label>CustomerAlerts</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerAlerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerAlerts__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Service Appointment</description>
    <label>Service Appointment</label>
    <referenceTo>Service_Appointment__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>ContactId</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>All app feedbacks are migrated to be case records</description>
    <label>Feedback (Not Used Anymore)</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{YYMM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/contactID__c.field-meta.xml
<CustomField>
    <fullName>contactID__c</fullName>
    <formula>Contact__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>contactID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Custom_Quote__c.field-meta.xml
<CustomField>
    <fullName>Custom_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Drive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Order__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <formula>Contact__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactId</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <formula>CASESAFEID(Contact__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactID</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Appointment__c/Service_Appointment__c.object-meta.xml
<CustomObject>
    <label>Service Appointment</label>
    <nameField>
        <label>Service Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Appointment__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Share__c/Share__c.object-meta.xml
<CustomObject>
    <label>Share</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Share</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/SMS_Reply__c/SMS_Reply__c.object-meta.xml
<CustomObject>
    <description>Store sms reply from campaign member</description>
    <label>SMS Reply</label>
    <nameField>
        <label>Phone Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Replies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/User/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <description>End User derived from this Contact from JCC contact</description>
    <inlineHelpText>End User derived from this Contact from JCC contact</inlineHelpText>
    <label>ContactId (deprecated)</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/classes/PABatchContactWithoutPAConverter.cls
/** *****
 * Description : Batch class to create/Link PA based on the corresponding Contact's info
 *
 * Change History
 * Date(YYYYMMDD)      Name        Description
 * 20200219            AT          Created Initial Version.
 *
** *****/
global class PABatchContactWithoutPAConverter implements Database.Batchable<sObject>, Database.Stateful{

    private List<String> errMsgs = new List<String>();
    Set<Id> setContIdsWithoutPA = new Set<Id>();

    global PABatchContactWithoutPAConverter(){}

    global PABatchContactWithoutPAConverter( Set<Id> setOfContactIds ){
        this.setContIdsWithoutPA = setOfContactIds;
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        Set<String> setContIdsWithPA = new Set<String>();
        for(User us : [ SELECT ContactId__c
                        FROM User
                        WHERE Profile.Name = 'End User' AND IsPortalEnabled = true AND AccountId != null AND ContactId__c != null]) {
            setContIdsWithPA.add(us.ContactId__c);
        }

        ContactSelector selector = new ContactSelector();
        return Database.getQueryLocator( selector.selectContactWithoutPA( setContIdsWithPA, ( setContIdsWithoutPA<>null && !setContIdsWithoutPA.isEmpty() ? setContIdsWithoutPA : null ) ) );
    }


    global void execute(Database.BatchableContext bc, List<Contact> contacts){
        try{
            System.debug('@@@@DEBUG PABatchContactWithoutPAConverter >> execute >> contacts.size() = ' + contacts.size() );
            ContactSelector selector = new ContactSelector();
            List<String> childObjects = new List<String>{   'Registered_Vehicle__c', 'Campaign_Member_Vehicle__c', 'ContactHobby__c',
                                                            'CustomerAlerts__c', 'Sales_Agreement__c', 'Case', 'Feedback__c', 'SMS_Reply__c',
                                                            'Service_Appointment__c', 'Event_Registration__c', 'Share__c', 'ClashDeal__c',
                                                            'Opportunity', 'Invoice__c', 'Custom_Quote__c', 'Customer_Detail__c',
                                                            'Test_Drive__c', 'Order__c'};

            Set<String> contIds = new Set<String>();
            for(Contact con : contacts){
                contIds.Add(con.Id);
            }

            List<Map<String, List<SObject>>> childListMaps = new List<Map<String, List<SObject>>>();
            for(String childObject : childObjects) {
                childListMaps.add( selector.getSObjectContactMap( contIds, childObject ) );
            }

            if(!contacts.isEmpty()){
                PAMigrationService.processConversion( contacts, null, childListMaps );
            }

            System.debug('@@@@DEBUG PABatchContactWithoutPAConverter >> execute >>  Limits.getSoslQueries() = ' + Limits.getSoslQueries() );
            System.debug('@@@@DEBUG PABatchContactWithoutPAConverter >> execute >>  Limits.getDmlRows() = ' + Limits.getDmlRows() );
            System.debug('@@@@DEBUG PABatchContactWithoutPAConverter >> execute >>  Limits.getDmlStatements() = ' + Limits.getDmlStatements() );
        }
        catch(Exception ex){
            errMsgs.add(ex.getMessage());
        }
    }


    global void finish(Database.BatchableContext BC){

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses              = new String[] {'hwanshyan.lim@aodigy.com'};
        mail.setToAddresses(toAddresses);
        // mail.setTargetObjectId( UserInfo.getUserId() );
    	// mail.setSaveAsActivity(false);
        String body;
        if(!errMsgs.isEmpty()){
            for(Integer i=0; i<errMsgs.size(); i++){
                body += (String.valueof(i+1)+' '+errMsgs[i]+ '\r\n');
            }
        }
        else{
            body = 'Success';
        }
        mail.setPlainTextBody(body);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

    }

}