force-app/main/default/objects/Campaign_Member_Vehicle__c/Campaign_Member_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Campaign Member and Vehicles</label>
    <nameField>
        <label>Campaign Member  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member and Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated in case of Sales Targeted Promo</description>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/ClashDeal__c/ClashDeal__c.object-meta.xml
<CustomObject>
    <description>Temporary Storage of Clash Deals Notification for End of Day Reporting</description>
    <label>Clash Opportunity</label>
    <nameField>
        <displayFormat>CLASH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clash Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClashDeal__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clash Deals</relationshipLabel>
    <relationshipName>Clash_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Share__c.field-meta.xml
<CustomField>
    <fullName>Share__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Share?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAlerts__c/CustomerAlerts__c.object-meta.xml
<CustomObject>
    <label>CustomerAlerts</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerAlerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerAlerts__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/CustomerAlerts__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Service Appointment</description>
    <label>Service Appointment</label>
    <referenceTo>Service_Appointment__c</referenceTo>
    <relationshipLabel>CustomerAlerts</relationshipLabel>
    <relationshipName>CustomerAlerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>ContactId</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{YYMM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/contactID__c.field-meta.xml
<CustomField>
    <fullName>contactID__c</fullName>
    <formula>Contact__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>contactID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sales_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Sales_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Agreement</label>
    <referenceTo>Sales_Agreement__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Opportunity/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Custom_Quote__c.field-meta.xml
<CustomField>
    <fullName>Custom_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Test_Drive__c.field-meta.xml
<CustomField>
    <fullName>Test_Drive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Drive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Order__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <formula>Contact__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactId</label>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/ContactID__c.field-meta.xml
<CustomField>
    <fullName>ContactID__c</fullName>
    <formula>CASESAFEID(Contact__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Appointment__c/Service_Appointment__c.object-meta.xml
<CustomObject>
    <label>Service Appointment</label>
    <nameField>
        <label>Service Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Appointment__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <displayFormat>TD-{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Test Drive ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Test_Drive__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot be JCC Contact</errorMessage>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>notEqual</operation>
            <value>JCC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>Test_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PABatchLinkRecordToPersonContact.cls
/** ******
 * Description : Batch Class to Link Contact's child objects' records to corresponding PA.PersonContactId
 * 
 * Change History : 
 * Date(YYYYMMDD)       Name                        Description
 * 20201012             khanh.do@aodigy             Created Initial Version
 * 
** ******/
global with sharing class PABatchLinkRecordToPersonContact implements Database.Batchable<sObject>, Database.Stateful{    
    
    List<Exception> lstException = new List<Exception>();
    Set<String> setRecordIds = new Set<String>();
    String childObject;

    public PABatchLinkRecordToPersonContact(Set<String> personAccIds, String childObject) {
        this.setRecordIds = personAccIds;
        this.childObject = childObject;
    }

    public PABatchLinkRecordToPersonContact() {
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {    

        String query = 'SELECT Id, PersonContactId FROM Account WHERE IsPersonAccount = true';
        if(setRecordIds != null && !setRecordIds.isEmpty()) {
            query += ' AND Id IN :setRecordIds';
        }

        System.debug('**** PABatchLinkRecordToPersonContact **** query = ' + query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        System.debug('scope = ' + scope);
        try {
            Set<String> personAccIds = new Set<String>();
            for(SObject pa: scope) {
                personAccIds.add(pa.Id);
            }

            List<String> childObjects = new List<String>{'Event_Registration__c','Share__c','ClashDeal__c','Opportunity','Invoice__c',
                                                         'Campaign_Member_Vehicle__c', 'Order__c', 'Registered_Vehicle__c',
                                                         'Sales_Agreement__c','CustomerAlerts__c', 'ContactHobby__c', 'Case',
                                                         'SMS_Reply__c', 'Service_Appointment__c',
                                                         'Custom_Quote__c','Customer_Detail__c','Test_Drive__c','Feedback__c'};
            Map<String, List<SObject>> sObjectContactMap = new Map<String, List<SObject>>();
            
            String contactFieldName;
            String strQuery;
            Set<String> conIds = new Set<String>();
            if(childObjects.contains(childObject)) {
                childObjects = new List<String>{childObject};
            }

            for(String sObjectName: childObjects) {
                switch on sObjectName {
                    when 'Event_Registration__c' {
                        contactFieldName = 'ContactId__c';
                    }
                    when 'Opportunity' {
                        contactFieldName = 'Contact_Person__c';
                    }
                    when 'Test_Drive__c' {
                        contactFieldName = 'Prospect__c';
                    }
                    when 'Case' {
                        contactFieldName = 'ContactId';
                    }
                    when else {
                        contactFieldName = 'Contact__c';
                    }
                }
                
                strQuery = ' SELECT Id, Account__c, Account__r.PersonContactId, ' + contactFieldName
                         + ' FROM ' + sObjectName 
                         + ' WHERE Account__c IN :personAccIds'; //AND contactFieldName !=null AND( contactFieldName + != Account__r.PersonContactId ';
                
                for( SObject record : Database.query(strQuery) ) {
                    String personContactId = (String)record.getsObject('Account__r').get('PersonContactId');
                    String contactIdString = (String)record.get(contactFieldName);
                    System.debug('record = ' + record);
                    conIds.add(personContactId);
                    if(personContactId != contactIdString) {
                        if( sObjectContactMap.containsKey( personContactId )) {
                            sObjectContactMap.get( personContactId).add(record);
                        } else {
                            sObjectContactMap.put( personContactId, new List<SObject>{record} );
                        }
                    }                    
                }
            }
            
            ADGLIB_SObjectUnitOfWork uow = new ADGLIB_SObjectUnitOfWork(
            new Schema.SObjectType[]{   Event_Registration__c.SObjectType,
                                        Share__c.SObjectType,
                                        ClashDeal__c.SObjectType,
                                        Opportunity.SObjectType,
                                        Invoice__c.SObjectType,
                                        Custom_Quote__c.SObjectType,
                                        Customer_Detail__c.SObjectType,
                                        Test_Drive__c.SObjectType,
                                        Feedback__c.SObjectType,
                                        Campaign_Member_Vehicle__c.SObjectType,
                                        Order__c.SObjectType,
                                        Registered_Vehicle__c.SObjectType,
                                        Sales_Agreement__c.SObjectType,
                                        CustomerAlerts__c.SObjectType,
                                        ContactHobby__c.SObjectType,
                                        Case.SObjectType,
                                        SMS_Reply__c.SObjectType,
                                        Service_Appointment__c.SObjectType
                                    }
            );
            List<Contact> contacts = [SELECT Id FROM Contact WHERE Id IN :conIds];
            for(Contact cont: contacts) {
                List<SObject> childRecords = sObjectContactMap.get(cont.Id);
                System.debug('childRecords = ' + childRecords);
                linkToPersonContact(childRecords, uow, cont);
            }
            initTriggerExlusion(childObjects);
            uow.commitWork();
        } catch (Exception ex) {
            lstException.add(ex);
            System.debug('ex: ' + ex + ' .Cause: ' + ex.getCause() + ' .At line: ' + ex.getLineNumber());
            loggerDataPool.buildLogDataPool('== PABatchLinkRecordToPersonContact == ', ex);
        }
        
    }

    private static void initTriggerExlusion(List<String> childObjects){
        for( String strObject : childObjects ) 
        {
            TriggerExclusion.excludeTrigger( strObject , true );
        }
    }

    private static void linkToPersonContact (List<sObject> childRecords, ADGLIB_SObjectUnitOfWork uow, Contact personCon ){
        if( !childRecords.isEmpty() ){
            for( SObject sObj : childRecords ){
                if( sObj.getSObjectType().getDescribe().fields.getMap().containsKey('Contact__c') ){
                    uow.registerDirty( sobj, sObj.getSObjectType().getDescribe().fields.getMap().get('Contact__c'), personCon);
                } else if( sObj.getSObjectType().getDescribe().fields.getMap().containsKey('ContactId__c') ) {
                    uow.registerDirty( sobj, sObj.getSObjectType().getDescribe().fields.getMap().get('ContactId__c'), personCon);
                } else if( sObj.getSObjectType().getDescribe().fields.getMap().containsKey('Contact_Person__c') ) {
                    uow.registerDirty( sobj, sObj.getSObjectType().getDescribe().fields.getMap().get('Contact_Person__c'), personCon);
                } else if( sObj.getSObjectType().getDescribe().fields.getMap().containsKey('Prospect__c') ) {
                    uow.registerDirty( sobj, sObj.getSObjectType().getDescribe().fields.getMap().get('Prospect__c'), personCon);
                }
            }
        }
    }

    global void finish(Database.BatchableContext db){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses              = new String[] {'khanh.do@aodigy.com'};
        mail.setToAddresses(toAddresses);

        String body;
        if(!lstException.isEmpty()){
            for(Integer i=0; i<lstException.size(); i++){
                body += (String.valueof(i+1)+' '+lstException[i]+ '\r\n');
            }   
        }
        else{
            body = 'Sucess';
        }
        mail.setSubject('PABatchLinkRecordToPersonContact');
        mail.setPlainTextBody(body);

        System.debug('@@@@DEBUG RecordSharPABatchLinkRecordToPersonContactingBatch >> finish :: mail = ' + mail );
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }

}