force-app/main/default/objects/Campaign_Member_Vehicle__c/Campaign_Member_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Campaign Member and Vehicles</label>
    <nameField>
        <label>Campaign Member  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member and Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles (Account)</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Vehicle__c/fields/Registered_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Registered_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Vehicle</label>
    <referenceTo>Registered_Vehicle__c</referenceTo>
    <relationshipLabel>Campaign Member and Vehicles</relationshipLabel>
    <relationshipName>Campaign_Member_and_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Account)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/global_var__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>JCC Global Variables</label>
</CustomObject>

force-app/main/default/objects/global_var__c/fields/APIGateway_key__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_key__c</fullName>
    <label>APIGateway_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/global_var__c/fields/APIGateway_url__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_url__c</fullName>
    <label>APIGateway_url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/Registered_Vehicle__c/Registered_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Registered Vehicle</label>
    <nameField>
        <label>Registered Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registered_Vehicle__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registered Vehicles (Person Account)</relationshipLabel>
    <relationshipName>Registered_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_AddCampaignMember.cls
@isTest
private class Test_AddCampaignMember{
    
    @isTest
    private static void testInsertCampaignMember(){
        Account personAccToInsert = Test_DataFactory.createPerson(true, 'lastName', 'Customer');
        Account personAcc = [SELECT PersonContactId FROM Account WHERE Id = :personAccToInsert.Id];
        Contact personCon = [SELECT Id FROM Contact WHERE Id = :personAcc.PersonContactId];
        Campaign testCamp = Test_DataFactory.createCamp(true, 'Test', 'Events', 'CCK');
        Registered_Vehicle__c regVehicle = Test_DataFactory.createregVehicle(true,'Test', 'CCK', 'KIAPC', '74L1001', personCon.Id);
        
        List<Id> campIds = new List<Id>();
        Campaign_Member_Vehicle__c campMemVehicle = Test_DataFactory.createCampVehicle(false, 'Test', testCamp.Id, personCon.Id, regVehicle.Id);
        campMemVehicle.Account__c = personAcc.Id;
        insert campMemVehicle;
        campIds.add(campMemVehicle.Id);
        
		global_var__c JCC_GlobalVar = new global_var__c();     
		JCC_GlobalVar.APIgateway_URL__c = 'A';
		JCC_GlobalVar.APIGateway_key__c = 'B';
		insert JCC_GlobalVar;


        Test.startTest();
        AddCampaignMember.insertRecords(campIds);
        Test.stopTest();
    }
}