cncProd/force-app/main/default/objects/Person_Account_Profiling__c/Person_Account_Profiling__c.object-meta.xml
<CustomObject>
    <description>Customer Account Profile from other Business Unit (ex. Republic Auto, Car Leasing, etc.)</description>
    <label>Person Account Profiling</label>
    <nameField>
        <displayFormat>PROF-{00000000}</displayFormat>
        <label>Person Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account Profilings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Person_Account_Profiling__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Person Account Profilings</relationshipLabel>
    <relationshipName>Person_Account_Profilings</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Person_Account_Profiling__c/recordTypes/RA_Person_Account_Profiling_RT.recordType-meta.xml
<RecordType>
    <fullName>RA_Person_Account_Profiling_RT</fullName>
    <active>true</active>
    <label>RA Person Account Profiling RT</label>
</RecordType>

cncProd/force-app/main/default/objects/RA_Global_Variable__c/RA_Global_Variable__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting for Republic Auto modules</description>
    <label>RA Global Variable</label>
</CustomObject>

cncProd/force-app/main/default/objects/RA_Global_Variable__c/fields/APIGateway_Key__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_Key__c</fullName>
    <description>API Gateway&apos;s apikey</description>
    <inlineHelpText>API Gateway&apos;s apikey</inlineHelpText>
    <label>APIGateway Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cncProd/force-app/main/default/objects/RA_Global_Variable__c/fields/APIGateway_URL__c.field-meta.xml
<CustomField>
    <fullName>APIGateway_URL__c</fullName>
    <description>API Gateway URL</description>
    <inlineHelpText>API Gateway URL</inlineHelpText>
    <label>APIGateway URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sales_Opportunity__c/Sales_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Custom Sales Opportunity Object</description>
    <label>Sales Opportunity</label>
    <nameField>
        <displayFormat>SO-{YYYYMM}-{000000}</displayFormat>
        <label>Sales Opportunity  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Sales_Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Opportunities</relationshipLabel>
    <relationshipName>Sales_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Opportunity__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Expected Close Date</label>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Opportunity__c/fields/Person_Account_Profiling__c.field-meta.xml
<CustomField>
    <fullName>Person_Account_Profiling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account Profiling</label>
    <referenceTo>Person_Account_Profiling__c</referenceTo>
    <relationshipLabel>Sales Opportunities</relationshipLabel>
    <relationshipName>Sales_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Vehicle_Stock__c/Used_Car_Vehicle_Stock__c.object-meta.xml
<CustomObject>
    <description>Vehicle Stock Master for Republic Auto (RA) Used Car</description>
    <label>Used Car Vehicle Stock</label>
    <nameField>
        <displayFormat>UCVS-{0000000}</displayFormat>
        <label>Used Car Vehicle Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Used Car Vehicle Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Used_Car_Vehicle_Stock__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Used Car Vehicle Stocks</relationshipLabel>
    <relationshipName>Used_Car_Vehicle_Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Used_Car_Vehicle_Stock__c/fields/Person_Account_Profiling__c.field-meta.xml
<CustomField>
    <fullName>Person_Account_Profiling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account Profiling</label>
    <referenceTo>Person_Account_Profiling__c</referenceTo>
    <relationshipLabel>Used Car Vehicle Stocks</relationshipLabel>
    <relationshipName>Used_Car_Vehicle_Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Stock_Reservation__c/Vehicle_Stock_Reservation__c.object-meta.xml
<CustomObject>
    <description>Stock Reservation for Non C&amp;C MF</description>
    <label>Vehicle Stock Reservation</label>
    <nameField>
        <displayFormat>STKRES-{0000000}</displayFormat>
        <label>Vehicle Stock Reservation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Stock Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Vehicle_Stock_Reservation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicle Stock Reservations</relationshipLabel>
    <relationshipName>Vehicle_Stock_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Stock_Reservation__c/fields/Person_Account_Profiling__c.field-meta.xml
<CustomField>
    <fullName>Person_Account_Profiling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account Profiling</label>
    <referenceTo>Person_Account_Profiling__c</referenceTo>
    <relationshipLabel>Vehicle Stock Reservations</relationshipLabel>
    <relationshipName>Vehicle_Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Stock_Reservation__c/fields/Sales_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Sales_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Opportunity</label>
    <referenceTo>Sales_Opportunity__c</referenceTo>
    <relationshipName>RA_Used_Car_Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/objects/Vehicle_Stock_Reservation__c/fields/Used_Car_Vehicle_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Car_Vehicle_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Used Car Vehicle Stock</label>
    <referenceTo>Used_Car_Vehicle_Stock__c</referenceTo>
    <relationshipName>Used_Car_Stock_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

cncProd/force-app/main/default/classes/RABatchSyncVehicle_Test.cls
/** *****
 * Description : Test Class for RASyncVehicleSch batch job
 * 
 * Change History
 * Date(YYYYMMDD)       Name                  Description
 * 20210205             huynh.hung@aodigy     Created Initial Version. 
 * 
** *****/
@isTest
private class RABatchSyncVehicle_Test {
    @testSetup
    private static void createData(){
        Account pa = Test_DataFactory.createPA(true, 'TestLastName','TestLastName@gmail.com', 'Customer');
        Person_Account_Profiling__c profiling = Test_DataFactory.createPAProfiling(true, pa.ID, 'RA_Person_Account_Profiling_RT');
        
        Used_Car_Vehicle_Stock__c car = Test_DataFactory.createSoldUsedCar(true, pa.Id, 'VEHDOC0000000000061212','SG00KA3', 'MERCEDES-BENZ', 'SMK9420z');
        
        Sales_Opportunity__c opp = Test_DataFactory.createSalesOpp(false, pa.ID, 'Stock Reserve', 'HungSC', 'HungSC@gmail.com', '6512365478');
        opp.Close_Date__c = Date.today().addMonths(6);
        insert opp;
        Vehicle_Stock_Reservation__c stockReserv = Test_DataFactory.createReservation(false, pa.Id, Date.today(), 'vietnam', 500, opp.ID, car.ID);
        
        RA_Global_Variable__c RA_GlobalVar = RA_Global_Variable__c.getOrgDefaults();
        RA_GlobalVar.APIGateway_URL__c = 'www.urlToTheNewHell.com';
        RA_GlobalVar.APIGateway_key__c = 'fakekey123';
        upsert RA_GlobalVar;
    }
    
    @isTest
    private static void testBatchSyncVehicle(){
        Test.startTest();
        String mockResponse = '[{"VEHDOCNO": "VEHDOC0000000000061212",'+
            '"VEHNO": "SMK9420z",'+
            '"MAKE": "MERCEDES-BENZ",'+
            '"MODEL": "C180 AVG (R17 LED)",'+
            '"LISTINGPRICE": "123800.00",'+
            '"COE": "123001.00",'+
            '"OMV": "123590.00",'+
            '"ARF": "12313.00",'+
            '"ENGINECAPACITY": "1235",'+
            '"REGDATE": "2016-02-29",'+
            '"MILAGE": "12338.00",'+
            '"NOOFOWNDER": "12",'+
            '"AGEOFVEHICLE": "12",'+
            '"SOLDDATE": "2016-02-29",'+
            '"CUSTOMERNAME": "HungTest04021 HungTest04021",'+
            '"MOBILE": "6501100402",'+
            '"EMAIL":"HungTest04021@ratest.com",'+
            '"CONSENT": "YES"}]';
        
        HttpResponse res = new HttpResponse();
        res.setBody(mockResponse);
        res.setStatusCode(200);

        RASyncVehicleService.syncVehicleFromUCS(res, mockResponse);
        
        Test.stopTest();
        System.assertNotEquals(null, [Select ID from Person_Account_Profiling__c WHERE Account__r.PersonEmail ='HungTest04021@ratest.com']);
    }
    
    @isTest
    private static void testBatchSyncVehicle_ExistingPAProfiling(){
        Test.startTest();
        String mockResponse = '[{"VEHDOCNO": "VEHDOC0000000000061212",'+
            '"VEHNO": "SMK9420z",'+
            '"MAKE": "MERCEDES-BENZ",'+
            '"MODEL": "C180 AVG (R17 LED)",'+
            '"LISTINGPRICE": "123800.00",'+
            '"COE": "123001.00",'+
            '"OMV": "123590.00",'+
            '"ARF": "12313.00",'+
            '"ENGINECAPACITY": "1235",'+
            '"REGDATE": "2016-02-29",'+
            '"MILAGE": "12338.00",'+
            '"NOOFOWNDER": "12",'+
            '"AGEOFVEHICLE": "12",'+
            '"SOLDDATE": "2016-02-29",'+
            '"CUSTOMERNAME": "HungTest04021 HungTest04021",'+
            '"MOBILE": "6501100402",'+
            '"EMAIL":"TestLastName@gmail.com",'+
            '"CONSENT": "YES"}]';
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        res.setBody(mockResponse);
        res.setStatusCode(200);
        RASyncVehicleService.syncVehicleFromUCS(res, '');

        Test.stopTest();
        System.assertNotEquals(null, [Select ID from Person_Account_Profiling__c WHERE Account__r.PersonEmail ='TestLastName@gmail.com']);
    }
    
    @isTest
    private static void testBatchSyncVehicle_NoCustomer(){
        Test.startTest();
        String mockResponse = '[{"VEHDOCNO": "VEHDOC0000000000061212",'+
            '"VEHNO": "SMK9420z",'+
            '"MAKE": "MERCEDES-BENZ",'+
            '"MODEL": "C180 AVG (R17 LED)",'+
            '"LISTINGPRICE": "123800.00",'+
            '"COE": "123001.00",'+
            '"OMV": "123590.00",'+
            '"ARF": "12313.00",'+
            '"ENGINECAPACITY": "1235",'+
            '"REGDATE": "2016-02-29",'+
            '"MILAGE": "12338.00",'+
            '"NOOFOWNDER": "12",'+
            '"AGEOFVEHICLE": "12",'+
            '"SOLDDATE": "2016-02-29",'+
            '"CUSTOMERNAME": "",'+
            '"MOBILE": "",'+
            '"EMAIL":"",'+
            '"CONSENT": ""}]';
        
        HttpResponse res = new HttpResponse();

        RASyncVehicleSch batch = new RASyncVehicleSch('eq 2020-02-21','eq 2020-02-21','eq 2020-02-21','eq 2020-02-21');
        Database.executeBatch(batch, 1);
        RASyncVehicleService.syncVehicleFromUCS(res, mockResponse);
        
        Test.stopTest();
    }
    
    @isTest
    private static void testBatchSyncVehicle_Schedule(){
        Test.startTest();
        String mockResponse = '[{"VEHDOCNO": "VEHDOC0000000000061212",'+
            '"VEHNO": "SMK9420z",'+
            '"MAKE": "MERCEDES-BENZ",'+
            '"MODEL": "C180 AVG (R17 LED)",'+
            '"LISTINGPRICE": "123800.00",'+
            '"COE": "123001.00",'+
            '"OMV": "123590.00",'+
            '"ARF": "12313.00",'+
            '"ENGINECAPACITY": "1235",'+
            '"REGDATE": "2016-02-29",'+
            '"MILAGE": "12338.00",'+
            '"NOOFOWNDER": "12",'+
            '"AGEOFVEHICLE": "12",'+
            '"SOLDDATE": "2016-02-29",'+
            '"CUSTOMERNAME": "",'+
            '"MOBILE": "",'+
            '"EMAIL":"",'+
            '"CONSENT": ""}]';
        
        HttpResponse res = new HttpResponse();

        System.schedule('BatchAftersalesServiceHeader', '0 0 0 ? * * *', new RASyncVehicleSch());    
        RASyncVehicleService.syncVehicleFromUCS(res, mockResponse);
        
        Test.stopTest();
    }
    
    @isTest
    private static void testBatchSyncVehicle_withFreeTextFilterInput(){
        Test.startTest();
        String mockResponse = '[{"VEHDOCNO": "VEHDOC0000000000061212",'+
            '"VEHNO": "SMK9420z",'+
            '"MAKE": "MERCEDES-BENZ",'+
            '"MODEL": "C180 AVG (R17 LED)",'+
            '"LISTINGPRICE": "123800.00",'+
            '"COE": "123001.00",'+
            '"OMV": "123590.00",'+
            '"ARF": "12313.00",'+
            '"ENGINECAPACITY": "1235",'+
            '"REGDATE": "2016-02-29",'+
            '"MILAGE": "12338.00",'+
            '"NOOFOWNDER": "12",'+
            '"AGEOFVEHICLE": "12",'+
            '"SOLDDATE": "2016-02-29",'+
            '"CUSTOMERNAME": "",'+
            '"MOBILE": "",'+
            '"EMAIL":"",'+
            '"CONSENT": ""}]';
        
        HttpResponse res = new HttpResponse();

        RASyncVehicleSch batch = new RASyncVehicleSch('LASTUPDATEDATE=eq 2021-03-02');
        Database.executeBatch(batch, 1);
        RASyncVehicleService.syncVehicleFromUCS(res, mockResponse);
        
        Test.stopTest();
    }
}