cncProd/force-app/main/default/objects/Person_Account_Profiling__c/Person_Account_Profiling__c.object-meta.xml
<CustomObject>
    <description>Customer Account Profile from other Business Unit (ex. Republic Auto, Car Leasing, etc.)</description>
    <label>Person Account Profiling</label>
    <nameField>
        <displayFormat>PROF-{00000000}</displayFormat>
        <label>Person Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account Profilings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Person_Account_Profiling__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Person Account Profilings</relationshipLabel>
    <relationshipName>Person_Account_Profilings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PersonAccountProfilingSelector.cls
/** ******
 * Description : Service class for Republic Auto (RA) Person Account Profiling object
 * 
 * Change History : 
 * Date(YYYYMMDD)      Name                     Description
 * 20210114            khanh.do@aodigy          Created Initial Version
 * 
** ******/
public with sharing class PersonAccountProfilingSelector extends ADGLIB_SObjectSelector {

    public Schema.SObjectType getSObjectType() 
    {
        return Person_Account_Profiling__c.sObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() 
    {
        return ADGLIB_UtilityHelper.getSObjectFieldListByObj('Person_Account_Profiling__c');
    }

    public List<Person_Account_Profiling__c> getProfilingsAccountIds(Set<Id> Ids) 
    {
        List<Person_Account_Profiling__c> profilingList = new List<Person_Account_Profiling__c>();
        if( !Ids.isEmpty() ) {
            adglib_QueryFactory query = newQueryFactory();
            String filter = ' Account__c IN :Ids ';
            query.setCondition( filter );
            profilingList = Database.query( query.toSOQL() );
        }
        System.debug('profilingList = ' + profilingList);
        return profilingList;        
    }
}