force-app/main/default/objects/BPE_Template_Configuration__mdt/BPE_Template_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>The configuration for BPE templates</description>
    <label>BPE Template Configuration</label>
    <pluralLabel>BPE Template Configurations</pluralLabel>
</CustomObject>

cncProd/force-app/main/default/objects/BPE_Template_Configuration__mdt/fields/Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Template_ID__c</fullName>
    <label>Template ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/Sales_Agreement__c.object-meta.xml
<CustomObject>
    <label>Sales Agreement</label>
    <nameField>
        <displayFormat>SA-{0000000}</displayFormat>
        <label>SF SA No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/Balance_Payment_Email__c.field-meta.xml
<CustomField>
    <fullName>Balance_Payment_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Balance Payment Email will be available after Insurance Premium has been confirmed</inlineHelpText>
    <label>Balance Payment Email</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/BalancePayment__c.field-meta.xml
<CustomField>
    <fullName>BalancePayment__c</fullName>
    <formula>Vehicle_Purchase_Price__c -  Vehicle_Deposit__c - COE_Deposit__c - Amount_to_Finance__c - ( Trade_in_Value__c -  Full_Settlement_Amount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/CUM_FIRSTNAME__c.field-meta.xml
<CustomField>
    <fullName>CUM_FIRSTNAME__c</fullName>
    <label>Customer Full Nam (not used)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/emailaddress__c.field-meta.xml
<CustomField>
    <fullName>emailaddress__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/GMS_Package__c.field-meta.xml
<CustomField>
    <fullName>GMS_Package__c</fullName>
    <label>GMS Package</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/objects/Sales_Agreement__c/fields/SOH_SONO__c.field-meta.xml
<CustomField>
    <fullName>SOH_SONO__c</fullName>
    <externalId>true</externalId>
    <label>Sales Agreement No</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sales_Agreement__c/fields/TradeInBalance__c.field-meta.xml
<CustomField>
    <fullName>TradeInBalance__c</fullName>
    <formula>Trade_in_Value__c -  Full_Settlement_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trade-In Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

cncProd/force-app/main/default/classes/BPETemplatePreviewCtrl.cls
public with sharing class BPETemplatePreviewCtrl {

    public Sales_Agreement__c getSalesAgreement() {
        ID recordID = ApexPages.CurrentPage().getParameters().get('id');
        return [SELECT CUM_FIRSTNAME__c, Owner.Name, SOH_SONO__c, emailaddress__c, OwnerId, BalancePayment__c, TradeInBalance__c, GMS_Package__c FROM Sales_Agreement__c WHERE ID = :recordID];
    }

    public string getBPETemplate () {
        
        Sales_Agreement__c currentSA = [SELECT Owner.Name, SOH_SONO__c, emailaddress__c, OwnerId, BalancePayment__c, TradeInBalance__c, GMS_Package__c FROM Sales_Agreement__c WHERE ID = :ApexPages.CurrentPage().getParameters().get('id')];

        EmailTemplate BpeTemplate = templateSelector(currentSA);
        
        Messaging.SingleEmailMessage renderEmail = Messaging.renderStoredEmailTemplate(BpeTemplate.Id, currentSA.OwnerId, currentSA.ID);
        
        return renderEmail.getHtmlBody();
    }

    public void emailToCustomer() {

        string recordID = ApexPages.CurrentPage().getParameters().get('id');
        Sales_Agreement__c currentSA = [SELECT Owner.Name, SOH_SONO__c, emailaddress__c, OwnerId, BalancePayment__c, TradeInBalance__c, GMS_Package__c, Balance_Payment_Email__c FROM Sales_Agreement__c WHERE ID = :recordID];
        
        EmailTemplate template = templateSelector(currentSA);
        
        // dummy contact required to render the template, will delete when the email sent
        //Contact dummyContact = new Contact(FirstName = 'Test', LastName = 'Test', email = currentSA.emailaddress__c);
        //insert dummyContact;

        // render email template
        Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(template.Id, null, recordID);
        
        // set display name in email
        mail.setSenderDisplayName(currentSA.Owner.Name);

        // set target email address
        string customerEmail = Test.isRunningTest()? 'test@gmail.com' : currentSA.emailaddress__c;
        List<string> toAddress = new List<string> {customerEmail};
        mail.setToAddresses(toAddress);
        
        // send email
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>{mail};

        // process the response and delete dummy contact
        try {
            Messaging.SendEmailResult[] results = Messaging.sendEmail(allmsg, false);
            system.debug('Email Result');
            system.debug(results);
            if (results[0].success) {
                currentSA.Balance_Payment_Email__c = true;
                update currentSA;
                system.debug('Send success');
                //delete dummyContact;
            } else {
                system.debug('Send failed');
                //delete dummyContact;
            }
            return;
        } catch (Exception e) {
            system.debug(e.getMessage());
        }
    }

    private enum Template {NORMAL, DEFICIT, DEFICIT_RA, CUSTOMER_REFUND}

    private EmailTemplate templateSelector(Sales_Agreement__c salesAgreement) {
        decimal totalBalance = salesAgreement.BalancePayment__c;
        decimal tradeInBalance = salesAgreement.TradeInBalance__c;
        decimal gmsBalance = salesAgreement.GMS_Package__c;
        boolean negativeTotalBalance = (totalBalance <= 0 || totalBalance == null) ? true : false;
        boolean negativeTradeInBalance = (tradeInBalance < 0 || tradeInBalance == null) ? true : false;
        boolean negativeGmsBalance = (gmsBalance < 0 || gmsBalance == null) ? true : false;
        string templateName = Template.NORMAL.name(); // baseline scenario: NORMAL
        
        if (negativeTotalBalance) {
            templateName = Template.CUSTOMER_REFUND.name();
        }
        
        if (!negativeTotalBalance && !negativeTradeInBalance) {
            templateName = Template.NORMAL.name();
        }

        if (!negativeTotalBalance && negativeTradeInBalance && !negativeGmsBalance) {
            templateName = Template.DEFICIT.name();
        }

        if (!negativeTotalBalance && negativeTradeInBalance && negativeGmsBalance) {
            templateName = Template.DEFICIT_RA.name();
        }

        List<BPE_Template_Configuration__mdt> templates = (List<BPE_Template_Configuration__mdt>) [SELECT MasterLabel, Template_ID__c, Active__c FROM BPE_Template_Configuration__mdt WHERE Active__c = true AND MasterLabel = :templateName];
        if (templates.size() == 1) {
            string templateId = templates[0].Template_ID__c;
            system.debug('BPE Template ID: ' + templateId);
            system.debug('BPE Template Label: ' + templates[0].MasterLabel);
            if (!Test.isRunningTest()) {
                return [SELECT Id, Name, Subject, HtmlValue, Body FROM EmailTemplate WHERE ID = :templateId];
            } else {
                templateName = 'BalancePaymentInfo_' + templateName;
                return [SELECT Id, Name, Subject, HtmlValue, Body FROM EmailTemplate WHERE Name = :templateName];
            }
            
        } else {
            throw new templateSelectorException('There are no or more than 1 template found');
        }
    }

    private class templateSelectorException extends Exception {}
}