force-app/main/default/objects/MB_Promotion__c/MB_Promotion__c.object-meta.xml
<CustomObject>
    <description>Promotion master data for MB</description>
    <label>MB Promotion</label>
    <nameField>
        <label>MB Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MB Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Promotion__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>AND( TODAY() &gt;= Start_Date__c, TODAY() &lt;= End_Date__c)</formula>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Promotion__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Promotion__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return to Pool</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MB_Promotion__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Promotion_Stock__c/MB_Promotion_Stock__c.object-meta.xml
<CustomObject>
    <description>Junction object between Promotion__c and MB_Stock_Vehicle_Master__c</description>
    <label>MB Promotion Stock</label>
    <nameField>
        <displayFormat>MBPS-{0000000}</displayFormat>
        <label>MB Promotion Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Promotion Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cncProd/force-app/main/default/objects/MB_Promotion_Stock__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>MB_Promotion__r.Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Promotion_Stock__c/fields/MB_Promotion__c.field-meta.xml
<CustomField>
    <fullName>MB_Promotion__c</fullName>
    <label>MB Promotion</label>
    <referenceTo>MB_Promotion__c</referenceTo>
    <relationshipLabel>MB Promotion Stocks</relationshipLabel>
    <relationshipName>MB_Stock_Vehicles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MB_Promotion_Stock__c/fields/MB_Stock_Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>MB_Stock_Vehicle_Master__c</fullName>
    <label>MB Stock Vehicle Master</label>
    <referenceTo>MB_Stock_Vehicle_Master__c</referenceTo>
    <relationshipLabel>MB Promotion Stocks</relationshipLabel>
    <relationshipName>MB_Promotions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

cncProd/force-app/main/default/objects/MB_Stock_Vehicle_Master__c/MB_Stock_Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>MB Stock Vehicle Master</label>
    <nameField>
        <displayFormat>MBSVM-{000000}</displayFormat>
        <label>MB Stock Vehicle Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MB Stock Vehicle Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MB_Stock_Vehicle_Master__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Test Drive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cncProd/force-app/main/default/classes/MB_BatchPromoAutomation.cls
global class MB_BatchPromoAutomation implements Database.Batchable<sObject> {
    global static Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, Name, Active__c, MB_Stock_Vehicle_Master__c, MB_Promotion__r.Active__c, MB_Promotion__r.End_Date__c, MB_Promotion__r.Start_Date__c, MB_Promotion__r.Flag__c,
                                                MB_Stock_Vehicle_Master__r.Status__c, MB_Stock_Vehicle_Master__r.Name
                                        FROM MB_Promotion_Stock__c
                                        WHERE MB_Stock_Vehicle_Master__r.Status__c != 'Reserved' AND MB_Stock_Vehicle_Master__r.Status__c != 'Blocked'
                                        ORDER BY MB_Promotion__r.CreatedDate DESC]);
    }

    global void execute(Database.BatchableContext bc, List<MB_Promotion_Stock__c> records) {
        Map<Id, List<MB_Promotion_Stock__c>> promoByStockIds = new Map<Id, List<MB_Promotion_Stock__c>>();
        Set<String> pStockPromoIds = new Set<String>();
        for (MB_Promotion_Stock__c pStock : records) {
            pStockPromoIds.add(pStock.MB_Stock_Vehicle_Master__c);
            if (promoByStockIds.containsKey(pStock.MB_Stock_Vehicle_Master__c)) {
                promoByStockIds.get(pStock.MB_Stock_Vehicle_Master__c).add(pStock);
            } else {
                promoByStockIds.put(pStock.MB_Stock_Vehicle_Master__c, new List<MB_Promotion_Stock__c>{pStock});
            }
        }
        system.debug('ID SIZE:: ' + promoByStockIds.size());

        List<MB_Promotion_Stock__c> promos;
        MB_Promotion_Stock__c latestPromo;
        MB_Stock_Vehicle_Master__c stockVehicleMaster;
        List<MB_Stock_Vehicle_Master__c> stocksToBeUpdated = new List<MB_Stock_Vehicle_Master__c>();
        Map<Id, MB_Stock_Vehicle_Master__c> vStocks = new Map<Id, MB_Stock_Vehicle_Master__c>([SELECT Id, Status__c
                                                                                               FROM MB_Stock_Vehicle_Master__c
                                                                                               WHERE Id in :pStockPromoIds]);
        for (Id key : promoByStockIds.keySet()) {
            promos = promoByStockIds.get(key);
            if (hasValidPromo(promos)) {
                stockVehicleMaster = vStocks.get(key);
                stockVehicleMaster.Status__c = 'Open';
                stocksToBeUpdated.add(stockVehicleMaster);
            }
            else {
                latestPromo = getPromoToBeApplied(promos)[0];
                if (latestPromo.MB_Promotion__r.Flag__c == 'Blocked') {
                    stockVehicleMaster = vStocks.get(key);
                    stockVehicleMaster.Status__c = 'Available';
                    stocksToBeUpdated.add(stockVehicleMaster);
                } else if (latestPromo.MB_Promotion__r.Flag__c == 'Return to Pool') {
                    stockVehicleMaster = vStocks.get(key);
                    stockVehicleMaster.Status__c = 'Open';
                    stocksToBeUpdated.add(stockVehicleMaster);
                }
            }
        }
        system.debug('Stock to update:: ' + stocksToBeUpdated);
        system.debug('AAAAAAAAAAA:: ' + latestPromo);

        try {
            Database.update(stocksToBeUpdated, false);
        } catch(Exception e) {
            loggerDataPool.buildLogDataPool('MBBatchPromoAutomation', e);
		}
    }

    global void finish(Database.BatchableContext bc) {
        batchDataPool.buildBatchDataPool('MBBatchPromoAutomation', bc.getJobId());
    }

    private static Boolean hasValidPromo(List<MB_Promotion_Stock__c> promos) {
        //system.debug('VALID PROMOS:: ' + promos);
        for (MB_Promotion_Stock__c pStock : promos) {
            if (pStock.MB_Promotion__r.Active__c) {
                return true;
            }
        }
        return false;
    }

    public static List<MB_Promotion_Stock__c> getPromoToBeApplied(List<MB_Promotion_Stock__c> promos) {
        // If promos has same end date then return promo by latest CreatedDate
        // If promos has different end date then return promo by latest EndDate
        //system.debug('PROMOS APPLIED:: ' + promos);
        Date tmpLatestEndDate = Date.newInstance(1990, 1, 1);
        List<MB_Promotion_Stock__c> tmpLatestPromoStocks = new List<MB_Promotion_Stock__c>();
        for (MB_Promotion_Stock__c pStock : promos) {
            if (pStock.MB_Promotion__r.End_Date__c >= tmpLatestEndDate) {
                tmpLatestEndDate = pStock.MB_Promotion__r.End_Date__c;
                tmpLatestPromoStocks.add(pStock);
            }
        }
        return tmpLatestPromoStocks;
    }
}